openshift/rosa

cmd/initialize/cmd.go
cmd/login/cmd.go
cmd/whoami/cmd.go
docs/moactl.md
docs/moactl_whoami.md
main.go
pkg/ocm/config/config.go

This new command outputs information about the current account
configurations for both AWS and Red Hat. It also displays which
OpenShift API environment the user is logged into through OCM.

whoami: Add command to display account information

---

cmd/create/cluster/cmd.go
cmd/create/idp/cmd.go
cmd/create/ingress/cmd.go
cmd/create/user/cmd.go
cmd/describe/cluster/cmd.go
cmd/dlt/cluster/cmd.go
cmd/dlt/idp/cmd.go
cmd/dlt/ingress/cmd.go
cmd/dlt/user/cmd.go
cmd/edit/cluster/cmd.go
cmd/edit/ingress/cmd.go
cmd/initialize/cmd.go
cmd/list/cluster/cmd.go
cmd/list/idp/cmd.go
cmd/list/ingress/cmd.go
cmd/list/user/cmd.go
cmd/login/cmd.go
cmd/logs/cluster/cmd.go
cmd/verify/permissions/cmd.go
cmd/verify/quota/cmd.go
pkg/reporter/reporter.go

- Add `CreateReporterOrExit` function to reporter
- Use it in commands rather than the same code block
Admittedly not well tested but seems like it's a safe change :smile:

CreateReporterOrExit function for commands

---

cmd/logs/cluster/cmd.go
cmd/logs/cmd.go
docs/moactl_logs_cluster.md

When fetching cluster logs, in addition to passing the cluster name/ID
as a command-line argument, we also allow it to be sent as a flag. This
allows for more consistent behavior across commands and resources, while
still allowing the current behavior.

logs: Allow the use of --cluster as identifier

---

cmd/whoami/cmd.go

To distinguish data from AWS versus OCM, we prefix the output to include
the source. Also renames "OpenShift API" to "OCM API" to avoid
confusion.

whoami: Prefix output with source API

---

pkg/aws/client.go

This makes the linter complain:
```
$ golangci-lint run
pkg/aws/client.go:118:35: unnecessary conversion (unconvert)
MinThrottleDelay: time.Duration(1 * time.Second),
^
```

linter: Fix unnecessary conversion

---

cmd/create/cluster/cmd.go
cmd/create/ingress/cmd.go
cmd/edit/cluster/cmd.go

In the past we parsed error messages coming from OCM and display only
a portion of this. This is not scalable, as we cannot know what the
error message structure is. This patch expands them to display the
entire error as it comes from the OCM API.

errors: Expand error messages

---

cmd/create/cluster/cmd.go
cmd/create/idp/cmd.go
cmd/create/ingress/cmd.go
cmd/create/user/cmd.go
cmd/describe/cluster/cmd.go
cmd/dlt/cluster/cmd.go
cmd/dlt/idp/cmd.go
cmd/dlt/ingress/cmd.go
cmd/dlt/user/cmd.go
cmd/edit/cluster/cmd.go
cmd/edit/ingress/cmd.go
cmd/initialize/cmd.go
cmd/list/cluster/cmd.go
cmd/list/idp/cmd.go
cmd/list/ingress/cmd.go
cmd/list/user/cmd.go
cmd/login/cmd.go
cmd/logs/cluster/cmd.go
cmd/verify/permissions/cmd.go
cmd/verify/quota/cmd.go
cmd/whoami/cmd.go
pkg/logging/logger.go

Very similar to https://github.com/openshift/moactl/pull/15/
- Add CreateLoggerOrExit function to reporter
- Use it in commands rather than the same code block
- Update `whoami` to use the functions as well

CreateLoggerOrExit function for commands

---

pkg/cluster/cluster.go

moactl now supports custom cluster properties during cluster creation.
Note: Manual tests have yielded that this behaves as expected.

Custom cluster properties.

---

cmd/initialize/cmd.go
cmd/verify/cmd.go
cmd/verify/permissions/cmd.go
cmd/verify/quota/cmd.go
docs/moactl_init.md
docs/moactl_verify.md
docs/moactl_verify_permissions.md
docs/moactl_verify_quota.md
pkg/aws/client.go

When verifying quota or permissions, these commands defaults to the
locally-configured AWS region. However, since clusters can be installed
with the --region flag, the verify commands may not representative of
the region in which a cluster will be installed.

AWS Region: Allow passing --region to verify and init commands

---

cmd/create/idp/cmd.go
cmd/create/idp/github.go
cmd/create/idp/google.go
docs/moactl_create_idp.md
pkg/interactive/interactive.go

This adds support for the interactive flag on the `create idp` command.
Currently supported by GitHub and Google IdPs. The OpenID and LDAP
options will fall back to the legacy interactive mode.
Demo: https://asciinema.org/a/Koqdz81jtapuawl3rxRe7qOK8

interactive: Add interactive flag to create idp

---

cmd/edit/cluster/cmd.go
cmd/edit/cmd.go
docs/moactl_edit.md
docs/moactl_edit_cluster.md
docs/moactl_edit_ingress.md

In interactive edit mode, if a cli flag is not supplied, the default value is set directly from the cluster itself.
Demo: https://asciinema.org/a/bkaHd59KW71GUGp6bCdCIDtIj

interactive: Add interactive mode to edit cluster

---

cmd/create/addon/cmd.go
cmd/create/cmd.go
cmd/list/addon/cmd.go
cmd/list/cmd.go
docs/moactl_create.md
docs/moactl_create_addon.md
docs/moactl_list.md
docs/moactl_list_addons.md
pkg/cluster/cluster.go
pkg/ocm/helpers.go

When listing add-ons for a cluster, we show the list of enabled add-ons
that the current organization has quota for, as well as those already
installed in the cluster. From this list the user can use the ID to
manually install add-ons using the `create` command.
Since there can be confusion regarding the spelling of add-ons, I've
added aliases for "addon", "add-on", as well as their plurals. Also,
since the user is not "creating" and add-on, we can use the alias "add"
instead of "create", although both work similarly.
Demo: https://asciinema.org/a/rlF6g0IujtKZNwT1s1d3B6f0u

addons: Add list and create commands for add-ons

---

README.adoc
README.md
install-troubleshooting.md

Updated the quickstart guide from here - https://github.com/jeremyeder/moa-docs/blob/install/INSTALL.md
2 questions:
1. Do we want to recommend using the latest version of moactl?
2. Can we provide info on how much quota is needed (and how to change this in AWS) in order to spin up a cluster?
I have a handful of other things I need to test, and a few placeholder docs for troubleshooting and permissions.

adding quickstart

---

cmd/create/idp/cmd.go
cmd/create/idp/github.go

If required fields are not sent as flags, we should fall back to
interactive mode to gather necessary data.

create-idp: Fallback to interactive mode

---

pkg/interactive/interactive.go

If a field is not required and a default is not available or supplied by
flags, then the field prompt will include "(optional)" to indicate to
the user that they can just continue without entering/selecting any
data.

interactive: Display optional marker for non-required fields

---

pkg/aws/permissions.go

Don't validate AWS policy specifically for validating SCP changes and not required for cluster install.

Don't validate AWS Organization List Policies

---

pkg/aws/client.go
pkg/aws/permissions.go

Currently permissions are validation in a single region, this PR changes that to use the region set in the client.

Validate permissions in the AWS client region

---

CHANGES.adoc
pkg/info/info.go

- README: updates from second moa hackday
- Don't validate AWS Organization List Policies
- Validate permissions in the AWS client region
- Validate only permissions in the OSD SCP policy document

Release v0.0.5

---

cmd/create/idp/cmd.go
docs/moactl_create_idp.md

If the user does not supply a name for the identity provider, one will
be generated based on the identity provider type.

create-idp: Allow user to specify IdP name

---

cmd/create/cluster/cmd.go
docs/moactl_create_cluster.md

To avoid the API from rejecting a cluster creation request based on the
number of nodes, we set a reasonable default: 4 nodes for single AZ
clusters and 9 for multi AZ clusters.

create-cluster: Set compute node defaults based on AZ

---

cmd/list/addon/cmd.go
docs/moactl_list_addons.md
pkg/ocm/helpers.go

We should not show the entire list of add-ons in our database. Instead,
we should just gate the list of add-ons by cluster and take into account
the organization's quota.

addons: Remove global list of add-ons

---

README.md
cmd/create/cluster/cmd.go
docs/moactl_create_cluster.md

This makes the flag shorthand to be '-c', which makes it consistent
across all other cluster commands.

create-cluster: Deprecate --name in favor of --cluster-name

---

cmd/dlt/user/cmd.go

When deleting a single user which is a cluster-admin as well as a dedicated-admin, the confirmation message displays different format of comma-separated users (",travi" and "travi,") for either categories.
While deleting dedicated-admin user:
```
$ moactl delete user -c rbt-moa-test --dedicated-admins travi
? Are you sure you want to delete users ,travi from cluster rbt-moa-test? Yes
```
While deleting cluster-admin user:
```
$ moactl delete user -c rbt-moa-test --cluster-admins travi
? Are you sure you want to delete users travi, from cluster rbt-moa-test? Yes
```
This patch fixes it so that commas are trimmed on output.

delete-user: Fix confirmation output

---

cmd/describe/cluster/cmd.go

```
$ moactl describe cluster -c vkareh-moa
Name:        vkareh-moa
ID:          1esan91qstimslmuvn5evm9p5nf0i960
External ID: 
AWS Account: 765374464689
API URL:     
Console URL: 
Nodes:       Master: 3, Infra: 3, Compute: 4
Region:      us-east-2
State:       error
Created:     Aug  5, 2020
```

describe-cluster: Show AWS account ID used to create cluster

---

cmd/create/cluster/cmd.go
cmd/dlt/cluster/cmd.go
cmd/logs/install/cmd.go
cmd/logs/uninstall/cmd.go
docs/moactl_create_cluster.md
docs/moactl_delete_cluster.md
pkg/cluster/cluster.go
pkg/ocm/helpers.go
pkg/ocm/logs.go

There are 4 commits here:
*    create-cluster: Allow user to watch cluster installation logs
*    delete-cluster: Allow user to watch cluster uninstallation logs
*    create-cluster: Describe cluster automatically after creation
*    logs: Detach logs once operation is complete

Log improvements

---

cmd/verify/permissions/cmd.go

@vkareh  PTAL
This is how it displays now. 
E: Unable to validate SCP policies
E: Error simulating policy: Throttling: Rate exceeded
status code: 400, request id: 315eb277-86ab-470a-bac5-92c586fa044d. Please wait 3-5 minutes before retrying.

Added Detailed Error Message for Throttling

---

CHANGES.adoc
pkg/info/info.go

- create-cluster: Set compute node defaults based on AZ
- create-idp: Allow user to specify IdP name
- addons: Add list and describe commands for add-ons
- addons: Direct the user to check add-on status after install
- aws: Return error if using root account
- improve moactl verify quota error messages
- Check cloudformation stack exists
- Add tests for EnsureOsdCcsAdminUser
- create-cluster: Deprecate --name in favor of --cluster-name
- describe-cluster: Show AWS account ID used to create cluster
- fix long line
- Change from ginkgo to to go test
- logs: Make command more intuitive
- logs: Update SDK client
- logs: Add uninstall logs
- logs: Add separate install/uninstall logs
- logs: Update API endpoints
- interactive: Fix function call from broken dependency
- addons: Remove global …

Release v0.0.6

---

pkg/cluster/cluster.go
pkg/logging/ocm_logger.go

When creating a cluster, we want to make sure we instantiate the AWS client using the same region that the cluster is set to.
This also updates the OCM SDK to the latest version, which adds extra logging output. After discussion with @cben, we've determined that most SDK logs belong to the debug level output.

Ensure region on cluster create, update SDK

---

cmd/verify/oc/cmd.go

Detecting an invalid or unsupported version of the openshift-clients is
not an error, but the successful output of the 'verify' command. Since
we also call this command from the 'download' command, we need to ensure
that instead of exiting with an error, the command just ends and allows
the rest of 'download' to go through.

verify-oc: Do not error out on invalid version

---

cmd/verify/oc/cmd.go

When the oc client is not connected to any cluster, it still outputs the
version string, but also exits with an error. Instead of bailing out on
the error, we ensure that the version string is empty before we assume
that there is no 'oc' tool installed.

verify-oc: Ensure no output on error

---

pkg/reporter/reporter.go

Windows seems to output control characters instead of properly colored
output, so we check whether the client is running on Windows and then
remove the color codes.

reporter: Do not use colors on Windows

---

cmd/logs/install/cmd.go
cmd/logs/uninstall/cmd.go
go.mod
go.sum

To avoid users being concerned about their cluster not starting install,
we add a spinner while we poll the installation logs endpoint. Once the
logs are available, we remove the spinner and show the logs instead.
https://asciinema.org/a/WoaLz9coGMc5quqKjTBDRPBJY

logs: Add progress indicator when waiting for logs

---

cmd/list/cmd.go
cmd/list/version/cmd.go
docs/moactl_list.md
docs/moactl_list_versions.md

When creating a cluster, the user is able to pass a parameter with the
version of OpenShift to use. Unless the user goes through the
interactive flow, they won't be able to see which versions are
available. This command allows a user to view a list of all enabled
versions in the current environment.
https://asciinema.org/a/3G1EgphgPxmcD5hK2M1XVTuuE

list-versions: Add command to list enabled versions

---

assets/bindata.go
templates/policies/osd_scp_policy.json

Since billing is recommended, but not required, we should not check
during the verify-permission check so as to not block the user if they
do not have this policy.

verify-permissions: Do not check ViewBilling policy

---

pkg/aws/client.go
pkg/aws/client_test.go

When running `make test` there is text comparison that doesn't match:
```
• Failure [0.000 seconds]
Client
/home/vkareh/go/src/github.com/openshift/moactl/pkg/aws/client_test.go:15
EnsureOsdCcsAdminUser
/home/vkareh/go/src/github.com/openshift/moactl/pkg/aws/client_test.go:41
When the cloudformation stack already exists
/home/vkareh/go/src/github.com/openshift/moactl/pkg/aws/client_test.go:49
When stack is in ROLLBACK_COMPLETE state
/home/vkareh/go/src/github.com/openshift/moactl/pkg/aws/client_test.go:87
Returns error telling the stack is in an invalid state [It]
/home/vkareh/go/src/github.com/openshift/moactl/pkg/aws/client_test.go:92
Expected
<string>: Error creating user: Cloudformation stack fake-stack existing with status ROLLBACK_COMPLETE.Expected status is CREATE_COMPLETE.
Ensure …
```

tests: Fix expected text comparison

---

cmd/initialize/cmd.go
pkg/aws/client.go
pkg/cluster/cluster.go
pkg/ocm/regions/regions.go

Since a CloudFormation stack is region-specific, we avoid using the
user-set flag and hard-code a default AWS region. This ensures that the
stack is queried always from the same region, regardless where the
cluster is being created.

Use default region for CloudFormation stack

---

.gitignore
cmd/create/cluster/cmd.go
pkg/aws/client.go
pkg/aws/client_test.go

Fixes: OSD-4707
The credential check has been added to cluster create command.
Example output when the creds for `osdCcsAdmin` are being changed manually
```shell
└─ ▶./moactl create cluster -c boran-test
I: Validating AWS credentials for CFUser...
E: Error validating AWS credentials: Invalid CloudFormation stack credentials: osdCcsAdmin is not valid
you can recreate the CloudFormation stack with:
moactl init --delete-stack && moactl init
```

refactor(create): add credential check for osdCcsAdmin when cluster starts to be created

---

cmd/describe/cluster/cmd.go

@vkareh PTAL
In the logs we have the format as 2020-09-10T20:01:09Z with z for UTC and T for timestamp.  
Format "Sep 10 2020 19:12:55 UTC" was more user friendly. 
PTAL

Added Timestamp to created date

---

cmd/login/cmd.go

When asking the user for the OCM access token, the field should be
required and not allow the user through if they do not supply it.

login: Ensure token is required

---

cmd/create/cluster/cmd.go
cmd/list/version/cmd.go
pkg/ocm/versions/versions.go

We keep the flag hidden for now, and we hard-code the default to
'stable' when creating clusters. Eventually we will want to expose this
to end-users and tell the OCM what channel group to use.

versions: Allow querying for channel-groups

---

CHANGES.adoc
pkg/info/info.go

- reporter: Do not use colors on Windows
- list-versions: Add command to list enabled versions
- logs: Add progress indicator when waiting for logs
- verify-permissions: Do not check ViewBilling policy
- Add 'Channel Group' attribute to 'moactl describe cluster'
- tests: Fix expected text comparison
- Use default region for CloudFormation stack
- login: Ensure token is required
- refactor(create): add credential check for osdCcsAdmin when cluster starts to be created
- Added Timestamp to created date
- versions: Allow querying for channel-groups

Release v0.0.10

---

pkg/aws/client.go
pkg/aws/quota.go

When fetching quota for comparison, if the AWS response contains a nil
servicequota item, it crashes moactl.

verify-quota: Avoid nil pointer dereferencing

---

cmd/verify/oc/cmd.go

openshift-client is not strictly necessary to use moactl, erroring out
is a bad user experience if the user is not intending on using oc.
A warning is less aggressive.

verify-oc: Only warn when oc client missing

---

cmd/create/cluster/cmd.go
docs/moactl_create_cluster.md
go.mod
go.sum
pkg/ocm/properties/properties.go
pkg/ocm/versions/versions.go

Since the MOA AMIs are not yet live in the AWS Marketplace, only
allowlisted accounts with a valid subscription will be able to use them.
Using the new --use-marketplace-ami flag will tell OCM that it should
use the MOA image, rather than the default OSD one.

create-cluster: Allow selective override of the marketplace AMI

---

cmd/create/cluster/cmd.go
cmd/list/version/cmd.go
docs/moactl_create_cluster.md
docs/moactl_list_versions.md
go.mod
go.sum
pkg/cluster/cluster.go
pkg/ocm/versions/versions.go

When listing versions or creating a cluster, we can now specify the
channel group to use, with a default of 'stable'. Interactive mode now
reads the channel group flag and displays the correct list when creating
the cluster.
https://asciinema.org/a/b4vW7EtlDp0vRBbljSbnnGwBa

versions: Expose channel-group

---

go.mod
go.sum
pkg/ocm/config/config.go

Since new tokens can be generated without an 'exp' claim, we defer to
the OCM SDK, which handles token claims correctly.

Use OCM SDK to get token expiration

---

pkg/aws/quota.go

To allow users to create a single cluster, we can decrease the quota
check for only 100 vCPU.

verify-quota: Check for only 100 vCPU

---

CHANGES.adoc
pkg/info/info.go

- Add Provision Type and Reason for error cluster
- Review Comments
- Fixed lint and reverted wrong line
- idp: Warn the user that it will take about 1 minute to add IdP
- aws: Add support for AWS profiles
- logs: Improve warnings when cluster is pending
- Adding validations to cluster create command
- remove validations from create command
- aws: Split configuration to ensure early failure

Release v0.0.13

---

cmd/create/idp/cmd.go
cmd/create/idp/github.go
cmd/create/idp/ldap.go
cmd/create/idp/openid.go
docs/moactl_create_idp.md
pkg/interactive/interactive.go

When defining a custom hostname for the identity provider, we need to
support a ca-bundle file to be used when making requests to the server.
* https://asciinema.org/a/tSA28OuNKshJz1ihmIKox2MPJ
* https://asciinema.org/a/eWfw7AlgV4PwMQP8zKI7eMjfa

idp: Add support for certificate bundles

---

cmd/create/idp/cmd.go
cmd/create/idp/gitlab.go
cmd/list/idp/cmd.go
docs/moactl_create_idp.md

To allow customers to authenticate into their clusters against GitLab,
we provide an IDP flow using the standard web application flow.
https://asciinema.org/a/VtNiqFZuzYFH5QgntxHdUEkWK

idp: Add support for GitLab

---

cmd/create/cluster/cmd.go
cmd/initialize/cmd.go
docs/moactl_create_cluster.md
go.mod
go.sum
pkg/cluster/cluster.go

* create-cluster: Add --dry-run flag   
With the dry-run flag we allow the customer to simulate creating
a cluster. This runs through the entire process of validating, preflight
and quota checks and returns with either success or error. The cluster
is not persisted nor written to the OCM database.
* init: Simulate cluster creation
To ensure that a customer has all necessary permissions and quota in
their OCM account, we attempt creating a very basic cluster with the
dry-run flag and warn the customer in case of failuer.

Support dry-run parameter for 'init' and 'create cluster'

---

Makefile
go.mod
go.sum

Also, remove it from the repository module configuration, since we only
need the local binary

Makefile: only download go-bindata when not available

---

CHANGES.adoc
pkg/info/info.go

- idp: Add support for certificate bundles
- Added New Error Message Implementation
- Updated OCM SDK version
- idp: Add support for GitLab
- create-cluster: Add --dry-run flag
- init: Simulate cluster creation
- Makefile: only download go-bindata when not available
- Move main.go to moactl directory, add make install target

Release v0.0.14

---

CONTRIBUTING.md

Actually all I wanted is document where the `.golangciversion` file gets used (not mentioned anywhere inside this repo) :grin:

Add CONTRIBUTING.md file, with some details about CI

---

cmd/create/cluster/cmd.go
cmd/initialize/cmd.go

If the osdCcsAdmin user does not exist, the dry-run will always fail. We
should always ensure that the cloudformation stack is set before
attempting a cluster install.

init: Ensure osdCcsAdmin exists before attempting cluster dry-run

---

cmd/create/admin/cmd.go
cmd/create/cmd.go
cmd/describe/admin/cmd.go
cmd/describe/cmd.go
cmd/dlt/admin/cmd.go
cmd/dlt/cmd.go
docs/moactl_create.md
docs/moactl_create_admin.md
docs/moactl_delete.md
docs/moactl_delete_admin.md
docs/moactl_describe.md
docs/moactl_describe_admin.md

To allow customers to login to a cluster without needing to setup an IdP
with a third-party provider and without using the web console, we allow
them to create a cluster-admin user using the htpasswd identity
provider. This auto-generates a password and a cluster-admin user and
then outputs the oc login command necessary to login to the cluster.
https://asciinema.org/a/RakSNcoGpoi0R1klhDEhGGbus

htpasswd: Add admin resource to login to cluster

---

cmd/create/idp/cmd.go
cmd/create/ingress/cmd.go
cmd/create/user/cmd.go
cmd/dlt/idp/cmd.go
cmd/dlt/ingress/cmd.go
cmd/dlt/user/cmd.go
cmd/edit/ingress/cmd.go
cmd/whoami/cmd.go
pkg/cluster/cluster.go
pkg/ocm/helpers.go
pkg/ocm/logs.go
pkg/ocm/machines/machines.go
pkg/ocm/regions/regions.go
pkg/ocm/versions/versions.go

Now errors only output the relevant message to the user

ocm: Keep error opIds and codes behind debug flag

---

README.md
cmd/create/cluster/cmd.go
cmd/edit/cluster/cmd.go
docs/moactl_create_cluster.md
docs/moactl_edit_cluster.md

With the new vCPU-based SKUs we now support clusters with 2 compute
nodes (for single AZ) and 3 compute node (for multi AZ). The new
minimums are also the defaults for new clusters.

nodes: Bring the default number of nodes down

---

cmd/create/cluster/cmd.go
docs/moactl_create_cluster.md

Since the goal is to move entirely to using the AWS paid AMI, we default
the flag to true and hide it from end-users. It can still be explicitly
set to 'false' for debugging purposes, and eventually we will deprecate
it.

cluster: Default to using paid AMI

---

cmd/create/cluster/cmd.go
docs/moactl_create_cluster.md
pkg/cluster/cluster.go

This flag indicates if cloud permission checks are disabled when
attempting installation of the cluster by setting mint credential mode
in the installer config.

cluster: Add flag to disable SCP checks

---

cmd/initialize/cmd.go

Cluster names must be shorter than 15 char.
Prevents the following warning during init:
```
moactl init          
I: Logged in as 'test' on 'https://api.openshift.com'                                                                     
I: Validating AWS credentials...                                                                                                                                                                                                                                                
I: AWS credentials are valid!                                                                                                           
I: Validating SCP policies... …
```

Init test cluster name to less than 15 char

---

pkg/cluster/cluster.go
pkg/ocm/helpers.go
pkg/ocm/logs.go
pkg/ocm/machines/machines.go
pkg/ocm/regions/regions.go
pkg/ocm/versions/versions.go

If the user-friendly error Reason is not available, show the OCM
api-friendly error string to avoid empty errors.

errors: Fall back to full error message

---

cmd/create/idp/openid.go

Even if the user did not set the --interactive flag, if we request any
claims information we should display the help to avoid confusion.

openid: Always show help text for claims

---

cmd/list/user/cmd.go

When a user runs the 'create admin' command, the service creates
a 'cluster-admin' user for the HTPasswd IdP. This user is generated
internally and not intended to be exposed, so we hide it from the list.

users: Do not show cluster-admin user

---

cmd/edit/cluster/cmd.go

If no flags are sent when editing a cluster, we should fall back to
interactive mode instead of sending an empty payload to the API.

edit-cluster: Fallback to interactive mode

---

README.md
cmd/create/cluster/cmd.go
cmd/initialize/cmd.go

@acathrow - For now, I'm leaving the `--use-paid-ami` as a hidden/secret flag until we move the selection to Unleash.

aws: Default to free AMI

---

CHANGES.adoc
assets/bindata.go
pkg/info/info.go

- Add tags to template, not working
- Add Check Admin User function, and add tests to verify
- Added Display Name and Domain name to describe
- errors: Fall back to full error message
- cluster: Fail name check before calling API
- aws: Check region after profile credentials have been validated
- admin: Advise user to store password securely
- addressing vkareh review
- Fix idp name generation
- Adressing code review items
- describe-cluster: Display Provision Shard if available
- openid: Always show help text for claims
- users: Do not show cluster-admin user
- ccs: Ensure CCS is enabled before asking to disable SCP checks
- edit-cluster: Fallback to interactive mode
- aws: Default to free AMI

Release v0.0.16

---

cmd/create/admin/cmd.go
cmd/describe/admin/cmd.go
cmd/dlt/admin/cmd.go
cmd/list/idp/cmd.go
pkg/ocm/helpers.go

This makes it more user-friendly when the user opens the console.

admin: Rename IDP to Cluster-Admin

---

CHANGES.adoc
pkg/info/info.go

- admin: Rename IDP to Cluster-Admin
- ingress: Enable interactive mode
- Red Hat OpenShift Service on AWS
- Remove shard info from describe cluster
- roles: Update flow to use grant and revoke

Release v0.1.0

---

cmd/initialize/cmd.go
cmd/verify/permissions/cmd.go
pkg/aws/client.go
pkg/aws/permissions.go

Fixes: [OSD-4708](https://issues.redhat.com/browse/OSD-4708)
Note that ValidateSCP is not testable because of calling private functions continuously. As well as that can be handled in that PR, though I'd prefer to work on it at another PR

refactor(init): verify permissions for osdccsadmin using ValidateSCP

---

assets/bindata.go
cmd/create/cluster/cmd.go
cmd/validations/validations.go
pkg/aws/client.go
pkg/aws/client_test.go
pkg/aws/utils.go
pkg/cluster/cluster.go
pkg/ocm/regions/regions.go
templates/cloudformation/iam_user_osdCcsAdmin.json

Rotate IAM access keys for the IAM user osdCcsAdmin user each time we use the client to create a cluster. There is no need to permanently store these credentials since they are only used on create, the cluster uses a completely different set of IAM credentials provisioned by this user.

 Rotate osdCcsAdmin credentails on creation of each cluster

---

cmd/dlt/machinepool/cmd.go
cmd/edit/cluster/cmd.go
cmd/edit/machinepool/cmd.go
cmd/list/machinepool/cmd.go
docs/rosa_edit_cluster.md

Since we have the machinery for managing machinepools, we can scale the
cluster itself using this resource and so remove the scaling options on
'edit cluster'.

machinepool: Allow managing 'default' machinepool

---

CHANGES.adoc
pkg/info/info.go

- refactor(init): verify permissions for osdccsadmin using ValidateSCP
- machinepools: Support full CRUD operations for machine pools
- Added validation for name
- Added Details Page Link
- machinepool: Allow managing 'default' machinepool
- Rotate osdCcsAdmin credentails on creation of each cluster (#118)

Release v0.1.1

---

cmd/create/idp/cmd.go
cmd/create/idp/github.go
cmd/create/idp/gitlab.go
cmd/create/idp/google.go
cmd/create/idp/ldap.go

For any required attributes, if the user has not set it as a flag in the
CLI, we fallback to displaying the interactive mode for it instead of
failing the request. This also means that for any attribute that the
user has explicitly set through a flag, the tool will not show it even
if the user requested interactive mode.

idp: Always use interactive mode on unset required flags

---

cmd/create/machinepool/cmd.go
cmd/edit/machinepool/cmd.go
docs/rosa_create_machinepool.md

When creating a new machinepool, we now add a default instance type
(m5.xlarge) and drop the user into interactive mode if there is missing
required data.
Also provide faster validation on the number of compute nodes when
editing the default machine pool.

machinepool: Fix interactive mode

---

cmd/create/cluster/cmd.go

When a user provides some random channel-group (or one that she isn't authorized to see) she receives the following error:
```
[nshneor@localhost moactl]$ ./rosa create cluster --channel-group=foo
? Cluster name: foo
? Multiple availability zones (optional): No
? AWS region: us-west-1
E: Expected a valid OpenShift version: please provide options to select from
```
This patch fixes this behavior by returning a more clear error message for this scenario:
```
...
E: Failed to find versions for the provided channel-group: 'foo'.
```
JIRA: https://issues.redhat.com/browse/SDA-2968
cc: @vkareh @igoihman

Return clear error message when no version is found

---

CHANGES.adoc
pkg/info/info.go

- Remove API ingress when listing ingress
- idp: Always use interactive mode on unset required flags
- Added Confirmation option for default network parameters
- Update implementation to include the default values in the interactive mode only
- Enabling Interactive mode if no arguments specified
- machinepool: Fix interactive mode
- Add support for existing VPC
- [rosa create cluster] Return more clear error message when no versions are found.

Release v0.1.2

---

README.md
cmd/create/cluster/cmd.go
cmd/login/cmd.go
docs/rosa_login.md
pkg/cluster/cluster.go
pkg/ocm/properties/properties.go
pkg/ocm/versions/versions.go

Since we're now moving paid AMIs to be a feature flag in Unleash, we
remove the attribute from here and let OCM make the decision based on
the user's organization.
We also finalize the transition from MOA to ROSA, since all dependencies
are now deployed.

Remove paid AMI flag and finalize ROSA transition

---

cmd/dlt/cmd.go
cmd/dlt/upgrade/cmd.go
cmd/list/cmd.go
cmd/list/upgrade/cmd.go
cmd/rosa/main.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/cmd.go
docs/rosa.md
docs/rosa_delete.md
docs/rosa_delete_upgrade.md
docs/rosa_list.md
docs/rosa_list_upgrades.md
docs/rosa_upgrade.md
docs/rosa_upgrade_cluster.md
go.mod
go.sum
pkg/ocm/upgrades/upgrades.go
pkg/ocm/versions/versions.go

When there are available OpenShift version upgrades for a cluster, this
set of commands will allow the customer to list, schedule, and cancel
them as needed.
https://asciinema.org/a/DSX7yu5NIDQ74vzeoWVroUqKQ

upgrades: Allow scheduling, listing, canceling cluster upgrades

---

CHANGES.adoc
pkg/info/info.go

- create: Ask user before showing subnets
- Dont ignore subnets from command line args if provided
- [rosa create cluster] Verify provided subnets for Existing VPC exist in AWS
- Remove paid AMI flag and finalize ROSA transition
- add taints to machinepool commands
- upgrades: Allow scheduling, listing, canceling cluster upgrades

Release v0.1.3

---

OWNERS

Allow contributing members to review and approve PRs, to speed up
review process in moactl

Adding Orange team members to OWNERS file

---

cmd/login/cmd.go
docs/rosa_init.md
docs/rosa_login.md

Since end-users should not have access to our integration and staging
environments, there's no need to expose the '--env' parameter.

login: Hide 'env' parameter

---

cmd/create/cluster/cmd.go
cmd/edit/machinepool/cmd.go

Instead of waiting for the API request to return a failure, we can
easily validate that the user requests compute nodes in multiples of
3 for multi-az clusters.

multi-az: Validate that compute nodes are multiple of 3

---

cmd/create/cluster/cmd.go

If no version is set in the CLI, the interactive mode does not set
a proper default. This means that a user pressing [Enter] through the
prompts will end up _not_ selecting a version, even though it appears as
they do.

create-cluster: Set default version

---

cmd/create/cluster/cmd.go
cmd/create/cmd.go
cmd/describe/cluster/cmd.go
cmd/edit/cluster/cmd.go
docs/rosa_create.md
docs/rosa_create_admin.md
docs/rosa_create_cluster.md
docs/rosa_create_idp.md
docs/rosa_create_ingress.md
docs/rosa_create_machinepool.md

Since users will not be able to access private clusters unless they
configure their network settings in AWS, we warn them whenever creating
a private cluster (or editing a cluster to make it private).
We also display whether the cluster is private in the 'describe cluster'
output.
Demo: https://asciinema.org/a/EtUqEPWae07r2Fj8stIzJ9Wa0

cluster: Show warnings when user makes cluster private

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/cmd.go
cmd/edit/machinepool/cmd.go

This change disallows entering negative numbers on any machine pool
replicas, and will validate the minimum required number of nodes based
on the cluster type and machine pool type.

replicas: Fix local validation for worker nodes and machinepool replicas

---

.golangci.yml

It limits the order of struct members, e.g.:
struct of size 320 bytes could be of size 312 bytes (maligned)
Such micro-optimizations are not interesting for this project IMHO.
@zgalor @vkareh please review.

Disable `maligned` linter

---

cmd/login/cmd.go
docs/rosa_init.md
docs/rosa_login.md

As a user, it's unclear where I get a token when trying to use `rosa` programatically.

login: Add link to retrieve tokens

---

CHANGES.adoc
pkg/info/info.go

- Adding Orange team members to OWNERS file
- Update OWNERS
- aws: Advise user to run init for failed credentials
- init: Advise user to run init for failed credentials
- user: Determine if user exists before revoking
- rosa: Rename repository from moactl to rosa
- create-cluster: Set default version
- multi-az: Validate that compute nodes are multiple of 3
- login: Hide 'env' parameter
- cluster: Show warnings when user makes cluster private
- replicas: Fix local validation for worker nodes and machinepool replicas
- describe-cluster: Display scheduled upgrades
- login: Add link to retrieve tokens
- Disable `maligned` linter
- Fix formatting and add generated docs
- Add autoscaling support
- addons: Enable all commands
- addons: Use install command instead of create
- addons: Allow …

Release v0.1.4

---

cmd/describe/addon/cmd.go
cmd/install/addon/cmd.go
cmd/rosa/main.go
cmd/uninstall/addon/cmd.go
cmd/uninstall/cmd.go
docs/rosa.md
docs/rosa_uninstall.md
docs/rosa_uninstall_addon.md
go.mod
go.sum
pkg/cluster/cluster.go

Since some add-ons require custom parameters before installation, we
iterate through the list generating interactive prompts for those
parameters. Those parameters are then sent as part of the payload to the
add-on installation API and will be available in the cluster's addon
target namespace.
Also, since OCM now supports uninstalling addons from any managed cluster, we
enable this new command for ROSA clusters.

addons: Uninstall and custom parameters

---

cmd/edit/machinepool/cmd.go

Require min/max replicas on interactive mode iff existing machinepool autoscaling is disabled
Related: https://issues.redhat.com/browse/SDA-3543

Require min/max replicas iff existing machinepool autoscaling is disabled

---

CHANGES.adoc
pkg/info/info.go

- Require min/max replicas on interactive mode iff existing machinepool autoscaling is disabled
- addon: Support addon uninstallation form cluster
- addons: Support add-on installation parameters
- add openshift version to describe output

Release v0.1.5

---

cmd/edit/cluster/cmd.go
cmd/list/user/cmd.go
docs/rosa_edit_cluster.md
pkg/cluster/cluster.go

Because adding a user to cluster-admins already requires manual
intervention, enabling it first seems superfluous and can lead to
customer friction. We remove this requirement and the associated flag,
and immediately allow customers to grant users the cluster-admin role
without the need for an explicit opt-in for a cluster.

cluster-admins: Remove explicit enable

---

pkg/ocm/machines/machines.go

Since size is an arbitrary string, sorting by it means that 'xlarge' and
'small' are next to one another. CPU cores is already used to determine
the size, and sorting by it is more consistent.

machines: Sort machine types by CPU cores

---

cmd/describe/cluster/cmd.go

@jonquilwilliams this will help with your multiAZ PR https://github.com/openshift/managed-openshift-docs/pull/13
> $ ./rosa describe cluster jeder-log-prod1                                                          
Name:                       jeder-log-prod1                                                                                             
OpenShift Version:          4.6.8                                                                                                       
DNS:                        jeder-log-prod1.tg7j.p1.openshiftapps.com                                                                   
ID:                         1i7naeu990l3ark4u9jeae7pjl86nc0b                                                                            
External ID: …

add multi-az status to describe

---

cmd/initialize/cmd.go

When running init, we also ensure the user is logged in. If the user
sets any login flags, we force those as part of the login process,
otherwise we reuse the existing OCM session. By comparing against an
explicit list, we make sure that another flag (e.g. --debug) won't
trigger a re-login with incomplete flags.

init: Use explicit login flag checks

---

cmd/create/cluster/cmd.go
cmd/create/idp/cmd.go
cmd/create/machinepool/cmd.go

To ensure that the names of clusters/idps/machinepools all have
invisible characters stripped, we trim them as soon as we read them from
the argument flags and after they are read from the interactive mode.

Trim user-provided machine-friendly names

---

go.mod
go.sum

The v0.1.156 version of the ocm-sdk-go package should fix issues when
connecting to the OCM API on a Windows machine, as it bypasses loading
a non-available system root certificate pool.

ocm-sdk: Update version

---

cmd/create/cluster/cmd.go
pkg/cluster/cluster.go

In the case where a user went through the interactive mode and the
cluster failed installation, they would need to go through the entire
interactive prompt again until their cluster succeeds. To simplify this
scenario, the cluster creation process now prints out a populated
command to re-create a cluster with the same parameters.
This is useful even if the cluster does not fail installation to allow
for reproducible clusters.
Demo: https://asciinema.org/a/qu9pOxdo49lF9iJO4JraIPgUn

interactive: Output command to rerun cluster creation

---

pkg/cluster/cluster.go

Since the AWS credentials are not longer generated during 'init',
suggesting to the user to run 'init' is misleading.

cluster: Remove suggestion to run init

---

cmd/grant/user/cmd.go
cmd/revoke/user/cmd.go

If local validation fails, there is no need to call the API as it is
expected to fail again.

user: Avoid calling API after failed validation

---

cmd/create/idp/google.go

If hosted domain is supplied for mapping methods other than 'lookup', we
do not need to force interactive mode.

google: Only force interactive mode when necessary

---

cmd/create/cluster/cmd.go
pkg/cluster/cluster.go
pkg/ocm/helpers.go

Usage: `rosa create cluster --flavour=scale-test-r` (default is `[osd-4](https://issues.redhat.com/browse/osd-4)`)

cluster: Add hidden flag to set cluster flavour

---

cmd/create/cluster/cmd.go
pkg/ocm/properties/properties.go

Since we have an internal flag to create fake clusters that consume no
AWS resources, we can expose that as a _hidden_ flag when creating
clusters.

cluster: Allow the creation of fake clusters

---

cmd/describe/cluster/cmd.go
cmd/edit/cluster/cmd.go

Also provide a better warning regarding API versus Ingress when setting
a cluster as private.

cluster: Use correct privacy flag on describe

---

CHANGES.adoc
pkg/info/info.go

- fix example
- Align command with auto-generated docs
- machinepools: Fix doc typos
- machinepools: Fix default taints in interactive mode
- upgrade: Ensure interactive mode for schedule
- upgrade: Display explicit values in grace period help
- upgrade: Specify UTC for schedule time
- Trim user-provided machine-friendly names
- ocm-sdk: Update version
- addons: Fix parameter defaults in interactive prompt
- interactive: Output command to rerun cluster creation
- cluster: Remove suggestion to run init
- user: Avoid calling API after failed validation
- google: Only force interactive mode when necessary
- idp: Validate mapping method input
- Show success message on write operations
- args: Clean up argument and flag requirements
- Cleaning up some leftover obsolete code from autoscaling PR …

Release v0.1.7

---

Makefile

Since assets are rebuilt as part of the development flow, there is no
need to have it as a hard dependency on the main build process. This
simplifies build requirements on automated pipelines.

Remove asset build dependency

---

cmd/create/cluster/cmd.go
cmd/describe/cluster/cmd.go
cmd/dlt/cluster/cmd.go
cmd/logs/install/cmd.go
cmd/logs/uninstall/cmd.go

For programmatically-called commands, we should only rely on Run, as
PreRun would need to be explicitly called. Otherwise the command will
not have access to the argument flags.

cmd: Use Run instead of PreRun

---

cmd/upgrade/cluster/cmd.go

Since only a few specific values are allowed, we check that user-entered
values match one of the allowed values.

upgrade: Validate node drain grace period

---

cmd/list/upgrade/cmd.go

When listing available upgrades, cast parts of the semver to numbers so
that we can compare the latest numeric version for each minor.

upgrades: Fix list of recommendations

---

CHANGES.adoc
pkg/info/info.go

- Remove asset build dependency
- cmd: Fix programmatically-run commands
- init: Fix empty flavour when validating cluster creation
- Fix Makefile build command
- cmd: Use Run instead of PreRun
- upgrade: Validate node drain grace period
- upgrades: Fix list of recommendations

Release v0.1.8

---

cmd/install/addon/cmd.go

Currently when an addon parameter fails validation it shows the ID,
which might be confusing for some users. This changes it to the
displayed name to make it more user-friendly.

addon: Validation message should show parameter name

---

cmd/list/addon/cmd.go
pkg/ocm/helpers.go

Since all ROSA clusters are BYOC and use AWS as the cloud provider, we
can further narrow down the list of addons to those that contain quota
resources matching those specifications.
When listing addons available for a cluster, determine whether AMS will
allow the addon to be installed based on the availability zone. If the
addon quota is not compatible with the cluster, we hide it from the
list.

addons: Filter list of addons to those compatible with ROSA

---

cmd/docs/cmd.go

Instead of hard-coding the year, we can generated based on the date in
which the binary was built last.

docs: Update copyright year for manpages

---

cmd/edit/addon/cmd.go
cmd/edit/cmd.go
cmd/install/addon/cmd.go
pkg/cluster/cluster.go
pkg/interactive/interactive.go

Since some addon parameters support being edited, we can run through the
parameter list to allow the user to update them, defaulting to the
values currently set up in the existing addon installation.

addons: Allow editing of addon parameters

---

cmd/upgrade/cluster/cmd.go

When the user passes the schedule time or date as a CLI flag in an
invalid format, we should display what the expected format should be
instead of defaulting the the current datetime.

upgrade: Display datetime format in error output

---

cmd/describe/cluster/cmd.go
cmd/dlt/upgrade/cmd.go
cmd/list/upgrade/cmd.go
cmd/upgrade/cluster/cmd.go
pkg/ocm/upgrades/upgrades.go

Instead of always referring to a 'scheduled upgrade', we now use the
actual upgrade state to display 'pending upgrade', 'started upgrade',
etc.

upgrade: Display upgrade state whenever showing existing upgrades

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go
pkg/arguments/arguments.go

To enable scriptin/automation for addon installation, we now support
passing arbitrary flags to the 'install|edit addon' commands. When these
flags match the addon parameter ID, they get set as the chosen value and
so the interactive mode can be skipped.

addons: Allow installation parameters in CLI

---

cmd/create/cluster/cmd.go
cmd/list/version/cmd.go

When listing available versions, the format should match the expected
input when creating a cluster.

versions: Align version list with cluster creation

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go

There is currently no use case for float values as addon parameters, and
setting them as integers looks better from the UX point of view.

addons: Use integer for numeric params

---

cmd/dlt/machinepool/cmd.go
cmd/edit/machinepool/cmd.go
cmd/list/machinepool/cmd.go

This aligns it with the OCM Web UI and avoids possible confusion.

machinepools: Display default machine pool as Default

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go

When a nil IPNet is parsed, it returns a string "<nil>". This breaks
validation in the API when determining whether the addon parameter has
any data, so we set it as "" in that case.

addons: Send empty string when CIDR is nil

---

cmd/rosa/main.go

Adding the flags managed by golang/flag adds an unnecessary verbosity
level flag that is not currently used by ROSA.

flag: Remove unnecessary flags

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/cmd.go

If the user sets an explicit replica when creating a machine pool, we
should not ask about auto-scaling, as it should always be set to false.

machinepool: Skip autoscaling prompt when setting replicas

---

cmd/create/machinepool/cmd.go

Instead of continuing with max-replicas, if we can already determine
that the min-replicas are wrong, we should error out before moving on.

machinepool: Error out on invalid min-replica

---

cmd/create/admin/cmd.go

This makes the copy-pasteable command to work on Windows and makes it
clear that it will take some time to sync the new user credentials.

cluster-admin: Format the success message

---

cmd/create/cluster/cmd.go
cmd/create/cmd.go
cmd/create/idp/cmd.go
cmd/create/ingress/cmd.go
cmd/create/machinepool/cmd.go

Not all create commands support interactive mode, so instead of adding
it to all sub-commands, we add it to those that do.

interactive: Remove flag from global create

---

cmd/list/version/cmd.go
pkg/ocm/versions/versions.go

When selecting the default version for any cluster, we align the
selection query with OCM. This ensures that the selected version is the
closest ROSA-enabled one to the current default for OSD.
We also display available upgrades when listing versions.

version: Align sort with OCM version list

---

cmd/install/addon/cmd.go
cmd/uninstall/addon/cmd.go

If an addon installation exists, we should not attempt re-installation.
Similarly, if an addon installation does not exist, there is no reason
to uninstall it.

addons: Check existence of addon installation before installing

---

cmd/grant/user/cmd.go
cmd/revoke/user/cmd.go
pkg/ocm/helpers.go

The cluster-admin username is reserved and so we disallow grant and
revoke actions on this user.

users: Disallow grant and revoke on cluster-admin

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go
cmd/install/cmd.go
pkg/arguments/arguments.go

If the user sets all required addon parameters as command-line flags, we
can safely skip the interactive mode. Otherwise we enable it.

addons: Enforce interactive mode if required params are missing

---

cmd/describe/cluster/cmd.go

Also reformat the output to display data in a more organized way.
Example output:
```
$ rosa describe cluster -c vkareh-rosa
Name:                       vkareh-rosa
ID:                         1jegmk19749k70qjt44otfncl6gi96p4
External ID:                75ecee0e-5ea0-49dd-934a-07671660f0df
OpenShift Version:          4.6.1
DNS:                        vkareh-rosa.4bei.i1.devshift.org
AWS Account:                765374464689
API URL:                    https://example.com/veryfakeapi
Console URL:                https://https://example.com/veryfakewebconsole
Region:                     us-east-1
Multi-AZ:                   false
Nodes:
- Master:                  3
- Infra:                   2
- Compute:                 3 (m5.xlarge)
Network:
- Service CIDR: …
```

describe: Add cluster network configuration

---

CHANGES.adoc
pkg/info/info.go

- addons: Allow editing of addon parameters
- addons: Accept numeric parameters as floats
- upgrade: Display datetime format in error output
- upgrade: Display upgrade state whenever showing existing upgrades
- login: Update URL for integration environment
- addons: Allow installation parameters in CLI
- ingress: Better message when deleting non-existent ingress
- versions: Align version list with cluster creation
- Add missing region flags
- idp: Allow schema-less hosted domains on Google IDP
- addons: Disallow editing addons without parameters
- addons: Disallow editing params of a non-ready addon
- addons: Use integer for numeric params
- logs: Report better errors for incompatible installation states
- machinepools: Display default machine pool as Default
- clusters: Remove count flag …

Release v1.0.0

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go
pkg/arguments/arguments.go

Since we are overriding cobra's flag parsing function, we need to also
check whether the --help/-h flag is being passed in the CLI. The cobra
executor expects the raw error to match and so we also avoid wrapping
the flag parsing error.

arguments: Parse help flag when overriding flag parsing

---

cmd/upgrade/cluster/cmd.go

When entering date and time in an unexpected format, we show the
expected format in the error message.

upgrade: Display expected format in error

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go

If a user sets all required addon parameters in the CLI in
non-interactive mode, we skip the prompt non-required ones. Since the
prompt is not shown, we should avoid sending these values as part of the
API request.

addons: When setting CLI params skip unset values

---

cmd/list/addon/cmd.go
pkg/ocm/helpers.go

Based on quota calculation we determine whether the addon is available
to be installed and display it when listing addons.

addons: Display availability

---

CHANGES.adoc
pkg/info/info.go

- arguments: Parse help flag when overriding flag parsing
- revoke: Fix example and help text
- grant: Remove unnecessary interactive flag
- addons: When setting CLI params skip unset values
- upgrade: Display expected format in error
- addons: Display availability

Release v1.0.1

---

cmd/describe/cluster/cmd.go

Since we can already list the machine pools with a different command,
displaying the instance type during describe can cause confusion if the
machine pool instance types do not match the default compute node
instance type.

describe: Remove instance type

---

cmd/logs/install/cmd.go

Since logs are forwarded directly from the installer, we remove log
lines containing misleading KUBECONFIG instrutions as well as lines
already redacted by Hive.

logs: Filter out misleading output

---

cmd/edit/addon/cmd.go

Since editing does not require a full interactive flow if at least one
parameter is supplied, we just verify that any CLI flags that match an
addon parameter are editable.

addons: Error when editing non-editable parameters

---

pkg/cluster/cluster.go

To display the complete terms acceptance error, which includes the URL
in the details, we intercept the 451 error code and display a static
link to the terms and conditions app.

errors: Display legal terms URL

---

pkg/aws/client.go
pkg/aws/utils.go

Currently we don't support using STS users to create ROSA clusters. This PR will better inform the user of the issue. 
Old error message:
`E: Error creating AWS client: ValidationError: Must specify userName when calling with non-User credentials`
New error message:
```
E: Error creating AWS client: The AWS Access Key ID AAAFFFDSDDDSSSSSS is associated with with STS credentials ARN arn:aws:sts::11223344556612:assumed-role/Role/SREAccess
STS users are not supported, please set AWS credentials to use an IAM user
```
Feel free to make suggestions on the error message.

aws: Add helpful error message when using STS credentials

---

cmd/logs/install/cmd.go

This causes confusion to users and is unnecessary for logs.
Fixes https://github.com/openshift/openshift-docs/issues/30903

logs: Redact KUBECONFIG line

---

CHANGES.adoc
pkg/info/info.go

- aws: Enable skip SCP check on init
- ocm-sdk-go: Bump version
- init: Track ad-hoc authenticated events

Release v1.0.3

---

cmd/initialize/cmd.go
cmd/verify/permissions/cmd.go
cmd/verify/quota/cmd.go

Since we want to capture all instances of a client being created with
STS credentials, we move things around and parse the error coming from
the AWS client for the "STS" string, then we log an event for it.

aws: Log event when creating client with STS credentials

---

cmd/initialize/cmd.go

When running the 'init' command, the user has the option of setting the
AWS_REGION environment variable or passing a --region flag. Instead, the
cluster dry-run always ends up using the default 'us-east-1'. This fix
reads the correct region from the session.

init: Use correct region instead of default

---

cmd/create/cluster/cmd.go
cmd/create/ingress/cmd.go
cmd/edit/ingress/cmd.go
go.sum
pkg/cluster/cluster.go

To allow fully private clusters, we use AWS PrivateLink. Setting this
new flag will ensure that the default ingress is private, as well as
setting the corresponding configuration on the cluster deployment and
install config.

Enable PrivateLink on clusters

---

cmd/create/cluster/cmd.go

To avoid confusion due to non-GA'd features, we hide all mentions of
PrivateLink when creating a cluster. Only if the user explicitly sets
the --private-link flag, we then show all available options and help
text.

PrivateLink: Hide references to PrivateLink

---

cmd/initialize/cmd.go

This PR will correctly handle the `--disable-scp-checks` argument when supplied to the `rosa init` command by ignoring SCP checks on the `osdCcsAdmin` user. As most enterprise AWS accounts have significant guardrails in place, the SCP policy ROSA is validating against is often going to be rejected. This allows us to continue deployment.

Correctly handle --disable-scp-checks argument in rosa init

---

CHANGES.adoc
pkg/info/info.go

- Enable PrivateLink on clusters
- PrivateLink: Hide references to PrivateLink
- Correctly use the --disable-scp-checks parameter when supplied to init command
- Add support for STS clusters
- describe: Output OIDC Endpoint URL if available

Release v1.0.6

---

cmd/create/machinepool/cmd.go
cmd/edit/machinepool/cmd.go

This is blocked until this is supported in CS backend

Allow setting 0 replicas to autoscaling machine pool (Not default)

---

cmd/create/cluster/cmd.go
cmd/describe/cluster/cmd.go
pkg/cluster/cluster.go

By default OCM is 'Preparing account' during 'Pending', but if we
override the state description, we should show that instead.
Example:
```
$ rosa describe cluster -c vkareh-sts | grep State
State:                      pending (Waiting for OIDC configuration)
```

describe: Display description during Pending state

---

CHANGES.adoc
pkg/info/info.go

- Added SSO Validation
- Removed default region from CloudFormation stack check
- verify: Include note about quota limitations
- Disable IAM user checks for STS
- Added wait for accountclaims to get ready
- Fix tests with missing TagUser call
- Increase golangci timeout to 5 minutes
- Added new rosa list instance-types api
- Support STS users (#351)
- sts: Normalize instace role parameters
- sts: Expose all flags
- sts: Ensure interactive mode for STS credentials without role ARN
- sts: Add support role ARN attribute

Release v1.0.8

---

.golangci.yml
cmd/create/cluster/cmd.go
pkg/cluster/cluster.go

A few flags were missing from the re-create command output.
Also since the interfacer has been deprecated due to it being prone to bad suggestions, we remove it from this repository.

create: Add missing flags to re-create script

---

cmd/create/cluster/cmd.go
go.mod
go.sum
pkg/ocm/versions/versions.go
vendor/github.com/hashicorp/go-version/CHANGELOG.md
vendor/github.com/hashicorp/go-version/LICENSE
vendor/github.com/hashicorp/go-version/README.md
vendor/github.com/hashicorp/go-version/constraint.go
vendor/github.com/hashicorp/go-version/go.mod
vendor/github.com/hashicorp/go-version/version.go
vendor/github.com/hashicorp/go-version/version_collection.go
vendor/modules.txt

When creating STS clusters we should only allow 4.7.11 and higher, as
lower OpenShift versions will fail installation when using STS
attributes.

versions: Ensure versions with STS support

---

cmd/describe/cluster/cmd.go
cmd/list/cluster/cmd.go
cmd/list/idp/cmd.go
cmd/list/ingress/cmd.go
cmd/list/instancetypes/cmd.go
cmd/list/machinepool/cmd.go
cmd/list/region/cmd.go
cmd/list/version/cmd.go
go.mod
pkg/output/flag.go
pkg/output/output.go
vendor/modules.txt

To use this, you can call `rosa describe cluster -c foo -o json` or `rosa list regions --output yaml`, etc. It also has autocomplete (if you have it enabled) so that you can do `--output [tab][tab]` and auto-complete the `json`/`yaml` parts.

output: Add flag for JSON and YAML output

---

cmd/describe/cluster/cmd.go
cmd/login/cmd.go

The new URL already works so it's safe to merge & release this,
and since users take time to upgrade the CLI, better sooner IMHO.
* internal `StageURL` has not moved yet, will need separate update.
related to https://github.com/openshift-online/ocm-cli/pull/294, https://issues.redhat.com/browse/OSDOCS-2290

Update URLs for upcoming move to console.redhat.com

---

pkg/aws/quota.go

Recent changes in AWS quota have caused the EBS quota checks to fail. This PR allows the quota checks to pass, this requires testing as the low quota likely will prevent a cluster install.
I'm going to open this PR and put it on hold until we work with AWS to figure out the correct path forward.

Reduce EBS quota checks

---

cmd/create/idp/cmd.go

To create an administrator user it's `admin` not `user`.
It also seems that `user` isn't available anymore either.
Signed-off-by: JJ Asghar <awesome@ibm.com>

There is no "user" anymore

---

pkg/ocm/clusters.go

Since external IDs are unique and are a valid identifier for a cluster,
we should allow clusters to be found by external ID.

ocm: Find cluster by external ID

---

cmd/create/cluster/cmd.go

Since etcd is already encrypted and this flag provides a secondary layer
of encryption, we note that in the help text. This also shows up in the
interactive help.

create-cluster: Update help text for etcd encryption

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
pkg/aws/policies.go

Since we now have the list of valid credential requests we can generate
all necessary operator IAM roles directly. The operator-iam-roles flag
is now deprecated and we only ask for an optional operator-roles-prefix
that defaults to the cluster name.
New command format for STS clusters:
```
rosa create cluster \
--cluster-name vkareh-sts \
--role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Installer-Role \
--support-role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Support-Role \
--master-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-ControlPlane-Role \
--worker-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-Worker-Role \
--operator-roles-prefix FOO # (defaults to cluster name)
```

create-cluster: Automatically populate operator IAM roles

---

cmd/create/oidcprovider/cmd.go
pkg/aws/client.go
pkg/aws/idps.go

If a cluster already has the OIDC provider configured, we skip trying to
re-create it. Also, if there is a configuration issue we expose it to
the user.

create-oidcprovider: Verify if OIDC Provider already exists

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

If a customer creates roles and policies for OpenShift 4.7 clusters and
then decides to upgrade to 4.8, we need to ensure that they can re-run
the initialization commands that will update the resources to be
compatible. Since later versions are a superset of older versions, we
enforce upgrading and ignore downgrade requests.

account-roles: Ensure that roles and policies can be upgraded

---

cmd/create/machinepool/cmd.go
cmd/list/machinepool/cmd.go
pkg/interactive/interactive.go

```
$ rosa create machinepool -c 1m1hjsebcs6sbnv3qs5m9u1k7nhhlc9m --name=mp-2 --replicas=2 --instance-type=m5.xlarge --use-spot-instances --spot-max-price=0.5
$ rosa create machinepool -c 1m1hjsebcs6sbnv3qs5m9u1k7nhhlc9m --name=mp-1 --replicas=2 --instance-type=m5.xlarge --use-spot-instances
$ rosa list machinepools -c 1m1hjsebcs6sbnv3qs5m9u1k7nhhlc9m
ID       AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONES    SPOT INSTANCES
Default  No           2         m5.xlarge                          us-east-1a            No
mp-2     No           2         m5.xlarge                          us-east-1a            Yes (max $0.50)
mp-1     No           2         m5.xlarge                          us-east-1a            Yes (on-demand)
```

Add support for machine pool spot instances

---

assets/bindata.go
pkg/aws/policies.go
templates/policies/4.7/operator_iam_role_policy.json
templates/policies/4.8/operator_iam_role_policy.json
templates/policies/4.9/operator_iam_role_policy.json
templates/policies/sts_installer_trust_policy.json
templates/policies/sts_instance_controlplane_trust_policy.json
templates/policies/sts_instance_worker_trust_policy.json
templates/policies/sts_support_trust_policy.json

When creating roles in AWS, if the role already exists, instead of
ignoring the update we ensure that the new trust policy contains the
combination of what was there and the new one. That way the new policy
does not override the old one.

roles: Update trust policy

---

pkg/ocm/clusters.go

When blocking a pending cluster from installing based on a waiting
account claim, ensure that the blocking cluster is not STS.

clusters: Ensure blocking pending clusters are non-STS

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

Since the operator role policies created through 'rosa create
account-roles' are tagged with the operator metadata, we can drop the
requirement for a user-set prefix and instead automatically find the
corresponding policy.

create-operatorroles: Auto-find policies for roles

---

CHANGES.adoc
hack/commit-release.sh
pkg/info/info.go

- confirm: Move to interactive package
- properties: Move to separate package
- cluster: Move to ocm package
- ocm: Move all OCM API wrappers to ocm package
- ocm: Split resources into files
- ocm: Refactor OCM client code
- ocm: Do not expose internal API structure
- add etcd-encryption flag to buildCommand
- ocm: Bump SDK version
- ocm: Bump SDK version
- aws: Filter clusters by AWS account ID
- output: Add flag for JSON and YAML output
- Add region tag for older versions
- There is no "user" anymore
- Added hibernation and resume support to rosa cli
- hack: Add directory with development scripts
- Update cmd/create/idp/cmd.go
- output: Ensure that JSON output for empty arrays looks correct
- reporter: Send WARN output to STDERR
- aws: Refactor AWS client code
- init: Replace …

Release v1.1.0

---

cmd/create/cluster/cmd.go

Since the prefix is used to generate the role name, the prefix itself
needs to conform to the Role Name regular expression.

create-cluster: Validate operator roles prefix

---

cmd/create/cluster/cmd.go

We want a customer to be able to add the option for etcd encryption as
a CLI flag but do not want to present this in interactive mode.

create-cluster: Remove etcd encryption from interactive mode

---

assets/bindata.go
templates/policies/osd_scp_policy.json

Since we only use SCP checks to verify whether a cluster can be created,
we need to only query for the strictly necessary permissions.
Ref: https://cloud.redhat.com/dedicated/ccs

Remove unnecessary SCP checks

---

cmd/create/accountroles/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go
pkg/interactive/confirm/confirm.go

This is useful for non-destructive operations that echo the intention of
the user when running the command.

confirm: Add confirmation prompt with default of 'Y'

---

cmd/logs/install/cmd.go
cmd/logs/uninstall/cmd.go

This fixes exiting during log watch after uninstalling a cluster. It also fixes exiting any log watch on Windows.

logs: Exit once done watching logs

---

cmd/create/accountroles/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go

We want to have insight on whether users prefer automatic versus manual
mode, as moving forward we want to be able to provide more options for
resource creation.
Relevant: https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/3223

events: Track mode for AWS resource creation

---

cmd/create/accountroles/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go
pkg/reporter/reporter.go

The output of certain commands can be piped or directed to a file for
processing. In this case we want to avoid info-level output, as it
interferes with the actual command output.

reporter: Determine whether output is meant for terminal

---

cmd/create/cmd.go
cmd/create/idp/cmd.go
cmd/describe/cluster/cmd.go
cmd/describe/cmd.go
cmd/dlt/cluster/cmd.go
cmd/dlt/cmd.go
cmd/edit/cmd.go
cmd/grant/cmd.go
cmd/grant/user/cmd.go
cmd/hibernate/cluster/cmd.go
cmd/hibernate/cmd.go
cmd/install/cmd.go
cmd/list/cluster/cmd.go
cmd/list/cmd.go
cmd/list/user/cmd.go
cmd/logs/cmd.go
cmd/resume/cluster/cmd.go
cmd/resume/cmd.go
cmd/revoke/cmd.go
cmd/uninstall/cmd.go
cmd/upgrade/cmd.go
cmd/whoami/cmd.go
pkg/aws/client.go

Also simplify code by removing the explicit set in every client
instantiation, and read the flag directly from the AWS client builder.

region: Move flag up a level

---

cmd/logs/install/cmd.go

Since we do not control the installer output, redacting can lead to
missed log lines and cause confusion when debugging. Hive already
redacts private and sensitive data when necessary.

logs-install: Do not redact install log output

---

CHANGES.adoc
pkg/info/info.go

- hack: Fix query to fetch changelog
- create-operatorroles: Fix prefix prompt text
- create-cluster: Validate operator roles prefix
- Fix validation of spot max price
- confirm: Add confirmation prompt with default of 'Y'
- create-cluster: Remove etcd encryption from interactive mode
- config: Use standard config path for ocm.json
- events: Track mode for AWS resource creation
- scp-policy: Remove optional policy checks
- scp-policy: Update to minimum required SCP
- Update OWNERS file
- logs: Exit once done watching logs
- Add customer managed key for rosa cluster
- interactive: Provide real-time validators
- create-accountroles: Use interactive validators
- create-cluster: Use interactive validators
- create-idp: Use interactive validators
- create-machinepool: Use interactive …

Release v1.1.1

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

Since we generate account roles with a predictable pattern, we can determine the proper role ARNs from a single prefix. This simplifies input when creating STS clusters.
Also add a `--sts` flag. This allows the CLI to use sane defaults based on whether the user wants to deploy a cluster using IAM or STS models.

create-cluster: Replace account role ARNs with account roles prefix

---

CHANGES.adoc
pkg/info/info.go

- add check and prompt for required true addon parameters
- create-cluster: Allow setting --output flag
- idp: Allow empty URL and CA Path in interactive mode
- create: Return error when request fails
- permissions-boundary: Fix help and error messages
- fix broken links
- create-cluster: Ensure operator roles are unique
- create-cluster: Replace account role ARNs with account roles prefix
- create-cluster: Add STS flag
- create-cluster: Use AWS Tags to find pre-configured account roles
- create-cluster: Remove account roles prefix flag
- Add validation to user tags
- use default version on create account-roles
- create-cluster: Force AWS PrivateLink for private STS clusters
- logs: Suppress spinner on non-terminal output

Release v1.1.2

---

hack/list-jiras.sh

This is useful when creating errata advisories, which need a list of JIRA cards for QE to verify.
/cc @pvasant @ciaranRoche - make sure that there is always a reference to the relevant JIRA card in any commit message or branch name. It can be just the branch name ('SDA-9999/fix-foo-bar') or the commit message ('SDA-9999: Fix foo bar')

hack: Add script to list JIRA tickets addressed on current release

---

cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go

Since the resulting AWS commands are useful even without the correct
permissions in the current account, we force the mode to manual if the
current user is not allowed to verify the existence of
operator-roles/oidc-provider.

aws: Force manual mode when getting AccessDenied

---

cmd/create/oidcprovider/cmd.go

Closes : https://issues.redhat.com/browse/SDA-4829
Copied thumbprints from http to tls to show no differences in the peer certificates returned : https://gist.github.com/ciaranRoche/3c0054a28c4d7a608a7d8ebc4e06ffa0

SDA-4829 update getThumbprints to use http package instead of tls

---

pkg/aws/policies.go

Since OpenShift policy permissions are incremental across versions, When
creating a cluster, the policy auto-finder should ensure that it can use
current and newer policies, instead of restricting to only the current
version.

policies: Allow compatible policies to create clusters

---

CHANGES.adoc
pkg/info/info.go

- add rosa list account roles
- hack: Add script to list JIRA tickets addressed on current release
- add disable workload monitoring to ROSA
- update user tag regexp to include unicode spaces
- cluster: Support custom properties
- Remove ROSA init account command
- Add StopInstances action to support Hibernation
- add kmskey for sts
- RemoveSTSfrominit
- Bump OCM SDK to v0.1.209
- aws: Silently ignore AccessDenied errors when validating resources
- [SDA-4829](https://issues.redhat.com/browse/SDA-4829) update getThumbprints to use http package instead of tls
- policies: Allow compatible policies to create clusters

Release v1.1.3

---

cmd/create/cluster/cmd.go

Closes : https://issues.redhat.com/browse/SDA-4926
Issues - if mode was not passed explicitly the validation would fail, this change only validates mode if a value is passed

fix sts mode validation

---

cmd/create/oidcprovider/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/dlt/cluster/cmd.go
cmd/dlt/cmd.go
cmd/dlt/oidcprovider/cmd.go
cmd/dlt/operatorrole/cmd.go
pkg/aws/client.go
pkg/aws/idps.go
pkg/aws/policies.go
pkg/ocm/clusters.go

rosa delete operator-roles -c <clusterID>
rosa delete oidc-provider -c   <clusterID>
rosa delete account-roles --role-name  
rosa delete account-roles --role-name 
rosa delete account-roles --role-name 
./rosa delete cluster -c test
```
? Are you sure you want to delete cluster test? Yes
I: Cluster 'test' will start uninstalling now
I: Your cluster 'ttt' will be deleted but the following object may remain
I: Operator IAM Roles:
- arn:aws:iam::765374464689:role/ttt-e1n6-openshift-ingress-operator-cloud-credentials
- arn:aws:iam::765374464689:role/ttt-e1n6-openshift-cluster-csi-drivers-ebs-cloud-credentials
- arn:aws:iam::765374464689:role/ttt-e1n6-openshift-machine-api-aws-cloud-credentials
- arn:aws:iam::765374464689:role/ttt-e1n6-openshift-cloud-credential-operator-cloud-credential-op
- …
```

delete oidc provider and operator roles

---

cmd/verify/permissions/cmd.go

Related: [SDA-4729](https://issues.redhat.com/browse/SDA-4729)

Clarify `verify permissions` cmd is only for non-STS clusters

---

cmd/create/cluster/cmd.go

substituted 'specify' for 'specific'

fix minor typo

---

cmd/create/cluster/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

Related: [SDA-4624](https://issues.redhat.com/browse/SDA-4624)
```
$ ./rosa create cluster --sts --operator-roles-prefix zg-oct-14-u8z3 -c zg-nov-3
? Installer role ARN: arn:aws:iam::765374464689:role/ManagedOpenShift-Installer-Role
I: Using arn:aws:iam::765374464689:role/ManagedOpenShift-ControlPlane-Role for the ControlPlane role
I: Using arn:aws:iam::765374464689:role/ManagedOpenShift-Worker-Role for the Worker role
I: Using arn:aws:iam::765374464689:role/ManagedOpenShift-Support-Role for the Support role
E: Error validating role: A role named 'zg-oct-14-u8z3-openshift-machine-api-aws-cloud-credentials' already exists. Please delete the existing role, or provide a different prefix
```

Check for pre-existing operator roles and error if they exist

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/cmd.go
cmd/upgrade/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/helpers.go
pkg/aws/policies.go

```
? Account role upgrade mode: manual
I: All policy files saved to the current directory
I: Run the following commands to upgrade the account role policies:
aws iam create-policy-version \
--policy-arn arn:aws:iam::765374464689:policy/nov4-Support-Role-Policy \
--policy-document file://sts_support_permission_policy.json \
--set-as-default
aws iam tag-policy \
--tags Key=rosa_openshift_version,Value=4.9 \
--policy-arn arn:aws:iam::765374464689:policy/nov4-Support-Role-Policy
aws iam tag-role \
--tags Key=rosa_openshift_version,Value=4.9 \
--role-name nov4-Support-Role
aws iam create-policy-version \
--policy-arn arn:aws:iam::765374464689:policy/nov4-Installer-Role-Policy \
--policy-document file://sts_installer_permission_policy.json \
--set-as-default
aws iam tag-policy \
--tags …
```

add rosa upgrade account/operator role

---

cmd/create/cluster/cmd.go
pkg/ocm/clusters.go

https://issues.redhat.com/browse/SDA-4981
https://issues.redhat.com/browse/SDA-4982
Removed the '--enable-proxy' argument. Made it behaving the same as 'Use existing VPC', where we don't use any other flag when we set subnets.

removed --enable_proxy argument

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/dlt/oidcprovider/cmd.go
cmd/dlt/operatorrole/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/flag.go
pkg/aws/policies.go

Closes : https://issues.redhat.com/browse/SDA-4818
```
rosa upgrade cluster --cluster croche-upgrade --mode manual                                                                                              
? Version: 4.7.36
I: Ensuring cluster roles and policies are compatible with upgrade.
I: Preparing to upgrade account roles.
I: All policy files saved to the current directory
I: Run the following commands to upgrade the account role policies:
aws iam create-policy-version \
--policy-arn arn:aws:iam::765374464689:policy/croche-upgrade-ControlPlane-Role-Policy \
--policy-document file://sts_instance_controlplane_permission_policy.json \
--set-as-default
aws iam tag-policy \
--tags Key=rosa_openshift_version,Value=4.9 \
--policy-arn …
```

validate sts roles on sts cluster upgrade

---

cmd/create/accountroles/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/dlt/oidcprovider/cmd.go
cmd/dlt/operatorrole/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go

Fixes issue of setting `mode` option in interactive mode.
```
$ rosa create account-roles
I: Logged in as 'croche_openshift' on 'https://api.stage.openshift.com'
I: Current OpenShift Client Version: 4.5.8
? Role prefix: delete
the prefix  delete
? Permissions boundary ARN (optional): 
? Role creation mode: manual
I: All policy files saved to the current directory
I: Run the following commands to create the account roles and …
```

fix interactive setting of `mode` option

---

pkg/aws/client.go
pkg/info/info.go

```
$ rosa list clusters --debug 2>&1 | grep -i user.agent | head -n1
time="2021-11-05T08:12:59-04:00" level=debug msg="Request header 'User-Agent' is 'ROSACLI/1.1.5 aws-sdk-go/1.39.3 (go1.16.8; linux; amd64)'"
```

aws: Add ROSACLI/version to User-Agent string

---

cmd/upgrade/cluster/cmd.go
cmd/upgrade/operatorroles/cmd.go

Closes : 
- https://issues.redhat.com/browse/SDA-5017
- https://issues.redhat.com/browse/SDA-5018
- https://issues.redhat.com/browse/SDA-5022
```
$ rosa upgrade cluster --cluster croche-upgrade --mode manual           
? Version: 4.7.36
I: Ensuring cluster roles and policies are compatible with upgrade.
I: Preparing to upgrade account roles.
I: All policy files saved to the current directory
I: Run the following commands to upgrade the account role policies:
aws iam create-policy-version \
--policy-arn arn:aws:iam::765374464689:policy/croche-test-Installer-Role-Policy \
--policy-document file://sts_installer_permission_policy.json \
--set-as-default
aws iam tag-policy \
--tags Key=rosa_openshift_version,Value=4.9 \
--policy-arn arn:aws:iam::765374464689:policy/croche-test-Installer-Role-Po …
```

Upgrade cluster bug fixes

---

CHANGES.adoc
pkg/info/info.go

- Update OWNERS file
- ROSA: Support cluster-wide proxy during cluster creation
- Add missing update message for default machine pool
- Handle minor issues in delete handling
- clusters: Fix proxy config validations
- updated pendo event for rosa
- Clarify `verify permissions` cmd is only for non-STS clusters
- fix minor typo
- Check for pre-existing operator roles and error if they exist
- add rosa upgrade account/operator role
- removed --enable_proxy argument
- changing cluster proxy attirbutes to pointers
- aws: Add ROSACLI/version to User-Agent string
- validate sts roles on sts cluster upgrade
- fix interactive setting of `mode` option
- [SDA-5022](https://issues.redhat.com/browse/SDA-5022) : fix operator role upgrade being blocked by account role upgrade
- …

Release v1.1.6

---

cmd/create/ocmrole/cmd.go
cmd/create/userrole/cmd.go
cmd/link/ocmrole/cmd.go
cmd/link/userrole/cmd.go

When calling link cmd internally we set the roleArn, but not via flags,
so `Flags().Changed()` returns false.
I changed the test to determine if interactive mode is required to check if
roleArn has a value instead of using `Changed()`
Before the fix:
```
$ rosa create ocm-role --prefix zg --mode auto
I: Creating ocm role
I: Creating role using 'arn:aws:iam::765374464689:user/zgalor'
? Create the 'zg-OCM-Role' role? Yes
I: Created role 'zg-OCM-Role' with ARN 'arn:aws:iam::765374464689:role/zg-OCM-Role'
I: Linking OCM role
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12575f4]
goroutine 1 [running]:
github.com/openshift/rosa/cmd/link/ocmrole.run(0x2436420, 0xc001488c20, 0x1, 0x1, 0x0, 0x0) …
```

Fix crash when calling link cmd internally

---

assets/bindata.go
templates/policies/sts_ocm_permission_policy.json

This will allow OCM to fetch a list of available VPCs for adding
new clusters to.
https://issues.redhat.com/browse/SDA-5080

ocm-role: Add permission to describe VPCs

---

cmd/initialize/cmd.go

Change the ``rosa init --help`` message to specify that this is for non-STS ROSA clusters.
Solve [SDA-5098](https://issues.redhat.com/browse/SDA-5098)

Change rosa init help message

---

pkg/aws/client.go
pkg/ocm/clusters.go
pkg/ocm/regions.go

This forces a fall back on the region configured in the current AWS
session and allows the user to override the region with the use of the
'profile' and 'region' flags.
https://issues.redhat.com/browse/OSD-9245

aws: Remove hard dependency on default region

---

CHANGES.adoc
pkg/info/info.go

- Fix crash when calling link cmd internally
- Fix call to link cmd
- Add org external id to ocm role name
- ROSA: Support editing cluster-wide proxy
- link: Allow linking multiple role ARNs
- create-cluster: Allow FIPS mode support
- ocm-role: Add permission to describe VPCs
- add org admin validation for ocm-role
- improve UX in ROSA edit cluster and ROSA delete roles
- Change rosa init help message
- fix org admin validation
- Ignore .envrc (DirEnv)
- Ignoring environment config
- add permission for describe region and route tables
- aws: Remove hard dependency on default region
- Add pendo eventor account roles manual mode
- Add --admin option to create ocm-role command
- Make `--admin` flag idempotent
- added validation for ocm-role

Release v1.1.7

---

cmd/dlt/oidcprovider/cmd.go
cmd/dlt/operatorrole/cmd.go
pkg/ocm/clusters.go

Subscription takes time to move to deprovisioned status when the cluster is uninstalled. So if the user immediately tries the rosa delete operatorrole/oidc provider we get the error that the cluster is not present which is not correct.

fix issue with delete operatorrole/oidcprovider role

---

cmd/create/idp/cmd.go
cmd/create/idp/github.go
cmd/create/idp/gitlab.go
cmd/create/idp/google.go
cmd/create/idp/ldap.go
cmd/create/idp/openid.go

To ensure a consistent experience in interactive mode, instead of
prompting the user for only the required fields, we verify if the flags
are missing and enable interactive mode globally. This ensures that when
dropped into interactive mode no options are skipped.
https://issues.redhat.com/browse/SDA-5229

idp: Enable interactive mode when missing required flags

---

cmd/create/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/cluster/cmd.go
pkg/aws/helpers.go
pkg/ocm/upgrades.go

**Upgrade with ack** 
```
./rosa upgrade cluster -c 1pq7u8m8grp32kob42qu1cqbv0hhbp4n
? Version: 4.9.13
W: Missing required acknowledgements to schedule upgrade. 
? Read the below description and acknowledge to proceed with upgrade
- Description: OpenShift removes several Kubernetes APIs in OpenShift 4.9. To help prevent issues with workloads and tools after upgrading, an administrator is required to provide manual acknowledgement before the cluster can be upgraded from OpenShift 4.8 to 4.9.
URL:         https://access.redhat.com/articles/6329921
? I acknowledge Yes
? Please input desired date in format yyyy-mm-dd: 2022-01-21
? Please input desired UTC time in format HH:mm: [? for help] (16:50) 
```
**Upgrade with auto mode update** 
```
./rosa upgrade cluster -c …
```

added Version gates acks

---

cmd/upgrade/accountroles/cmd.go
cmd/upgrade/cluster/cmd.go

https://issues.redhat.com/browse/SDA-5343 
```
./rosa upgrade cluster -c 1pq7u8m8grp32kob42qu1cqbv0hhbp4n
? Version: 4.9.13
I: Ensuring account and operator role policies for cluster '1pq7u8m8grp32kob42qu1cqbv0hhbp4n' are compatible with upgrade.
I: Account and/or operator roles needed upgrade
? Upgrade mode: auto
? Upgrade the 'ManagedOpenShift-Installer-Role' role polices to version 4.9? No
E: Account roles need to be upgraded to proceed
I: Account and/Or Operator Role policies are not valid with upgrade version 4.9.13. Run the following command(s) to upgrade the roles:
rosa upgrade account-roles --prefix ManagedOpenShift
I: Run the following command to continue scheduling cluster upgrade once account and operator roles have been upgraded : 
rosa …
```

Fix issue with Auto mode during upgrade cluster

---

cmd/create/cluster/cmd.go

If the call to ocmClient.GetDefaultClusterFlavors fails, it returns a
`nil` pointer which then causes the process to panic when it is
dereferenced. If that occurs, we should exit early with an informative
message.

Avoid nil pointer dereference in cluster create

---

pkg/ocm/machines.go

Reverts openshift/rosa#578
Looks like `MachineType.available` doesn't actually indicate if a type is available in a specific zone, but rather if the user has appropriate quota to use it. We'll probably need to handle the logic of checking for availability in a specified zone on the server side.

Revert "Verify chosen machine pool type is available"

---

CHANGES.adoc
pkg/info/info.go

- Adding password argument to create admin
- Add stop and run instance permissions for support
- Send rosa cli login event to pendo
- Generate static assets for STS support permissions
- Fix linter errors
- Update to version 4 of JWT library
- Update to Ginkgo 2
- Bump go version to 1.16
- fix etcdEncryption
- OVN: Add network type selection
- fixed issue with operator role upgrade
- fixed upgade' to 'upgrade'
- fix issue with delete operatorrole/oidcprovider role
- clean up upgrade command
- idp: Enable interactive mode when missing required flags
- add rosa cli version to header
- Add gate support in rosa cli cluster upgrade
- Add version gate ackto ROSA 
- remove openshift version from operator role name
- Fix missing vendored module
- Addsupportforwarningmessage
- Avoid nil pointer …

Release v1.1.8

---

cmd/dlt/cluster/cmd.go

Related: [SDA-5208](https://issues.redhat.com/browse/SDA-5208)

Fix bug - remove duplicated error message when deleting a cluster

---

pkg/ocm/helpers.go

In some places in our code, we display an error message to the user depending
on the error type.
Function `handleErr` omits the error type in the new error it generates.
This function is called in many places in our code, and this change might affect the
error message returned to the user.
These are some occurrences that I found that can be affected by this change:
`dlt/oidcprovider/cmd.go 101`
`dlt/oidcprovider/cmd.go 126`
`link/userrole/cmg.go 140`
`ocm/logs.go 40`
`logs/install/cmd.go 164`
`logs/uninstall/cmd.go 150`

Modify function `handleErr` to include the error type in the new error

---

cmd/list/cmd.go
cmd/list/ocmroles/cmd.go
pkg/aws/client.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/helper/helper.go
pkg/ocm/helpers.go

The new command is implemented similarly to the `rosa list account-roles` command.
The code checks if a `role name` contains the `OCM-Role` infix to identify an ocm-role.
Related: [SDA-5405](https://issues.redhat.com/browse/SDA-5405)

Create command 'rosa list ocm-roles'

---

cmd/list/cmd.go
cmd/list/userroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/helper/helpers.go
pkg/ocm/client.go
pkg/ocm/helpers.go

The new command is implemented similarly to the `rosa list ocm-roles` command.
The code checks if a `role name` contains the `User` infix and in addition,
checks if the role has the tag `rosa_role_type: User`, because 'user' is a common word.
Related: [SDA-5412](https://issues.redhat.com/browse/SDA-5412)

Create command 'rosa list user-roles'

---

cmd/rosa/main.go
cmd/unlink/cmd.go
cmd/unlink/ocmrole/cmd.go
pkg/helper/helpers.go
pkg/ocm/helpers.go

The new command modifies the `sts_ocm_role` label's value.
If the role is the last one linked to the organization,
the 'sts_ocm_role' will be removed.
Otherwise, only the label's value will be updated.
Related: [SDA-5410](https://issues.redhat.com/browse/SDA-5410)

Create command 'rosa unlink ocm-role'

---

cmd/dlt/cmd.go
cmd/dlt/ocmrole/cmd.go
cmd/unlink/ocmrole/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/aws/sts.go

The new command follows these steps:
1. Unlink role if needed.
2. Detach Attached role policies.
3. Delete the policies from step 2.
4. Delete permissions boundary (doesn't delete the policy).
5. Delete role.
Related: [SDA-5202](https://issues.redhat.com/browse/SDA-5202)

Add 'rosa delete ocm-role' command

---

cmd/dlt/cmd.go
cmd/dlt/userrole/cmd.go
cmd/unlink/userrole/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/aws/sts.go

The new command is implemented similarly to `rosa delete ocm-role`.
1. Unlink user role if needed.
2. Detach attached role policies.
3. Delete permission boundary (doesn't delete the policy).
4. Delete role.
Related: [SDA-5437](https://issues.redhat.com/browse/SDA-5437)

Add 'rosa delete user-role' command

---

cmd/dlt/ocmrole/cmd.go
cmd/unlink/ocmrole/cmd.go

In case a role is linked, and the user doesn't have permission to unlink the role,
print an error message and exit the program.
At the moment, if there is an error when unlinking the role, the role will be
deleted anyway.
Related: [SDA-5482](https://issues.redhat.com/browse/SDA-5482)

Fix bug - forbid deletion of ocm-role in case user cannot unlink role

---

cmd/list/idp/cmd.go

Now that the HTPasswd IDP has been [introduced to ROSA](https://github.com/openshift/rosa/pull/608), we can stop hiding it when listing the IDPs.

Display HTPasswd IDP when listing a cluster's IDPs

---

cmd/list/accountroles/cmd.go
cmd/list/ocmroles/cmd.go
cmd/list/userroles/cmd.go

The command of fetching the roles with the AWS client can take some time when
there are a lot of roles in an account.
A spinner was added to `list ocm-roles`, `list user-roles`, and `list account-roles`
to improve the user experience.
https://user-images.githubusercontent.com/57869309/155566837-cc94abab-804f-4984-b826-bce2e1c00392.mp4

List roles - display a spinner while fetching the roles

---

cmd/dlt/ocmrole/cmd.go
cmd/dlt/userrole/cmd.go
pkg/aws/client.go
pkg/aws/sts.go

To delete a role using the AWS client the role name is sufficient.
For `delete ocm-role` and `delete user-role`, we ask the user to enter the whole role ARN,
in order to unlink the role in case it's linked, and to be consistent with other ROSA commands.
This PR adds validation to check if the user account ID match the role ARN account ID,
if not, an error message will be displayed and the program will terminate.
Related: [SDA-5544](https://issues.redhat.com/browse/SDA-5544)

Fix bug - deletion of a role with the wrong account ID in role ARN

---

cmd/dlt/ocmrole/cmd.go

Related: [SDA-5558](https://issues.redhat.com/browse/SDA-5558)

Fix bug - `delete ocm-role` should be hidden in rosa cli

---

cmd/unlink/userrole/cmd.go

- Specify that a user can unlink a user role from its account,
also without `orgAdmin` permissions.
- Fix the argument in the error message, for case the `role ARN` is not
provided as a flag.
Related: [SDA-5546](https://issues.redhat.com/browse/SDA-5546)

Improve `rosa unlink user role` error message

---

cmd/dlt/ocmrole/cmd.go
cmd/dlt/userrole/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

To delete a role using the AWS client, a role name is sufficient.
This PR adds the following validations:
- `delete ocm-role`: check that the provided role is an **ocm role**.
- `delete user-role`: check that the provided role is a **user role**.
Related: [SDA-5564](https://issues.redhat.com/browse/SDA-5564)

Fix bug - validate role type before deletion

---

cmd/create/admin/cmd.go
cmd/create/idp/htpasswd.go
cmd/dlt/admin/cmd.go
pkg/ocm/idps.go

In this MR:
- Correctly fetch the HTPasswd user list to if idp indeed `HasClusterAdmin`
- Don't dispatch the request to delete the `cluster-admin` user from the `cluster-admins` group, since this is now done on the CS side.

HTPasswd bug fixes corresponding with some CS changes

---

CHANGES.adoc
pkg/info/info.go

- Fix bug - add warning when creating ocm-role with duplicate name
- Update linter configuration to newer version
- Drop unused GetMachineTypeList method
- Initial MachineTypeList implementation
- Refactor GetMachineTypes to use MachineTypeList
- Refactor GetAvailableMachineTypeList
- Refactor ValidateMachineType to use MachineTypeList
- Refactor setting available quota for MachineTypeList
- Unify quota calculation logic for MachineType
- Modify function `handleErr` to include the error type in the new error
- Create command 'rosa list ocm-roles'
- Create command 'rosa list user-roles'
- Create command 'rosa unlink ocm-role'
- added policies for ocm admin role
- Fix bug - improve the help message of 'rosa unlink ocm-role'
- Create command 'rosa unlink user-role'
- Fix bug - capitalize …

Release v1.1.10

---

cmd/list/ocmroles/cmd.go
cmd/list/userroles/cmd.go
pkg/aws/sts.go

For the commands `list user-roles` and `list ocm-roles` linked roles
will be displayed first.
The order between the unlinked roles stays the same.
The same applied to the linked roles.
Related: [SDA-5574](https://issues.redhat.com/browse/SDA-5574)

Sort roles to display linked ones first

---

cmd/list/ocmroles/cmd.go

Implementation is similar to the command `list user-roles`.
This change improves the time complexity of marking the linked roles.

Refactor `list ocm-role` to use a map of linked roles

---

assets/bindata.go
templates/policies/sts_installer_permission_policy.json

This MR will enable CS to run preflight quota checks.
Related: [SDA-5429](https://issues.redhat.com/browse/SDA-5429)

Add quota service permissions to the `installer policy`

---

pkg/aws/client.go

MinRetryDelay is the minimum retry delay after which retry will be performed. If not set, the value is 0ns.
https://docs.aws.amazon.com/sdk-for-go/api/aws/client/

Set minimum retry delay for AWS API calls

---

cmd/upgrade/cluster/cmd.go

- Add `--yes` arg to `rosa upgrade cluster`, matching usage of `rosa upgrade account-roles` and `rosa upgrade operator-roles`

Permit overriding confirmation prompt for cluster upgrades

---

cmd/create/ocmrole/cmd.go
pkg/ocm/helpers.go

In case the user deleted a linked ocm-role using the AWS console,
there is a scenario where the role is linked to the organization but doesn't exist.
We want the provide the user with the command to unlink it.
Related: [SDA-5689](https://issues.redhat.com/browse/SDA-5689)

Fix bug - create ocm-role - prompt the role ARN

---

pkg/aws/client.go

Potential Fix for Throttle delay. Increase the number of retries and optimize the throttle retry delay

fix throttle delay

---

cmd/create/cluster/cmd.go

Having the install logs command run before the creation of operator
roles and the OIDC provider (`--mode auto`) causes the cluster creation
to hang waiting for these to be created. Moving watch to be after the
STS block executes the creation of the operator roles and OIDC provider
before blocking on cluster install logs
fixes #659
validation:
```
❯ ./rosa create cluster --cluster-name=testing-123 --sts --mode=auto --yes --watch
I: Using arn:aws:iam::x:role/ManagedOpenShift-Installer-Role for the Installer role
I: Using arn:aws:iam::x:role/ManagedOpenShift-ControlPlane-Role for the ControlPlane role
I: Using arn:aws:iam::x:role/ManagedOpenShift-Worker-Role for the Worker role
I: Using arn:aws:iam::x:role/ManagedOpenShift-Support-Role for the …
```

fix cluster creation hanging with auto+watch flags

---

cmd/describe/cluster/cmd.go

When running the below command, `rosa describe cluster ...` is called
causing an early exit before `--mode=auto`+STS is evaluated.
`rosa create cluster --cluster-name=testing-124 --sts --mode=auto --yes --output=json`
Rather than exiting early, return to the caller to finish and exit.
mentioned in #659
culprit
https://github.com/openshift/rosa/blob/b5af865e3f78ac8cf7ffc9d26540b89a3be893bf/cmd/create/cluster/cmd.go#L1799

fix early exit in cluster creation(json+mode=auto)

---

cmd/create/cluster/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go

When executing with `--output=json` and `--mode=auto`, plain info logs
are printed from the create commands of `oidc-provider` and
`operator-roles` causing the output to no longer parse as JSON. Bug was
surfaced in #661 and mentioned in #662.
Simply add the output flag/terminal check conditional to offending log
statements. This does not include support for the commands themselves,
the `output` flag variable is set when calling from the cluster creation
command and prevents plain text logs. 
Test command:
```
rosa create cluster -c <cluster-name> --mode=auto --output=json --sts --yes | jq .
```

fix json output for cluster creation (sts+mode=auto)

---

cmd/create/cluster/cmd.go
pkg/interactive/confirm/confirm.go

When using the '--yes' flag in non-interactive mode, we should
automatically select the default set of account roles. This ensures that
automation processes can be run without having to manually feed flags.

sts: Automatically select default account roles

---

CHANGES.adoc
pkg/info/info.go

- Sort roles to display linked ones first
- Refactor `list ocm-role` to use a map of linked role
- Add quota service permissions to the `installer policy`
- Set minimum retry delay for AWS API calls
- Introducing HTPasswd IDP
- Fix help for --compute-nodes
- Add KMS permission to installer and more permissions for ocm role
- added link to help menu
- Permit overriding confirmation prompt for cluster upgrades
- Fix bug - create ocm-role - prompt the role ARN
- add more permissions to ocm admin role
- Add support for 4.10 upgrade
- fix throttle delay
- fix cluster creation hanging with auto+watch flags
- fix early exit in cluster creation(json+mode=auto)
- sts: Automatically select default account roles
- fix json output for cluster creation
- Add max throttle delay to avoid exponential …

Release v1.1.12

---

cmd/create/ocmrole/cmd.go

If an ocm-role is linked to an organization, either the role exists or not,
Prompt the user with a concise error message and possible action.
Related: [SDA-5689](https://issues.redhat.com/browse/SDA-5689)

Fix error message - rosa create ocm-role

---

cmd/rosa/main.go
pkg/color/flag.go
pkg/interactive/interactive.go
pkg/reporter/reporter.go

To allow for automation that cannot handle ANSI escape sequences, we
provide a '--color' with options for 'auto', 'always', 'never'.

Add global color flag

---

CHANGES.adoc
pkg/info/info.go

- Fetch sts policies from ocm
- Add global color flag
- added command to create managed services
- added command to list managed services
- added command to describe managed services
- added command to delete managed services
- enhancing usability of managed service commands
- HTPasswd: Add username & password validations in CLI
- Fix `rosa describe admin` to look at HTPasswd IDP users to determine existence of admin
- Fix error message - rosa delete ocm-role
- Fix error message - rosa create ocm-role
- Remove AUTH URL from HTPasswd entries of `rosa list idps`
- Fix bug - delete account roles - make the `prefix` flag optional
- Updated ocm sdk to v0.1.262
- Adding support for byo-vpc in creating services

Release v1.2.0

---

cmd/upgrade/operatorroles/cmd.go
pkg/helper/helpers.go

CS first attempts to validate the new roles right after the creation fails.
Add 5 seconds delay with a spinner to reduce the number of retries on conflict in CS.
It's better to wait in the CLI, instead of blocking both CLI and CS.
Related: [SDA-5753](https://issues.redhat.com/browse/SDA-5753)

Upgrade cluster to 4.10.* - add delay after roles creation

---

cmd/create/idp/cmd.go
cmd/create/idp/htpasswd.go

Addresses [SDA-5645](https://issues.redhat.com/browse/SDA-5645)
This MR introduces some UX improvements for the HTPasswd IDP flow in the ROSA CLI based on the different configurations it may have. 
- User will only be prompted for a name for their HTPasswd IDP if a new IDP is actually created
- User will not be prompted for a name for their HTPasswd IDP if we will be adding users to an existing IDP serving as an admin container
- User will not be prompted for a name for their HTPasswd IDP if there's already an HTPasswd IDP on the cluster.
[See a detailed flow here](https://docs.google.com/document/d/1fyJL9sE74bSGHN7_dhwNo6WKDT9FcxucXgE-FOqt8EA/edit?usp=sharing)
PTAL @pvasant

Only prompt for HTPasswd IDP name when actually creating a new IDP

---

CHANGES.adoc
pkg/info/info.go

- support for cmk multi-region keys
- Warn that deleting HTPasswd IDP with cluster-admin user will delete the admin
- Add username & password requirements to the flags' help messages
- Fix login error
- Upgrade cluster to 4.10.* - add delay after roles creation
- Only prompt for HTPasswd IDP name when actually creating a new IDP
- add metric for throttle
- supporting different regions for create service command
- Fix Throttle issue for Operator roles

Release v1.2.1

---

pkg/arguments/arguments.go

Flags with values that contain equal signs were not properly handled by `ParseUknownFlags`. For example:
--foo="bar=bar"
was processed to:
`[foo, "bar, bar"]`
when it should be:
`[foo, "bar=bar"]`

supporting flag values that contain equal signs

---

cmd/create/userrole/cmd.go

Add an example of creating a user role with a permission boundary.
Related: [SDA-6013](https://issues.redhat.com/browse/SDA-6013)

Create user-role - improve help message

---

cmd/install/addon/cmd.go

Related: [SDA-6022](https://issues.redhat.com/browse/SDA-6022)

Addon install -	fix bug - do not print not-set parameters

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go
cmd/uninstall/addon/cmd.go
pkg/ocm/addons.go

Looking up an addon installation triggers another call to OCM just to
get the cluster ID, but we already have it every time we fetch the
installation.

Reduce extra call to OCM when manipulating addons

---

pkg/aws/policy_document.go

Add helpers for creating a policy document and allowing actions

---

cmd/create/idp/htpasswd.go

[SDA-6160](https://issues.redhat.com//browse/SDA-6160)
@pvasant @zgalor @oriAdler  PTAL

creating htpassword idp still prompts for username even if provided

---

cmd/create/machinepool/cmd.go

Bug example before changes:
**rosa create machinepool -c oadler-test --instance-type m5.2xlarge --name workload --labels node-role.kubernetes.io/workload= --taints role=workload:NoSchedule --replicas 3 --yes
? Create multi-AZ machine pool: [? for help] (Y/n) 
E: Expected a valid value for create multi-AZ machine pool**

Prompt the user to select multi or single AZ only in an interactive mood

---

cmd/edit/machinepool/cmd.go

Related: [SDA-6229](https://issues.redhat.com/browse/SDA-6229)

Fix bug - remove replicas constraint when editing single AZ machine pool

---

cmd/create/machinepool/cmd.go

Use the `availability-zone` flag's value only if provided by the user,
otherwise, choose az arbitrarily.
Before the `make` command - the state before this MR changes.

Create a single AZ machine pool - availability zone flag

---

CHANGES.adoc
pkg/info/info.go

- adding command to update managed service
- list parameters when describing managed services
- Addon install - add non-interactive commands
- Remove version dependency from rosa
- Create user-role - improve help message
- Bump OCM-SDK to 0.1.266
- Run go mod tidy
- Update templates
- Add credential requests to describe addon command
- Addon install -	fix bug	- do not print not-set parameters
- ROSA - Allow for additional, customer-provided "no_proxy" values for cluster-wide proxy
- Update to OCM SDK 0.1.268
- Make CredRequest API
- adding private-link flag to managed service create
- Add group support for OpenID IDP in ROSA CLI
- Reduce extra call to OCM when manipulating addon installation
- Fix a bug when editing no-proxy field
- Reject '*' when validating no-proxy field
- The wildcard …

Release v1.2.3

---

cmd/create/accountroles/cmd.go
cmd/create/admin/cmd.go
cmd/create/cluster/cmd.go
cmd/describe/addon/cmd.go
cmd/describe/cluster/cmd.go
pkg/rosa/runtime.go

The runtime provides command run() methods with common tools such as
logger, reporter and various clients. This change will allow removing a
lot of boilerplate from the various commands and make refactoring them
simpler as extracting methods will require fewer parameters.
@vkareh @pvasant @oriAdler @zvikorn WDYT?
I'd be happy for any suggestions on better naming, if we want this level of flexibility or if we should initialize all the clients for all commands anyways, and if you think this approach makes sense. If we agree on this direction i'll follow up with a cleanup of all the other commands (right now added just a couple to show the impact).
[SDA-6207](https://issues.redhat.com//browse/SDA-6207)

Initial implementation of runtime

---

cmd/create/cluster/cmd.go
pkg/aws/client.go
pkg/aws/helpers.go

1. Modify `GetSubnetsIDs` to recieve `DescribeSubnetsInput` for re-use.
2. Move `setSubnetOption` and `ParseSubnet` to `pkg/aws/helpers.go` for re-use.
Related: https://github.com/openshift/rosa/pull/765

Refactor function for more general use

---

cmd/create/machinepool/cmd.go
pkg/aws/client.go

1. Add the `subnet` flag to the `create machine pool` command.
2. Add functions to fetch VPC's private subnets.
Possible flows:
1. BYOVPC single AZ cluster - the user is prompted with the option to select subnet.
2. BYOVPC multi-AZ cluster - if the user chooses a single AZ, they have the option
to provide a subnet or an availability zone.
Related: [SDA-6289](https://issues.redhat.com/browse/SDA-6289)
[select_subnet_for_single_az_machine_pool.webm](https://user-images.githubusercontent.com/57869309/176680592-b632f2f6-8fdb-44de-8d89-22a115eef6f6.webm)

Select a single subnet for a single AZ machine pool - BYOVPC clusters

---

cmd/create/cluster/cmd.go

If the user provided three availability zones using the flags, set the multi-AZ
to true.
Related: [SDA-6330](https://issues.redhat.com/browse/SDA-6330)

Create cluster - detect multi-AZ cluster

---

cmd/create/cluster/cmd.go

Mention region name in the error message when the availability zone
doesn't belong to the region's availability zones.
Related: [SDA-6327](https://issues.redhat.com/browse/SDA-6327)

Fix error message - create non-BYOVPC - select availability zone

---

cmd/create/cluster/cmd.go

Add subnets number validation to improve user experience.
Related: [SDA-6331](https://issues.redhat.com/browse/SDA-6331)

Fix bug - create a cluster with an invalid number of subnets

---

cmd/create/machinepool/cmd.go

In this case, the user wants to create a single AZ machine pool for
a multi-AZ cluster.
If the user provided a subnet, consider	it as choosing a single	AZ
machine pool.
**Note:** the default value for `args.multiAvailabilityZone` is true.
Related: [SDA-6354](https://issues.redhat.com/browse/SDA-6354)

Create a single AZ machine pool implicitly by providing a subnet

---

cmd/list/addon/cmd.go

Use the `SetClusterKey` to assign the `cluster key` to the global variable.
In order to use it in the `r.FetchCluster` function.
Related: [SDA-6362](https://issues.redhat.com/browse/SDA-6362)
Follows up on https://github.com/openshift/rosa/pull/768

Set `clusterKey` properly to support `r.FetchCluster`

---

cmd/create/admin/cmd.go
cmd/create/idp/cmd.go
cmd/dlt/admin/cmd.go

[SDA-6170](https://issues.redhat.com//browse/SDA-6170)
@pvasant 
1) rosa create admin: 'cluster-admin' user is added to group 'cluster-admins'. htpasswd idp with the name 'htpasswd' is created and 'cluster-admin' user is added to this idp. If the htpasswd idp already exists, we just add the 'cluster-admin' user to this idp
2) rosa delete admin: 'cluster-admin' user is deleted from group 'cluster-admins'. user 'cluster-admin' is deleted from htpasswd idp. If htpasswd idp user list is empty, we delete the htpasswd idp as well.
3) rosa create (htpasswd) idp: if htpasswd idp does not exist, we create the idp and add users to it. 'cluster-admin' user is NOT allowed. if htpasswd exists,  we allow adding users.
4) on rosa create admin -> if htpasswd …

Having the option to remove or add a new cluster-admin in rosa cli

---

cmd/create/cluster/cmd.go
pkg/aws/helpers.go
pkg/interactive/validation.go

Use the interactive validation to provide fast feedback to the user,
to achieve a better user experience.
Related: [SDA-6331](https://issues.redhat.com/browse/SDA-6331)
This PR follows up on https://github.com/openshift/rosa/pull/772
[validate_subnet_interactive.webm](https://user-images.githubusercontent.com/57869309/177284154-e415bf8c-717d-43bd-bfd6-ab73de0d5a5c.webm)

Create cluster - validate subnets count interactively

---

cmd/upgrade/cluster/cmd.go
pkg/ocm/versions.go

./rosa upgrade cluster -c 1t9qanso4h9ch0n0du5af0htdk177qqv --version 4.10
I: Ensuring account and operator role policies for cluster '1t9qanso4h9ch0n0du5af0htdk177qqv' are compatible with upgrade.
I: Account and operator roles for cluster '1t9qanso4h9ch0n0du5af0htdk177qqv' are compatible with upgrade
? Are you sure you want to upgrade cluster to version '4.10.20'? (y/N) 
pvasanth@localhost: (acceptmajorminorforclusterupgrade *) $ ./rosa upgrade cluster -c 1t9qanso4h9ch0n0du5af0htdk177qqv --version 4.9
E: Expected a valid version to upgrade to
pvasanth@localhost: (acceptmajorminorforclusterupgrade *) $ ./rosa upgrade cluster -c 1t9qanso4h9ch0n0du5af0htdk177qqv --version 4.8
E: Expected a valid version to upgrade to
pvasanth@localhost: (acceptmajorminorforclusterupgrade *) $ ./rosa upgrade …

accept major minor version for cluster upgrade

---

pkg/aws/policies.go

Fix typo in error message when looking up account role prefix

---

cmd/create/idp/htpasswd.go
cmd/dlt/admin/cmd.go
cmd/grant/user/cmd.go
cmd/list/user/cmd.go
cmd/revoke/user/cmd.go
pkg/ocm/idps.go

fix for - Can't create temporary admin user for ROSA cluster
[SDA-6170](https://issues.redhat.com//browse/SDA-6170)
[SDA-6106](https://issues.redhat.com//browse/SDA-6106)

fix for - Not able to remove or add a new cluster-admin in rosa cli

---

cmd/create/cluster/cmd.go
pkg/aws/helpers.go
pkg/interactive/validation.go
pkg/ocm/helpers.go

Add a validator to the selecting availability zones prompt,
to improve user experience and enable the user to fix their choices.
Related: [SDA-6415](https://issues.redhat.com/browse/SDA-6415)

Create cluster - validate availability zones count interactively

---

CHANGES.adoc
pkg/info/info.go

- Fix typo in error message when looking up account role prefix
- fix for - Not able to remove or add a new cluster-admin in rosa cli fix for - Can't create temporary admin user for ROSA cluster
- Create cluster - validate availability zones count interactively
- Delete admin should not deleted htpasswd idp as the htpasswd list is not empty
- fedramp: Add environment-specific configuration (#702)

Release v1.2.5

---

cmd/create/service/cmd.go
pkg/ocm/managedservice.go

Verify create fake cluster service
```
╭─croche@localhost ~/Projects/sda/rosa ‹master*› 
╰─$ rosa create service --name=croche-test --type=ocm-addon-test-operator --fake-cluster  
W: More than one Installer role found, using "arn:aws:iam::765374464689:role/ManagedOpenShift-Installer-Role"
I: Using "arn:aws:iam::765374464689:role/ManagedOpenShift-Support-Role" for the Support role
I: Using "arn:aws:iam::765374464689:role/ManagedOpenShift-ControlPlane-Role" for the ControlPlane role
I: Using "arn:aws:iam::765374464689:role/ManagedOpenShift-Worker-Role" for the Worker role
I: Service created!
Service ID: 2CDHo6iluqf48vm6ySqO3MBmWlW
I: Run the following commands to continue the cluster creation:
rosa create operator-roles --cluster croche-test
rosa create oidc-provider --cluster croche-test …
```

add fake cluster parameter to create services

---

cmd/upgrade/cluster/cmd.go
go.mod
pkg/aws/sts.go
pkg/ocm/managedservice.go
vendor/modules.txt

https://github.com/pkg/errors has been archived due to essentially all of its capabilities being added to the standard library in [Go 1.13](https://go.dev/blog/go1.13-errors). So, I've replaced all of the places its used with the `fmt` equivalent.
Furthermore, typically with Go, [error messages are not capitalized](https://github.com/golang/go/wiki/CodeReviewComments#error-strings), so I also applied those fixes for the errors I interacted with.

Switch from `github.com/pkg/errors` to stdlib

---

CHANGES.adoc
pkg/info/info.go

- login: Remove token from error output
- debug: Remove AWS info from debug output
- add fake cluster parameter to create services
- fedramp: Update rosa-authenticator configuration
- network: Ensure there is no default network type
- Removed DisplayName from cluster
- Replaced display_name with name in query
- Removed change to query
- Create cluster - for single AZ, only allow to select one AZ
- Switch from github.com/pkg/errors to stdlib
- Updated SDK version and ran go mod vendor
- Ran go mod vendor after rebasing

Release v1.2.6

---

cmd/create/cluster/cmd.go
pkg/ocm/clusters.go
pkg/ocm/helpers.go

1. Modify `GetCluster` to try to fetch the cluster using cluster ID or UUID,
if the `clusterKey` is the cluster's name, list the cluster with parameters.
2. Modify `rosa create cluster` to pass the cluster's ID to `describe cluster`
instead of the cluster's name.
**Note:** This change aims to solve the bug where large organizations like `RedHat1` create a cluster,
and then `describeCluster` is listing all clusters and we get **504** from OCM.
Related: [SDA-6551](https://issues.redhat.com/browse/SDA-6551)

Create cluster - use a GET request to describe cluster details

---

cmd/create/cluster/cmd.go
pkg/aws/client.go
pkg/ocm/clusters.go
pkg/properties/properties.go

This is an experimental internal feature where we allow local
credentials to be used for creating legacy IAM clusters.
https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/4148

cluster: Allow using local AWS credentials

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/cmd.go
pkg/ocm/machines.go

**Note:** the new endpoint requires `role ARN` for STS clusters or
`access keys` for non-STS clusters.
Related: [SDA-6357](https://issues.redhat.com/browse/SDA-6357)
For example `m6a.12xlarge` isn't supported in `ap-southeast-3`:

Only display supported machine types by region

---

pkg/aws/helpers.go
pkg/ocm/config.go

This ensures that developers and contributors can use the full flow of
commands necessary for STS cluster requirements.

ocm: Add aliases for local development

---

cmd/create/operatorroles/cmd.go

[SDA-6625](https://issues.redhat.com/browse/SDA-6625)
This is a bug related to [SDA-6439](https://issues.redhat.com/browse/SDA-6439) where the operator-roles did not have the red-hat-managed=true tag even after releasing the MR for that story.

[SDA-6625] red-hat-managed=true tag now added to operatorroles

---

cmd/create/cluster/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/cmd.go
cmd/create/userrole/cmd.go
cmd/dlt/ocmrole/cmd.go
cmd/dlt/userrole/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/aws/sts.go

the operator policies moved back to account roles commands
this commit is for supporting the latest changes
[sda-6246](https://issues.redhat.com//browse/sda-6246) [sda-6560](https://issues.redhat.com//browse/sda-6560) [sda-6579](https://issues.redhat.com//browse/sda-6579) [sda-6621](https://issues.redhat.com//browse/sda-6621) [sda-6620](https://issues.redhat.com//browse/sda-6620) [sda-6619](https://issues.redhat.com//browse/sda-6619) [sda-6634](https://issues.redhat.com//browse/sda-6634) [sda-6647](https://issues.redhat.com//browse/sda-6647) [sda-6606](https://issues.redhat.com//browse/sda-6606) [sda-6737](https://issues.redhat.com//browse/sda-6737)
[sda-6740](https://issues.redhat.com//browse/sda-6740)

path for account and operator roles and policies

---

cmd/create/cluster/cmd.go
pkg/ocm/helpers.go
pkg/ocm/machines.go
pkg/ocm/regions.go

Use the `aws_inquiries` endpoint and pass the `version` to fetch the supported regions.
Related: [SDA-6765](https://issues.redhat.com/browse/SDA-6765)

Create cluster - list region filtered by OCP version

---

cmd/create/oidcprovider/cmd.go

Retrieves the root CA from the SSL certificate of the URL where the OIDC provider endpoint.
Additionally, to get the PR green I had to make the following changes to the code, which are not related to the change previously mentioned:
* <del>Moved to use `crypto/sha512` when calculating the Thumbnail for the OIDC SSL endpoint certificate due to [security issues](https://deepsource.io/gh/gogs/gogs/issue/GSC-G505/occurrences).</del>

SDA-4308: use root CA to generate OIDC thubmnail

---

cmd/create/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go
pkg/ocm/helpers.go

Allows version of policy to be chosen from available openshift versions
Before using command `rosa create account-roles` it autos to the latest default version, in this case 4.11
After using command `rosa create account-roles --version=4.10` the roles are created tagged with the chosen version. `--channel-group` could also be specified if a new version gets released in a specific channel, but it makes no difference for the example currently as the possible versions in the 'major.minor' format are the same.

[SDA-6405] feat: add version and channelGroup args to create/update acc. roles

---

cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go

Related: [SDA-6744](https://issues.redhat.com/browse/SDA-6744)

Upgrade cluster - manual mode - prompt the aws operator role upgrade commands

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go
pkg/interactive/addon.go
pkg/interactive/flag.go
pkg/interactive/interactive.go

Removing WIP status
Addressed in this pr.
- Use GetOptions in cases where params have options listed - matches UI, the user is forced to select - set the first value in the array as the default.
- Check that val selected, or provided is contained in the options when there are options
- Move logic for install/edit get parameters section to function

checking addon params

---

cmd/whoami/cmd.go
pkg/object/data.go
pkg/output/output.go

Adding possibility for -o json/yaml accommodating more usability in automations as stated by #726.
Usual whoami call
```
AWS ARN:                      arn:aws:iam::xxxxx:user/gbranco
AWS Account ID:               xxxxxxxxx
AWS Default Region:           us-east-1
OCM API:                      xxxxxxxx
OCM Account Email:            xxxxx
OCM Account ID:               xxxxxxx
OCM Account Name:             Guilherme Branco
OCM Account Username:         gbranco.openshift
OCM Organization External ID: xxxxx
OCM Organization ID:          xxxxx
OCM Organization Name:        xxxxxx
```
-o json
```
{
"AWS ARN": "arn:aws:iam::xxxxx:user/gbranco",
"AWS Account ID": "xxxxxxxxx",
"AWS Default Region": "us-east-1",
"OCM API": "xxxxxxxx",
"OCM Account Email": "xxxxx",
"OCM Account ID": "xxxxxxx",
"OCM …
```

feat: adding -o yaml/json option to cmd whoami

---

cmd/create/cluster/cmd.go
pkg/ocm/regions.go

For non-interactive mode, the CLI doesn't display the regions to the user, 
therefore fetching all regions to get the correct error message eventually.
Related: [SDA-6837](https://issues.redhat.com/browse/SDA-6837)

Fetch all regions for non-interactive mode

---

cmd/create/ocmrole/cmd.go

This PR only adds an escaped \n before adding the --path prefix to create ocm-roles in manual mode, simply to make sure the args will be separated. Aims to solve [SDA-6858](https://issues.redhat.com/browse/SDA-6858)
Original issue the --path arg was not separated from the rest of the command for some reason, could not reproduce
```
aws iam create-role \
--role-name xxxxxxx \
--assume-role-policy-document file://sts_ocm_trust_policy.json \
--tags Key=rosa_role_prefix,Value=ManagedOpenShift Key=rosa_role_type,Value=OCM Key=rosa_environment,Value=staging Key=red-hat-managed,Value=true--path /test2/
```
Changed to make sure it is in a new line
```
aws iam create-role \
--role-name xxxxxxx \
--assume-role-policy-document file://sts_ocm_trust_policy.json \
--tags …
```

[SDA-6858] adding escaped carrier to start of --path argument in ocm-role

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/cmd.go

Unify path for account roles and policies, as well as identify this path for operator roles and policies later
Related task: https://issues.redhat.com/browse/SDA-6866
Currently, there are limitations from AWS that is confusing CX with separate paths for account roles and operator roles and policy. Hence we are limiting our option to use only one path for all IAM  roles and policies 
`./rosa create account-roles --prefix=ManagedOpenShift-path-test --path /gdbsts/ -i`
```
I: AWS quota ok. If cluster installation fails, validate actual AWS resource usage against https://docs.openshift.com/rosa/rosa_getting_started/rosa-required-aws- …
```

[SDA-6866] feat/unify role path

---

cmd/describe/cluster/cmd.go

Why?: The stage URL changed from `https://qaprodauth.cloud.redhat.com/` to `https://qaprodauth.console.redhat.com/`

Update stage console URL

---

cmd/dlt/admin/cmd.go
pkg/ocm/idps.go

Creating an admin with rosa cli 1.1.5 then deleting it with 1.2.6 was not deleting correctly and newly created admin with 1.2.6 would cause 500 response codes on `oc login`.
Related issue: https://issues.redhat.com/browse/SDA-6780
This causes frustration for clients as they needed to have a second idp with admin access to delete the resources through `oc`.
The entire identity provider was being deleted when created from older clis, but a condition was still trying to delete it a second time. I'm not too familiar as to why the second call didn't give back an error or why it caused the 500 response codes, maybe we should look into the delete route of idp for ocm.
`rosa115 create admin -c htpwd-test`
`rosa126 delete admin -c htpwd-test`
`rosa126 create admin -c htpwd-test`
`oc login <url> …

[SDA-6780] fix: compatibility issue older rosa cli

---

cmd/create/cluster/cmd.go

Related issue: [SDA-5286](https://issues.redhat.com/browse/SDA-5286)
Deprecate 'compute-nodes' arg in favor of 'replicas'
Keep old hidden to make sure automations don't fail
To be consistent with other commands

feat: deprecate 'compute-nodes' args in favor of 'replicas' in create cluster cmd

---

cmd/create/ocmrole/cmd.go

Remove path arg from ocm-roles -h description
It was still showing --path but the actual arg is hidden

fix: remove path arg from -h ocm-roles description

---

pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-5894
Interactive mode of input is still not trimming 'invisible characters'
Facilitates user input

[SDA-5894] fix: adding trim spaces and tabs when validating cluster name

---

cmd/create/cluster/cmd.go

Adds a check for STS clusters when running the cluster create command that fails if the user specifies the `--watch` flag with `--mode auto`, unless the confirmation flag `-y` is also used.
@vkareh @pvasant PTAL.

[SDA-5966]: Rosa STS mode auto conflicts with the watch option

---

cmd/describe/cluster/cluster_suite_test.go
cmd/describe/cluster/cmd.go
cmd/describe/cluster/cmd_test.go
pkg/output/output.go
vendor/github.com/onsi/ginkgo/v2/dsl/core/core_dsl.go
vendor/github.com/onsi/ginkgo/v2/dsl/decorators/decorators_dsl.go
vendor/github.com/onsi/ginkgo/v2/dsl/table/table_dsl.go
vendor/modules.txt

Adds the upgrade policy fields into the json/yaml content with `rosa describe cluster -o[json|yaml]` as when displayed without the `-o` flag.
@vkareh @pvasant  PTAL.

[SDA-6075] Add upgrade policy to rosa struct information when displayed with the rosa describe cluster with -o json or -o yaml

---

cmd/upgrade/accountroles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6791
Compatibility issue with upgrading account roles policies when the policy was created as inline instead of attached, this happened when the acc roles were created from older ROSA CLI
Clients couldn't upgrade their account roles if they created it from an older ROSA CLI version (tested with 1.1.3)
If policy type is 'inline' than consider the path from the role, as it will be the same considering current implementation. This might be changed in the future to support different paths, so it might need to be revised later.
With this path in consideration, it deletes the inline policy and creates an attached one with the path from role as the flow is supposed to be.

[SDA-6791] fix: path compatibility issue with inline policies from acc roles

---

cmd/create/accountroles/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/userrole/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6784
path arg visibility for account, ocm and user roles was hidden
Allows clients to see the help for path arg

[SDA-6784] fix: enable path arg visibility

---

CHANGES.adoc
pkg/info/info.go

- fix - Google IDP doesn't work when created with ROSA CLI
- Refactored ROSA to create operator policies when running `rosa create cluster`.
- move operator policies from account to operator commands
- SDA_4308: use root CA to generate OIDC thumbnail
- Support for ARN paths in iam roles and policies
- Add ARN path to ocm-role and user-role
- compare arn path for existing policy/role
- missing '--operator-roles-path' in 'To create this cluster again...'
- hide arn path flags
- fix: missing changes for --role-path
- path for account and operator roles and policies
- fix: using installer instead of control plane role for path
- adding escaped carrier to start of --path argument in ocm-role
- feat: unify account roles its policies paths
- feat: unify operator role and policy with path from …

Release v1.2.7

---

cmd/create/admin/cmd.go

Related issue: #452 [SDA-5272](https://issues.redhat.com/browse/SDA-5272)
Add -o/--output option alongside json/yaml output formats for `create admin` command
Improves automation without parsing string output

[SDA-5272] feat: add --output json/yaml to create admin, omit when passwordArg is set

---

cmd/create/accountroles/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/userrole/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6784
'path' arg was being check for explicitly set to accept interactive mode question
'path' arg does not need to be explicitly set for the user to use it in interactive mode

[SDA-6784] fix: path args need not to be explicitly set for interactive mode to ask about it

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/cmd.go

Related issues: https://issues.redhat.com/browse/SDA-6966
Info log for path detection was being written to output file when performing pipe or -o
It shouldn't as the client might use the file to run the commands

[SDA-6966] fix: adding conditions for piping the output

---

cmd/create/accountroles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6965
Path was not being validate outside interactive mode
Clients may setup a wrong path and won't be able to continue with their flow
`./rosa create account-roles --mode manual -y --prefix xueli --path /xueli/test/t1`
```
I: Current OpenShift Client Version: 4.11.2
E: The specified value for path is invalid. …
```

[SDA-6965] fix: adding arn path validator to create account roles --path arg

---

cmd/create/service/cmd.go

Related issues: https://issues.redhat.com/browse/SDA-6974
Adding support for path in acc roles ARN
Adds feature parity to ms even though clients might not be using it

[SDA-6974] add managed services path support

---

cmd/create/ocmrole/cmd.go
cmd/create/userrole/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6965
A validation to the path was done to acc roles, but not for ocm/user roles
Making sure client knows what is happening if he inputs a wrong path

[SDA-6965] Add validation to path ocm/user roles

---

cmd/create/accountroles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6986
Validation was being applied when path is empty
Empty path is a valid path

[SDA-6986] Consider empty path valid creating acc roles

---

cmd/create/accountroles/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/cmd.go
cmd/create/userrole/cmd.go
cmd/upgrade/operatorroles/cmd.go
pkg/aws/sts.go

Related issues: https://issues.redhat.com/browse/SDA-6858
There was no leading space to the '\' on last line
Making sure commands will run without issues

[SDA-6858] Adding leading space before all path args when building commands

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/cmd.go

Related issues: https://issues.redhat.com/browse/SDA-6966
Path detected message should not show on redirect to file
Path detected message was still showing up on redirect to file

[SDA-6966] Invert path detected message condition

---

cmd/create/admin/cmd.go
cmd/create/idp/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6982
When a user does `rosa create-admin` or does other htpasswd idp setup, the ROSA CLI indicates "It may take up to a minute for the account to become active."
We should change this to a more realistic number because almost always, it takes longer.

[SDA-6982] Change message from one minute wait for several minutes

---

cmd/create/cluster/cluster_suite_test.go
cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go

Removes the channel group from the error message when the OCP cluster version is not compatible with HyperShift.

[SDA-6984] Better not clarify channel group when validating OCP version for HyperShift

---

pkg/aws/policies.go

AWS path response when path is empty is '/'
Making sure creating account roles stay idempotent when no path is specified
`rosa create account-roles -y`
```
I: Current OpenShift Client Version: 4.11.2
? Role prefix: ManagedOpenShift
? Permissions boundary ARN (optional): 
? Path (optional): 
? Role creation mode: auto
I: Creating roles using …
```

aws empty path is different than ours when creating existing acc roles

---

CHANGES.adoc
pkg/info/info.go

- fix: path args need not to be explicitly set for interactive mode to ask about it
- chore: add gdbranco to reviewers and approvers
- [SDA-6760] Add validation for minimum supported OCP version in HyperShift
- fix: adding arn path validator to create account roles --path arg
- fix: clearer message
- fix: adding conditions for piping the output
- fix: setting path arg in a new line for all commands
- fix: differentiate between '/' and /
- fix: block managed services path option
- fix: remove error to add support for path in ARN
- feat: add validation to path ocm/user roles
- add renan-campos to reviewers, approvers, and maintainers
- fix: consider empty path valid creating acc roles
- fix: accepts empty path
- fix: adding leading space before all path args when building commands
- fix: …

Release v1.2.8

---

cmd/create/cluster/cmd.go

[SDA-7021](https://issues.redhat.com/browse/SDA-7021)
Now, if you include the `--hosted-cp` flag when creating a cluster:
`rosa create cluster --sts --mode auto --hosted-cp`
Then once you get to the `Would you like to install on an existing VPC?`  step, it automatically responds Yes and asks you which subnets to use.Before, it always prompted Would you like to install on an existing VPC? even with the `--hosted-cp`  flag

[SDA-7021] --hosted-cp flag now forces byo vpc prompt like privatelink does

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go
pkg/ocm/versions.go
pkg/ocm/versions_test.go

Adds support for nightly builds of OCP as viable versions for Hosted Clusters. Previously only 4.11.6-candidate and newer were supported, but not nightly builds as they are tagged with `<major>.<minor>.0-nightly-<timestamp>-nightly`, example:
```
4.11.0-0.nightly-2022-10-17-040259-nightly
4.10.0-0.nightly-2022-10-17-082154-nightly
4.10.0-0.nightly-2022-10-14-023020-nightly
4.10.0-0.nightly-2022-10-13-011121-nightly
4.10.0-0.nightly-2022-10-12-184111-nightly
4.8.0-0.nightly-2022-10-14-021947-nightly
4.8.0-0.nightly-2021-05-26-071911-nightly
```
@pvasant @jakub-dzon  PTAL

[SDA-6984] Add support for nightly builds for Hosted CP clusters

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6936
When creating the cluster the manual commands still list --compute-nodes instead of --replicas
-- compute nodes has been deprecated

[SDA-6936] Favor replicas instead of deprecated compute-nodes param

---

cmd/create/cluster/cmd.go

@tzvatot PTAL
[SDA-7066](https://issues.redhat.com//browse/SDA-7066)

removed --channel-group  from --help options.

---

cmd/version/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-4611
Check if rosa version is up to date when running `rosa version`
Easier for user to check latest released version

[SDA-4611] Check if rosa cli is up to date

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6320
When no flags are passed to `rosa edit ingress` a request without changes was being sent
Make sure user will input changes if for some reason he forgets to specify arg changes

[SDA-6320] feat: set interactive enabled if local flags are unchanged, except for cluster flag

---

pkg/interactive/interactive.go

This change was brought about because you cannot set labels to an empty string (which is supposed to mean no labels) in interactive mode. When  you set the labels to `""` in interactive mode, the CLI thinks you are entering `""""` and does not work as expected.
This change just sets a string containing two quotes to an empty string to fix this problem.

[SDA-6857] Labels & taints strings containing only quotes ("""") are set to empty string

---

cmd/create/cluster/cmd.go

[SDA-6643](https://issues.redhat.com/browse/SDA-6643)
Adds `mint-mode` [alias] and `non-sts` flags to ROSA CLI, and sets STS as the default mode with mint mode being an optional mode now. Also only prompts if they want to use STS when mint-mode and interactive are enabled.
Flow:
When creating a new cluster, just using the default `rosa create cluster` will now use STS mode. If you use the new flags (either one) `rosa create cluster --non-sts` or `rosa create cluster --mint-mode` -- it will use the legacy (IAM) mode for creating clusters.
If you are in interactive mode (by not providing a cluster name for example) and are using `--non-sts` or `--mint-mode` , you will be prompted whether or not you'd like to use STS mode instead. Otherwise, the flow of using `rosa create cluster` or `rosa …

[SDA-6643] STS is now default mode for cluster creation, added flags for mint mode/non-sts mode

---

cmd/create/accountroles/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/cmd.go
cmd/create/userrole/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/dlt/ocmrole/cmd.go
cmd/dlt/oidcprovider/cmd.go
cmd/dlt/operatorrole/cmd.go
cmd/dlt/userrole/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
pkg/aws/commandbuilder/commandbuilder.go
pkg/aws/helpers.go
pkg/aws/sts.go
pkg/aws/tags/tags.go

Related issues: https://issues.redhat.com/browse/SDA-6920
Share behavior for constructing manual aws commands.
From time to time we change the manual commands, adding or removing parameter. This can cause differences on how they behave throughout each rosa command.
`rosa create account-roles --mode manual --prefix=gdb-path --path /gdbsts/ --version=4.9 -y`
```
I: Current OpenShift …
```

[SDA-6920] Aws command builder

---

cmd/create/cluster/cmd.go

Allow for passing `--yes` to `create cluster` which gets passed down the
the operator-roles and oidc-provider create commands, blocking on a
prompt otherwise.
resolves #914

add `--yes` to create cluster cmd

---

pkg/aws/commandbuilder/commandbuilder.go

Related issue: https://issues.redhat.com/browse/SDA-7178
Map was not being setup before use
go panics when trying to assign an entry to nil map

fix: add tags check when b.tags nil

---

cmd/create/oidcprovider/cmd.go

For context:
https://coreos.slack.com/archives/CB53T9ZHQ/p1667278725525159
While working through a pipeline setup I noticed rosa was setting the interactive.Enabled() to true even while passing args:
"--mode auto --yes" 
Root caused this to the oidcProvider missing a check for the skipInteractive condition.

Create/oidcprovider bug sets interactive.Enable

---

cmd/create/cluster/cmd.go

By unhiding the FIPS flag we effectively expose it for all customers to provision FIPS-enabled clusters.
Related: https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/4803

FIPS: Unhide flag

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6643
`rosa create cluster --sts --mode auto`
```
? Cluster name: test
W: --sts flag won't be necessary.
```
`rosa create cluster --mode auto`
```
? Cluster name: test
? Deploy cluster using AWS STS: No
W: --non-sts/--mint-mode flag will be necessary in a future release if you do not wish to use STS.
```

[SDA-6443] Message deprecation non sts (legacy iam creds)

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/cmd.go
pkg/aws/client.go
pkg/ocm/machines.go

Pass the availability zones to the OCM client to filter supported instances.
Related: [SDA-7160](https://issues.redhat.com/browse/SDA-7160)

Create machinepool - filter supported instances by availability zones

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/cmd.go
cmd/create/service/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/commandbuilder/helper/roles/roles.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/aws/sts.go
pkg/helper/helpers.go
pkg/helper/roles/helpers.go
pkg/ocm/flag.go
pkg/ocm/helpers.go

Related Issues: 
https://issues.redhat.com/browse/SDA-6407
https://issues.redhat.com/browse/SDE-1816
Setting up a new command to upgrade acc/operator roles/policies
Easier flow for the client to use when roles are linked to a cluster
`./rosa upgrade cluster -c ns --mode auto -y`
```
? Version: 4.10.37
I: Ensuring account and operator role policies for cluster '1vosh3jn3trq9101s4dm4tt30d4qq9u2' are compatible with upgrade.
I: Upgraded policy with ARN 'arn:aws:iam::765374464689:policy/rosa-ccoe-dev-installer-Policy' to version '4.11'
I: Upgraded policy with ARN 'arn:aws:iam::765374464689:policy/rosa-ccoe-dev-controlplane-Policy' to version '4.11'
I: Upgraded policy with ARN 'arn:aws:iam::765374464689:policy/rosa-ccoe-dev-compute-Policy' to version '4.11' …
```

[SDE-1816] new command upgrade roles from cluster

---

cmd/create/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/commandbuilder/commandbuilder.go
pkg/helper/helpers.go
pkg/ocm/helpers.go

User couldn't upgrade roles to tag policies with the nightly release
Allow option to choose nightly channel group when upgrading policy tags

Add channel group and option to choose version for policy tags in upgrade roles cmd

---

cmd/upgrade/roles/cmd.go
pkg/helper/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-7342
* Remove os exit when roles are up to date
* Sort prefixes to ensure consistency when they are the same rank
* Order of messages
* Does not os exit when called from other command

[SDA-7342] Fixing wrongful behaviors on upgrade roles

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7207
Moved through, but can't edit a default ingress in this example
`./rosa edit ingress -c sda7345 --private o1r3`
```
E: Failed to update ingress 'o1r3' on cluster 'sda7345': Can't update listening mode of default ingress on an AWS STS cluster
```

[SDA-7207] Invert condition for no reason to update ingress

---

cmd/upgrade/cluster/cmd.go
cmd/upgrade/roles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7345
`./rosa upgrade cluster -c sda7345`
```
? Version: 4.10.40
? IAM Roles/Policies upgrade mode: auto
```

[SDA-7345] Prompt mode for upgrade cluster when sts and mode is empty

---

cmd/create/cluster/cmd.go
cmd/initialize/cmd.go
pkg/aws/helpers.go
pkg/aws/region/flag.go
pkg/helper/helpers.go
pkg/interactive/interactive.go
pkg/ocm/regions.go

Related issue: https://issues.redhat.com/browse/SDA-7382
Non existing region should be validated
The command is stuck and returns only after 20 minutes return only after 20 minutes with not user-friendly error. 
`./rosa create cluster -c region-check --region="undefined"`
```
E: Unsupported region 'undefined', available regions: [ap-east-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, us-east-1, us-east-2, us-west-1, us-west-2, af-south-1, ap-south-1, eu-north-1, eu-south-1, me-south-1, ca-central-1, eu-central-1, us-gov-east-1, us-gov-west-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-southeast-1, ap-southeast-2, ap-southeast-3]
```

[SDA-7382] Checking undefined aws region on init and create cluster

---

cmd/create/cluster/cmd.go
cmd/edit/cluster/cmd.go
pkg/helper/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-6826
No proxy value should not be sent if it contains empty string
Empty string was being sent as part of the no proxy values
```
.
.
.
? PrivateLink cluster (optional): Yes
? Subnet IDs (optional): subnet-xxxx (us-east-1b)
.
.
.
? Use cluster-wide proxy (optional): Yes
? HTTP proxy (optional): http://xxx.us-west-2.compute.internal
? HTTPS proxy (optional): https://xxx.us-west-2.compute.internal
? No proxy (optional): 
.
.
.
I: To create this cluster again in the future, you can run:
rosa create cluster --cluster-name no-proxy --sts --role-arn arn:aws:iam::xxx:role/ManagedOpenShift-Installer-Role --support-role-arn arn:aws:iam::xxx:role/ManagedOpenShift-Support-Role --controlplane-iam-role …
```

[SDA-6826] Handle empty strings before validation

---

cmd/create/cluster/cmd.go

Without this `isReplicaSet` was set to false even when `--replicas` was changed.
This affected in the long run because it failed the check in line [#1635](https://github.com/openshift/rosa/blob/master/cmd/create/cluster/cmd.go#L1635) and was assigned the minimum `computeNodes` that was 3.
Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>
fixes #946

Adding check for Changes in `replicas` flag too

---

CHANGES.adoc
pkg/info/info.go

- feat: set interactive enabled if local flags are unchanged, except for cluster flag
- feat: don't send update request if there are no changes
- refactor: setting up a function to look into given params expected to be unchanged
- Hosted-cp flag now forces byo vpc prompt
- bump ocm sdk to 0.1.289
- update hypershift naming convention for latest SDK
- add market specific billing options for addon installations
- [SDA-6984] Add support for nightly builds for HyperShift
- [Hypershift] Filter regions where HostedCP is avalaible
- feat: check if rosa cli is up to date
- fix: lint
- refactor: clean up
- fix: favor replicas instead of deprecated compute-nodes param
- Revert "[Hypershift] Filter regions where HostedCP is avalaible"
- removed --channel-group  from --help options.
- [Hypershift] …

Release v1.2.9

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go
pkg/ocm/versions.go
pkg/ocm/versions_test.go

Align version check with the backend to fail early
Related: [SDA-7087](https://issues.redhat.com//browse/SDA-7087)

Check HostedCP version support also in interactive mode

---

cmd/upgrade/operatorroles/cmd.go
pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-7429
Some of the policies were not upgraded but are not being considered when checking
Check was ending prematurely
#Changes
Run the command once, remove the newly created role and it's policy from aws. Now all operator policies will be up to date but one. Run the command again, check if the policy got recreated and the recreated role also has it attached.
`./rosa upgrade operator-roles -c [sda-7429](https://issues.redhat.com//browse/sda-7429) --version=4.10.40`
```
I: Starting to upgrade the operator IAM roles and policies
? Operator IAM role/policy upgrade mode: auto
? Upgrade the operator role policy to version 4.11? Yes
I: Upgraded policy with ARN 'arn:aws:iam::123:policy/sda-7429-openshift-ingress-operator-cloud-credentials' to …
```

[SDA-7429] Going through all policies to check upgrade

---

cmd/list/user/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-3843
Adjust spacing between columns based on longest user id
Spacing was not aligned
`./rosa list users -c sda-7429`
```
ID                           GROUPS
gdb                          cluster-admins
adminnnnnnnnnnnnnnnnnnnnnnnn dedicated-admins
admin                        dedicated-admins
```

[SDA-3843] Align spacing listing users

---

cmd/list/idp/cmd.go
pkg/ocm/idps.go

LDAP IDP type is showing auth url info when listing idps
LDAP IDP type shouldn't show this info
`./rosa list idps -c sda-5825`
```
NAME        TYPE        AUTH URL
github-1    GitHub      https://xxx/oauth2callback/github-1
github-2    GitHub      https://xxx/oauth2callback/github-2
ldap-1      LDAP        https://xxx/oauth2callback/ldap-1
htpasswd    HTPasswd    
```
`./rosa list idps -c sda-5825`
```
NAME        TYPE        AUTH URL
github-1    GitHub      https://xxx/oauth2callback/github-1
github-2    GitHub      https://xxx/oauth2callback/github-2
ldap-1      LDAP        
htpasswd    HTPasswd    
```

[SDA-5825] Remove auth url info from LDAP idp when listing

---

cmd/upgrade/operatorroles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7420
Running the command for a second time in sequence had missing info about the status of the roles/policies.
The API does not return newly created operator until the upgrade is scheduled. So a check is needed to make sure the expected new roles were actually created or if they have been previously.
`./rosa upgrade operator-roles -c [sda-7420](https://issues.redhat.com//browse/sda-7420) --version=4.10.42 --mode auto -y`
```
I: Starting to upgrade the operator IAM roles and policies
I: Upgraded policy with ARN 'arn:aws:iam::765374464689:policy/sda-7420-openshift-machine-api-aws-cloud-credentials' to version '4.11'
I: Upgraded policy with ARN 'arn:aws:iam::765374464689:policy/sda-7420-openshift-cloud-credential-operator-cloud-credential-o …
```

[SDA-7420] Check if any new operator roles have been created before hand

---

cmd/create/cluster/cmd.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/roles/cmd.go
pkg/ocm/versions.go

Related issue: https://issues.redhat.com/browse/SDA-7474
Upgrading from a channel group other than stable would fail to validate version
Channel group was not being taken into account for some validations

[SDA-7474] Upgrading from pre release would fail to validate version

---

cmd/create/machinepool/machinepool.go

Related issue: https://issues.redhat.com/browse/SDA-7233
Quotes are not being validated for machine pool labels in the CLI
The regex does not allow quotes
`./rosa create machinepool -c oadler-byo-mlt`
```
? Machine pool name: a
? Create multi-AZ machine pool: Yes
? Enable autoscaling (optional): No
? Replicas: 3
I: Fetching instance types
? Instance type: m5.xlarge
X Sorry, your reply was invalid: name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character
? Labels (optional): aaa=bbb
? Taints (optional): [? for help] 
```

[SDA-7233] Validating regex for machine pool label key and value

---

cmd/create/idp/github.go

Related issue: https://issues.redhat.com/browse/SDA-3685
Adds error message to alert user CA is not be passed as param if github hostname is empty
CA is not expected to be used when not using a hosted instance of Github  Enterprise
`./rosa create idp -c cluster --type github --ca notexisted --client-id aaa --client-secret aaa --teams aaa/bbb`
```
E: Failed to create IDP for cluster 'cluster': CA is not expected when not using a hosted instance of Github Enterprise
```

[SDA-3685] Add error message when CA is passed but github hostname is not

---

cmd/create/cluster/cmd.go

Uses lower case before comparison
AWS IAM names are case insensitive

Using lower case before comparing expected acc role arns

---

pkg/helper/roles/helpers.go

Related issue: https://issues.redhat.com/browse/OHSS-14855
Uses value for operator roles prefix retrieved from backend
Doing in the front end means duplicated functionality, plus it should be retrieved from a central place so to minimize possible failure points by having possibility of different strategies in place.
`./rosa upgrade roles -c [ohss-14855](https://issues.redhat.com//browse/ohss-14855) --mode auto --cluster-version=4.10.43`
```
I: Ensuring account role/policies compatibility for upgrade
? Upgrade the 'ROSA-devel-posttrade-support' role policy latest version (4.11) ? Yes
I: Upgraded policy with ARN 'arn:aws:iam::xxx:policy/ROSA-devel-posttrade-support-p' to version '4.11'
? Upgrade the 'ROSA-devel-posttrade-install' role policy latest …
```

[OHSS-14855] Retrieve operator role prefix from backend

---

cmd/upgrade/roles/cmd.go
pkg/aws/helpers.go
pkg/helper/helpers.go

Uses LCP algorithm to retrieve operator policy prefix
One more option before resorting to operator role prefix
`./rosa upgrade roles -c hss-14855 --mode auto --cluster-version=4.10.43`
```
I: Ensuring account role/policies compatibility for upgrade
? Upgrade the 'ROSA-devel-control' role policy latest version (4.11) ? Yes
I: Upgraded policy with ARN 'arn:aws:iam::xxx:policy/ROSA-devel-control-Policy' to version '4.11'
? Upgrade the 'ROSA-devel-worker' role policy latest version (4.11) ? Yes
I: Upgraded policy with ARN 'arn:aws:iam::xxx:policy/ROSA-devel-worker-Policy' to version '4.11'
? Upgrade the 'ROSA-devel-support' role policy latest version (4.11) ? Yes
I: Upgraded policy with ARN 'arn:aws:iam::xxx:policy/ROSA-devel-support-Policy' to version …
```

Using LCP to retrieve operator policy prefix

---

cmd/edit/addon/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7565
Populates in place/default value of param before checking values from arguments
Params not specified in the args were being sent as empty or nil

[SDA-7565] Use default/in-place value for addon param first

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/machinepool.go

Related: [SDA-7377](https://issues.redhat.com//browse/SDA-7377)
1. Not hypershift cluster
2. No label key duplications

Add default machine pool labels validations

---

cmd/describe/cmd.go
cmd/describe/upgrade/cmd.go
pkg/ocm/upgrades.go

[SDA-3653](https://issues.redhat.com//browse/SDA-3653)
@etabak @oriAdler 
```
~/workPlace/rosa (describe-upgrade)! S $ ./rosa describe upgrade -c=20mv05nk2dk8ghfbcvn9tm378mrt0bft
ID:                         3b8f9265-7f9b-11ed-a809-0a580a820878
Cluster ID:                 20mv05nk2dk8ghfbcvn9tm378mrt0bft
Schedule At:                
Next Run:                   2022-12-19 12:56:00 +0000 UTC
```

make rosa describe upgrade

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7633
Remove "-<channel_group> from output version command if present
This is treated within creation flow
`rosa create cluster --cluster-name [test-2](https://issues.redhat.com//browse/test-2) --sts --role-arn arn:aws:iam::xxx:role/ManagedOpenShift-Installer-Role --support-role-arn arn:aws:iam::xxx:role/ManagedOpenShift-Support-Role --controlplane-iam-role arn:aws:iam::xxx:role/ManagedOpenShift-ControlPlane-Role --worker-iam-role arn:aws:iam::xxx:role/ManagedOpenShift-Worker-Role --operator-roles-prefix test-p2n3 --region us-east-1 --channel-group candidate --version 4.12.0-rc.4-candidate --replicas 2 --compute-machine-type m5.xlarge --machine-cidr 10.0.0.0/16 --service-cidr 172.30.0.0/16 --pod-cidr 10.128.0.0/14 --host-prefix 23`
`rosa …

[SDA-7633] Remove channel group from recreate output

---

cmd/create/accountroles/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/cmd.go
cmd/create/userrole/cmd.go
cmd/install/addon/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/helpers.go
pkg/aws/permissions.go
pkg/helper/roles/helpers.go
pkg/ocm/helpers.go

Refactor the function to return a map with `AWSSTSPolicy` values, 
in order to use the `ARN` attribute for managed policies in the future.
Related: [SDA-7609](https://issues.redhat.com/browse/SDA-7609)

Refactor `GetPolicies` function

---

cmd/list/user/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7657
Changes the setup of output to use tab writer options
Makes it less prone to error
`./rosa list users -c gdb-user`
```
ID                                    GROUPS                                
cu                                    cluster-admins                        
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  cluster-admins                        
du                                    dedicated-admins 
```

[SDA-7657] Using tabwriters options instead of manually formatting `list users`

---

cmd/create/accountroles/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/cmd.go
cmd/create/userrole/cmd.go
cmd/install/addon/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/aws/tags/tags.go
pkg/ocm/config.go

This is a preparation for managed policies.
1. Validate the environment supports the `managed` flag (not production).
2. Don't output the `create policy` commands in manual mode.
3. Validate there aren't existing unmanaged roles with the same names.
4. Add a new role tag `rosa_managed_policies` to managed roles.
**Note:** In order to use this command one has to create policies in the AWS account
with these ARNs https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/blob/master/pkg/aws/loader/aws_sts_managed_policies.go#L6.
Related: [SDA-7656](https://issues.redhat.com/browse/SDA-7656)
Validate environment:
Don't display `create policy` commands in the manual mode:
Check if there are exiting unmanaged roles with the same names:

Create account roles with existing policies

---

cmd/create/cmd.go
cmd/dlt/cmd.go
cmd/list/cmd.go
cmd/upgrade/cmd.go
pkg/arguments/arguments.go

Related issue: [SDA-4764](https://issues.redhat.com/browse/SDA-4764)
Account roles region arg should be hidden
Account roles commands don't need to specify region as they are global
```
Global Flags:
--color string     Surround certain characters with escape sequences to display them in color on the terminal. Allowed options are [auto never always] (default "auto")
--debug            Enable debug mode.
--profile string   Use a specific AWS profile from your credential file.
--region string    Use a specific AWS region, overriding the AWS_REGION environment variable.
-y, --yes              Automatically answer yes to confirm operation.
```
```
Global Flags:
--color string     Surround certain characters with escape sequences to display them in color on the terminal. Allowed options are …
```

[SDA-4764] Hide region arg in account roles commands

---

cmd/create/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/helper/helpers.go

Determine if the cluster account roles have managed policies, 
if so, create the operator roles accordingly.
Related: [SDA-7660](https://issues.redhat.com/browse/SDA-7660)
The CLI detects that the account roles have managed policies:
and creates operator roles with managed policies:

Create operator role with existing policies

---

cmd/create/cmd.go
cmd/dlt/cmd.go
cmd/list/cmd.go
cmd/upgrade/cmd.go
pkg/arguments/arguments.go

Related issue: https://issues.redhat.com/browse/SDA-4764
Hides region in globally available commands, basically what deals with aws iam service
Globally available commands should have region hidden in help

[SDA-4764] Hide region from other globally available commands

---

cmd/create/cluster/cmd.go

[SDA-7662](https://issues.redhat.com/browse/SDA-7662)
The Tags question which prompts what tags youd like to add to the cluster, was disabled if `--tags` wasn't passed with at least one tag. Now it runs all the time in interactive mode.

[SDA-7662] Display Tags question in interactive mode

---

cmd/create/cluster/cmd.go

[SDA-7662](https://issues.redhat.com//browse/SDA-7662) is a "bug" where the Tags question was only appearing if you typed `--tags=X:Y` or any other tags in the command. Now it appears even when no `--tags` flag is specified.

[SDA-7662] Made it so the Tags question appears always in interactive mode

---

cmd/create/operatorroles/cmd.go
cmd/upgrade/accountroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

If the roles have the tag `rosa_managed_policies:true`, verify that the managed policies are attached and exit. 
Policies upgrade isn't needed for managed policies.
Related: [SDA-7678](https://issues.redhat.com/browse/SDA-7678)
Examples:
1. User provides invalid prefix:
2.  User upgrades roles with managed policies successfully:
3. One of the roles is missing the attached managed policy:
4. Managed policies are disabled on production:

Upgrade account roles with managed policies

---

cmd/create/cluster/cmd.go

mode
Related: [SDA-7622](https://issues.redhat.com//browse/SDA-7622)

Add the default-mp-labels flag to cluster create command on interactive

---

cmd/create/cluster/cmd_test.go
cmd/create/idp/github.go
cmd/create/idp/gitlab.go
cmd/create/idp/google.go
cmd/create/idp/openid.go
cmd/list/idp/cmd.go
pkg/ocm/idps.go
pkg/ocm/idps_test.go

The implementation leverages ExternalDNS which will be the default for all the clusters. 
No change for the non HyperShift clusters
Fixes: [SDA-7648](https://issues.redhat.com//browse/SDA-7648)

Fix OAuth callback URL logic for HyperShift clusters

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7663
Checks current values from ingress to make sure there will be changes or not
Changes were not going through due to some conditions
`./rosa create ingress  -c non-sts --label-match a=b`
```
I: Ingress has been created on cluster 'non-sts'.
I: To view all ingresses, run 'rosa list ingresses -c non-sts'
```
`./rosa edit ingress c4r1 -c non-sts --label-match="a=b"`
```
W: No need to update ingress as there are no changes
```
`./rosa list ingresses -c non-sts`
```
ID    APPLICATION ROUTER                              PRIVATE    DEFAULT    ROUTE SELECTORS
c4r1  https://apps2.non-sts.9so3.s1.devshift.org      no         no         a=b
p2s8  https://apps.non-sts.9so3.s1.devshift.org       no         yes        
```
`./rosa edit ingress c4r1 …

[SDA-7663] Check current ingress values to see if there are no changes

---

cmd/create/operatorroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/commandbuilder/helper/roles/roles.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/helper/roles/helpers.go

1. Check that managed policies are attached to the roles.
2. If the user specified the upgrade version, check for missing roles.
Related: [SDA-7679](https://issues.redhat.com/browse/SDA-7679)

Upgrade operator roles with managed policies

---

pkg/ocm/clusters.go

[SDA-6753](https://issues.redhat.com//browse/SDA-6753) was a bug where in ROSA when you created a cluster using auto mode (`rosa create cluster --sts --mode auto` for example), the "credential_configuration_mode" Tracking property was set to `manual`. It is now updated properly by updating `stsBuilder.AutoMode` with the correct value depending on if it's auto mode or manual mode.
This change was tested using Segment and creating a cluster.

[SDA-6753] Now updating stsBuilder.AutoMode properly

---

cmd/create/cluster/cmd.go

We were skipping the string splitting if no tag was passed in input

Fix tags passing in cluster creation interactive mode

---

cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/helper/roles/helpers.go

1. Check that the account roles have managed policies attached.
2. Check that the operator roles have managed policies attached.
2. Check for missing operator roles by OCP version.
Related: [SDA-7712](https://issues.redhat.com/browse/SDA-7712)

Upgrade roles command - handle managed policies

---

cmd/create/machinepool/machinepool.go

Related issue: https://issues.redhat.com/browse/SDA-7741
Changes introduced in https://issues.redhat.com/browse/SDA-7233 aimed at resolving an issue but created another. Decided to move to a simplified solution instead of going for regex as it is due to a single case
Empty value in labels value part should be accept
`rosa create machinepool -c <cluster_key> --name workload --instance-type m5.2xlarge --labels node-role.kubernetes.io/workload= --taints role=workload:NoSchedule --replicas 3 -i`
```
? Machine pool name: workload3
? Replicas: 3
I: Fetching instance types
? Instance type: m5.2xlarge
? Labels: node-role.kubernetes.io/workload=
? Taints: [? for help] (role=workload:NoSchedule)
```
`./rosa create machinepool -c <cluster_key>`
```
? Machine pool name: …
```

[SDA-7741] Machine pool label validation

---

cmd/dlt/oidcprovider/cmd.go

Fixes a bug where the wrong OIDC Provider may be targeted for removal when more than one OIDC Provider exists and a request to delete an OIDC Provider by Cluster Name is issued, and the Cluster Name specified either does not exist, or belongs to a cluster in a ready state.

fix: Incorrect OIDC Provider Sometimes Targeted for Deletion

---

pkg/ocm/versions.go

Related issue: https://issues.redhat.com/browse/SDA-7758
Check if it is a pre release version
Version was defaulting to the first available upgrade in slice

[SDA-7758] Accept pre release version during upgrade

---

cmd/create/machinepool/cmd.go
cmd/create/machinepool/machinepool.go
cmd/create/machinepool/nodepool.go
pkg/output/output.go

allow outputing the newly created pools as json/yaml to allow easier use
from automation
```
$ ./rosa create machinepool --replicas=3 rw-hyper-osde2e --cluster=rw-hyper --output=json
{
"kind": "NodePool",
"id": "216tlklcjdu14fq1fddbl9ohs20f6jel",
"href": "/api/clusters_mgmt/v1/clusters/.../node_pools/216tlklcjdu14fq1fddbl9ohs20f6jel",
"aws_node_pool": {
"kind": "AWSNodePool",
"instance_profile": "staging-...-rw-hyper-worker",
"instance_type": "m5.xlarge",
"tags": {
"api.openshift.com/environment": "staging",
"api.openshift.com/id": "...",
"api.openshift.com/legal-entity-id": "...",
"api.openshift.com/name": "rw-hyper",
"api.openshift.com/nodepool": "rw-hyper-workers1",
"red-hat-clustertype": "rosa",
"red-hat-managed": "true"
}
}, …
```

SDCICD-893: cmd/create/machinepool: support output flag

---

pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-7784
Checks preexisting actions under a policy to check if it is needed to recreate it
If there are changes under a policy within the same version tag it is not updated

[SDA-7784] Tagged current version on policy is not necessarily compatible

---

CHANGES.adoc
pkg/info/info.go

- fix: Incorrect OIDC Provider Sometimes Targeted for Deletion
- Removed len(tags) > 0 from if for Tags question in interactive
- Revert "[SDA-7662] Display Tags question in interactive mode"
- Upgrade account roles with managed policies
- fix: check current values to see if there are no real changes
- Fixed panic
- Re-added tags question
- Add the default-mp-labels flag to cluster create command on interactive mode
- fix: code review
- Now updating stsBuilder.AutoMode properly
- Added constant for "auto" string
- Upgrade operator roles with managed policies
- feat: command create oidc-config
- fix: add mocks
- feat: add manual mode
- fix: review comments
- Used better flag
- Edited query for GetClusterUsingSubscription to fix deletions
- Fix tags passing in cluster creation interactive …

Release v1.2.12

---

cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/OHSS-14855
Skips acc roles that are not within cluster spec for some reason
By expecting all to exist it can fail upgrading roles in some clusters

Skip missing acc roles during upgrade

---

cmd/create/machinepool/nodepool.go
cmd/list/machinepool/nodepool.go

Follow-up work for [SDA-7767](https://issues.redhat.com//browse/SDA-7767), is needed when the backend MR is merged.
Summary of changes:
- Removing the "INSTANCE-PREFIX" column (as now the machinepool is properly identify by the ID).
- Allow to use "--name" parameter for specifying the name of a MachinePool for hosted clusters.
Use cases, test scenarios covered with this work:
```
$ rosa list machinepools -c lponce-local-02
ID       AUTOSCALING  REPLICAS  INSTANCE TYPE  AVAILABILITY ZONE  SUBNET                    
workers  No           2         m5.xlarge      us-west-2a         subnet-0e3a4046c1c2f1078  
test1    No           2         m5.xlarge      us-west-2a         subnet-0e3a4046c1c2f1078  
test3    No           3         m5.xlarge      us-west-2a         subnet-0e3a4046c1c2f1078 …
```

SDA-7767 Let user define machinepool name on hosted cluster

---

cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go

In case of success in the upgrade roles command, return nil instead of exit. 
This change is required since we trigger the upgrade roles command from the upgrade cluster command.
Related: [SDA-7761](https://issues.redhat.com/browse/SDA-7761)

Fix managed policies cluster upgrade path

---

cmd/create/ocmrole/cmd.go
pkg/aws/tags/tags.go

Attach existing policy instead of creating a new one.
Related: [SDA-7864](https://issues.redhat.com/browse/SDA-7864)

Create OCM role with managed policies

---

CHANGES.adoc
pkg/info/info.go

- Skip region check if we use shard pinning
- Remove GitHub IDP dependency to console availability
- Bump ocm-sdk-go to v0.1.310
- Fix managed policies cluster upgrade path
- Delete roles with managed policies
- feat: store private key for byo oidc in secrets manager
- [SDA-7757] byo OIDC secret arn support (#1018)
- feat: add download rosa option
- Create OCM role with managed policies
- Upgrade to Go 1.19
- Delete OCM role with managed policies

Release v1.2.13

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-7898
When creating account roles this param "--force-policy-creation" or "-f" skips compatibility checks ensuring policy will be created.
Current version might receive extra permissions during it's lifetime and needs to be updated
`./rosa create account-roles --mode auto -y -f `
```
I: Current OpenShift Client Version: 4.11.2
I: …
```

[SDA-7898] Add force param to forcefully create policies

---

cmd/create/operatorroles/cmd.go

Asks for permissions boundaries for operator roles during the cluster creation. If supplied consider we can skip interactive on creation of operator roles
Some automations may get interactive question during creation operator roles

Permissions boundary shouldn't be asked if supposed to skip interactive

---

cmd/upgrade/cluster/cmd.go
cmd/upgrade/roles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7879
The correct flags should be prompted
User was prompted with incorrect flag

[SDA-7879] Incorrect flags in message and hidden for upgrade roles

---

cmd/create/admin/cmd.go
cmd/create/idp/cmd.go
cmd/create/idp/github.go
cmd/create/idp/gitlab.go
cmd/create/idp/google.go
cmd/create/idp/htpasswd.go
cmd/create/idp/ldap.go
cmd/create/idp/openid.go
pkg/ocm/idps.go

* Use SDK enums which are now correct
* Remove a (broken) usage of a global variable to align with the rest

IDP related minor cleanup

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go

Use interface for role creation with implementation for `managed` and `unmanaged` policies, to simplify code.
This is a preparation to accommodate more changes for the managed policies flow.
Related: [SDA-7941](https://issues.redhat.com/browse/SDA-7941)

Refactor `create account roles command` to use interfaces

---

cmd/create/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7984
Adds regions param when user specifies a different region then default
Manual command failed if region param is not specified

[SDA-7984] Add region when creating manual s3 bucket for oidc config

---

cmd/edit/addon/cmd.go
cmd/install/addon/cmd.go
pkg/interactive/addon.go

The interactive mode was terminating if the user passed an invalid string argument when installing an addon.
This set of commits modifies the behavior of _interactive.GetAddonArgument()_ to continue prompting the user.
[SDA-6852](https://issues.redhat.com/browse/SDA-6852)

reprompt user when passed invalid addon argument

---

cmd/rosa/main.go

Related issue: https://issues.redhat.com/browse/SDA-3651
Checks if it has suggestions in error so we don't get double ouput
It showed the suggestions a second time

[SDA-3651] Only show root command error if it is not a suggestion error

---

cmd/dlt/operatorrole/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8025
`./rosa delete operator-roles -c 21gv47khdrd9mg58igoir4kp8crg0n9f --mode=auto -y`
```
I: Fetching operator roles for the cluster: 21gv47khdrd9mg58igoir4kp8crg0n9f
I: Deleting operator role 'hs-hosted-oidc-m9c1-kube-system-capa-controller-manager'
I: Deleting operator role 'hs-hosted-oidc-m9c1-kube-system-control-plane-operator'
I: Deleting operator role 'hs-hosted-oidc-m9c1-kube-system-kube-controller-manager'
I: Deleting operator role 'hs-hosted-oidc-m9c1-openshift-image-registry-installer-cloud-cre'
I: Deleting operator role 'hs-hosted-oidc-m9c1-openshift-ingress-operator-cloud-credentials'
I: Successfully deleted the operator roles
```

[SDA-8025] Show info report when deleting operator roles

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8022
When forcing creation of policies for updating actions on current version should validate if they are using managed policies first
Managed policies are always up to date and don't require forcing update
`rosa create account-roles --mode auto -y -f --managed`
```
.
.
.
W: Forcing creation of policies only works for unmanaged policies
```

[SDA-8022] Forcing creation should only work for unmanaged policies

---

cmd/dlt/machinepool/cmd.go

the flag is a global flag but is not picked up when programmatically
calling `cmd.SetFlags` with `--yes` which is done in osde2e. This aligns
the behavior to match `create cluster --yes`.
In `osde2e`, we programmatically execute the cobra commands which requires the
flags to be configured locally, not globally. An example of this is:
```go
import machinepooldelete "github.com/openshift/rosa/cmd/dlt/machinepool"
cmd := machinepooldelete.Cmd
cmd.SetArgs([]string{"--yes", fmt.Sprintf("--cluster=%s", clusterName), machinePoolName})
_ = cmd.Execute()
```
The create cluster command is set up the same which works in `osde2e`:
https://github.com/openshift/rosa/blob/2215aeffc61c48d03c1bb4d926e1d22367d7aa5e/cmd/create/cluster/cmd.go#L580 …

cmd/dlt/machinepool: add confirm flag

---

cmd/create/machinepool/helper.go
cmd/create/machinepool/machinepool.go
cmd/create/machinepool/nodepool.go

ROSA CLI UX for
https://issues.redhat.com/browse/SDA-7895
It requires backend MR 
https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/5154
it will enable using "subnet" parameter for creating a machine-pool for a hosted cluster.
Additionally, it will allow the user to resolve the "subnet" from an "availability zone."
ROSA CLI UX:
```
rosa create machinepool -c lponce-local-02 --name mp-2c --subnet subnet-06023544bf8e5b199 --replicas 2
rosa create machinepool -c lponce-local-02 --name mp-2c-public --subnet subnet-0fd5b560cd0518bb9 --replicas 2
rosa create machinepool -c lponce-local-02 --name mp-2c --subnet subnet-bad --replicas 2
rosa create machinepool -c lponce-local-02 --name mp-2b --availability-zone us-west-2b
rosa create machinepool -c lponce-local-02 --name …
```

SDA-7895 Enable editing subnet in machinepools for hosted clusters

---

cmd/create/oidcconfig/cmd.go
cmd/dlt/cmd.go
cmd/dlt/oidcconfig/cmd.go
pkg/aws/client.go
pkg/aws/commandbuilder/commandbuilder.go
pkg/aws/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-8059
ROSA needs to support deleting oidc configs
Currently the client needs to go to aws to remove the configs that were created within ROSA

[SDA-8059] Add command delete oidc-config and minor fixes

---

cmd/create/cluster/cmd.go
cmd/create/idp/gitlab.go
cmd/create/idp/openid.go
pkg/helper/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-8005
Checks supplied oidc endpoint url to be HTTPS
When in waiting state the validation expects it to be HTTPS

[SDA-8005] Oidc endpoint url should be of https scheme

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/cmd.go
pkg/aws/helpers.go

Not all ARNs belong to the 'aws' partition based on their region. This ensures that all ARNs have the correct one.

aws: Ensure ARNs have the correct partition

---

cmd/describe/cluster/cmd.go

With hostedCP  when the `cluster.status.dns_ready: false`  the command `rosa describe` displays only the name of the cluster. 
The fix proposed display `DNS:    Not ready` instead of for example 'DNS:    my-cluster.`

to fix empty DNS domain when DNS not ready: SDA-7418

---

cmd/create/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8092
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
Prefixed with `xn--` or suffixed with `-s3alias` are considered invalid
Invalid for aws

[SDA-8092] Add a few more validations to bucket/folder name

---

cmd/create/accountroles/creators.go
pkg/aws/helpers.go
pkg/aws/policies.go

For managed policies, attach `core`, `vpc`, and `private link` installer policies.
Validate three policies are in place upon cluster creation and cluster upgrade.
Related: [SDA-7941](https://issues.redhat.com/browse/SDA-7941)
Create a role with managed policies (manual mode):
Three policies are attached to the installer role:
Validating all three policies are attached to the installer role:

Attach three policies to the installer role - managed policies

---

cmd/list/accountroles/cmd.go
cmd/list/ocmroles/cmd.go
pkg/aws/policies.go

Display a new column with info about the role's policies.
Related: [SDA-7969](https://issues.redhat.com/browse/SDA-7969)

Add a `AWS managed` column to list role commands

---

CHANGES.adoc
pkg/info/info.go

- fix: improve error messages for deleting oidc-config
- fix: adding some validations to bucket name
- fix: allow empty label match editing ingress interactive
- aws: Ensure ARNs have the correct partition
- Attach three policies to the installer role - managed policies
- to fix empty DNS domain when DNS not ready: [SDA-7418](https://issues.redhat.com//browse/SDA-7418)
- fix: add a few more validations to bucket/folder name
- Add a `AWS managed` column to list role commands
- Add etcd encyprtion kms arn support

Release v1.2.15

---

cmd/create/cluster/cmd.go

Default should be false unless fips or kms arn provided
Related: [SDA-7675](https://issues.redhat.com//browse/SDA-7675)

Fix etcd encryption default enforecment

---

cmd/dlt/oidcconfig/cmd.go
pkg/ocm/clusters.go

Related issue: https://issues.redhat.com/browse/SDA-8078
Checks if there are any clusters using the oidc config
Safer flow for client
`./rosa delete oidc-config --mode auto`
```
? OIDC Private Key Secret ARN: xxx
E: There are clusters using OIDC config 'xxx', can't delete the configuration
```

[SDA-8078] Check if any clusters are using the oidc config

---

pkg/aws/client.go

Customers can get this log when attempting to upgrade account and operator roles, but it's not immediately obvious what the problem is from the existing logs:
```
I: Ensuring account and operator role policies for cluster 'REDACTED' are compatible with upgrade.
E: expected a valid IAM role ARN: arn: invalid prefix
```
[OHSS-18020](https://issues.redhat.com//browse/OHSS-18020)

[OHSS-18020] Improve logging so that it's more obvious what is wrong

---

cmd/create/machinepool/helper.go
cmd/create/machinepool/machinepool.go
cmd/create/machinepool/nodepool.go
cmd/edit/machinepool/helper.go
cmd/edit/machinepool/machinepool.go
cmd/edit/machinepool/nodepool.go

This covers both creation and modification. The UX should be the same as Classic ROSA.
Related: [SDA-8219](https://issues.redhat.com//browse/SDA-8219)

Add support for labels and taints to HostedCP NodePools

---

cmd/create/accountroles/cmd.go
cmd/create/ocmrole/cmd.go

Related: [SDA-8213](https://issues.redhat.com//browse/SDA-8213)
Adding the `--unmanaged-policies` flag will be taken care of in a separate PR.

Change managed policies flag name to `aws-policies`

---

cmd/list/machinepool/helper.go
cmd/list/machinepool/machinepool.go
cmd/list/machinepool/nodepool.go

Align the output with classic machinepools
```
rosa list machinepool -c ad2
ID        AUTOSCALING  DESIRED REPLICAS  CURRENT REPLICAS  INSTANCE TYPE  LABELS          TAINTS                  AVAILABILITY ZONE  SUBNET                    MESSAGE
workers   No           2                 2                 m5.xlarge                                              us-west-2a         subnet-0e3a4046c1c2f1078
workers3  No           1                 2                 m5.xlarge      aa=bb, cc=dd    key2=val2:NoSchedule    us-west-2a         subnet-0e3a4046c1c2f1078
```
Related: [SDA-8219](https://issues.redhat.com//browse/SDA-8219)

Add labels and taints to the list machinepools command

---

cmd/create/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go
pkg/ocm/versions.go

1. Modify the call to the backend to get the latest version first.
2. Unhide the `version` flag for creating and upgrading account roles.
Related: [SDA-8123](https://issues.redhat.com/browse/SDA-8123)

Use latest OCP version instead of the default version

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8274

[SDA-8274] Missing '--' for the oidc endpoint url flag

---

cmd/describe/cluster/cmd.go
pkg/ocm/clusters.go

Related issue: https://issues.redhat.com/browse/SDA-8074
Add description when available for error state in describe cluster
Better info for client/SRE to understand

[SDA-8074] Add description when available for error state in describe cluster

---

cmd/create/operatorroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go

Since we are now persisting this information upon cluster creation, use the attribute to reduce API calls to AWS.
Related: [SDA-8278](https://issues.redhat.com/browse/SDA-8278)

Use cluster attribute `ManagedPolicies` to identify policy type

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/cmd.go
pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-7716
Allows reusing operator roles by specifying each operator role or operator role prefix as long as the provided OIDC matches the the trust relationship to the role
Client does not need to created operator roles for each cluster

[SDA-7716] Add possibility to reuse operator roles

---

pkg/aws/policies.go

Since managed policies are always going to be up-to-date, 
skip the `rosa_openshift_version` tag check for roles with managed policies.
Related: [SDA-8328](https://issues.redhat.com/browse/SDA-8328)

Create cluster - roles with managed policies

---

cmd/list/machinepool/machinepool.go

A minimal PR to fix https://issues.redhat.com/browse/SDA-8325
As the "Default" machinepool for Hive clusters is built in the rosa side, it requires logic to populate the subnets from the cluster.
Please @oriAdler @zgalor @gdbranco take a look; feel free to suggest if there is a better way to patch this. 
I don't usually work on hive clusters, and I may miss some context.
Thanks

SDA-8325 Add subnets field for Default Worker

---

cmd/dlt/cluster/cmd.go
cmd/dlt/operatorrole/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/aws/sts.go

Related issue: https://issues.redhat.com/browse/SDA-8387
Operator roles created from/for BYO OIDC clusters do not have cluster ID tag, so it is required to provide a different way of deleting them
Facilitates flow for customers so they don't need to deal directly with aws console/cli

[SDA-8387] Add possibility to delete operator roles from prefix

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/cmd.go
cmd/create/operatorroles/common_utils.go
cmd/create/service/cmd.go
pkg/aws/helpers.go
pkg/aws/policy_document.go
pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-8354
Allow creating operator roles prior to cluster spec
Ensures full BYO OIDC flow creating all needed resources prior to cluster spec

[SDA-8354] Allow creating operator roles prior to cluster spec

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go
cmd/create/machinepool/cmd.go
cmd/create/machinepool/machinepool.go
cmd/create/machinepool/nodepool.go
cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/machinepool.go
cmd/edit/machinepool/nodepool.go
cmd/list/machinepool/nodepool.go
pkg/helper/versions/helpers.go
pkg/helper/versions/helpers_test.go
pkg/helper/versions/main_test.go
pkg/ocm/versions.go
pkg/ocm/versions_test.go

The "hosted machinepools" can accept a "version" parameter on "create" and "edit" commands.
This PR exposes this parameter on "list" command:
```
$ rosa list machinepools -c lponce-local-01
ID       AUTOSCALING  DESIRED REPLICAS  CURRENT REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONE  SUBNET                    VERSION  MESSAGE            
mp-02    No           2                 2                 m5.xlarge                          us-west-2a         subnet-0d65e2465258986db  4.12.2   NodeProvisioning   
workers  No           2                 2                 m5.xlarge                          us-west-2a         subnet-0d65e2465258986db  4.12.4                      
mp-01    No           1                 2                 m5.xlarge                          us-west-2a …
```

SDA-8218 Support version parameter on hosted machine pools

---

cmd/create/operatorroles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8354
Error should only be checked when user is calling not when progmatically called

[SDA-8354] Check if cmd was progmatically called before erroring

---

cmd/create/cluster/cmd.go
cmd/dlt/cluster/cmd.go

This change keeps the watch flag consistent across rosa commands. Previously some commands (e.g. rosa logs <install|uninstall>) provided both long/short form for the flag while others (e.g. rosa <create|delete> cluster) provided only long form for the flag.
It adds the short form `-w` for rosa <create|delete> clusters.

Fix inconsistencies across commands providing a watch flag

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/by_clusterkey.go
pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-8445
Extra check to make sure operator roles are ok to be reused

[SDA-8445] Add check for cluster version compatibility when reusing the operator roles

---

cmd/create/operatorroles/by_prefix.go

Related issue: https://issues.redhat.com/browse/SDA-8450
AWS does not accept role arn, should have been role name

[SDA-8450] Use role name instead of role arn for manual creation by prefix

---

cmd/dlt/oidcprovider/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8451
Fixes incorrect check when progmatically called

[SDA-8451] Delete oidc-provider cmd should not check flags when is progmatically called

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-7003
Block watch param when on manual mode for creating cluster
User need to input outputted commands so we can't watch
`rosa create cluster --sts --mode=manual --yes --watch`
```
? Cluster name: asd
W: --sts flag won't be necessary.
? OpenShift version: 4.11.12
E: Cannot watch in mode 'manual' since the user will need to run outputted commands.
```

[SDA-7003] Block --watch when on manual mode for creating cluster

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/by_prefix.go
pkg/helper/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-8452
Checks if bucket url 404s
Not sure when, but it looks like aws is now returning a page with 404 status code, so dialing is not enough to check if page exists.

[SDA-8452] Check if bucket page returns 404

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go
pkg/aws/policies.go
pkg/aws/tags/tags.go

Run `rosa create account-roles --hosted-cp` to get a set of Hypershift roles.
**Note:** The default flow for Hypershift is going to be managed policies.
Related: [SDA-8494](https://issues.redhat.com/browse/SDA-8498)
Auto mode:
Manual mode:

Create Hypershift account roles with managed policies

---

cmd/create/accountroles/cmd.go

Hide the flag until AWS managed policies are in place.
Related: [SDA-8498](https://issues.redhat.com/browse/SDA-8498)

Create account roles - hide `hosted-cp` flag

---

cmd/create/accountroles/cmd.go

Related: [SDA-8539](https://issues.redhat.com/browse/SDA-8539)

Create account roles - prompt accurate message for cluster creation

---

cmd/create/cluster/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/helper/roles/helpers.go

Omit the control plane role when creating a Hypershift cluster.
**Note:** a follow-up PR will ensure the set of account roles is a Hypershift set.
Related: [SDA-8454](https://issues.redhat.com/browse/SDA-8454)
Only three account roles are required from the user:

Hypershift - create cluster

---

cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
pkg/aws/helpers.go
pkg/aws/tags/tags.go

If the account roles have Hypershift managed policies, attach the managed policies to the operator roles instead of creating policies in the user account.
Related: [SDA-8507](https://issues.redhat.com/browse/SDA-8507)

Create Hypershift operator roles

---

cmd/create/cluster/cmd.go
pkg/interactive/validation.go

cc @oriAdler 
For hosted clusters, the subnet validation is relaxed compared with classic clusters.
There was a bug in the interactive mode not updating the current logic.

Fix hostedcp multiaz subnets validation on interactive mode

---

cmd/dlt/accountroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

1. Default flow deletes classic ROSA roles.
2. If "--hosted-cp" is specified, delete the Hypershift roles (same behavior as `create account roles`).
**TODO:** we can delete both by default once we have the managed policies in place. 
Otherwise, deleting the Hypershift roles for users is meaningless.
Related: [SDA-8565](https://issues.redhat.com/browse/SDA-8565)
By default delete classic ROSA account roles:
When the **--hosted-cp** flag is provided, delete the Hypershift account roles:

Delete account-roles - handle Hypershift roles

---

cmd/create/operatorroles/by_clusterkey.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/helper/roles/helpers.go

1. Validate that managed policies are attached to the account roles.
2. Validate that managed policies are attached to the operator roles.
**Note:** Upgrade hosted control plane isn't supported yet, this PR adds validation for missing policies/roles.
Related: [SDA-8552](https://issues.redhat.com/browse/SDA-8552)
Upgrade cluster - installer role without the managed policy:
Upgrade cluster - operator role without the managed policy:
Upgrade operator roles - all managed policies are attached to the roles:

Upgrade cluster with hosted CP policies

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8621
Correctly setup usage help
Avoid segfault

[SDA-8621] Use oidcConfigIdFlag instead of var

---

pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-8587
Given prefix was deleting extra roles that started with prefix however didn't completely match it
Should only match a specific prefix

[SDA-8587] Check specific prefix instead of all op roles that start with prefix

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8611

[SDA-8611] Cluster flow oidc provider flow should use issuer url instead

---

cmd/dlt/accountroles/cmd.go

Add the `classic` specification to the messages of the command.
Related: [SDA-8599](https://issues.redhat.com/browse/SDA-8599)

Delete account roles - classic ROSA

---

pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-8653
Add a warning like message for a possible flow the user might not be too familiar with or made a mistake

[SDA-8653] Extra message when operator roles prefix is already in use

---

cmd/create/machinepool/nodepool.go
cmd/edit/machinepool/nodepool.go
pkg/helper/machinepools/helpers.go

This ticket is a follow-up of https://issues.redhat.com/browse/SDA-7929 for ROSA CLI.
Hypershift Operator updated the minimal replica validation, and those changes have been propagated into the backend ([SDA-7929](https://issues.redhat.com//browse/SDA-7929)) and frontend ([SDA-8551](https://issues.redhat.com//browse/SDA-8551)).
cc @oriAdler @gdbranco

SDA-8551 Sync replicas validation for hosted clusters

---

pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-8587
Favors regex when deleting operator roles by prefix
There was still an edge case that was not accommodated by the last mechanism
Created two sets of operator roles, gdb and gdb-, deleted each individually making sure the other was not taken into account by current mechanism

[SDA-8587] Favoring regex when deleting operator roles by prefix

---

cmd/describe/cluster/cmd.go
cmd/describe/upgrade/cmd.go
cmd/list/gates/cmd.go
cmd/upgrade/cluster/cmd.go
pkg/ocm/upgrades.go

This is the only supported mode for Hypershift cluster at the moment. We also enforce that upgrades will start immediately, no scheduling possible in the first phase.
Examples:
```
rosa upgrade cluster -c ad3 --control-plane
? Version: 4.12.8
? IAM Roles/Policies upgrade mode: auto
I: Ensuring account and operator role policies for cluster '22oaveu9j278qh79814p2aug5ahtvl2h' are compatible with upgrade.
I: Account roles/policies for cluster '22oaveu9j278qh79814p2aug5ahtvl2h' are already up-to-date.
I: Operator roles/policies associated with the cluster '22oaveu9j278qh79814p2aug5ahtvl2h' are already up-to-date.
I: Account and operator roles for cluster 'ad3' are compatible with upgrade
? Are you sure you want to upgrade cluster to version '4.12.8'? Yes
? Node draining: 1 hour
I: Upgrade …
```

Add control plane upgrades for Hypershift cluster

---

cmd/list/version/cmd.go

[SDA-8685](https://issues.redhat.com//browse/SDA-8685) -- Add hosted-cp and only list HCP-enabled versions in rosa CLI

[SDA-8685] Added hosted-cp to rosa list versions

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8717
Does not list oidc configs for HCP clusters if param for classic-oidc-config is specified
We already know user is not interested in the pre registered oidc configs

[SDA-8717] Interactive mode --classic-oidc-config param should not list oidc configs

---

cmd/create/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8741
Don't enter interactive mode if forcing to choose default role arn
Faster UX flow, specially in automation

[SDA-8741] If -y is specified no need to go into interactive mode creating oidc-config

---

cmd/verify/oc/cmd.go

We are using only the local oc client version.
By passing the --client flag we can avoid any remote call making the call faster.

oc client version local check only

---

cmd/list/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8752
Add type of cluster column in list clusters command
Easier for customer to check

[SDA-8752] Add type of cluster column in list clusters command

---

cmd/list/accountroles/cmd.go
cmd/list/cmd.go
cmd/list/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-8753
Add list operator-roles command with version and prefix params
With the possibility of reusing operator-roles might be nice for the user to be able to check which are in place and which version they belong to

[SDA-8753] Add list operator-roles command

---

cmd/verify/rosa/cmd.go

This ensures that automation is not interrupted when running the version/verify commands.
Fixes #1157

verify: Ensure stdout is only printed in terminal mode

---

CHANGES.adoc
pkg/info/info.go

- Use cluster attribute `ManagedPolicies` to identify cluster with managed policies
- fix: add red-hat-managed tag to oidc config and oidc provider resources
- feat: add possibility to reuse operator roles
- feat: add description when available for error state in describe cluster
- Describe cluster - add managed policies field to the output
- [SDA-8325](https://issues.redhat.com//browse/SDA-8325) Add subnets field for Default Worker
- Create cluster - roles with managed policies
- fix: block --watch when on manual mode for creating cluster
- [SDA-8040](https://issues.redhat.com//browse/SDA-8040) Align machinepool condition for enter in interactive mode
- Update k8s.io/apimachinery to v0.26.2
- Create OCM admin roles in manual mode - add all tags to policy
- feat: Add option to remove oidc …

Release v1.2.16

---

cmd/create/oidcconfig/cmd.go
pkg/interactive/helper.go

Related issue: https://issues.redhat.com/browse/SDA-8790
Should use passed role arn when creating the oidc config
Role ARN from arguments was being overwritten

SDA-8790 | fix: use parameter installer role arn when passed

---

pkg/ocm/versions.go

As the `HasHostedCPSupport` method is used in the nodepool flow, so we need to handle errors in the caller

Fix version validation error handling

---

cmd/list/operatorroles/cmd.go
pkg/output/output.go

Related issues:
* https://issues.redhat.com/browse/SDA-8804
* https://issues.redhat.com/browse/SDA-8805
Corrects behavior when listing operator roles
Few things were not working as intended

SDA-8804,8805 | fix: better behavior for listing operator roles

---

cmd/create/idp/github.go
cmd/create/idp/gitlab.go
cmd/create/idp/ldap.go
cmd/create/idp/openid.go
cmd/edit/cluster/cmd.go
pkg/config/config.go
pkg/logging/round_tripper.go
pkg/ocm/helpers.go

```
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.
```

chore: remove deprecated lib `io/ioutil`

---

cmd/create/cluster/cmd.go
cmd/list/oidcconfig/cmd.go
pkg/interactive/helper.go
pkg/ocm/oidc_config.go

Related issue: https://issues.redhat.com/browse/SDA-8808
Filters unmanaged OIDC configs by aws account ID
When customer selects a config from a different account cluster install will fail

SDA-8808 | feat: add aws account ID to filter unmanaged OIDC configs

---

cmd/list/operatorroles/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8805

SDA-8805 | fix: better messages when listing operator roles for specific version

---

cmd/dlt/oidcprovider/cmd.go
pkg/aws/helpers.go

When customer sets up oidc provider using '/' at the end of the URL the deletion process fails
Fixes a flow issue

fix: small issue when customer sets up oidc provider with issuer url '/' at the end

---

cmd/initialize/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-6239
Adds message from the deprecated value this substituted
There was no helper message

SDA-6239 | fix: Add message to helper --delete param on init cmd

---

cmd/create/cluster/cmd.go
pkg/aws/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-7708
Removes the actual param when exemplifying tags usage
Easier for user to understand

SDA-7708 | fix: remove --tags param from example for usage

---

cmd/create/accountroles/cmd.go

Related: [SDA-8842](https://issues.redhat.com/browse/SDA-8842)

Warn about `version` flag in combination with HCP managed policies

---

.github/workflows/check-commit-format.yml
CONTRIBUTING.md

This is an initial change to start adding some github action helpers. 
This change is a simple change to check the format of the git commit message.

chore: add initial github action to checking commit message format

---

pkg/ocm/config.go

Related issue: https://github.com/openshift/rosa/issues/975

fix: trims trailing slash in ocm api when checking env

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8861
Add param when building commands for creating cluster
Currently missing param

SDA-8861 | feat: add --etcd-encryption-kms-arn to cluster build command when in use

---

cmd/upgrade/roles/cmd.go
pkg/aws/policies.go
pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/SDA-8897
When using shared operator roles with managed policies the validation does not need to consider the policies version
Managed policies are compatible with all cluster versions

SDA-8897 | fix: shared operator roles with managed policies

---

cmd/create/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8900
Only allows auto to be selected in interactive mode if output param is also present
Better CX

SDA-8900 | feat: only allow aws auto mode when choosing and output flag enabled

---

cmd/upgrade/cluster/cmd.go

Fix the order of parameter requests. Currently interrupting the creation when drain time is asked will cause the upgrade to be already scheduled.
JIRA: [SDA-8892](https://issues.redhat.com//browse/SDA-8892)

SDA-8892 | fix: Ask for drain period before scheduling the update

---

cmd/describe/upgrade/cmd.go
cmd/list/upgrade/cmd.go
pkg/ocm/clusters.go

This implements `rosa list upgrade` command for Hypershift clusters
Example
```
rosa list upgrade -c 2380giimi8ahlqk4g6af942749u9o9p4
VERSION      NOTES
4.13.0-rc.4  recommended
4.13.0-rc.3
4.13.0-rc.2
4.12.14      recommended
4.12.13      scheduled for 2023-04-21 09:47 UTC
4.12.11
4.12.10
```
It is now aligned with `rosa describe upgrade`
```
rosa describe upgrade -c 2380giimi8ahlqk4g6af942749u9o9p4
ID:                         1c000386-e028-11ed-b02d-0a580a800b63
Cluster ID:                 2380giimi8ahlqk4g6af942749u9o9p4
Next Run:                   2023-04-21 09:47:00 +0000 UTC
Upgrade State:              scheduled
Version:                    4.12.13
```
Related: [SDA-8880](https://issues.redhat.com//browse/SDA-8880)

SDA-8880 | Fix: implement list upgrades for Hypershift

---

CHANGES.adoc
pkg/info/info.go

- logging: Disable quoting of values - makes request/response dumps readable
- chore: remove deprecated lib `io/ioutil`
- fix: version tests
- [SDA-8789](https://issues.redhat.com//browse/SDA-8789) | feat: add oidc config id to message
- [SDA-8777](https://issues.redhat.com//browse/SDA-8777) | feat: check if there are clusters using operator roles prefix
- [SDA-8790](https://issues.redhat.com//browse/SDA-8790) | fix: use parameter installer role arn when passed
- Fix version validation error handling
- SDA-8804,8805 | fix: better behavior for listing operator roles
- [SDA-8775](https://issues.redhat.com//browse/SDA-8775): Align label and taints validation between create and edit
- [SDA-8786](https://issues.redhat.com//browse/SDA-8786) | feat: add bucket policy to allow public read
- …

Release v1.2.17

---

cmd/hibernate/cluster/cmd.go
cmd/hibernate/cmd.go
cmd/resume/cluster/cmd.go
cmd/resume/cmd.go
cmd/rosa/main.go

When calling `rosa hibernate|resume cluster` it always asks for a confirmation. However, the `--help` text does not show that the confirmation prompt can be bypassed with the `--yes`.
This PR adds the --yes flag to these operations.

fix: Add flag to bypass confirmation for hibernate/resume

---

cmd/create/cluster/cmd.go

Update the help message to include the hosted cluster case.

SDA-8690 Update replicas help message for hosted-cp cluster

---

cmd/dlt/tuningconfigs/cmd.go

Align the command to the rest of tuning config commands to accept
```
rosa delete tuning-config -c <cluster> name
```
Related: [SDA-8382](https://issues.redhat.com//browse/SDA-8382)

SDA-8382| Fix: delete tuning config bad definition

---

cmd/create/machinepool/helper.go
cmd/create/machinepool/machinepool.go

Related issue: https://issues.redhat.com/browse/SDA-6562
Shows only subnets from supplied AZ
So as not to show user subnets he might not be interest in

SDA-6562 | feat: skip subnet choice when AZ is supplied

---

CHANGES.adoc
pkg/info/info.go

- SDA-8382|feat:Add create/list/describe/update/delete tuning configs
- SDA-8382|feat:Add tuning config support for node pools
- [SDA-8883](https://issues.redhat.com//browse/SDA-8883) | Feat: expose scheduling time for hypershift upgrade
- fix: Add flag to bypass confirmation for hibernate/resume
- refactor: removing init and global variables for hibernate/resume
- [SDA-8920](https://issues.redhat.com//browse/SDA-8920) | fix: improve upgrade roles / operator-roles info messages
- [SDA-8900](https://issues.redhat.com//browse/SDA-8900) | fix: adjust behavior for creating with -o
- [SDA-8971](https://issues.redhat.com//browse/SDA-8971) | build : update dep golang.org/x/net
- [SDA-8690](https://issues.redhat.com//browse/SDA-8690) Update replicas help message for hosted-cp cluster
- SDA-8382| …

Release v1.2.18

---

cmd/create/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go

1. Prevent creating classic account roles with prefixes ending with `-HCP`.
2. Improve the error message for `rosa upgrade account-roles`.
Prevent `-HCP` for classic account roles:
Improve `upgrade account roles` error messages:

SDA-8914 | fix: rosa upgrade hcp account roles - handle edge cases

---

cmd/create/oidcprovider/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8636
When calling from oidc config flow the cluster ID is unknow
Was failing to create the oidc provider from oidc config flow

SDA-8636 | fix: OIDC provider behavior when calling internally from oidc config flow

---

cmd/create/cluster/cmd.go

ref: https://issues.redhat.com/browse/SDA-8716?filter=-1

SDA-8716 | Fix: provide warning message when no OIDC config is found

---

cmd/create/cluster/cmd.go
pkg/interactive/helper.go

Related issue: https://issues.redhat.com/browse/SDA-8770
Selects only official default prefix when selecting as part of auto confirm mode
Non official default prefix shouldn't be selected without args being supplied

SDA-8770 | fix: accept only official default prefix when selecting default prefix

---

cmd/dlt/accountroles/accountroles_suite_test.go
cmd/dlt/accountroles/cmd.go
cmd/dlt/accountroles/cmd_test.go

For the interactive mode, prompt a message for deleting hosted CP account roles.

SDA-8600 | feat: add interactive option for delete account roles

---

cmd/create/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-9041
Managed configs are easier to setup and use

SDA-9041 | feat: defaults to managed oidc configs

---

cmd/create/cluster/cmd.go
cmd/edit/machinepool/nodepool.go

On hosted clusters, when the user doesn't define the number of replicas, instead having a fixed number, it takes the number of private subnets as default.

SDA-8689 Adjust default replicas on hosted clusters

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/create/oidcconfig/cmd.go
cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
cmd/verify/rosa/cmd.go
pkg/ocm/helpers.go

Related issues:
* https://issues.redhat.com/browse/SDA-9048
* https://issues.redhat.com/browse/SDA-9053
Helps customer to be more aware of the flow through each step prior to creating the cluster
Also adds a check for the path between installer role and operator roles
Makes the flow less confusing

SDA-9048 | feat: add messages and checks to ensure a better flow UX wise

---

CHANGES.adoc
pkg/info/info.go

- [SDA-8770](https://issues.redhat.com//browse/SDA-8770) | fix: accept only official default prefix when selecting default prefix
- [SDA-8914](https://issues.redhat.com//browse/SDA-8914) | fix: rosa upgrade account roles - handle edge cases
- SDA-8382| Fix: skip replicas when passing tuning configs to edit
- [SDA-8636](https://issues.redhat.com//browse/SDA-8636) | fix: OIDC provider behavior when calling internally from oidc config flow
- [SDA-9041](https://issues.redhat.com//browse/SDA-9041) | feat: defaults to managed oidc configs
- [SDA-8716](https://issues.redhat.com//browse/SDA-8716) | Fix: provide warning message when no OIDC config is found
- added billing account information to rosa describe cluster command
- [SDA-8600](https://issues.redhat.com//browse/SDA-8600) | feat: add …

Release v1.2.19

---

cmd/edit/ingress/cmd.go

Related: [SDA-8109](https://issues.redhat.com//browse/SDA-8109)

Allow editing ingress privacy for private hypershift cluster

---

cmd/create/cluster/cmd.go

Minor one, as "multi-az" flag is deprecated for hosted clusters.

SDA-8718 Update rosa create message for hosted cluster

---

cmd/dlt/operatorrole/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-186
Only prints the success message if no errors occur for any deletion of operator roles
Success shouldn't be shown if errored

OCM-186 | fix: only print success message if no errors occur

---

cmd/create/oidcprovider/cmd.go
cmd/dlt/oidcprovider/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-9078
Only asks for aws mode if flag is not changed
No reason to ask for mode if user already requested it

[SDA-9078] fix: only ask mode if flag is not changed

---

cmd/create/machinepool/machinepool.go
cmd/create/machinepool/nodepool.go
cmd/list/instancetypes/cmd.go
pkg/ocm/machines.go

~~Minimal change to improve the wording of the machine type not found error.~~
I've prepared a patch for two similar issues (I see more complexity in splitting the patch, and I think it makes sense to put it together)
https://issues.redhat.com/browse/SDA-8963
https://issues.redhat.com/browse/SDA-9075
This PR will cover the following:
- A minimal refactoring to include the region and the availability zones in the MachineTypeList object.
- Improve the validation message when an instance type is not found in a given AZ.
- Fix a situation where the user may select a new subnet/AZ that is not part of day 1, and in the new AZ, there are different machine types.
Please, @andreadecorte @ciaranRoche @gregsheremeta, feel free to review. 
Thanks

SDA-8963 Improve machine type not found message

---

CHANGES.adoc
pkg/info/info.go

- Allow editing ingress privacy for private
- [SDA-6451](https://issues.redhat.com//browse/SDA-6451) Fix: Improve error msg displayed when deletion of admin user fails
- [SDA-8718](https://issues.redhat.com//browse/SDA-8718) Update rosa create message
- fix : update action to run on each commit in a pull request
- [SDA-9074](https://issues.redhat.com//browse/SDA-9074) | fix : only create route selector builder on ingress edit if route selectors exist
- [OCM-186](https://issues.redhat.com//browse/OCM-186) | fix: only print success message if no errors occur
- [SDA-9078](https://issues.redhat.com//browse/SDA-9078) | fix: only ask mode if flag is not changed
- [SDA-8963](https://issues.redhat.com//browse/SDA-8963) Improve machine type not found message …

Release v1.2.21

---

cmd/dlt/operatorrole/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-9086
Check aws errors before moving flow forward when deleting roles by prefix
Was not being checked

SDA-9086 | fix: check error when retrieving operator-roles

---

cmd/create/accountroles/cmd.go

**Note:** this change will be available in prod once all managed policies are published.
Example:
```
oadler@fedora:rosa (SDA-8538)$ ./rosa create account-roles -i
I: Logged in as 'oadler.openshift' on 'https://api.stage.openshift.com'
I: Current OpenShift Client Version: 4.11.0
? Role prefix: oadler
? Permissions boundary ARN (optional): 
? Path (optional): 
? Role creation mode: auto
? Create hosted CP account roles: Yes
I: …
```

SDA-8538 | fix: create hcp account roles in interactive mode

---

cmd/create/cluster/cmd.go

this causes osde2e to exit before running the test suite due our usage of rosa (imported)
closes #1238

remove os.Exit in cluster creation cmd

---

cmd/create/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-9105
Asks customer which oidc configuration kind when interactive is enabled
Was not asking prior and assuming default of managed

SDA-9105 | feat: asks for OIDC Configuration kind in interactive

---

cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
pkg/helper/helpers.go

Related issue: https://issues.redhat.com/browse/OCM-263
Adjusts behavior when creating operator-roles with `-f` param
No need to check s3 bucket as we can trust oidc-config spec, if something wrong happens will be caught creating the cluster
When using `-f` it should bypass validation that the operator already exist

OCM-263 | fix: behavior when creating operator-roles

---

cmd/create/oidcconfig/cmd.go
pkg/aws/client.go
pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/SDA-9087
Validates version of installer role arn
When specifying the param directly version was not being validated

SDA-9087 | fix: validate installer role arn after selection

---

cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/cmd.go
pkg/ocm/clusters.go
pkg/ocm/clusters_test.go
pkg/ocm/helpers.go
pkg/ocm/helpers_test.go

Related issue: https://issues.redhat.com/browse/OCM-264
Properly checks the path when validating trusted relationship
Customer shouldn't be able to change the trusted relationship of existing roles

OCM-264 | fix: Properly checks the path when validating trusted relationship

---

cmd/hibernate/cmd.go
cmd/resume/cmd.go

My dear colleagues, I must confess to a grave mistake in the form of a grammatical error which had crept into our code's help message. It was a flaw that marred the very fabric of our work and tarnished our reputation as meticulous developers. But fear not, for I have undertaken the noble task of rectifying this grammatical oversight with all the fervor and passion of a true grammarian. Let it be known that this error shall plague us no more, and our help message shall now read with the grace and fluidity befitting of our esteemed profession.
https://issues.redhat.com/browse/SDA-9101

fix: remidiating gramatical typo in hibernation help messages

---

cmd/dlt/operatorrole/cmd.go
pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/OCM-301
Goes through both classic and hcp operator roles when deleting by prefix
At some point credential requests API changed to only return either classic or hcp and not both merged together

OCM-301 | fix: goes through both operator roles type when deleting by prefix

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/list/region/cmd.go
cmd/upgrade/accountroles/cmd.go

- Remove the `Hypershift` from the help messages.
- Unhide the `--classic` flag.
Related: [OCM-285](https://issues.redhat.com/browse/OCM-285)

OCM-285 | feat: unhide hcp params

---

CHANGES.adoc
pkg/info/info.go

- [SDA-8538](https://issues.redhat.com//browse/SDA-8538) | fix: create hcp account roles in interactive mode
- [SDA-9086](https://issues.redhat.com//browse/SDA-9086) | fix: check error when retrieving operator-roles
- remove os.Exit in cluster creation cmd
- [SDA-9105](https://issues.redhat.com//browse/SDA-9105) | feat: asks for OIDC Configuration kind in interactive
- [OCM-140](https://issues.redhat.com//browse/OCM-140): ROSA Cli for IMDSv2 for OSD/ROSA adding new http-tokens params to match aws cli option
- [OCM-213](https://issues.redhat.com//browse/OCM-213) | ci : skip tests that can not be run in prow
- fix: behavior when creating operator-roles
- [SDA-9087](https://issues.redhat.com//browse/SDA-9087) | fix: validate installer role arn after selection
- …

Release v1.2.22

---

cmd/create/cluster/cmd.go
cmd/upgrade/accountroles/cmd.go

Omit the `--hosted-cp` flag from the error message and fix the string formatting.
```
oadler@fedora:rosa (create-cluster-fix-warning-message)$ ./rosa create cluster --cluster-name zg-may18 --sts --region us-west-2 --replicas 2 --compute-machine-type m5.xlarge --machine-cidr 10.0.0.0/16 --service-cidr 172.30.0.0/16 --pod-cidr 10.128.0.0/14 --host-prefix 23 --subnet-ids subnet-0d65e2465258986db,subnet-0cbc29215162f7548 --hosted-cp --yes --mode=auto --oidc-config-id 23ihr0nit0krcdvt4v8qtjltkptj2947 --dry-run true
I: NOTE: Hosted control planes are currently in Technology Preview (https://access.redhat.com/support/offerings/techpreview). Any Technology Preview clusters will need to be destroyed and recreated prior to general availability. …
```

Create cluster - fix error messages

---

README.md

Existing rosa-aws-cli:latest image in registry.ci could be leveraged to test the binary
locally without the need to build from source code. Added instructions to get the rosa
cli binary from the container.

OCM-785 | docs: Add instructions to get rosa binary from latest

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/upgrade/accountroles/cmd.go

In 1.2.22 we emit an info message when running rosa create cluster --hosted-cp, but we missed also including Technology Preview reference in the --help output.  Revert this PR when we exit Technology Preview phase.

add Technology Preview to --help output for hosted-cp

---

cmd/list/cmd.go
cmd/list/oidcprovider/cmd.go
pkg/aws/client.go
pkg/aws/sts.go
pkg/output/output.go

Related issue: https://issues.redhat.com/browse/SDA-4652
Adds listing of identity providers in current AWS account filtering `red-hat-managed:true` tags
For the identity providers which are created through an OIDC configuration is shows the cluster ID as empty ("") and the OIDC configuration ID is not yet retrieved. This will be part of second PR 
```
./rosa list oidc-provider                                    
I: Fetching OIDC providers
/ time=2023-05-29T09:04:19-03:00 level=warning msg=Throttling Rate limit exceeded. Retrying the request again
OIDC PROVIDER ARN                                                                                                Cluster ID
arn:aws:iam::xxx:oidc-provider/d1b0cha94ris3q.cloudfront.net/xxx …
```

SDA-4652 | feat: add list oidc providers command

---

cmd/create/operatorroles/by_prefix.go
pkg/helper/helpers.go

Related issue: https://issues.redhat.com/browse/OCM-1013
Removes dial call, trusting OCM registered configuration

OCM-1013 | fix: remove dial issuer url when creating operator roles by prefix

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/SDA-8838

SDA-8838 | fix: STS default warning does not show for hcp

---

cmd/edit/cluster/cmd.go

JIRA: https://issues.redhat.com/browse/OCM-1361
This PR adds functionality to the edit cluster command to accept a "-y" flag to bypass confirmation on certain changes. Editing proxy values remains unchanged as the confirmation question was never asked on these commands

OCM-1361 | fix: Add flag to bypass confirmation on edit cluster

---

cmd/link/userrole/cmd.go
cmd/unlink/userrole/cmd.go

Related Issue: https://issues.redhat.com/browse/OCM-1410

OCM-1410 | fix: correct error message when 'rosa link user-role' with account-id under diff org

---

cmd/list/cluster/cmd.go
pkg/ocm/clusters.go

This adds an option to list all clusters associated with a Red Hat account that are spread across different AWS accounts.  
This is the default view when using the Hybrid Console.  This change brings the same functionality to the ROSA CLI.
Related: https://issues.redhat.com/browse/OCM-1021

Add the ability to list all clusters

---

cmd/list/service/cmd.go
pkg/output/output.go

Related issue: [OCM-1179](https://issues.redhat.com/browse/OCM-1179)

OCM-1179 | fix: act on output flag for list service command

---

cmd/create/idp/cmd.go
cmd/create/idp/htpasswd.go
pkg/ocm/idps.go

-- Currently, ROSACLI for htpasswd idp, accepts only one username and password to add to the IDP 
-- the changes in this PR allow user to input multiple users at a time through the -users flag 
-- the old flags of username/password will continue to be supported for backward comptability 
-- and so as not to break existing automation
Refers to https://issues.redhat.com/browse/OCM-842

OCM-842|Feat: Accept multiple users for htpasswd IDP

---

cmd/upgrade/cluster/cmd.go
cmd/upgrade/cluster/cmd_test.go
cmd/upgrade/cluster/upgrade_suite_test.go
go.mod
go.sum
pkg/ocm/client.go
vendor/github.com/robfig/cron/v3/.gitignore
vendor/github.com/robfig/cron/v3/.travis.yml
vendor/github.com/robfig/cron/v3/LICENSE
vendor/github.com/robfig/cron/v3/README.md
vendor/github.com/robfig/cron/v3/chain.go
vendor/github.com/robfig/cron/v3/constantdelay.go
vendor/github.com/robfig/cron/v3/cron.go
vendor/github.com/robfig/cron/v3/doc.go
vendor/github.com/robfig/cron/v3/logger.go
vendor/github.com/robfig/cron/v3/option.go
vendor/github.com/robfig/cron/v3/parser.go
vendor/github.com/robfig/cron/v3/spec.go
vendor/modules.txt

This change adds 2 additional parameters to pass a schedule to the control plane upgrades.
It also improve the behaviour of interactive mode to be more useful. Testing has been added by mocking the calls to the backend. A new dependency is added to check the cron syntax with the same library used in the backend.
All the changes applies for the moment only to Hosted Control Planes
Related: [OCM-953](https://issues.redhat.com//browse/OCM-953)

OCM-953 | feat: add automatic upgrades for hypershift control plane

---

cmd/create/idp/htpasswd.go

Only the last user in the list was being set on the userlistBuilder, 
Adding each individual userBuilder to an array before setting the items on the userListBuilder
Ref: https://issues.redhat.com/browse/OCM-2241

OCM-2241| fix: Ensure all input users are added to the user list

---

pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/OCM-2157
When creating policies the error check for deleting older policy versions was missing

OCM-2157 | fix: ensure policy when calling delete policy versions was  not checking for errors

---

cmd/describe/upgrade/cmd.go
cmd/upgrade/cluster/cmd.go

This is not available at this step. Version is computed by the backend. Improve also output of describe upgrade command
Related: [OCM-2274](https://issues.redhat.com//browse/OCM-2274) [OCM-2278](https://issues.redhat.com//browse/OCM-2278)
Output example
```
rosa describe upgrade -c ad-stg1
ID:                                21ac7f1a-06da-11ee-b176-0a580a830047
Cluster ID:                        248f2o9pi208rpjfe2mjdnqa1j11c1sg
Schedule Type:                     automatic
Next Run:                          2023-06-09 20:20:00 +0000 UTC
Upgrade State:                     scheduled
Schedule At:                       20 20 * * *
Enable minor version upgrades:     true
Version:                           4.12.19
```

OCM-2274 | Fix: skip version check for automated upgrade

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go
cmd/dlt/accountroles/cmd.go

1. The default flow creates two sets of roles: 3 for Hypershift and 4 for Hive.
2. Passing the `classic` flag will create only 4 roles for Hive.
3. Passing the `hosted-cp` flag will create only 3 roles for Hypershift.
Related: [[SDA-8665](https://issues.redhat.com/browse/SDA-8665)]
Default flow creates double sets:
Passing the `hosted-cp` flag creates one set:

Create Hypershift dedicated account roles

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go

AWS published all the managed policies, therefore, exposing the flag.
Related: [OCM-2259](https://issues.redhat.com/browse/OCM-2259)

OCM-2259 | feat: Expose `--hosted-cp` flag

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
cmd/dlt/accountroles/cmd.go
cmd/dlt/operatorrole/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go

1. Remove the check for HCP-managed policies in production.
2. Leave the check for Classic ROSA managed policies in the commands: `create account-roles`, and `create ocm-role`.
**Note:** The `--managed-policies` flag applies to classic ROSA.
Unblock the path for `--hosted-cp` in production, which comes along the HCP AWS managed policies.
Related: [OCM-300](https://issues.redhat.com/browse/OCM-300)

OCM-300 | feat: remove environment check for managed policies

---

cmd/upgrade/cluster/cmd.go

Backend is already returning enough context for the user, the additional message may be misleading
Related: [OCM-2181](https://issues.redhat.com//browse/OCM-2181)

OCM-2181 | Fix: error message was misleading

---

cmd/create/oidcconfig/cmd.go
cmd/register/cmd.go
cmd/register/oidcconfig/cmd.go
cmd/rosa/main.go
pkg/constants/oidc_config.go
pkg/helper/oidc_config/helper.go

Related issue: https://issues.redhat.com/browse/OCM-955
Command to register unmanaged oidc configurations. This allows the customer to try again if something fail during the creation of resources

OCM-955 | feat: register oidc config command

---

pkg/aws/helpers.go

Description of problem:
The AuditLogArnRE (regex) should allow the iam role arn with path setting and pass the validation.
BEFORE FIX
Example that passes:
arn:aws:iam::000000000000:role/asdf-audit-r
Example that fails:
arn:aws:iam::000000000000:role/aa/asd/asdf-audit-r
AFTER FIX
Example that passes:
arn:aws:iam::000000000000:role/asdf-audit-r
arn:aws:iam::000000000000:role/aa/asd/asdf-audit-r

OCM-2347: Accept path setting thru iam role check - regex

---

cmd/create/cluster/cmd.go
cmd/edit/cluster/cmd.go
pkg/aws/helpers.go

Per AWS documentation,
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
Role name can compose of some characters outside of "alphanumeric" characters:
I previously made an incorrect assumption; thus making the correct adjustment.
Regex (`^arn:aws[\w-]*:iam::\d{12}:role(?:\/+[\w+=,.@-]+)+$`) is also the same format being used in CS for generic IAM Roles

[OCM-2347] fix: accept limited symbols in role name section of arn

---

cmd/dlt/machinepool/nodepool.go
cmd/edit/machinepool/nodepool.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/cluster/cmd_test.go
pkg/interactive/upgrades.go
pkg/ocm/controlplane_upgrades.go
pkg/ocm/nodepools.go
pkg/ocm/upgrades.go

No functional change. Changing the message when a node pool is not found from
```
Failed to get machine pools for hosted cluster 'ad-loc1': Node pool with id 'workers4' not found.
```
to
```
Machine pool 'workers4' does not exist for hosted cluster 'ad-loc1'
```
To be consistent with the wording.

OCM-954 | Feat: small refactor to prepare for nodepool upgrades

---

cmd/create/idp/htpasswd.go

Ref: https://issues.redhat.com/browse/OCM-2256

OCM-2256| Fix : Remove debug msg that prints the user/password list

---

cmd/create/idp/cmd.go
cmd/create/idp/htpasswd.go

REF: https://issues.redhat.com/browse/OCM-2257
Remove  flags  username/password from help/usage msg as they are only for backwards compatibility.
Validate users and username flags are mutually exclusive

OCM-2257 | fix: Ensure only one of users or username flags is provided

---

pkg/aws/helpers.go

[OCM-1150](https://issues.redhat.com/browse/OCM-1150)
Tags previously had no validation for a value, leaving them susceptible to being empty upon cluster creation. This leads to an error when creating the cluster, and the whole interactive process must be redone to try again.
This validation checks if the substring after ":" is empty. If it is, throw an error and ask for tags again.
PS if someone could let me know if this is a proper way of handling, or if I should log an error then keep going/ignore the tags? I feel like it's best to re-try, but this might affect scripts to create clusters if they have invalid tags in them.

OCM-1150 | fix: Validation for 'value' in tags when creating a non-sts cluster

---

cmd/create/accountroles/cmd.go

[OCM-1755](https://issues.redhat.com/browse/OCM-1755) is about removing an unneeded log message that pops up after creating account roles. This affects the ROSA UI.

OCM-1755 | fix: Removed unneeded log about creating cluster after creating accout-roles

---

cmd/create/oidcconfig/cmd.go

[OCM-2427](https://issues.redhat.com/browse/OCM-2427) requires extra information in a info message to  the user. The reporter requested suggesting the user run the following command: `rosa register oidc-config`

OCM-2427 | fix: Added command in INFO message to register oidc config after creating

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
pkg/ocm/helpers.go

In the case of creating a cluster with managed policies and reusing existing operator roles, validate the operator roles have managed policies.
Related: [OCM-2440](https://issues.redhat.com/browse/OCM-2440)

OCM-2440 | fix: reuse operator roles - validate compatible policies

---

cmd/register/oidcconfig/cmd.go

[OCM-2422](https://issues.redhat.com/browse/OCM-2422) Is about an error message that has 'please try again' + a command to try again with the same information, which will cause the same error message to occur.
So, I have removed this command + 'please try again' from the error message.

OCM-2422 | fix: Edited error message to no longer include 'please try again'

---

cmd/create/idp/cmd.go
cmd/create/idp/htpasswd.go

https://issues.redhat.com/browse/OCM-844
Add flag to provide a htpasswdfile , create IDP from the users and hashed passwords loaded  from the htpasswd file

OCM 844 | feat:  Support loading users from htpasswd file

---

cmd/verify/network/cmd.go

```
$ rosa verify network --subnet-ids subnet-0b761d44d3d9a4663,subnet-0f87f640e56934cbc --role-arn arn:aws:iam::765374464689:role/tomckay-Installer-Role
I: Verifying the following subnet IDs are configured correctly: [subnet-0b761d44d3d9a4663 subnet-0f87f640e56934cbc]
I: subnet-0b761d44d3d9a4663: pending
I: subnet-0f87f640e56934cbc: passed
I: Run the following command to wait for verification to complete:
rosa verify network --watch --status-only --subnet-ids subnet-0b761d44d3d9a4663,subnet-0f87f640e56934cbc
```

OCM-152 | feat: update the displayed output

---

cmd/login/cmd.go
pkg/fedramp/config.go
pkg/fedramp/flag.go
pkg/ocm/config.go

REF: [OCM-2433](https://issues.redhat.com/browse/OCM-2433) and [OSD-16451](https://issues.redhat.com/browse/OSD-16451)
* adds new --admin flag that overrides aliases for FedRAMP for the SREP Cognito endpoints (hidden flag)
* adds new login/url aliases for SREP endpoints for FedRAMP
* updates all related logic to check for this flag and set the correct aliases accordingly

OCM-2433 | feat: adds admin flag for fedramp

---

pkg/fedramp/config.go

Adapted from https://github.com/openshift/rosa/pull/1337

OCM-347 | fix: Align FedRAMP non-admin token url and client IDs for integration

---

cmd/dlt/oidcconfig/cmd.go

[OCM-2421](https://issues.redhat.com/browse/OCM-2421) is about a prompt that came up when deleting an oidc config and passing in the `--oidc-config-id` flag that should not have came up. It asked for the OIDC config ID when it was already given in the flag. The prompt no longer comes up if the flag is Changed.

OCM-2421 | fix: Made prompt for OIDC COnfig ID not happen when flag given

---

cmd/describe/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-2348
What
Adds a row in "rosa describe cluster -c $CLUSTER" output that indicates whether audit log forwarding is enabled as well as the audit log ARN (if forwarding is enabled). 
Why
Better UX

[OCM-2348] Add audit log details in rosa describe cluster

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go
cmd/create/cluster/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go

As there are still some blockers for HCP managed policies, we need to:
1. Hide the "hosted-cp" flags for the roles commands.
2. Block creation of account-roles in production.
3. Revert default flow of create account-roles (not creating two sets).
4. Adjust error messages for create/upgrade cluster.
Related: [OCM-2653](https://issues.redhat.com/browse/OCM-2653)

OCM-2653 | fix: remove/hide HCP managed policies before release

---

cmd/create/admin/cmd.go
cmd/create/idp/cmd.go
cmd/create/idp/htpasswd.go
cmd/describe/admin/cmd.go
cmd/dlt/admin/cmd.go
cmd/dlt/idp/cmd.go

Ref: https://issues.redhat.com/browse/OCM-2506
As part of this work,
Any number of htpasswd IDPs can now be created just as any other IDP type like LDAP, OPENID etc.
admin user is created in a separate htpasswd IDP instance  named "cluster-admin".
Changes have been  made to the following flows to implement this design change.
admin - create, describe, delete flow to allow for this.
htpasswd idp - create, delete.

OCM-2506 | feat : Allow creation of multiple htpasswd idps

---

cmd/link/ocmrole/cmd.go
cmd/link/userrole/cmd.go

JIRA: [OCM-1295](https://issues.redhat.com//browse/OCM-1295)
This change has been updated to include user roles in the filtering as well as making sure that the ARN path is correct

OCM-1295 | fix: add validation for roles

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go
pkg/aws/helpers.go
pkg/aws/helpers_test.go

JIRA - https://issues.redhat.com/browse/SDA-8534
This change enabled using tags with a `:` value in either key or value. 
To support backwards compatibility we still support the `:` delim between the key value pairs. To pass a key or value with the `:` value a user can use a whitespace as a delim 
```
rosa create cluster           
? Cluster name: croche1
? Deploy cluster with Hosted Control Plane (optional): No
? Create cluster admin user: No
? Deploy cluster using AWS STS: Yes
W: --sts flag won't be necessary if you wish to use STS.
W: --non-sts/--mint-mode flag will be necessary if you do not wish to use STS.
? OpenShift version: 4.12.22
? Configure the use of IMDSv2 for ec2 instances optional/required …
```

SDA-8534 | fix : update tag format to all `:` be a valid value

---

cmd/list/version/cmd.go

This should help users to migrate to the correct command.
@xueli181114

OCM-2180 | fix: improve info message for the command to use to list upgrades

---

cmd/verify/network/cmd.go

```
$ rosa verify -h
Verify resources are configured correctly for cluster install
Usage:
rosa verify [command]
Available Commands:
network          Verify VPC subnets are configured correctly
openshift-client Verify OpenShift client tools
permissions      Verify AWS permissions are ok for non-STS cluster install
quota            Verify AWS quota is ok for cluster install
rosa-client      Verify ROSA client tools
Flags:
-h, --help   help for verify
Global Flags:
--color string   Surround certain characters with escape sequences to display them in color on the terminal. Allowed options are [auto never always] (default "auto")
--debug          Enable debug mode.
Use "rosa verify [command] --help" for more information about a command.
```

OCM-2649 | fix: add 'rosa verify network' help message

---

cmd/upgrade/operatorroles/cmd.go

JIRA - https://issues.redhat.com/browse/OCM-2731
When creating operator roles, we default to the `latest` version and not the `default` version. This change ensures we get the `latest` version when upgrading the operator roles.

OCM-2731 | fix: ensure operator roles always use the latest version

---

cmd/create/cluster/cmd.go
pkg/aws/helpers.go
pkg/aws/helpers_test.go

JIRA - https://issues.redhat.com/browse/OCM-1755
```
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-2742› 
╰─$ rosa create cluster --cluster-name croche5 --sts --role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Installer-Role --support-role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Support-Role --controlplane-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-ControlPlane-Role --worker-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-Worker-Role --operator-roles-prefix croche4-u5n7 --tags "v l,asd kl:sad,h:p asd,a:sd" --region eu-west-1 --version 4.12.22 --replicas 2 --compute-machine-type m5.xlarge --machine-cidr 10.0.0.0/16 --service-cidr 172.30.0.0/16 --pod-cidr 10.128.0.0/14 --host-prefix 23
W: --sts flag won't …
```

OCM-2742 | fix: handle nil pointer in user tag validations

---

cmd/create/accountroles/creators.go

JIRA - https://issues.redhat.com/browse/OCM-1755
Validation 
```
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-1755-fix› 
╰─$ git rev-parse HEAD
66e9593d4e9afe96b96569095fa6f51fa6ba4d8c
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-1755-fix› 
╰─$ date
Wed 12 Jul 16:35:37 IST 2023
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-1755-fix› 
╰─$ rosa create account-roles
I: Logged in as 'croche_openshift' on 'https://api.stage.openshift.com'
I: Current OpenShift Client Version: 4.12.15
I: …
```

OCM-1755 | fix: remove nudge command when creating account roles

---

cmd/create/operatorroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
pkg/ocm/versions.go

JIRA - https://issues.redhat.com/browse/OCM-2731
First issue was the function `getFirstVersion` was ignoring the `defaultFirst` param. 
Next issue is the upgrade operator roles ignores the channel of the cluster. This resulted in ending up with account roles and operator roles getting out of sync. This change uses the clusters version channel to determine the version needed to upgrade too. 
For pre-creating operator roles, this will default to the latest available on stable. 
```
rosa create account-roles --version 4.12
I: Logged in as 'croche_openshift' on 'https://api.stage.openshift.com'
I: AWS quota ok. If cluster installation fails, validate actual AWS resource usage against …
```

OCM-2731 | fix: ensure policy versions use the cluster channel

---

cmd/create/oidcconfig/cmd.go

[OCM-2424](https://issues.redhat.com/browse/OCM-2424) Is about an info message that wasn't supposed to pop up when using the create oidc-config command in Manual mode, but it did. Now the info message should only pop up when the mode is Auto

OCM-2424 | fix: Made info message only print when on auto mode

---

cmd/create/cluster/cmd.go
cmd/create/ingress/cmd.go
cmd/edit/ingress/cmd.go
cmd/list/ingress/cmd.go
pkg/ingress/policies.go
pkg/ingress/route_selector.go
pkg/interactive/interactive.go
pkg/ocm/clusters.go

Related issue: https://issues.redhat.com/browse/OCM-853
Day 2
```
rosa edit ingress -c 24qu5qv2ips5j2bhsan1kv0osagkq6pb apps
? Label match for ingress (optional): foo=bar
? Excluded namespaces for ingress (optional): stage,dev,int
? Private ingress (optional): No
? Wildcard Policy (optional, choose 'none' to skip selection): WildcardsAllowed
? Namespace Ownership Policy (optional, choose 'none' to skip selection): InterNamespaceAllowed
? Cluster Routes Hostname (optional): 
? Cluster Routes TLS Secret Reference (optional): 
I: Updated ingress 'f8g2' on cluster '24qu5qv2ips5j2bhsan1kv0osagkq6pb'
```
Syncset
```
kind: IngressController
name: default
namespace: openshift-ingress-operator
patch: >-
{"spec":{"defaultCertificate":{"name":"gdb-413-primary-cert-bundle-secret"},"domain":"apps.gdb-4 …
```

OCM-853 | feat: day1/2 operations for managed ingress attributes

---

cmd/create/idp/cmd.go
cmd/create/idp/cmd_test.go

Ref: https://issues.redhat.com/browse/OCM-2741

OCM-2741 | fix: Do not Allow IDP name cluster-admin

---

cmd/describe/cluster/cmd.go

Currently this flag is not showed in describe result and it is pretty difficult to check if it was set in rosa cli

OCM-2910: Adding Http tokens value to describe command

---

cmd/create/cluster/cmd.go
cmd/edit/ingress/cmd.go
pkg/ingress/policies.go

```
--namespace-ownership-policy string      Namespace Ownership Policy for ingress. Options are Strict,InterNamespaceAllowed. Default is 'Strict'.
--wildcard-policy string                 Wildcard Policy for ingress. Options are WildcardsDisallowed,WildcardsAllowed. Default is 'WildcardsDisallowed'.
```
```
--default-ingress-wildcard-policy string              Wildcard Policy for ingress. Options are WildcardsDisallowed,WildcardsAllowed. Default is 'WildcardsDisallowed'.
--default-ingress-namespace-ownership-policy string   Namespace Ownership Policy for ingress. Options are Strict,InterNamespaceAllowed. Default is 'Strict'.
```

OCM-2919 | fix: mention default values for args

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-1233

OCM-1233 | fix: The interactive mode should not exit after input invalid ingress label

---

cmd/dlt/ocmrole/cmd.go
cmd/dlt/userrole/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-1210

OCM-1210 | fix: enables interactive if role arn is not supplied

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-2918

OCM-2918 | fix: setting up the help in route-selector attribute

---

cmd/dlt/ocmrole/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-1138

OCM-1138 | fix: shouldnt ask for mode if supplied in args

---

cmd/create/cluster/cmd.go

We should set http tokens default value in order for user to see which version of ec2 metadata service he is using

OCM-2910 | fix: Adding default value for http tokens

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-2942

OCM-2942 | fix: adjust help usage for cluster routes attributes

---

cmd/create/cluster/cmd.go
cmd/edit/ingress/cmd.go
pkg/ingress/excluded_namespaces.go
pkg/ingress/excluded_namespaces_test.go
pkg/ingress/ingress_suite_test.go
pkg/ingress/route_selector_test.go

Related issue: https://issues.redhat.com/browse/OCM-3012

OCM-3012 | fix: trim spaces in each excluded namespace

---

pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/OCM-2276

OCM-2276 | fix: more clarity into why it might have not found the prefix

---

cmd/dlt/accountroles/cmd.go
cmd/list/operatorroles/cmd.go
cmd/upgrade/accountroles/cmd.go
pkg/aws/client.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/aws/tags/tags.go
pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/OCM-2683
Adds following values to the output when listing operator roles
- Operator name
- Operator namespace
- In-use status
- Attached policies

OCM-2683 | feat: include policies,namespace,name,in-use when listing operator roles

---

cmd/register/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-2425

OCM-2425 | fix: no need to choose installer arn when already specified in args

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-3047

OCM-3047 | fix: allow supplying empty values to reset component routes

---

cmd/register/oidcconfig/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-2425

OCM-2425 | fix: check args not changed instead of empty is more reliable

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/helper.go
pkg/aws/helpers.go

Related issue: https://issues.redhat.com/browse/OCM-2107
```
Subnet IDs:  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter, ? for more help]
[ ]  subnet-0d8b6a7d088842406 ('c12345678901234567890-9bzsf-public-us-east-1a',us-east-1a)
[ ]  subnet-0d55f331fa1124d08 ('dle-classic2-8rc8w-public-us-east-1a',us-east-1a)
[ ]  subnet-043cedb258fd4f28f ('rc-test-subnet-public1-us-east-1a',us-east-1a)
> [ ]  subnet-0caf94303dc775611 ('proxy-tests-public-do-not-delete',us-east-1b)
[ ]  subnet-09ae7dd300d7f9e61 ('zg-2-public-us-east-1a',us-east-1a)
[ ]  subnet-07cde4227fa425efb ('c12345678901234567890-9bzsf-private-us-east-1c',us-east-1c)
[ ]  subnet-0f87f640e56934cbc ('',us-east-1a)
```

OCM-2107 | fix: add name to subnet details when selecting interactively

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go
cmd/create/cluster/cmd.go
cmd/dlt/accountroles/cmd.go
cmd/upgrade/accountroles/cmd.go

This reverts commit 0cd43cabc5063077b528c04bb74828ca1c83242c.

Revert "OCM-2653 | fix: remove/hide HCP managed policies before release"
