openshift/rosa

- pkg/aws/client.go
This PR attempts to mitigate issues with throttling when checking permissions.
> Add a maximum number of retries and minimum throttle delay between retrying requests

- cmd/create/idp/cmd.go
- cmd/create/idp/github.go
- cmd/create/idp/google.go
- cmd/create/idp/ldap.go
- cmd/create/idp/openid.go
Demo: https://asciinema.org/a/7yja2V2Y9ZBaLjqiE9LT89CuX
> interactive: Add interactive mode to LDAP and OpenID IdPs

- README.md
> add moactl logs example

- README.md
Added more options around creating a cluster.
Fixed typos.
Updated the moactl logs command.
> updates to the quickstart

- README.md
Per hackday feedback, adding a tldr version to the top of the quickstart for extra eager or returning users.
> adding a tldr section to quickstart

- cmd/dlt/cluster/cmd.go
- cmd/dlt/cmd.go
- cmd/dlt/idp/cmd.go
- cmd/dlt/ingress/cmd.go
- cmd/dlt/user/cmd.go
- docs/moactl_delete.md
- docs/moactl_delete_cluster.md
- docs/moactl_delete_idp.md
- docs/moactl_delete_ingress.md
- docs/moactl_delete_user.md
- pkg/confirm/confirm.go
Also add --yes flag to automatically assume yes for delete confirmation.
> delete: Confirm operation

- install-troubleshooting.md
linking to SCP details to save having to look around
> link to aws scp doc

- README.md
Edits throughout and updating the "Add and IDP" section to call out where instructions do not need to be GitHub specific.
> update adding IDP section

- pkg/aws/client.go
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Fixes https://issues.redhat.com/browse/OSD-4403
This pr checks the IAM user of credentials, if it is a root account, return error.
> Return error if using root account

- README.md
- pkg/aws/client.go
- pkg/aws/permissions.go
- pkg/aws/quota.go
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Fixes https://issues.redhat.com/browse/OSD-4552
Readme also updated.
Verification
> OSD-4552: improve moactl verify quota error messages

- Makefile
* This will run ginkgo tests automatically but is independent
of the library used for testing
> Change from ginkgo to go test

- cmd/create/addon/cmd.go
Since add-ons cannot be uninstalled, we warn the user and ask for
confirmation before installing the add-on.
> addons: Confirm add-on installation

- cmd/download/cmd.go
- cmd/download/oc/cmd.go
- cmd/initialize/cmd.go
- cmd/verify/cmd.go
- cmd/verify/oc/cmd.go
- docs/moactl.md
- docs/moactl_download.md
- docs/moactl_download_openshift-client.md
- docs/moactl_verify.md
- docs/moactl_verify_openshift-client.md
- go.mod
- go.sum
- main.go
Demo: https://asciinema.org/a/l70JKKWWDkcAyxI6lOLYLzRxU
> Download oc tools

- CHANGES.adoc
- pkg/info/info.go
- create-cluster: List regions using user AWS creds
- list-regions: Add command to list available regions
- create-cluster: Ensure region is set when creating AWS client
- logs: Change how SDK logs are propagated
- verify-oc: Do not error out on invalid version
> Release 0.0.7

- CHANGES.adoc
- pkg/info/info.go
- verify-oc: Ensure no output on error
> Release v0.0.8

- CHANGES.adoc
- pkg/info/info.go
- AWS Rate limiting: Limit number of retries for API calls
- Prow: Add OWNERS file and pieces to support prow
> Release 0.0.9

- cmd/describe/cluster/cmd.go
cc: @vkareh @jeremyeder @igoihman  ptal
> Add 'Channel Group' attribute to 'moactl describe cluster'

- README.md
Also added a URL on how to create GitHub organizations
> Correct typos and incorrect commands in README

- CHANGES.adoc
- pkg/info/info.go
- verify-oc: Only warn when oc client missing
- verify-quota: Avoid nil pointer dereferencing
- versions: Use OpenShift versions that have MOA marketplace images
- create-cluster: Allow selective override of the paid AMI
- Correct typos and incorrect commands in README
- Update README.md
- versions: Expose channel-group
- Use OCM SDK to get token expiration
> Release v0.0.11

- cmd/describe/cluster/cmd.go
- go.mod
- go.sum
> Added Detailed Granular Status to match with OCM UI

- CHANGES.adoc
- pkg/info/info.go
- README: Update based on output of newer commands
- Added Detailed Granular Status to match with ocm UI
- verify-quota: Check for only 100 vCPU
> Release v0.0.12

- cmd/describe/cluster/cmd.go
> Add Provision Type and Reason for error cluster

- cmd/create/cmd.go
One more thing left for OSD-4972 to be completely done.
> remove validations from create command

- cmd/create/idp/cmd.go
https://asciinema.org/a/LxpgUyWNUDECxxbLjDDvXWWJd
> idp: Warn the user that it will take about 1 minute to add IdP

- cmd/logs/install/cmd.go
https://asciinema.org/a/Y96hrpdQAyfR0BZ6sFuXihbE9
note: In the demo there's an invisible 5 minute time gap to show what happens if the cluster is stuck in pending state
> logs: Improve warnings when cluster is pending

- pkg/aws/client.go
When checking whether credentials are valid, we do it on a basic shared
config, and the retrier configuration should get added later. This
ensures that whenever a request is done without valid credentials fails
early with an error instead of retrying.
> aws: Split configuration to ensure early failure

- cmd/describe/cluster/cmd.go
- go.mod
- go.sum
cc: @vkareh 
depends on https://github.com/openshift-online/ocm-api-model/pull/263
> Added New Error Message Implementation

- cmd/create/idp/cmd.go
- cmd/create/idp/ldap.go
- cmd/create/idp/openid.go
- docs/moactl_create_idp.md
* idp: Add extra scopes to OpenID IdP
* idp: Allow insecure connections on LDAP IdP
> Adding missing advanced options to IdP

- CHANGES.adoc
- pkg/info/info.go
- init: Fix test cluster name to be less than 15 characters
> Release 0.0.15

- cmd/describe/cluster/cmd.go
> Added Display Name and Domain name to describe

- cmd/create/ingress/cmd.go
- cmd/edit/ingress/cmd.go
When creating or editing an ingress, we should provide label-match and
private flag as interactive options.
> ingress: Enable interactive mode

- cmd/create/idp/cmd.go
> Added validation for name

- cmd/create/cluster/cmd.go
- cmd/create/cmd.go
- cmd/create/machinepool/cmd.go
- cmd/dlt/cmd.go
- cmd/dlt/machinepool/cmd.go
- cmd/edit/cmd.go
- cmd/edit/machinepool/cmd.go
- cmd/list/cmd.go
- cmd/list/machinepool/cmd.go
- docs/rosa_create.md
- docs/rosa_create_machinepool.md
- docs/rosa_delete.md
- docs/rosa_delete_machinepool.md
- docs/rosa_edit.md
- docs/rosa_edit_machinepool.md
- docs/rosa_list.md
- docs/rosa_list_machinepools.md
- pkg/ocm/helpers.go
- pkg/ocm/machines/machines.go
- pkg/ocm/regions/regions.go
This adds support for creating, listing, editing, and deleting machine
pools for a cluster.
Demo: https://asciinema.org/a/wZeUxAo9XAfcYqg80ZnFNs1Y3
> machinepools: Support full CRUD operations for machine pools

- cmd/create/cluster/cmd.go
- pkg/ocm/helpers.go
> Added Confirmation option for default network parameters

- cmd/create/cluster/cmd.go
To install the cluster in an existing VPC should be an explicit option
by the user. Showing the list of subnets without asking can cause
confusion as to the required cluster configuration. Here we add a simple
confirmation asking the user whether they want to use an existing VPC.
The list of subnets is only shown if the answer Yes.
https://asciinema.org/a/Wv0xh61TD0TE7bjSb0458Izqp
> create: Ask user before showing subnets

- cmd/create/cluster/cmd.go
- docs/rosa_create_cluster.md
- pkg/interactive/interactive.go
JIRA: https://issues.redhat.com/browse/SDA-3367
cc: @igoihman  @vkareh
> Dont ignore subnets from command line args if provided

- cmd/create/cluster/cmd.go
> [rosa create cluster] Verify provided subnets for Existing VPC exist in AWS

- cmd/describe/cluster/cmd.go
When a cluster version upgrade is scheduled, we display it in the
`describe cluster` command.
> describe-cluster: Display scheduled upgrades

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/cmd.go
- cmd/describe/cluster/cmd.go
- cmd/edit/machinepool/cmd.go
- cmd/list/machinepool/cmd.go
- docs/rosa_create_cluster.md
- docs/rosa_create_machinepool.md
- docs/rosa_edit_machinepool.md
- pkg/cluster/cluster.go
Add autoscaling to 
cluster create, cluster describe 
machinepool create list and edit
Related: https://issues.redhat.com/browse/SDA-3365
> Add autoscaling support

- CHANGES.adoc
- pkg/info/info.go
- cluster-admins: Remove explicit enable
- machines: Sort machine types by CPU cores
- add multi-az status to describe
- init: Use explicit login flag checks
> Release v0.1.6

- pkg/cluster/cluster.go
> Cleaning up some leftover obsolete code from autoscaling PR

- CHANGES.adoc
- pkg/info/info.go
> Release v0.1.9

- cmd/describe/cluster/cmd.go
When describing worker nodes, we should take into account all machine
pools and whether they are auto-scaled or not. If at least 1 machine
pool is auto-scaled, then we display the full range of worker nodes,
otherwise we display the actual number of replicas.
```
$ rosa list machinepools -c vkareh-rosa
ID       AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONES
default  No           2         m5.xlarge                          us-east-1a
foo      No           2         m5.xlarge                          us-east-1a
bar      Yes          3-6       m5.xlarge                          us-east-1a
$ rosa describe cluster -c vkareh-rosa | grep Nodes
Nodes:                      Master: 3, Infra: 2, Compute (Autoscaled): 7-10
```
> describe: Display total worker nodes across all machine pools

- CHANGES.adoc
- pkg/info/info.go
- arguments: Move region and profile flags
- addon: Validation message should show parameter name
- describe: Display total worker nodes across all machine pools
- describe: Fix text capitalization
- Add region flag to list cmd
- Rebuild docs on list cluster command
- addons: Use quota_cost to determine compatibility
- Remove vendor dir from linter
- addons: Filter list of addons to those compatible with ROSA
- addons: Verify compatibility of addons on cluster
- interactive: Ensure that required inputs are same type as non-required
- docs: Remove from repo and refer users to official docs
- docs: Update copyright year for man pages
> Release v0.1.10

- cmd/edit/addon/cmd.go
If an addon has no parameters, there is nothing to edit and so we should
exit early.
> addons: Disallow editing addons without parameters

- cmd/list/cluster/cmd.go
> clusters: Remove count flag

- CHANGES.adoc
- pkg/info/info.go
- addons: Error when editing non-editable parameters
- describe: Remove instance type
- logs: Display logs when cluster is in error state
- errors: Display legal terms URL
- logs: Filter out misleading output
- delete: Fix example command
- describe: Fix command help example
- aws: Add helpful error message when using STS credentials
- logs: Redact KUBECONFIG line
> Release v1.0.2

- CHANGES.adoc
- pkg/info/info.go
- aws: Log event when creating client with STS credentials
> Release v1.0.4

- CHANGES.adoc
- pkg/info/info.go
- init: Use correct region instead of default
> Release v1.0.5

- cmd/describe/cluster/cmd.go
> Updated the details link

- CHANGES.adoc
- pkg/info/info.go
- Allow setting 0 replicas to autoscaling machine pool (Not default)
- Updated the details link
- Added custom IAM Roles
- Remove default region
- describe: Display description during Pending state
> Release v1.0.7

- cmd/initialize/cmd.go
When a customer intends on using ROSA for clusters with STS
authentication, we do not need the 'osdCcsAdmin' user. We skip those
checks entirely, as well as the cluster simulation.
> Disable IAM user checks for STS

- pkg/aws/client_test.go
Fix tests with missing TagUser call
> Fix tests with missing TagUser call

- pkg/cluster/cluster.go
@vkareh PTAL and let me know your thoughts
> Added wait for accountclaims for the clusters in the same user ARN to get ready

- cmd/create/cluster/cmd.go
- pkg/aws/client.go
- pkg/aws/permissions.go
- pkg/aws/utils.go
This PR allows users with STS credentials to use the ROSA CLI client
> Support STS users

- cmd/create/cluster/cmd.go
- cmd/initialize/cmd.go
- cmd/list/region/cmd.go
To enable customers at large to create STS clusters, we expose all
STS-related flags, along with interactive help.
> sts: Expose all flags

- OWNERS
Add @pvasant to the reviewers list
> Add Priya to reviewers list

- cmd/create/cluster/cmd.go
When creating an STS cluster, operator IAM roles are mandatory to ensure
proper cluster installation. We now validate that there are operator IAM
roles included in the payload, otherwise we error out with a message
describing the process for extracting the credentials requests.
> sts: Ensure operator IAM roles

- cmd/describe/cluster/cmd.go
To allow for proper OIDC configuration and visibility, we display all
STS configuration parameters, specifically the various role ARNs used
during installation of an STS cluster.
Example output:
```
$ rosa describe cluster -c vkareh-rosa
Name:                       vkareh-rosa
ID:                         1l41jlf77s5kn00lcsdpk656m9jpgsqg
External ID:                
OpenShift Version:          
DNS:                        vkareh-rosa.9gk1.i1.devshift.org
AWS Account:                123456789012
API URL:                    
Console URL:                
Region:                     us-east-1
Multi-AZ:                   false
Nodes:
- Master:                  3
- Infra:                   2
- Compute:                 2
Network:
- Service CIDR: …
```
> describe: Display STS configuration

- CHANGES.adoc
- pkg/info/info.go
- Add Priya to reviewers list
- describe: Display STS configuration
- versions: Ensure versions with STS support
- create: Add missing flags to re-create script
- lint: Remove interfacer linter
- sts: Ensure operator IAM roles
- Added quota validation for listing instance types
- Add option to enable etcd encryption
> Release v1.0.9

- cmd/list/idp/cmd.go
- cmd/list/ingress/cmd.go
- cmd/list/instancetypes/cmd.go
- cmd/list/region/cmd.go
- cmd/list/version/cmd.go
- pkg/output/output.go
- pkg/reporter/reporter.go
Also send warning output to stderr to make it all consistent.
> output: Ensure that JSON output for empty arrays looks correct

- pkg/aws/quota.go
This PR changes AWS quota verification for ROSA CLI. It will now report all invalid quotas instead of just the first invalid quota it encounters. 
This PR will resolve https://github.com/openshift/rosa/issues/380
```
$ rosa verify quota                                                                     
I: Validating AWS quota...                                                                
E: Insufficient AWS quotas                                                                
E: Service quota is insufficient for the following service quota codes:                   
- Service ebs quota code L-D18FCD1D General Purpose SSD (gp2) volume storage not valid, expected quota of at least 300, but got 50
- Service ebs quota code L-FD252861 Provisioned IOPS SSD (io1) volume storage not valid, …
```
> Report all insufficient quotas

- cmd/create/oidcprovider/cmd.go
- cmd/create/operatorroles/cmd.go
- pkg/aws/client.go
When creating a STS cluster validate operator roles exists even if the cluster install status is `installing`
```
$ rosa create oidc-provider -c james-sts --mode auto -y
E: Unable to find all required IAM roles for operators:
james-openshift-image-registry-installer-cloud-credentials
james-openshift-ingress-operator-cloud-credentials
james-openshift-cluster-csi-drivers-ebs-cloud-credentials
james-openshift-machine-api-aws-cloud-credentials
james-openshift-cloud-credential-operator-cloud-credential-oper
See rosa create operator-roles --help
$ rosa create operator-roles -c james-sts --mode auto -y --prefix james
I: Creating roles using 'arn:aws:iam::884684697417:role/OrganizationAccountAccessRole'
I: Created role 'james-openshift-ingress-operator-cloud-credentials' with ARN …
```
> Validate operator roles exist

- cmd/verify/permissions/cmd.go
Also add a 'verify scp' alias.
> verify-permissions: Add user-friendly error

- cmd/create/cluster/cmd.go
STS clusters require the instance roles for proper installation and
support role for SRE access.
> create-cluster: Ensure all role ARNs are required

- cmd/create/machinepool/cmd.go
Change argument to string and support "on-demand" default value
> Fix validation of spot max price

- cmd/create/cluster/cmd.go
> updated error message for KMS key 

- cmd/create/accountroles/cmd.go
Closes : https://issues.redhat.com/browse/SDA-4690
> use default version on create account-roles

- cmd/create/cluster/cmd.go
Private STS clusters are not supported unless also used with AWS
PrivateLink. This change disables setting an STS cluster as private
without enabling AWS PrivateLink.
> create-cluster: Force AWS PrivateLink for private STS clusters

- pkg/aws/helpers.go
Related to : https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/3314
> update user tag regex to include unicode spaces

- cmd/create/cluster/cmd.go
This hidden flag allows for the internal use of cluster properties.
Usage:
```
$ rosa create cluster --properties key:val --properties boolean --properties support:'{"json":"yes"}'
{
...
"properties": {
"key": "val",
"boolean": "true"
"support": "{\"json\":\"yes\"}"
}
}
```
> cluster: Support custom properties

- pkg/ocm/clusters.go
@vkareh  I m not sure if this was overwritten or was not pushed. PTAL
> add kmskey for sts

- cmd/create/cluster/cmd.go
- pkg/ocm/clusters.go
> changing cluster proxy attributes to pointers

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/SDA-5038
> Added support for master-iam-role

- assets/bindata.go
- cmd/create/cmd.go
- cmd/create/ocmrole/cmd.go
- cmd/link/cmd.go
- cmd/link/ocmrole/cmd.go
- pkg/aws/helpers.go
- pkg/aws/policies.go
- pkg/aws/tags/tags.go
- pkg/ocm/helpers.go
- templates/policies/sts_ocm_permission_policy.json
- templates/policies/sts_ocm_trust_policy.json
Related: [SDA-4988](https://issues.redhat.com/browse/SDA-4988)
This MR has a lot in common with https://github.com/openshift/rosa/pull/525
If merged after https://github.com/openshift/rosa/pull/525, I will fix the conflicts
> STS: Create OCM Role

- cmd/create/operatorroles/cmd.go
> added support for operator prefix

- cmd/create/ocmrole/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/create/userrole/cmd.go
- cmd/link/ocmrole/cmd.go
- pkg/aws/client.go
- pkg/aws/helpers.go
- pkg/ocm/helpers.go
Related: [SDA-5073](https://issues.redhat.com/browse/SDA-5073)
> Add org external id to ocm role name

- cmd/create/cluster/cmd.go
- cmd/edit/cluster/cmd.go
- pkg/interactive/validation.go
- pkg/ocm/clusters.go
https://issues.redhat.com/browse/SDA-4733
> ROSA: Support editing cluster-wide proxy

- pkg/ocm/helpers.go
To avoid overridding linked role ARNs, we fetch the label specifically
using its known name, and then verify whether the ARN is in place.
Otherwise we append it to the existing list.
> link: Allow linking multiple role ARNs

- cmd/dlt/accountroles/cmd.go
- cmd/dlt/oidcprovider/cmd.go
- cmd/dlt/operatorrole/cmd.go
- cmd/edit/cluster/cmd.go
[SDA-4976](https://issues.redhat.com/browse/SDA-4976) 
[SDA-5088](https://issues.redhat.com/browse/SDA-5088)
> improve UX in ROSA edit cluster and ROSA delete roles

- .gitignore
Adding .envrc (DirEnv) and .env (Docker) to .gitignore
> Ignore local environment files

- assets/bindata.go
- templates/policies/sts_ocm_permission_policy.json
https://issues.redhat.com/browse/SDA-5118
> add permission for describe region and route tables

- assets/bindata.go
- cmd/create/ocmrole/cmd.go
- pkg/aws/client.go
- pkg/aws/helpers.go
- pkg/aws/policies.go
- pkg/aws/tags/tags.go
- templates/policies/sts_ocm_admin_permission_policy.json
Related: [SDA-4992](https://issues.redhat.com/browse/SDA-4992)
> Add --admin option to create ocm-role command

- cmd/login/cmd.go
- pkg/ocm/helpers.go
https://issues.redhat.com/browse/SDA-4734
@tzvatot @zgalor @adlerOri
> Send rosa cli login event to pendo

- cmd/upgrade/accountroles/cmd.go
- cmd/upgrade/cluster/cmd.go
- cmd/upgrade/operatorroles/cmd.go
- pkg/aws/client.go
- pkg/aws/policies.go
https://issues.redhat.com/browse/SDA-5319
> clean up upgrade command

- cmd/create/admin/cmd.go
Let the user select a password so that it can be used in CI/CD without having to parse the output string for the generated password.
> Adding password argument to create admin

- cmd/create/operatorroles/cmd.go
1) Remove openshift version from operator role
2) Fix the issue with manual operator role (change name to arn) - https://issues.redhat.com/browse/SDA-5079
> remove openshift version from operator role name

- cmd/list/cmd.go
- cmd/list/gates/cmd.go
- go.mod
- go.sum
- pkg/ocm/gates.go
- pkg/output/output.go
- vendor/github.com/nathan-fiscaletti/consolesize-go/LICENSE
- vendor/github.com/nathan-fiscaletti/consolesize-go/README.md
- vendor/github.com/nathan-fiscaletti/consolesize-go/consolesize_unix.go
- vendor/github.com/nathan-fiscaletti/consolesize-go/consolesize_windows.go
- vendor/modules.txt
Add support for to list OCP gates
> ocp: Add list acknowledgement gate support

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/SDA-5327
> ROSA CLI Interactive install - make the choice default STS

- pkg/ocm/helpers.go
> The attribute name in error message should be same with the correct proxy attribute in body

- assets/bindata.go
- templates/policies/sts_support_permission_policy.json
Add IAM List and Get role permissions to the Managed OpenShift support policy
https://issues.redhat.com/browse/OSD-9661
Added to MCC https://github.com/openshift/managed-cluster-config/pull/1035
> Add IAM List and Get role permissions to support policy

- CHANGES.adoc
- pkg/info/info.go
- ROSA CLI Interactive install - make the choice default STS
- Add IAM List and Get role permissions to support policy
- The attribute name in error message should be same with the correct proxy attribute in body
- Fix bug - remove duplicated error message when deleting a cluster
> Release v1.1.9

- cmd/create/ocmrole/cmd.go
In case there is already an admin role name, and the user tries
to create (manually) a non-admin role with the same name,
We will prompt a warning message to the terminal.
Related: [SDA-5140](https://issues.redhat.com/browse/SDA-5140)
> Fix bug - add warning when creating ocm-role with duplicate name

- cmd/unlink/ocmrole/cmd.go
Related: [SDA-5449](https://issues.redhat.com/browse/SDA-5449)
> Fix bug - improve the help message of 'rosa unlink ocm-role'

- cmd/unlink/userrole/cmd.go
Related: [SDA-5464](https://issues.redhat.com/browse/SDA-5464)
> Fix bug - capitalize `rosa unlink user-role message`

- cmd/upgrade/cluster/cmd.go
- pkg/aws/client.go
[sda-5377](https://issues.redhat.com/browse/sda-5377)
[sda-5376](https://issues.redhat.com/browse/sda-5376)
> fix cosmetic issues rosa upgrade

- cmd/dlt/userrole/cmd.go
Related: [SDA-5548](https://issues.redhat.com/browse/SDA-5548)
> Fix bug - change the interactive message of `rosa delete user-role`

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/cmd.go
- pkg/ocm/machines.go
This got a bit larger than expected, broken down into small commits for easier review. The main changes:
- Introduce a new MachineTypeList type
- Break down the logic into smaller functions
> Refactor MachineTypes handling

- cmd/upgrade/accountroles/cmd.go
- pkg/aws/policies.go
[sda-5576](https://issues.redhat.com/browse/sda-5576)
> sda-5576-Fix upgrades to 4.9 or less with 4.10 operator roles

- cmd/create/admin/cmd.go
- cmd/create/idp/htpasswd.go
- cmd/dlt/admin/cmd.go
- pkg/ocm/idps.go
> Revert "HTPasswd bug fixes corresponding with some CS changes"

- CHANGES.adoc
- pkg/info/info.go
- fix operator roles issue for old rosa versions
- fix operator role issue
> Release v1.1.11

- cmd/create/admin/cmd.go
- cmd/create/idp/cmd.go
- cmd/create/idp/htpasswd.go
- cmd/dlt/admin/cmd.go
- pkg/ocm/idps.go
Last week we had to revert the ROSA HTPasswd work for an urgent ROSA version release. 
I am now reintroducing the same changes.
PTAL @pvasant
> Re-introducing HTPasswd IDP after revert

- cmd/rosa/main.go
[SDA-5618](https://issues.redhat.com/browse/SDA-5618)
@pvasant @tzvatot
> added link to help menu

- cmd/dlt/ocmrole/cmd.go
In case the user deleted the role in their account via the AWS,
and they try to delete it with rosa-cli.
Prompt a warning to the user that the role doesn't exist on their account.
Deleting non-existing linked ocm-role:
Deleting non-existing unlinked ocm-role:
Related: [SDA-5689](https://issues.redhat.com/browse/SDA-5689)
> Fix error message - rosa delete ocm-role

- cmd/create/idp/htpasswd.go
This is done in order to display meaningful error messages to ROSA CLI users early during the process of IDP creation. Doing the these validations on the CLI side while they users are constructing the IDP payload (to be sent and validated in the same manner in CS) provides better UX, for example:
```
I: Interactive mode enabled.
Any optional fields can be left empty and a default will be selected.
? Type of identity provider: htpasswd
? Identity provider name: htpasswd-1
I: At least one user is required to create the IDP.
X Sorry, your reply was invalid: invalid username 'user%%': username must not contain /, :, or %
```
PTAL @pvasant
> HTPasswd: Add username & password validations in CLI

- cmd/describe/admin/cmd.go
Before HTPasswd was introduced as an IDP in ROSA, it was enough to look for an HTPasswd IDP in the ROSA cluster to infer that there's a cluster admin, because the HTPasswd IDP used to serve as an admin container only. This is no longer the case. 
I'm surprised I missed this in the original HTPasswd MR, good thing that QE caught this.
PTAL @pvasant
> Fix `rosa describe admin` to look at HTPasswd IDP users to determine existence of admin

- cmd/create/idp/htpasswd.go
- cmd/dlt/admin/cmd.go
- cmd/list/idp/cmd.go
- pkg/ocm/idps.go
Now looks like so:
```
$ rosa list idp --cluster=1rgs3165jrlt0iec7qabne5i3abq6rbr
NAME          TYPE        AUTH URL
github-1      GitHub      https://oauth-openshift.apps.noa-apr11.vv6d.i1.devshift.org/oauth2callback/github-1
htpasswd-1    HTPasswd  
```
> Remove AUTH URL from HTPasswd entries of `rosa list idps`

- cmd/dlt/accountroles/cmd.go
Modify `rosa delete account-roles` to permit running the command without the `prefix` flag.
If the flag isn't provided, change to interactive mode, and get the prefix from the user.
Related: [SDA-5795](https://issues.redhat.com/browse/SDA-5797)
> Fix bug - delete account roles - make the `prefix` flag optional

- cmd/edit/addon/cmd.go
JIRA - [SDA-5935](https://issues.redhat.com//browse/SDA-5935)
> allow addons be edited, regardless of addon state

- cmd/create/service/cmd.go
> output validation error message when creating service with invalid parameter

- CHANGES.adoc
- pkg/info/info.go
- update dev script
- adding single-az byo-vpc support for create service
- output validation error message when creating service with invalid parameter
- allow addons be edited, regardless of addon state
- supporting flag values that contain equal signs
- SDA-5889-Fix User Role Error
- adding new alias for managed service commands
- unhide ui roles
> Release v1.2.2

- cmd/install/addon/cmd.go
This MR adds printing of additional output for non-interactive commands.
Related: [SDA-5569](https://issues.redhat.com/browse/SDA-5569)
> Addon install - add non-interactive commands

- cmd/describe/addon/cmd.go
> Add credential requests to describe addon command

- cmd/create/cluster/cmd.go
- cmd/describe/cluster/cmd.go
- cmd/edit/cluster/cmd.go
- pkg/aws/helpers.go
- pkg/ocm/clusters.go
[SDA-5612](https://issues.redhat.com//browse/SDA-5612)
@pvasant @vkareh  PTAL
> Allow for additional, customer-provided "no_proxy" values for cluster-wide proxy

- cmd/create/accountroles/cmd.go
- cmd/create/cluster/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/create/service/cmd.go
- cmd/dlt/operatorrole/cmd.go
- cmd/upgrade/accountroles/cmd.go
- cmd/upgrade/operatorroles/cmd.go
- pkg/aws/client.go
- pkg/aws/helpers.go
- pkg/aws/policies.go
- pkg/aws/sts.go
- pkg/ocm/helpers.go
https://issues.redhat.com/browse/SDA-5776 
This ensures operator dependency is removed from cli
> Make CredRequest API

- cmd/edit/cluster/cmd.go
[SDA-6062](https://issues.redhat.com//browse/SDA-6062)
@zgalor @oriAdler @pvasant
> Fix a bug when editing no-proxy field

- cmd/create/cluster/cmd.go
- cmd/edit/cluster/cmd.go
- pkg/aws/helpers.go
https://issues.redhat.com/browse/SDA-6102
> Reject '*' when validating no-proxy field

- pkg/aws/helpers.go
[SDA-6110](https://issues.redhat.com//browse/SDA-6110)
> The wildcard domain is not allowed to set in no_proxy field

- cmd/describe/cmd.go
- cmd/describe/installation/cmd.go
== Describe Add-on Installation sample output start ==
Id:                          bar
Href:                        /api/clusters_mgmt/v1/clusters/foo/addons/bar
Addon state:                 ready
Parameters:
"id_1"                      : "value_1"
"id_2"                      : "value_2"
== Describe Add-on Installation sample output end ==
> command to list parameters of add-on installation

- cmd/create/cluster/cmd.go
- cmd/create/service/cmd.go
- pkg/aws/helpers.go
- pkg/ocm/addons.go
Refs: [SDA-5368](https://issues.redhat.com//browse/SDA-5368)
> STS for addons - helper methods

- cmd/upgrade/accountroles/cmd.go
https://issues.redhat.com/browse/SDA-5739
> add more throttle metrics

- cmd/create/cluster/cmd.go
- pkg/aws/client.go
Currently, CS is choosing the availability zone arbitrarily for the user,
this PR adds the option to select the availability zone.
1. Add `availability-zones` flag.
2. Add a step for the interactive mode to choose an availability zone.
Related: [SDA-6222](https://issues.redhat.com/browse/SDA-6222)
Example 1:
Example 2:
> Allow to select availability zones when creating a non-BYOVPC cluster

- cmd/create/machinepool/cmd.go
When using the `runtime` object, we create an AWS client with the region
that the user configured locally.
The AWS client fetches only the subnets from that region.
If the cluster is installed in a different region, we'll get
an empty list of subnets.
This PR creates the AWS client with the cluster's region.
Related: [SDA-6355](https://issues.redhat.com/browse/SDA-6355)
> Fix bug - fetch the subnets from the cluster region

- cmd/list/machinepool/cmd.go
Related: [SDA-6356](https://issues.redhat.com/browse/SDA-6356)
> List machine pools - add a subnets column

- cmd/create/cluster/cmd.go
Related: [SDA-6361](https://issues.redhat.com/browse/SDA-6361)
> Fix bug - create cluster - validate subnets number for private link

- cmd/create/cluster/cmd.go
[SDA-6111](https://issues.redhat.com//browse/SDA-6111)
@zgalor PTAL
> setting useVPCExist to true when subnet ids are provided

- pkg/ocm/idps.go
[SDA-6106](https://issues.redhat.com//browse/SDA-6106)
> removing htpasswd idp even if there are no users in this idp

- cmd/describe/cluster/cmd.go
- pkg/ocm/clusters.go
https://issues.redhat.com/browse/SDA-5813
> SDA-5813 Remove DisplayName from cluster

- cmd/create/cluster/cmd.go
Use `interactive.GetOption` for a single AZ cluster.
Related: [SDA-6445](https://issues.redhat.com/browse/SDA-6445)
Bug:
Fix:
> Create cluster - for single AZ, only allow to select one AZ

- cmd/create/accountroles/cmd.go
- cmd/create/operatorroles/cmd.go
This MR moves the logic of operator policy creation to the cluster creation.
This is the pre-req for onboarding hypershift into ROSA: hypershift has different
set of policies. Therefore, the policy creation requires the cluster type, and we will have the
hosted-cp flag when creating a cluster.
> Refactored ROSA to create operator policies when running cluster creation

- cmd/create/accountroles/cmd.go
- cmd/create/cluster/cmd.go
- cmd/create/ocmrole/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/create/service/cmd.go
- cmd/create/userrole/cmd.go
- cmd/dlt/ocmrole/cmd.go
- cmd/dlt/userrole/cmd.go
- cmd/install/addon/cmd.go
- cmd/upgrade/accountroles/cmd.go
- cmd/upgrade/operatorroles/cmd.go
- pkg/aws/client.go
- pkg/aws/helpers.go
- pkg/aws/policies.go
- pkg/aws/sts.go
- pkg/ocm/clusters.go
This is for account roles (operator, installer and such)
ocm role and user role will be handled in a separate PR
[SDA-6246](https://issues.redhat.com//browse/SDA-6246)
https://issues.redhat.com/browse/SDA-6246
> support for path in iam roles and policies

- cmd/create/idp/google.go
- go.mod
- go.sum
- vendor/github.com/dchest/validator/.travis.yml
- vendor/github.com/dchest/validator/LICENSE
- vendor/github.com/dchest/validator/README.md
- vendor/github.com/dchest/validator/domain.go
- vendor/github.com/dchest/validator/email.go
- vendor/modules.txt
[SDA-6472](https://issues.redhat.com//browse/SDA-6472)
@zgalor @oriAdler @pvasant PTAL
> fix - Google IDP doesn't work when created with ROSA CLI

- go.mod
- pkg/helper/helpers.go
- pkg/ocm/clusters.go
- vendor/modules.txt
Related: [SDA-6551](https://issues.redhat.com/browse/SDA-6551)
> Refactor `GetCluster` function

- cmd/create/accountroles/cmd.go
- cmd/create/ocmrole/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/create/service/cmd.go
- cmd/create/userrole/cmd.go
- cmd/install/addon/cmd.go
- cmd/upgrade/operatorroles/cmd.go
- pkg/aws/helpers.go
- pkg/aws/policies.go
[SDA-6560](https://issues.redhat.com//browse/SDA-6560)
[SDA-6576](https://issues.redhat.com/browse/SDA-6576)
https://issues.redhat.com/browse/SDA-6560
https://issues.redhat.com/browse/SDA-6576
> add arn path to ocm and user role

- cmd/create/accountroles/cmd.go
- cmd/create/ocmrole/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/create/userrole/cmd.go
- cmd/upgrade/accountroles/cmd.go
- pkg/aws/sts.go
- pkg/aws/tags/tags.go
[SDA-6439](https://issues.redhat.com/browse/SDA-6439)
> [SDA-6439] Add red-hat-managed tag to roles and policies

- cmd/dlt/admin/cmd.go
[SDA-6501](https://issues.redhat.com//browse/SDA-6501)
@zgalor @pvasant @oriAdler @tbrisker @samira-barouti
> Adding an info message after `rosa delete admin`

- cmd/edit/cluster/cmd.go
…ractive mode
[SDA-6587](https://issues.redhat.com//browse/SDA-6587)
@zgalor @oriAdler @pvasant  @tbrisker @samira-barouti
> properly handle "" no_proxy option in interactive mode

- cmd/create/cluster/cmd.go
[SDA-6648](https://issues.redhat.com//browse/SDA-6648)
https://issues.redhat.com/browse/SDA-6648
> missing '--operator-roles-path' in 'To create this cluster again...'

- pkg/aws/policies.go
EnsureRole will succeed if role name exists with different path
EnsurePolicy actually fails but returns success and wrong ARN
this change causes both functions to succeed only if the existing resource has same path as the requested resource
[SDA-6596](https://issues.redhat.com//browse/SDA-6596)
https://issues.redhat.com/browse/SDA-6596
> compare arn path for existing policy/role

- pkg/aws/policies.go
When adding a new policy version, there is a risk of hitting an AWS
limit. We therefore remove all but the default policy version and add
the new one to ensure success.
Fixes https://issues.redhat.com/browse/SDA-6659
> policies: Ensure policy version succeeds

- cmd/dlt/accountroles/cmd.go
- cmd/dlt/operatorrole/cmd.go
- pkg/aws/policies.go
[SDA-6610](https://issues.redhat.com/browse/SDA-6610)
> [SDA-6610] account-role and operator-role policies are now deleted when roles are

- cmd/create/accountroles/cmd.go
- cmd/create/cluster/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/upgrade/accountroles/cmd.go
- cmd/upgrade/cluster/cmd.go
- cmd/upgrade/operatorroles/cmd.go
[SDE-2115](https://issues.redhat.com//browse/SDE-2115)
https://issues.redhat.com/browse/SDE-2115
> move operator policies from account to operator commands

- pkg/aws/policies.go
1. Check if the policy is attached to an entity.
2. Delete all policy versions.
Related: [SDA-6747](https://issues.redhat.com/browse/SDA-6747)
Delete a policy with multiple versions:
Skip policy deletion if it has attached entities:
> Ensure prerequisites for deleting operator and account role policies

- cmd/upgrade/operatorroles/cmd.go
[SDA-6733](https://issues.redhat.com/browse/SDA-6733)
> [SDA-6733] Added redhatmanaged=true tag to roles when `rosa upgrade operator-roles` is ran

- cmd/upgrade/operatorroles/cmd.go
[sda-6745](https://issues.redhat.com//browse/sda-6745)
> set mode only once in operator roles upgrade

- pkg/aws/policies.go
Related: [SDA-6606](https://issues.redhat.com/browse/SDA-6606)
> Improve `EnsurePolicy` error message

- cmd/create/service/cmd.go
https://issues.redhat.com/browse/SDA-6835
> Removing unnecessary hypershift check for managed services.

- cmd/describe/cluster/cmd.go
* Relates [SDA-6797](https://issues.redhat.com//browse/SDA-6797)
> [Hypershift] Modify `describe cluster` to differentiate between classic vs hosted-cp

- cmd/create/cluster/cmd.go
- pkg/ocm/client.go
* All private hosted clusters are privatelink clusters
* All hosted clusters are STS cluster
Fixes [SDA-6873](https://issues.redhat.com//browse/SDA-6873)
> [Hypershift] Arg validation for `create cluster`

- cmd/create/accountroles/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/create/userrole/cmd.go
[SDA-6886](https://issues.redhat.com/browse/SDA-6886)
Fixes bug 6886 by adding RedHatManaged=true to manual creation of user/account/operator roles.
> [SDA-6886] Added RedHatManaged=true to manual operator/account/user roles creation

- cmd/create/operatorroles/cmd.go
[SDA-6886](https://issues.redhat.com/browse/SDA-6886)
> [SDA-6886] Added redhatmanaged=true tag to operator roles in manual mode

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/SDA-6687
> unhide tags during cluster create

- cmd/dlt/operatorrole/cmd.go
Instead of having staging hardcoded
> Output current environment when it is not production

- cmd/create/cluster/cmd.go
> Revert "[SDA-6643] STS is now default mode for cluster creation, added flags for mint mode/non-sts mode"

- cmd/create/machinepool/cmd.go
- pkg/aws/client.go
Related: [SDA-7180](https://issues.redhat.com/browse/SDA-7180)
> Create a machine pool - prevent choosing a spot instance for a local AZ

- cmd/create/machinepool/cmd.go
Initiate an AWS client with the cluster's region to fetch the region's subnets.
Related: [SDA-7285](https://issues.redhat.com//browse/SDA-7285)
> Create a machine pool with a different region configured in the AWS CLI

- cmd/create/cluster/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-7201
This PR changes behavior for mint-mode/non-sts flags so that it does not prompt choice of sts mode if those have been supplied. It also always show the warning message for future release use of STS mode.
User was being asked for STS mode and the default was Yes. This behavior should only happen if no flags for sts mode were supplied.
`./rosa create cluster -c yuwan-ksr1 --mint-mode --sts -i`
```
I: Interactive mode enabled.
Any optional fields can be left empty and a default will be selected.
? Cluster name: yuwan-ksr1
E: Can't use both STS and mint mode at the same time.
```
`./rosa create cluster -c yuwan-ksr1 --sts -i`
```
I: Interactive mode enabled.
Any optional fields can be left empty and a default will be selected.
? Cluster …
```
> [SDA-7201] Always show warning, don't go into interactive if non sts mode is enabled

- cmd/describe/cluster/cmd.go
> SDA-7290 Remove redundant quotation

- CHANGES.adoc
- pkg/info/info.go
- Check HostedCP version support also in interactive mode + align versions
- fix: going through all policies to check upgrade
> Release v1.2.10

- cmd/login/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-4515
> [SDA-4515] Phrasing

- cmd/list/region/cmd.go
Fixes: [SDA-7486](https://issues.redhat.com//browse/SDA-7486)
> Log a warning if the user's organization doesn't have the needed capability

- cmd/upgrade/operatorroles/cmd.go
- cmd/upgrade/roles/cmd.go
- pkg/helper/roles/helpers.go
Related issue: https://issues.redhat.com/browse/OHSS-14855
Removes option of having different paths on operator in regards to policies
There was a design change on path task and this was a leftover from old design
`./rosa upgrade roles -c st-path-1816 --mode auto --cluster-version=4.10.43 `
```
I: Ensuring account role/policies compatibility for upgrade
? Upgrade the 'demo-1816-st-Worker-Role' role policy latest version (4.11) ? Yes
I: Upgraded policy with ARN 'arn:aws:iam::xxx:policy/gdbsts/demo-1816-st-Worker-Role-Policy' to version '4.11'
? Upgrade the 'demo-1816-st-Support-Role' role policy latest version (4.11) ? Yes
I: Upgraded policy with ARN 'arn:aws:iam::xxx:policy/gdbsts/demo-1816-st-Support-Role-Policy' to version '4.11'
? Upgrade the …
```
> [OHSS-14855] Using unified path on upgrade roles/operator-roles

- cmd/describe/cluster/cmd.go
Related: [SDA-7510](https://issues.redhat.com/browse/SDA-7510)
> Describe cluster - print `infra_id` to the output

- cmd/describe/cluster/cmd.go
- cmd/list/machinepool/nodepool.go
Discussed not using "NodePools" wording for "MachinePool for hosted clusters".
> [SDA-7580] Adjust NodePool headers

- cmd/edit/machinepool/machinepool.go
- pkg/ocm/clusters.go
Related: [SDA-7375](https://issues.redhat.com//browse/SDA-7375)
Also fixed some issues with interactive mode, in the additional machine pool. Before the fix, if the user sets only labels or taints, they we still be asked to set replicas, after the fix the user can set labels, taints (not for default machine pool), or replicas/autoscaling params.
```
$ ./rosa edit machinepool -c zg-dec18  Default
? Enable autoscaling (optional): No
? Labels: a=b
I: Updated machine pool 'Default' on cluster 'zg-dec18'
```
If the user set at least one of those they will not be prompted for anything more
```
$ ./rosa edit machinepool -c zg-dec18  --labels "a=f,b=w" Default
I: Updated machine pool 'Default' on cluster 'zg-dec18'
```
Taints are forbidden for default mp:
```
$ ./rosa edit machinepool -c zg-dec18 …
```
> Allow editing default machine pool labels

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/machinepool.go
- pkg/ocm/clusters.go
Related: [SDA-7377](https://issues.redhat.com//browse/SDA-7377)
> Enable day1 default machine pool labels

- cmd/describe/upgrade/cmd.go
[SDA-7635](https://issues.redhat.com//browse/SDA-7635)
PTAL @oriAdler @etabak 
```
~/workPlace/rosa (describe-ux-improvement)! P $ ./rosa describe upgrade -c 20rhdoc16rm95g0sd4jjvodl2lr1au3a
W: No scheduled upgrades for cluster id '20rhdoc16rm95g0sd4jjvodl2lr1au3a'
```
```
~/workPlace/rosa (describe-ux-improvement)! P $ ./rosa describe upgrade -c 20rhdoc16rm95g0sd4jjvodl2lr1au3a
ID:                         2c8cdbb6-84ff-11ed-a26d-0a580a83013f
Cluster ID:                 20rhdoc16rm95g0sd4jjvodl2lr1au3a
Next Run:                   2022-12-26 09:34:00 +0000 UTC
Upgrade State:              scheduled
Version:                    4.11.17
```
> fix ux issues related to rosa describe

- cmd/edit/machinepool/machinepool.go
Reltaed: [SDA-7651](https://issues.redhat.com//browse/SDA-7651)
Also, don't prompt for scaling params if minimal update cluster params were set
> Fix scaling bug and improve interactive mode

- cmd/create/accountroles/cmd.go
- cmd/create/ocmrole/cmd.go
- cmd/create/operatorroles/cmd.go
- cmd/create/userrole/cmd.go
- cmd/install/addon/cmd.go
- cmd/upgrade/accountroles/cmd.go
- cmd/upgrade/operatorroles/cmd.go
- cmd/upgrade/roles/cmd.go
- pkg/aws/helpers.go
- pkg/aws/permissions.go
- pkg/helper/roles/helpers.go
Related: https://issues.redhat.com/browse/SDA-7656
Create managed account roles:
Create unmanaged account roles:
> Fix bug create account roles with existing policies

- cmd/initialize/cmd.go
- pkg/aws/helpers.go
- pkg/helper/helpers.go
- pkg/ocm/helpers.go
Extracts sorting string with respects to length to it's own function
Cleaning up duplication
> Refactor sort strings helper

- cmd/create/machinepool/nodepool.go
This ROSA PR needs the OCM MR
https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/4979
When merged, ROSA CLI will support machine type selection for "hosted machinepools".
This is an example of the expected behaviour (on a local cluster using integration environment):
```
$ rosa create machinepool -c lponce-local-01 --interactive
? Enable autoscaling (optional): No
? Replicas: 2
? Instance type: m5d.2xlarge
I: Machine pool '210qd12ofei3bmn4u6pvih6vjn5eomps' created successfully on hosted cluster 'lponce-local-01'
I: To view all machine pools, run 'rosa list machinepools -c lponce-local-01'
rosa(support-machinetype) L  $ rosa list machinepool -c lponce-local-01
ID                                AUTOSCALING  REPLICAS  INSTANCE TYPE  AVAILABILITY ZONE  SUBNET …
```
> SDA-7521 Support instanceType selection on NodePools

- cmd/create/cluster/cmd.go
> Revert "[SDA-7662] Display Tags question in interactive mode"

- cmd/dlt/operatorrole/cmd.go
Adds support for hypershift credential requests coming from subscription
Hypershift roles were not being deleted and there was a chance to identify the wrong cluster when deleting operator roles
> Delete correct operator roles and support hypershift

- cmd/create/idp/cmd.go
As it may be not the case in HyperShift context during cluster creation
> Ensure console URL is available before offering it to the user

- cmd/create/cluster/cmd.go
- pkg/ocm/regions.go
- pkg/properties/properties.go
This is consistent with the behaviour on backend side, which will also check the authorization of using it
> Skip region check if we use shard pinning

- cmd/dlt/accountroles/cmd.go
- cmd/dlt/operatorrole/cmd.go
- pkg/aws/client.go
- pkg/aws/policies.go
Skip the policy deletion for managed policies.
Related: [SDA-7728](https://issues.redhat.com/browse/SDA-7728)
> Delete roles with managed policies

- cmd/dlt/ocmrole/cmd.go
- pkg/aws/client.go
- pkg/aws/sts.go
Skip the deletion of the attached managed policies.
Related: [SDA-7878](https://issues.redhat.com/browse/SDA-7878)
> Delete OCM role with managed policies

- .golangci.yml
- go.mod
> Upgrade to Go 1.19

- cmd/edit/machinepool/machinepool.go
Check if the min/max replicas value was updated, to differentiate the zero default value of the flags from the user input.
**Note:** Zero value for min/max replicas is a valid value.
Related: [SDA-7905](https://issues.redhat.com/browse/SDA-7905)
> Edit machinepool min replicas

- cmd/create/cluster/cmd.go
- pkg/helper/roles/helpers.go
Error out in case of missing managed policies for the account roles.
Related: [SDA-7904](https://issues.redhat.com/browse/SDA-7904)
Control plane role is missing the attached policy:
> Create cluster - validate account roles have managed policies attached

- cmd/create/oidcconfig/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-8006
> [SDA-8006] Add user prefix to oidc configuration

- cmd/dlt/oidcconfig/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-8075
> [SDA-8075] Add question for private key secret arn

- cmd/create/oidcconfig/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-8092
Validate bucket names before moving forward into creation
Some names are invalid for aws s3 bucket names
> [SDA-8092] Adding validation to bucket name

- pkg/aws/client.go
Related issue: https://issues.redhat.com/browse/SDA-8091
Improving some error messages when deleting oidc-config
Clearer steps for the client
> [SDA-8091] Improve error messages for deleting oidc-config

- cmd/edit/ingress/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-8115
Title self explanatory
Parity with other commands
`./rosa edit ingress v2e2 -c non-sts -i`
```
? Label match for ingress (optional): 
? Private ingress (optional): No
I: Updated ingress 'v2e2' on cluster 'non-sts'
```
`./rosa list ingresses -c non-sts `
```
ID    APPLICATION ROUTER                              PRIVATE    DEFAULT    ROUTE SELECTORS
m2j2  https://apps.non-sts.mnb9.s1.devshift.org       no         yes        
v2e2  https://apps2.non-sts.mnb9.s1.devshift.org      no         no         
```
> [SDA-8115] Allow empty label match editing ingress interactive

- cmd/describe/cluster/cmd.go
Related: [SDA-8320](https://issues.redhat.com/browse/SDA-8320)
> Describe cluster - add managed policies field to the output

- cmd/create/oidcconfig/cmd.go
- cmd/create/oidcprovider/cmd.go
- pkg/aws/client.go
- pkg/aws/commandbuilder/commandbuilder.go
- pkg/aws/idps.go
Related issue: https://issues.redhat.com/browse/SDA-8163
Adds red-hat-managed tag to OIDC config and provider resources
Ensures what RH has as managed to be able to work around it
> [SDA-8163] Add red-hat-managed tag to oidc config and provider resources

- cmd/edit/machinepool/nodepool.go
Minor PR to align classic / hosted machinepool UX.
> SDA-8040 Align machinepool condition for enter in interactive mode

- cmd/create/ocmrole/cmd.go
Related: [SDA-7958](https://issues.redhat.com/browse/SDA-7958)
> Create OCM admin roles in manual mode - add all tags to policy

- cmd/create/cluster/cmd.go
- pkg/aws/client.go
- pkg/ocm/helpers.go
Context, hosted cluster will deprecate the existing "multi-az" parameters and it will allow to create hosted clusters with:
- Public hosted clusters: at least one public subnet per VPC and at least one private subnet per VPC.
- Private hosted clusters: at least one private subnet per VPC.
When more than one private subnet is provided, the replicas will be distributed across machinepools, i.e. 4 replicas on 2 private subnets will mean creation of 2 machine pools with 2 replicas.
Also, classic format should be accepted not to break backward compatibility:
```
rosa create cluster --cluster-name lponce-local-06 --hosted-cp --machine-cidr 10.0.0.0/16 --subnet-ids subnet-0cbc29215162f7548,subnet-0d65e2465258986db,subnet-0310ceb7c0094e92a --mode auto --channel-group candidate --version 4.12.6 …
```
> SDA-8224 Deprecate MultiAZ validations for hosted clusters

- cmd/create/cluster/cmd.go
- cmd/create/cluster/cmd_test.go
- cmd/create/machinepool/nodepool.go
- cmd/edit/machinepool/nodepool.go
- cmd/list/accountroles/cmd.go
- pkg/helper/versions/helpers.go
- pkg/ocm/versions.go
- pkg/ocm/versions_test.go
[SDA-8369](https://issues.redhat.com//browse/SDA-8369)
"Display only the versions that are hypershift supported in ocm and rosa cli"
> [SDA-8369] Update versions to include hypershift_enabled and add validation

- cmd/create/machinepool/cmd.go
- cmd/create/machinepool/machinepool.go
- cmd/create/machinepool/nodepool.go
- cmd/edit/machinepool/cmd.go
- cmd/edit/machinepool/machinepool.go
- cmd/edit/machinepool/nodepool.go
- cmd/list/machinepool/helper.go
- cmd/list/machinepool/machinepool.go
- cmd/list/machinepool/nodepool.go
ROSA implementation for https://issues.redhat.com/browse/SDA-8220
UX is similar to other flags.
cc @gbranco @oriAdler
> SDA-8220 Support autorepair parameter for hosted clusters

- cmd/create/cluster/cmd.go
- cmd/create/oidcconfig/cmd.go
- cmd/create/oidcprovider/cmd.go
- cmd/create/operatorroles/by_prefix.go
- cmd/dlt/oidcconfig/cmd.go
- pkg/aws/policies.go
- pkg/interactive/helper.go
Related issues: 
* https://issues.redhat.com/browse/SDA-8657
* https://issues.redhat.com/browse/SDA-8653
* https://issues.redhat.com/browse/SDA-8667
* https://issues.redhat.com/browse/SDA-8669
* https://issues.redhat.com/browse/SDA-8671
* https://issues.redhat.com/browse/SDA-8672
Adds UX improvements and bug fixes to some oidc config flows
Better CX
> [SDA-8657] Better UX when using oidc config id and related commands

- cmd/dlt/accountroles/cmd.go
1. For `--hosted-cp` delete only hypershift account roles.
2. For `--classic` delete only classic account roles.
Related: [SDA-8666](https://issues.redhat.com/browse/SDA-8666)
Default flow deletes all account roles:
If role type is specified, delete only the adequate set:
> Delete account-roles - delete both types for the default flow

- cmd/create/cluster/cmd.go
- cmd/create/oidcconfig/cmd.go
- cmd/dlt/oidcconfig/cmd.go
- pkg/aws/client.go
Related issues:
* https://issues.redhat.com/browse/SDA-8696
* https://issues.redhat.com/browse/SDA-8698
* https://issues.redhat.com/browse/SDA-8699
* https://issues.redhat.com/browse/SDA-8701
* https://issues.redhat.com/browse/SDA-8702
* https://issues.redhat.com/browse/SDA-8703
Better UX
> UX improvements for oidc-config cmds and cluster creation

- cmd/create/oidcconfig/cmd.go
- cmd/dlt/oidcconfig/cmd.go
- pkg/aws/client.go
Related issues:
* https://issues.redhat.com/browse/SDA-8702
* https://issues.redhat.com/browse/SDA-8698
* https://issues.redhat.com/browse/SDA-8672
> Fixing some ui issues for oidc configs

- cmd/create/machinepool/machinepool.go
- cmd/create/machinepool/machinepool_suite_test.go
- cmd/create/machinepool/machinepool_test.go
Fix panic
Accept empty values
Add key and values validation
Related: OCPBUGS-10432 [SDA-8272](https://issues.redhat.com//browse/SDA-8272)
> Improve taint validation

- cmd/list/cluster/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-8752
> [SDA-8752] Proper naming for topology description in list clusters

- cmd/create/oidcconfig/cmd.go
- pkg/output/output.go
Related issue: https://issues.redhat.com/browse/SDA-8836
Adds output option for auto mode in create OIDC config
Easier for automation flows
> SDA-8836 | feat: add output json/yaml to create oidc config

- cmd/upgrade/accountroles/cmd.go
Add a `--hosted-cp` flag to upgrade a set of roles with hosted CP managed policies.
Related: [SDA-8879](https://issues.redhat.com/browse/SDA-8879)
> fix: upgrade account roles - support hosted CP managed policies

- cmd/dlt/upgrade/cmd.go
- pkg/ocm/upgrades.go
JIRA: [SDA-8905](https://issues.redhat.com//browse/SDA-8905)
> SDA-8905 | feat: Implement delete upgrade command for hypershift

- cmd/upgrade/cluster/cmd.go
Related: [SDA-8880](https://issues.redhat.com//browse/SDA-8880)
> SDA-8880 | Fix: correctly check if an upgrade is already scheduled

- cmd/create/oidcconfig/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-8900
> SDA-8900 | fix: adjust behavior for creating with -o

- cmd/upgrade/operatorroles/cmd.go
- cmd/upgrade/roles/cmd.go
[https://issues.redhat.com/browse/SDA-8920](url)
> SDA-8920 | fix: improve upgrade roles / operator-roles info messages

- cmd/edit/machinepool/nodepool.go
Align behavior of rosa edit machinepool to not ask for replicas if we have another parameter and we are not in interactive method.
Current behaviour
```
rosa edit machinepool -c ad1 workers --tuning-configs tuned-2
? Replicas: 2
I: Updated machine pool 'workers' on hosted cluster 'ad1'
```
Fixed behaviour
```
rosa edit machinepool -c ad1 workers --tuning-configs tuned-2
I: Updated machine pool 'workers' on hosted cluster 'ad1'
```
Align also behaviour for version and autorepair parameters
Fix autorepair interactive behaviour
> SDA-8382| Fix: skip replicas when passing tuning configs to edit

- CHANGES.adoc
- pkg/info/info.go
- fix: aws path differs from ocm expected path
> Release v1.2.20

- cmd/create/oidcconfig/cmd.go
Related issue: https://issues.redhat.com/browse/SDA-9122
When running validations for installer arn ensures first that there is a chosen role name
Not all configurations need to validate installer role arn, was failing for manual mode unmanaged config
> SDA-9122 | fix: only validate installer arn if role name is not empty

- cmd/create/operatorroles/by_prefix.go
Related issue: https://issues.redhat.com/browse/OCM-302
Allows to bypass issuer url does not match trusted relationship when first creating the operator roles
When specifying operator roles by prefix if no roles are found means the customer would like to create them in the first place
> OCM-302 | fix: if no such entity move operator roles creation forward

- cmd/list/region/cmd.go
- pkg/ocm/helpers.go
As this is not needed anymore
Related: [SDA-9126](https://issues.redhat.com//browse/SDA-9126)
> SDA-9126 | feat: remove hypershift capability check in list regions

- cmd/create/cluster/cmd.go
- pkg/ocm/clusters.go
- pkg/ocm/helpers.go
- pkg/ocm/helpers_test.go
- pkg/ocm/versions.go
- pkg/ocm/versions_test.go
> Revert "OCM-140 | chore : reverting IMDSv2"

- pkg/ocm/upgrades.go
> sda-6257: handle errors when retrieve versiongates

- README.md
Extension to this PR:
https://github.com/openshift/rosa/pull/1267
> OCM-785 | Add specific commit binary image to README.md

- cmd/link/userrole/cmd.go
Related Issue: https://issues.redhat.com/browse/OCM-2155
> exit link userrole cmd when errors

- cmd/list/oidcprovider/cmd.go
- pkg/aws/helpers.go
- pkg/aws/policies.go
Related issue: https://issues.redhat.com/browse/OCM-2103
> OCM-2103 | feat: add 'in use' column list oidc providers

- cmd/create/cluster/cmd.go
> OCM-158 | fix: enable clusteradmin if user set --cluster-admin-user arg

- cmd/link/ocmrole/cmd.go
JIRA: https://issues.redhat.com/browse/OCM-1295
Previously, we were allowed to link ocmroles that did not exist. This fix adds a check to make sure that the role exists on AWS and throws an error and quits the wizard if the role does not exist.
> OCM-1295 | fix: add existence  check for ocm-roles

- pkg/output/output.go
> OCM-2632 | fix: add output support for list dns domains

- cmd/dlt/cmd.go
- cmd/dlt/dnsdomains/cmd.go
- cmd/list/dnsdomains/cmd.go
- pkg/ocm/dns_domain.go
> OCM-2245 | feat: rosa cli delete dns domain

- cmd/list/operatorroles/cmd.go
- pkg/aws/client.go
- pkg/aws/policies.go
Related Issue: https://issues.redhat.com/browse/OCM-2112
> OCM 2112 | feat: add -c flag for listing operator-roles

- cmd/list/version/cmd.go
The target is to transition to cluster based updates recommandations,
which means no more available upgrades for a single version, only for a specific cluster.
So the rosa list version --hosted-cp should not show anymore the available upgrades,
as in any case the current list is not correct (also showing versions which are disabled for HCP).
The user is informed that it should use rosa list upgrades -c clusterID instead
No change for rosa classic versions.
CC @wgordon17 
Related: [OCM-2180](https://issues.redhat.com//browse/OCM-2180)
> OCM-2180 | Fix: hide available upgrades for HCP in list versions

- cmd/verify/network/cmd.go
Adjusted output messages slightly to more accurately reflect when to use `--watch`
> OCM-2650 | fix: update 'verify network' status message

- cmd/create/cmd.go
- cmd/create/dnsdomains/cmd.go
- pkg/ocm/dns_domain.go
https://issues.redhat.com/browse/OCM-2544
> OCM-2544 | feat: support dns domain creation in rosa cli

- cmd/create/idp/htpasswd.go
- cmd/create/idp/htpasswd_test.go
https://issues.redhat.com/browse/OCM-2690
> OCM-2690 | feat: Support HTPasswd from-file flag in interactive mode

- pkg/ocm/clusters.go
Related issue: https://issues.redhat.com/browse/OCM-2895
> OCM-2895 | fix: empty checks against nil

- cmd/verify/network/cmd.go
- cmd/verify/network/cmd_test.go
* role arn is pulled from cluster, if not specified
* region is pulled from cluster, if not specified
* subnets are pulled from cluster, if not specified
> OCM-2695 | fix: determine role-arn for verify network

- cmd/create/cluster/cmd.go
- cmd/edit/ingress/cmd.go
- pkg/interactive/consts/consts.go
- pkg/interactive/interactive.go
- pkg/ocm/clusters.go
Related issue: https://issues.redhat.com/browse/OCM-853
> OCM-853 | fix: Clearer message when skipping option

- cmd/create/cluster/cmd.go
- pkg/ocm/versions.go
Related issue: https://issues.redhat.com/browse/OCM-2118
```
rosa create cluster --cluster-name gdb-4134ns --version 4.10.63
W: --sts flag won't be necessary if you wish to use STS.
W: --non-sts/--mint-mode flag will be necessary if you do not wish to use STS.
W: The version of Red Hat OpenShift Service on AWS that you are installing will no longer be supported after '2023-09-09'. Red Hat recommends selecting a newer version. For more information, see https://docs.openshift.com/rosa/rosa_policy/rosa-life-cycle.html
? Are you sure you want to continue with version '4.10.63'? No
```
> OCM-2118 | feat: Warns when choosing a close to eol version

- cmd/describe/cluster/cmd.go
https://issues.redhat.com/browse/OCM-199
> OCM-199 | feat: Add shared pvc fields to `cluster describe` cmd

- cmd/create/cluster/cmd.go
Related issue: https://issues.redhat.com/browse/OCM-1209
> OCM-1209 | fix: take correct action based on vpc prompt

- cmd/create/cluster/cmd.go
- pkg/ocm/clusters.go
https://issues.redhat.com/browse/OCM-2865
> OCM-2865 | feat: support shared vpc in rosa

- cmd/create/cluster/cmd.go
- pkg/ocm/clusters.go
- pkg/ocm/helpers.go
- pkg/ocm/helpers_test.go
Addresses: [OCM-210](https://issues.redhat.com/browse/OCM-210)
> updating create-cluster command with autoscaler configurations

- cmd/dlt/cluster/cmd.go
[OCM-2611](https://issues.redhat.com/browse/OCM-2611)
Added log statement to inform the client that the cluster is already being uninstalled if a duplicate removal of the same cluster is executed.
Deletion code is skipped if cluster is in Uninstall stage.
- Build rosa cli binary locally `make rosa`
- Create a rosa cluster 
Replace:
- - Name
- - Prefix
``` 
rosa create cluster --cluster-name <name> --sts --role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Installer-Role --support-role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Support-Role --controlplane-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-ControlPlane-Role --worker-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-Worker-Role --operator-roles-prefix <prefix> --region eu-west-1 --version 4.12.28 …
```
> OCM-2611 / fix: Added check for duplcate deletion of same cluster

- cmd/create/cluster/cmd.go
It almost seems like the 'help' option ('?') doesn't show more information for some parameters.
Changing it into a bit more comprehensive messages.
> OCM-3356 | fix: change the wording for autoscaler params

- cmd/create/cluster/cmd.go
Making sure that when the user gives some value for a max parameter it's greater than or equal to a previous min value that was given.
> OCM-3357 | fix: add a min/max validation

- cmd/create/oidcprovider/cmd.go
> OCM-1419 | fix: validate oic-provider exists in manual mode

- cmd/create/cluster/cmd.go
- pkg/clusterautoscaler/flags.go
- pkg/ocm/clusterautoscaler.go
This adds support for setting the missing field of GPU limitations. Users are able to provide it via two options:
* CLI, by repeating the option multiple times. E.g.:
```
rosa create cluster --autoscaler-gpu-limit nvidia.com/gpu,0,10 --autoscaler-gpu-limit amd.com/gpu,1,5
```
* Interactively. E.g.:
```
rosa create cluster
...
? Enter the number of GPU limitations you wish to set (optional): 2
? 1. Enter the type of desired GPU limitation: nvidia.com/gpu
? 1. Enter minimum number of GPUS of type 'nvidia.com/gpu' to deploy in
the cluster. (optional): 0
? 1. Enter maximum number of GPUS of type 'nvidia.com/gpu' to deploy in
the cluster. (optional): 10
? 2. Enter the type of desired GPU limitation: amd.com/gpu
? 2. Enter minimum number of GPUS of type 'amd.com/gpu' to deploy in the
cluster. …
```
> OCM-3334 | feat: allow setting GPU limitations

- cmd/create/cluster/cmd.go
- cmd/create/idp/htpasswd.go
- go.mod
- go.sum
- vendor/github.com/openshift-online/ocm-common/pkg/idp/validations/passwordValidator.go
- vendor/modules.txt
[OCM-1294](https://issues.redhat.com/browse/OCM-1294)
- create a rosa cluster 
- Create idp on the cluster with the bellow command,
`rosa create idp -t htpasswd --name jaya --username jaya --password Forgerock@#$123 -c <cluster-name>`
Make sure it throws a more informative response on why the password doesn't meet requirements.
> OCM-1294 | feat: Changed Password Validator function to use shared library

- cmd/upgrade/roles/cmd.go
Found a small bug that occurs when a user elects to detach existing policies from an existing "operator" role and reattach updated the operator policy.
(When running commands "rosa upgrade roles" or "rosa upgrade cluster" only)
Conditions to emulate issue:
A. Operator roles only. Account roles working properly.
B. Attach custom policy onto existing operator role.
C. Upgrade operator role via "rosa upgrade roles" or "rosa upgrade cluster" only.
"rosa upgrade operator-roles" or "rosa upgrade account-roles"command is works fine.
D. When prompted if you'd like to "Would you like to dettach current policies and setup a new one", select YES.
Steps to emulate issue:
A. Create classic account roles via "rosa create account-roles --version 4.10"
B. Create classic cluster with classic account roles …
> OCM-3370 | fix: re-attach policies after detaching from operator roles

- cmd/upgrade/cluster/cmd.go
- cmd/upgrade/machinepool/cmd.go
- cmd/upgrade/machinepool/cmd_test.go
- pkg/ocm/nodepools_upgrades.go
- pkg/test/helpers.go
Features and UX should be aligned with control plane upgrades Related: [OCM-2447](https://issues.redhat.com//browse/OCM-2447)
> OCM-2447 | feat: add automatic upgrades for node pools

- pkg/clusterautoscaler/flags.go
Applying the same validations that are done interactively when the fields are provided via CLI options.
> OCM-3366 | fix: CLI options not validated client-side

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/machinepool.go
- pkg/interactive/validation.go
https://issues.redhat.com/browse/OCM-3711
https://issues.redhat.com/browse/OCM-3712
> OCM-3711 | feat: validate disk size during machinepool creation

- cmd/edit/machinepool/nodepool.go
Check if an upgrade has been scheduled and skip the version part if there is any to avoid conflicts. In the future the version change through edit machinepool will be removed.
Related: [OCM-3739](https://issues.redhat.com//browse/OCM-3739)
> OCM-3739 | fix: no version change in edit machinepool if upgrade scheduled

- cmd/edit/ingress/cmd.go
- cmd/edit/ingress/flags.go
Related issue: https://issues.redhat.com/browse/OCM-3738
> OCM-3738 | fix: error message to alert customer of new ingress attributes

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/OCM-3714
> OCM-3714 | fix: don't ask for disk size for hosted cp

- cmd/list/addon/cmd.go
- cmd/list/idp/cmd.go
- cmd/list/ingress/cmd.go
- cmd/list/machinepool/cmd.go
- cmd/list/upgrade/cmd.go
- cmd/list/user/cmd.go
https://issues.redhat.com/browse/OCM-3115
> OCM-3115 | fix: list resources when cluster in hibernating state

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/cmd.go
- cmd/create/machinepool/machinepool.go
- cmd/create/machinepool/nodepool.go
- pkg/ocm/clusters.go
- pkg/ocm/versions.go
Related issue: https://issues.redhat.com/browse/OCM-3724
> OCM-3724 | feat: day2 security groups

- cmd/create/operatorroles/common_utils.go
For the shared VPC flow, if the user overrides an existing policy with a new shared VPC role ARN, provide a verbose error message.
Example:
```
oadler@dhcp-0-129:rosa (OCM-3522)$ rosa create operator-roles --prefix oadler-oct-2 --shared-vpc-role-arn arn:aws:iam::962993289388:role/oadler-shared-vpc-2
.
.
.
E: There was an error creating the operator roles: Policy with ARN 'arn:aws:iam::765374464689:policy/ManagedOpenShift-openshift-ingress-operator-cloud-credentials' contains 'sts:AssumeRole' with an unexpected shared VPC role ARN [Expected: 'arn:aws:iam::962993289388:role/oadler-shared-vpc', Provided 'arn:aws:iam::962993289388:role/oadler-shared-vpc-2'].
The policy is associated with the installer role with the prefix 'ManagedOpenShift'.
To create operator roles with shared VPC role ARN …
```
> OCM-3522 | fix: improve create operator roles error message

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/machinepool.go
- cmd/create/oidcconfig/cmd.go
- cmd/create/oidcprovider/cmd.go
- cmd/create/operatorroles/by_prefix.go
- cmd/dlt/oidcconfig/cmd.go
- cmd/dlt/oidcprovider/cmd.go
- cmd/register/oidcconfig/cmd.go
- pkg/interactive/oidc/oidc.go
- pkg/interactive/roles/roles.go
- pkg/interactive/securitygroups/security_groups.go
Related issue: [OCM-3833](https://issues.redhat.com//browse/OCM-3833)
> OCM-3833 | fix: only show interactive SGs if there are any

- pkg/fedramp/config.go
- Fixes Admin URLs for FedRAMP staging environment
> OCM-4024 | fix: fedramp admin stage urls

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/cmd.go
Related issue: [OCM-4134](https://issues.redhat.com//browse/OCM-4134)
> OCM-4134 | fix: better help message

- cmd/create/cluster/cmd.go
- cmd/create/cluster/cmd_test.go
- pkg/helper/helpers.go
- pkg/ocm/billing.go
- pkg/ocm/billing_test.go
https://issues.redhat.com/browse/OCM-3663
Dup of https://github.com/openshift/rosa/pull/1500, the original pr was messed up by rebase/squash
> OCM-3663 | feat: AWS billing support

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/OCM-4302
> OCM-4302 | fix: hide billingaccount for classic

- cmd/describe/upgrade/cmd.go
- cmd/describe/upgrade/cmd_test.go
https://issues.redhat.com/browse/OCM-3492
> OCM-3492 | Fix: log should be aligned to left

- go.mod
- go.sum
- vendor/github.com/openshift-online/ocm-common/pkg/resource/validations/kms_arn_regex_validation.go
- vendor/modules.txt
links to: https://issues.redhat.com/browse/OCM-4433
> OCM-4433| feat: Fixing cluster creation bug

- cmd/describe/upgrade/cmd.go
- cmd/describe/upgrade/cmd_test.go
https://issues.redhat.com/browse/OCM-3492
> OCM-3492 | fix: Classic upgrade should align left

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/machinepool.go
- pkg/helper/versions/helpers.go
- pkg/helper/versions/helpers_test.go
- pkg/ocm/versions.go
Related issue: [OCM-4506](https://issues.redhat.com//browse/OCM-4506)
> OCM-4506 | fix: adjust min format so it allows nightlies

- go.mod
- go.sum
- vendor/github.com/openshift-online/ocm-common/pkg/resource/validations/kms_arn_regex_validation.go
- vendor/modules.txt
JIRA: https://issues.redhat.com/browse/OCM-4513
> OCM-4513 | fix: updating vendor

- cmd/create/cluster/cmd.go
https://github.com/openshift/rosa/issues/1578
> OCM-4602 | fix: adjust subnet ids passed

- pkg/ocm/billing.go
https://issues.redhat.com/browse/OCM-4721
> OCM-4721 | fix: update hcp billing account link

- cmd/upgrade/cluster/cmd.go
- cmd/upgrade/cluster/cmd_test.go
Jira: https://issues.redhat.com/browse/OCM-1443
- report error and exit if node-drain-grace-period flag is specifed for hosted cluster upgrade.
- updating node drain grade period in cluster should only be performed for classic clusters
> OCM-1443 | fix: disable node drain grace period for hosted clusters

- cmd/create/cluster/cmd.go
- pkg/ocm/helpers.go
- pkg/ocm/products.go
- pkg/ocm/products_test.go
Discussed linking the enforcement of the request of the billing account flow for HCP once that GA is released.
Use the new technology preview API for coordination and flexibility.
> OCM-4801 | feat: Link the enforce of billing account hcp for GA

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/cmd.go
- cmd/create/machinepool/machinepool.go
- cmd/create/machinepool/nodepool.go
- pkg/interactive/securitygroups/security_groups.go
Related issue: [OCM-4813](https://issues.redhat.com//browse/OCM-4813)
> OCM-4813 | fix: create machine pool interactive mode

- cmd/describe/cluster/cmd.go
Related issue: [OCM-4887](https://issues.redhat.com//browse/OCM-4887)
```
Nodes:
- Control plane:           3
- Infra:                   2
- Compute:                 2
- Additional Security Group IDs:
- Control Plane:           sg-1
- Infra:                   sg-2
```
> OCM-4602 | fix: describe cluster show sg ids

- cmd/create/cluster/cmd.go
Related issue:  [OCM-4890](https://issues.redhat.com//browse/OCM-4890)
> OCM-4890 | fix: helper message infra/control sgs

- CONTRIBUTING.md
Highlight to format the files before creating a PR in the contribution file.
> OCM-3618 | feat: order imports - contributing file

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/OCM-5108
> OCM-5108 | fix: revise help message for create-cluster-admin

- cmd/describe/cluster/cmd.go
Related issue: [OCM-4780](https://issues.redhat.com//browse/OCM-4780)
> OCM-4780 | fix: remove duplicated describe att

- cmd/create/oidcconfig/cmd.go
- cmd/dlt/oidcconfig/cmd.go
- cmd/list/oidcconfig/cmd.go
JIRA - https://issues.redhat.com/browse/OCM-4085
Validation 
```
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-4085› 
╰─$ make rosa && sudo mv rosa /usr/bin
go build ./cmd/rosa
[sudo] password for croche: 
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-4085› 
╰─$ rosa create oidc-config
? Would you like to create a Managed (Red Hat hosted) OIDC Configuration (Y/n) 
? OIDC Config creation mode:  [Use arrows to move, type to filter, ? for more help]
> auto
manual
E: Expected a valid OIDC Config creation mode: interrupt
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-4085› 
╰─$ rosa create oidcconfig                                         1 ↵
? Would you like to create a Managed (Red Hat hosted) OIDC Configuration (Y/n) 
? OIDC Config creation mode:  [Use arrows to move, type to filter, ? for more help]
> auto
manual
E: …
```
> OCM-4085 | fix: update aliases for oidc config

- cmd/create/cluster/cmd.go
- pkg/aws/client.go
Related issue: [OCM-1079](https://issues.redhat.com//browse/OCM-1079)
> OCM-1079 | fix: only show private subnets when private link cluster is selected

- cmd/create/cluster/cmd.go
Related issue: [OCM-4646](https://issues.redhat.com//browse/OCM-4646)
> OCM-4646 | fix: add prompt to then show default ingress custom options

- pkg/aws/client.go
- pkg/aws/client_test.go
- pkg/helper/helper_suite_test.go
- pkg/helper/helpers.go
- pkg/helper/helpers_test.go
Related issue: [OCM-5313](https://issues.redhat.com//browse/OCM-5313)
> OCM-5313 | fix: chunk slice before sending request to AWS

- cmd/create/cluster/cmd.go
Related issue: [OCM-5365](https://issues.redhat.com//browse/OCM-5365)
> OCM-5365 | fix: set IMDS as option prompt

- pkg/interactive/interactive.go
Related issue: [OCM-4646](https://issues.redhat.com//browse/OCM-4646)
> OCM-4646 | fix: parenthesis placement

- cmd/create/cluster/cmd.go
Related issue: [OCM-5088](https://issues.redhat.com//browse/OCM-5088)
> OCM-5088 | fix: if no subnets available refer to doc

- cmd/edit/ingress/cmd.go
Related issue: [OCM-5536](https://issues.redhat.com//browse/OCM-5536)
> OCM-5536 | fix: better message for ingress unsupported att on HCP

- pkg/ocm/helpers.go
Reverting back change to fix issue: https://issues.redhat.com/browse/OCM-5577
> OCM-5577 | fix: reverting back change

- go.mod
- go.sum
- vendor/github.com/openshift-online/ocm-common/pkg/rosa/oidcconfigs/oidcconfigs.go
- vendor/modules.txt
Related issue: [OCM-5647](https://issues.redhat.com//browse/OCM-5647)
> OCM-5647 | chore: bump ocm-common

- cmd/create/admin/cmd.go
- cmd/create/idp/htpasswd.go
- pkg/ocm/clusters.go
- pkg/ocm/idps.go
https://issues.redhat.com/browse/OCM-3294
> OCM-3294 | feat: secure password by hashing it in idp/cluster creation flow

- pkg/aws/policies.go
[JIRA](https://issues.redhat.com/browse/OCM-5626)
> OCM-5626 | feat: Added fix for showing empty account roles

- cmd/create/machinepool/nodepool.go
This PR ensures that the changes introduced in #1711 are applied to the creation of NodePools on HCP clusters for the sake of consistency.
> OCM-5544 | fix: Improve logging when fetching instance type data for creation of machine pools

- cmd/link/ocmrole/cmd.go
In the case of no admin permission error, include the OCM account ID in the error message.
e.g. 
```
E: OCM account '21PZhUMJwhZLwlf8iXVB4hqyT2m' has no permission for this command, Only organization admin can run this command. Please ask someone with the organization admin role to run the following command 
rosa link ocm-role --role-arn arn:aws:iam::765374464689:role/oadler-jan-24-OCM-Role-12541229 --organization-id 1jIHnIbrnLH9kQD57W0BuPm78f1
```
> OCM-1234 | feat: Improve error message for `rosa link ocm-role`

- cmd/grant/user/cmd.go
- cmd/revoke/user/cmd.go
https://issues.redhat.com/browse/OCM-5645
> OCM-5645 | fix: revise help message for `rosa grant/revoke` command

- OWNERS
I no longer review/approve PRs from `rosa`, so I removed myself from the list.
I also sorted the list alphabetically to make it easier to see who's in the list.
> Remove vkareh from approver/reviewer

- cmd/create/cluster/cmd.go
- cmd/create/machinepool/nodepool.go
- cmd/list/version/cmd.go
- pkg/helper/versions/helpers.go
- pkg/helper/versions/helpers_test.go
- pkg/ocm/versions.go
- pkg/ocm/versions_test.go
https://issues.redhat.com/browse/OCM-5461
> OCM-5461 | feat: use default version

- cmd/link/userrole/cmd.go
JIRA - https://issues.redhat.com/browse/OCM-1366
> OCM-1366 | fix: update description on link user roles command

- pkg/ocm/helpers.go
- pkg/ocm/helpers_test.go
Regression from - https://github.com/openshift/rosa/pull/1755 
JIRA - https://issues.redhat.com/browse/OCM-5974
> OCM-5974 | fix: update correct values for subnet count validation

- cmd/create/cluster/cmd.go
- cmd/describe/cluster/cmd.go
- cmd/describe/cluster/cmd_test.go
- pkg/ocm/clusters.go
https://issues.redhat.com/browse/OCM-4458
> OCM-4458 | feat: add new parameter to enable external auth config

- cmd/create/operatorroles/by_clusterkey.go
Originally moved all logic into auto mode that didn't have to be in manual. Now you can generate commands to make op roles even if roles exist. This MR moves the code that checks for already existing op roles back into general flow (manual & auto modes)
> OCM-1109 | fix: Check if op roles exist always again

- OWNERS
As I am not active in this repo at  this time, I would like to remove my name from the OWNERS file.
> updating OWNERS file

- cmd/version/cmd_test.go
- pkg/aws/policies.go
- pkg/aws/policies_test.go
- pkg/ocm/versions_test.go
[OCM-5665](https://issues.redhat.com//browse/OCM-5665) Removed unecessary err check
> OCM-5665 | feat: Removed unecessary err check

- cmd/create/cluster/cmd.go
- cmd/create/cluster/cmd_test.go
https://issues.redhat.com/browse/OCM-5963
> OCM-5963 | fix: add more instruction in billing account error

- cmd/login/cmd.go
- Adds device code flow login
- Minor cleanup to auth code flow login
> OCM-5815 | feat: Add Device Code Flow

- cmd/upgrade/roles/cmd.go
[JIRA](https://issues.redhat.com/browse/OCM-5830) Removing duplicate err output
> OCM-5830 | feat: removing duplicate err msg output

- pkg/ocm/helpers.go
math.MaxInt64 needs to be bound by int64() as that can otherwise overflow if the helpers are compiled for non-64bit architectures (e.g. armv7l) as per https://github.com/golang/go/issues/23086.
Context:
Now that ROSA control planes are supported in the upstream Cluster API Provider AWS, the code used in the provider needs to also be compatible with arm architectures (which are a valid CAPA target arch)
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4835
As such it is desirable for the ROSA helpers to be compilable for arm. The issue this PR fixes prevents that from happening. Thus this PR.
> OCM-6435 | fix: Bound math.MaxInt64 to avoid overflow on non-64bit arch

- cmd/create/cluster/cmd.go
- cmd/create/cluster/cmd_test.go
- pkg/aws/client.go
- pkg/aws/client_test.go
- pkg/aws/mock_client.go
https://issues.redhat.com/browse/OCM-1473
> OCM-1473 | fix: filter out local/wavelength zone in cluster creation

- cmd/edit/ingress/cmd.go
- cmd/edit/ingress/cmd_test.go
- cmd/edit/ingress/flags.go
- cmd/edit/ingress/main_test.go
- cmd/list/ingress/cmd.go
[OCM-6029](https://issues.redhat.com//browse/OCM-6029)
>  OCM-6029 | feat: allow to edit component routes of ingress

- cmd/config/cmd_test.go
- cmd/config/get/get.go
**Changed**
- Added more info to get config error message when config is not found
https://issues.redhat.com/browse/OCM-6514
> OCM-6514 | fix: Added more info to get config error message when config is not found

- cmd/create/admin/admin_suite_test.go
- cmd/create/admin/cmd.go
- cmd/create/admin/cmd_test.go
- cmd/create/cluster/cmd.go
- cmd/describe/admin/cmd.go
- cmd/dlt/admin/cmd.go
- cmd/dlt/idp/cmd.go
- cmd/list/user/cmd.go
- pkg/test/helpers.go
> OCM-4613 | feat: support customize username for cluster admin creation

- cmd/create/cluster/cmd.go
Follows up on https://github.com/openshift/rosa/pull/1814#issuecomment-1997276635
> OCM-6141 | fix: improve domain-prefix help message

- cmd/create/cmd.go
- cmd/create/externalauthprovider/cmd.go
- cmd/describe/cluster/cmd_test.go
- cmd/describe/cmd.go
- cmd/describe/externalauthprovider/cmd.go
- cmd/describe/externalauthprovider/cmd_test.go
- cmd/describe/externalauthprovider/main_test.go
- cmd/dlt/cmd.go
- cmd/dlt/externalauthprovider/cmd.go
- cmd/list/cmd.go
- cmd/list/externalauthprovider/cmd.go
- cmd/list/externalauthprovider/cmd_test.go
- cmd/list/externalauthprovider/externalauthprovides_suite_test.go
- pkg/externalauthprovider/externalauthconfig_test.go
- pkg/externalauthprovider/flags.go
- pkg/externalauthprovider/flags_test.go
- pkg/ocm/externalauthproviders.go
- pkg/ocm/externalauthproviders_test.go
- pkg/ocm/helpers.go
- pkg/ocm/helpers_test.go
- pkg/test/helpers.go
https://issues.redhat.com/browse/OCM-4459
> OCM-4459 | feature: CRUD for external auth providers

- cmd/config/cmd.go
- cmd/config/get/get.go
- cmd/config/set/set.go
- pkg/config/config.go
- pkg/config/config_test.go
**Changed**
- Improved help text for config get/set commands
https://issues.redhat.com/browse/OCM-6516
> OCM-6516 | fix: Improved help text for config get/set commands

- cmd/create/accountroles/cmd.go
1. Swap the order of validation for classic managed policies in prod.
2. Ignore the managed policies flag, if set to true, and also the `hosted-cp` flag is provided.
e.g.
```
oadler@fedora:rosa (OCM-6570)$ rosa create account-roles --hosted-cp --managed-policies=false --mode auto --prefix oadler-mar-17 -y
I: Logged in as 'oadler.openshift' on 'https://api.openshift.com'
E: Setting `hosted-cp` as unmanaged policies is not supported
oadler@fedora:rosa (OCM-6570)$ rosa create account-roles --hosted-cp --managed-policies --mode auto --prefix oadler-mar-17 -y
I: Logged in as 'oadler.openshift' on 'https://api.openshift.com'
W: Setting `managed-policies` flag for hosted CP account roles has no effect. Hosted CP account roles are managed policies only
I: AWS …
```
> OCM-6570 | fix: validation for classic managed policies

- cmd/describe/externalauthprovider/cmd.go
- cmd/list/externalauthprovider/cmd.go
- pkg/output/output.go
https://issues.redhat.com/browse/OCM-6840
> OCM-6840 | fix: Add json output of the external auth

- cmd/create/admin/cmd.go
- cmd/describe/admin/cmd.go
- cmd/dlt/admin/cmd.go
- hack/commit-msg-verify.sh
[OCM-6883](https://issues.redhat.com//browse/OCM-6883)
> Revert ocm-6883

- .gitignore
- tests/e2e/test_rosacli_node_pool.go
- tests/e2e/test_rosacli_region.go
https://issues.redhat.com/browse/OCM-6309
> OCM-6309 | ci: Verify test case(s) 55729/56782/60202/63178/61139/67414

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_kubelet_config.go
- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/profilehandler/profile_handler.go
Here is the log for all cases
https://privatebin.corp.redhat.com/?ce23b71bd1c37cb2#7TXzBJx3EtV9YkLTHUyHxSaAZB4hQGsffoZsWeoVFKEZ
> OCM-6309 | ci: Verify test cases 68828|68835|68836|38787|66872

- tests/e2e/test_rosacli_cluster.go
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus 45159 tests/e2e
2.13.2
2.13.0 used by e2e
Ginkgo CLI. …
```
> OCM-6309 | ci: Verify test case 45159

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/OCM-6079
> OCM-6079 | feat: support cluster admin day-1 creation for HCP cluster

- pkg/ocm/break_glass_credential.go
https://issues.redhat.com/browse/OCM-7340
> OCM-7340 | fix: Add poll length for break glass credential

- tests/e2e/test_rosacli_machine_pool.go
- tests/e2e/test_rosacli_verify.go
- tests/utils/common/string.go
- tests/utils/config/cluster.go
- tests/utils/exec/rosacli/machinepool_service.go
log [here](https://privatebin.corp.redhat.com/?fe2bdae33c8b7eee#Av44tSCNhwA81CWWWMKvhnWBnehB3XHcpuKg6PCAp1cY)
> OCM-7365 | ci: Automated cases 38838 and 68172 and verified 43251

- cmd/describe/machinepool/cmd_test.go
- cmd/describe/machinepool/nodepool.go
- pkg/ocm/output/machinepools.go
https://issues.redhat.com/browse/OCM-6729
> OCM-6729 | feat: Show user tags on describe machine pool for HCP

- cmd/list/instancetypes/cmd.go
- cmd/list/instancetypes/cmd_test.go
[OCM-7412](https://issues.redhat.com//browse/OCM-7412)
Adjusts to allow to supply a role-arn and uses interactive mode to filter existing installer role arns in logged in account
> OCM-7412 | fix: list instance types filter by region requires installer role arn

- tests/e2e/test_rosacli_iam_roles.go
Log: https://privatebin.corp.redhat.com/?50107baa044be04f#CqFjAewinFaBBUBz91kc1p1mxD789dc9rb3iFtcV6dKA
> OCM-6309: Verify test case 52419

- cmd/describe/breakglasscredential/cmd.go
- cmd/describe/breakglasscredential/cmd_test.go
https://issues.redhat.com/browse/OCM-7340
> OCM-7340 | fix: Add info msg for empty case

- tests/e2e/test_rosacli_ingress.go
- tests/e2e/test_rosacli_network_verifier.go
- tests/e2e/test_rosacli_node_pool.go
- tests/e2e/test_rosacli_verify.go
[Log ](https://privatebin.corp.redhat.com/?8543b35ec8e42141#92h6bLEn7nVeSEaH8gBncn8hhBcj3poLQjawX62JWQ2g) for  63323/64917/64040 
[Log ](https://privatebin.corp.redhat.com/?6895df83d7538fa0#Eq68rmZeMzY1YyjhgMbop9ErcRguPmHFBPzn2VB9ZHXf) for 61138
> OCM-6309 | ci: Verify test case(s) 63323|64917|64040|61138

- cmd/list/user/cmd.go
https://issues.redhat.com/browse/OCM-4806
> OCM-4806 | fix: align list users with list idps

- tests/e2e/test_rosacli_iam_roles.go
- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/exec/rosacli/ocm_resource_service.go
Here is the [log](https://privatebin.corp.redhat.com/?f20ff66235814dd1#EX2c62EuDERDuCKYyZUvjFGYFmgK6L6xiyGtqCKqBde9)
> OCM-6309 | ci: Verify test case(s) 43070|60971

- cmd/create/operatorroles/by_prefix.go
https://issues.redhat.com/browse/OCM-5247
> OCM-5247 | fix: error message for unmanaged policies

- tests/e2e/test_rosacli_node_pool.go
output log :- https://privatebin.corp.redhat.com/?dc617c3637b15044#48NgnJbApqXCNpW9Bt3ZKtnMUDzENQ5XRYcUnEQYuTxQ
> OCM-4597 | test: automate id:OCP-73391 validations for editing machinepool

- cmd/create/breakglasscredential/cmd.go
- cmd/create/externalauthprovider/cmd.go
- cmd/describe/breakglasscredential/cmd.go
- cmd/describe/externalauthprovider/cmd.go
- cmd/dlt/externalauthprovider/cmd.go
- cmd/list/breakglasscredential/cmd.go
- cmd/list/externalauthprovider/cmd.go
- cmd/revoke/breakglasscredential/cmd.go
https://issues.redhat.com/browse/OCM-7792
> OCM-7792 | fix: unhide breakglass and externalauth

- cmd/describe/ingress/cmd.go
- cmd/describe/ingress/cmd_test.go
[OCM-6527](https://issues.redhat.com//browse/OCM-6527)
[OCM-7822](https://issues.redhat.com//browse/OCM-7822)
> OCM-6527 | fix: adjust describe ingress binding

- pkg/externalauthprovider/flags.go
https://issues.redhat.com/browse/OCM-7673
> OCM-7673 | fix: Provide the default value to the external auth

- tests/e2e/hcp_external_auth_test.go
output log:- https://privatebin.corp.redhat.com/?d0c20245dd399d9f#aHq5Gi3rNryVpAwQxSAYG3rSDGMCZqUfyujvfVnLL9o
> OCM-4460 | test: automate id:OCP-73018 validations for breakglasscred

- pkg/machinepool/output_test.go
- pkg/ocm/output/nodepools.go
https://issues.redhat.com/browse/OCM-7526
> OCM-7526 | fix: Display min/max in describe machinepool

- cmd/create/cluster/cmd.go
https://issues.redhat.com/browse/OCM-5085
> OCM-5085 | fix: lower mapAZcreated to 1

- cmd/describe/breakglasscredential/cmd.go
- cmd/describe/breakglasscredential/cmd_test.go
https://issues.redhat.com/browse/OCM-7169
> OCM-7169 | fix: warn revoked break glass credential

- tests/e2e/test_rosacli_ingress.go
- tests/utils/exec/rosacli/ingress_service.go
successfully run both new cases:
```
oaharoni-mac:rosa oaharoni$ ginkgo -focus id:65799 tests/e2e/
Running Suite: e2e tests suite - /Users/oaharoni/rosa_workspace/rosa/tests/e2e
==============================================================================
Random Seed: 1715255945
Will run 1 of 61 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSS
Ran 1 of 61 Specs in 5.121 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 60 Skipped
PASS
Ginkgo ran 1 suite in 8.57407575s
```
```
oaharoni-mac:rosa oaharoni$ ginkgo -focus id:64767 tests/e2e/
Running Suite: e2e tests suite - /Users/oaharoni/rosa_workspace/rosa/tests/e2e
==============================================================================
Random Seed: 1715255788
Will run 1 of 61 specs …
```
> OCM-7880 | ci: Automate cases 65799 and 64767

- tests/README.md
- tests/ci/data/profiles/rosa-classic.yaml
> OCM-7958 | ci: Update readme for tests folder 

- pkg/ocm/helpers.go
- pkg/ocm/helpers_test.go
https://issues.redhat.com/browse/OCM-6569
> OCM-6569 | fix: print role arn for hcp

- cmd/create/kubeletconfig/cmd.go
- cmd/describe/cmd.go
- cmd/describe/kubeletconfig/cmd.go
- cmd/describe/kubeletconfig/cmd_test.go
- cmd/describe/kubeletconfig/kubeletconfig_suite_test.go
- cmd/dlt/kubeletconfig/cmd.go
- cmd/edit/kubeletconfig/cmd.go
- pkg/interactive/flag.go
- pkg/kubeletconfig/config.go
- pkg/kubeletconfig/consts.go
- pkg/kubeletconfig/output.go
- pkg/kubeletconfig/output_test.go
- pkg/ocm/nodepools.go
- pkg/test/helpers.go
This PR updates `rosa describe kubeletconfig` with support for HCP clusters.
> OCM-7267 | feat: Added ability to describe Kubeletconfigs for HCP clusters

- tests/e2e/test_rosacli_iam_roles.go
[OCM-7989](https://issues.redhat.com/browse/OCM-7989)  Validation will work when user create account-roles
$ ginkgo --focus 43067 tests/e2e
2.11.0
Ginkgo CLI.
If …
> SDA-4329 | feat: Validation for user creating account-roles

- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/exec/rosacli/ocm_resource_service.go
This PR adds ListInstanceTypes function to list
all available instance-types (rosa list instance-types) and 
it also verifies the presence of newly enabled instance-types
$ ginkgo --focus 73308 tests/e2e
2.11.0
from a path that contains a …
> Add support for ListInstanceTypes method

- tests/e2e/test_rosacli_ingress.go
- tests/utils/common/string.go
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus 38835 tests/e2e
Random Seed: 1715747626
Will run 1 of 64 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS+++++++++++++++++++++
[label-38835=label-value-38835 label-38835-2=label-value-38835-2]
+++++++++++++++++++++
•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 64 Specs in 22.885 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 63 Skipped
PASS
Ginkgo ran 1 suite in 29.219901079s
```
> OCM-7993 | test: Automated id:38835 List/Edit the default ingress on ROSA cluster via rosa-cli will succeed

- tests/e2e/hcp_external_auth_test.go
output log :- https://privatebin.corp.redhat.com/?a82569ade54d98a3#Bebud92EF4E8WmWVFBr77eLdGvBVVYzGG8XRVLAoMHLR
> OCM-4458 | test: automate id:71946 validation for create/list/delete idp and admin for exteranl auth cluster

- tests/e2e/test_rosacli_ingress.go
- tests/e2e/test_rosacli_kubelet_config.go
- tests/utils/exec/rosacli/kubelet_config_service.go
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "(73753|73754)" tests/e2e
Random Seed: 1715844438
Will run 2 of 74 specs
SSSSSSSSSSS••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 2 of 74 Specs in 58.513 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 72 Skipped
PASS
Ginkgo ran 1 suite in 1m5.175837227s
```
> OCM-8045 | test: Automated cases id:73753,73754 for kubeletconfig porting on HCP

- tests/README.md
[OCM-8133](https://issues.redhat.com//browse/OCM-8133) | ci: Update readme for test folder to document how to destroy resources
> OCM-8133 | ci: Update readme for test folder of  how to destroy resources

- tests/e2e/test_rosacli_kubelet_config.go
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "(68836|68835)" tests/e2e
Random Seed: 1716286090
Will run 2 of 78 specs
SSSSSSS••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 2 of 78 Specs in 39.738 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 76 Skipped
PASS
Ginkgo ran 1 suite in 47.565992334s
```
> OCM-8186 | test: fixed id:68835,68836 for kubeletconfig testing on classic

- cmd/create/machinepool/nodepool.go
This PR updates the `rosa create machinepool` command to only list KubeletConfigs for a HCP cluster when absolutely necessary. This is blocking QE testing due to the KubeletConfig feature for HCP clusters not being enabled in production.
If the user requests interactive mode, then we must fetch the KubeletConfigs.
Verified that this allows creation of MachinePools for HCP clusters in production:
```
rblake-mac:rosa robpblake$ ./rosa list machinepool -c rblake-hcp
ID       AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONE  SUBNET                    VERSION  AUTOREPAIR  
mp-1     No           2/2       m5.xlarge                          us-west-2a         subnet-0e3a4046c1c2f1078  4.15.12  Yes         
workers  No           2/2       m5.xlarge …
```
> OCM-8165 | fix: Only list kubeletconfigs when absolutely necessary when creating a machinepool

- cmd/edit/machinepool/cmd.go
- cmd/edit/machinepool/machinepool.go
- cmd/edit/machinepool/nodepool.go
- cmd/edit/machinepool/nodepool_test.go
https://issues.redhat.com/browse/OCM-3701
> OCM-3701 | feat: Remove version from editing machinepool

- cmd/describe/cluster/cmd.go
https://issues.redhat.com/browse/OCM-6544
```
bash-5.2$ ./rosa describe cluster -c marco --get-role-policy-bindings
Name:                       marco
Domain Prefix:              marco
Display Name:               marco
ID:                         2bdtlnmbjt4rv1vj48t3299qic4tomkv
External ID:                f491de52-5893-4207-9f18-558265d2e4e4
Control Plane:              Customer Hosted
OpenShift Version:          
DNS:                        marco.8j6c.i1.devshift.org
AWS Account:                765374464689
API URL:                    
Console URL:                
Region:                     us-east-1
Multi-AZ:                   false
Nodes:
- Control plane:           3
- Infra:                   2
- Compute: …
```
> OCM-6544 | feat: display attached policies for sts roles

- cmd/dlt/operatorrole/cmd.go
https://issues.redhat.com/browse/OCM-8202
> OCM-8202 | fix: remove redudant empty lines in manual mode

- tests/e2e/hcp_external_auth_test.go
output log :- https://privatebin.corp.redhat.com/?9cdb7dc44e59429b#8ScK6rdMGptkhN8AR1crGbeZssKvpRertJdKxuxpvee2
> OCM-4458 | test: automate id:73755 validation for create cluster with external_auth_config

- tests/e2e/test_rosacli_cluster.go
====================================================================
Random Seed: 1716347360
Will run 1 of 79 specs
------------------------------
Classic cluster creation validation to validate to create the sts cluster with invalid tag - [id:56440] [day1-validation, feature-cluster, Medium, NonHCPCluster]
/home/zhewang/go/src/rosa/tests/e2e/test_rosacli_cluster.go:502
STEP: Create cluster with invalid tag key @ 05/22/24 11:09:20.754
2024-05-22T11:09:20+08:00 - INFO : Running command: rosa create cluster -c ocp-56440 --tags=~~~:cluster
2024-05-22T11:09:28+08:00 - DEBUG : Get Combining Stdout and Stder is :
ERR: expected a valid user tag key '~~~' matching ^[\pL\pZ\pN_.:/=+\-@]{1,128}$
STEP: Create cluster with invalid tag value @ 05/22/24 11:09:28.731
2024-05-22T11:09:28+08:00 - INFO : …
> OCM-8187 | test: Automated case id:56440 validations for the '--tags'

- tests/e2e/e2e_pre_check_test.go
- tests/e2e/hcp_cluster_test.go
- tests/utils/config/cluster.go
- tests/utils/exec/rosacli/pr_check.go
- tests/utils/profilehandler/data_preparation.go
- tests/utils/profilehandler/interface.go
- tests/utils/profilehandler/profile_handler.go
```
[yingzhan@localhost rosa]$ ginkgo -focus "(71945|64491|60083|71050)" tests/e2e  
Running Suite: e2e tests suite - /home/yingzhan/autotest/rosa/tests/e2e
=======================================================================
Random Seed: 1716184110
Will run 4 of 79 specs
SSSSS••••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 4 of 79 Specs in 144.820 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 75 Skipped
PASS
Ginkgo ran 1 suite in 2m28.852597111s
```
> OCM-8134 | test: automated id:71945,64491,60083,71050

- pkg/aws/client.go
[OCM-8352](https://issues.redhat.com//browse/OCM-8352)
```
export AWS_CA_BUNDLE=~/Documents/test-ca.pem
rosa list clusters
E: Failed to create AWS client: unable to add custom RootCAs HTTPClient, has no WithTransportOptions, *http.Client
```
```
export AWS_CA_BUNDLE=~/Documents/test-ca.pem
rosa list clusters
E: Failed to create AWS client: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 12, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.us-west-2.amazonaws.com/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
```
unset AWS_CA_BUNDLE
rosa list clusters
ID                                NAME             STATE         TOPOLOGY
xxx
```
Error relates to invalid certificate rather than …
> OCM-8352 | fix: use aws default http client

- tests/e2e/hcp_external_auth_test.go
- tests/utils/exec/rosacli/break_glass_credential_service.go
$ ginkgo --focus 72899 tests/e2e/
2.14.0
Ginkgo CLI. …
> OCM-7647 | test: automate id:OCP-72899 Updated the checkpoints for tc

- tests/e2e/test_rosacli_cluster.go
zhewang@fedora:~/go/src/rosa$ ginkgo -focus 52692 tests/e2e/
2.14.0
Ginkgo CLI.
version …
> OCM-8419 | test: Automate case id: OCP-52692 Validation for availability zones

- tests/e2e/test_rosacli_kubelet_config.go
- tests/e2e/test_rosacli_machine_pool.go
https://issues.redhat.com/browse/OCM-8466
> OCM-8466 | ci: Fix classic checks

- tests/README.md
- tests/ci/labels/features.go
- tests/ci/labels/labels.md
- tests/ci/labels/runtime.go
Automation labels Docs: https://docs.google.com/document/d/1R7ZC9vJ6FsXOBA3zlQVA5jrF9hlBuwWViZMo5AOxPWk/edit
> OCM-8418 | test: update readme for automation labels usage

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_kubelet_config.go
- tests/utils/config/cluster.go
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "(45161|73753)" tests/e2e
Running Suite: ROSA CLI e2e tests suite - /Users/lixue/Workspace/rosa/tests/e2e
===============================================================================
Random Seed: 1717725946
Will run 2 of 95 specs
SSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 2 of 95 Specs in 169.228 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 93 Skipped
PASS
Ginkgo ran 1 suite in 2m56.681555902s
```
> OCM-8623 | test: fixed id:73753,45161 in HCP pipeline

- cmd/create/externalauthprovider/cmd_test.go
- cmd/create/externalauthprovider/externalauthprovider_suite_test.go
- pkg/externalauthprovider/flags.go
https://issues.redhat.com/browse/OCM-7871
> OCM-7871 | fix: Mandatory fields should enter interactive mode if not provided

- tests/e2e/test_rosacli_idp.go
[OCM-8390](https://issues.redhat.com//browse/OCM-8390)
$ ginkgo --focus 38788 tests/e2e
2.11.0
Ginkgo CLI. …
> OCM-8390 | test: automate id:38788 [rosacli] Validation for IDP creation commands

- cmd/create/machinepool/cmd.go
- cmd/create/machinepool/nodepool.go
- cmd/describe/machinepool/cmd_test.go
- cmd/edit/machinepool/cmd.go
- cmd/edit/machinepool/nodepool.go
- pkg/helper/machinepools/helpers.go
- pkg/helper/machinepools/helpers_test.go
- pkg/machinepool/output.go
- pkg/machinepool/output_test.go
- pkg/ocm/output/nodepools.go
- pkg/ocm/output/nodepools_test.go
https://issues.redhat.com/browse/OCM-6654
> OCM-7289 | feat: create/update of maxUnavailable and maxSurge for NodePool

- cmd/attach/cmd.go
- cmd/attach/policy/cmd.go
- cmd/detach/cmd.go
- cmd/detach/policy/cmd.go
https://issues.redhat.com/browse/OCM-8269
> OCM-8269 | feat: hide attach/detach commands

- cmd/upgrade/roles/cmd.go
https://issues.redhat.com/browse/OCM-8648
> OCM-8648 | feat: handle 412 response in upgrade commands

- pkg/cache/cache.go
[OCM-8680](https://issues.redhat.com//browse/OCM-8680)
> OCM-8680 | fix: use a tmp file per username

- cmd/create/machinepool/helper_test.go
- cmd/create/machinepool/nodepool.go
https://issues.redhat.com/browse/OCM-6477
> OCM-6477 | fix: fetch subnets for availability zone

- tests/e2e/test_rosacli_cluster.go
[OCM-8640](https://issues.redhat.com//browse/OCM-8640) | Validate --worker-mp-labels option for ROSA cluster creation
Output log :- https://privatebin.corp.redhat.com/?a314a6d2c1a5d93a#BX25geuRQUGyg9HGAymM97M1YtLrxpgpc4LyQTGnvz1G
> OCM-8640 | test: automated case id:71329 

- go.mod
- go.sum
- tests/ci/labels/features.go
- tests/e2e/test_rosacli_policy.go
- tests/e2e/test_rosacli_upgrade.go
- tests/utils/exec/rosacli/ocm_resource_service.go
- tests/utils/exec/rosacli/version_service.go
- vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/client.go
- vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/policy.go
- vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/role.go
- vendor/modules.txt
[OCM-8848](https://issues.redhat.com//browse/OCM-8848) | test: automate id:74402,74403,73731 upgrade/delete roles with attaching arbitrary policies
Logs: https://privatebin.corp.redhat.com/?f8e9c754f600eea1#96YYCSwUsQmUKn7d7V6knUKbTQ2v5S1Qc2uMY8ih8KFf
> OCM-8848 | test: automate id:74402,74403,73731 upgrade/delete roles with attaching arbitrary policies

- tests/e2e/e2e_setup_test.go
- tests/e2e/test_rosacli_cluster.go
output log :- https://privatebin.corp.redhat.com/?87a3fc76031b60b4#4aUGmtYNT8V1HChDRu1c8WUfqACPQKZe64AT3xTJ6317
> OCM-8985 | test: fixing id:66372,73725,72657,70970,56440 hcp ci fix

- tests/ci/data/profiles/rosa-hcp.yaml
- tests/e2e/hcp_external_auth_test.go
- tests/e2e/test_rosacli_cluster.go
45161, 73755 output log :- https://privatebin.corp.redhat.com/?c697f71e341e8188#2UCcETVAadnyj5JBykt3emuDqBJcy4GbNV8mAaJZyYBG 
rosa-hcp-upgrade-z-stream log :- https://privatebin.corp.redhat.com/?ac38e9b4cd9a5693#DN6n6MnW8iFU1wEgXkacQP2SX1eSB9QFi6MuSaTVECPi
> OCM-9008 | test: fixing id:45161,73755 hcp ci fix

- cmd/create/admin/cmd.go
https://issues.redhat.com/browse/OCM-8329
> OCM-8329 | fix: add password validator for create admin

- tests/ci/config/config.go
- tests/ci/data/resources/cilium.yaml
- tests/e2e/e2e_setup_test.go
- tests/e2e/test_rosacli_cluster.go
- tests/utils/config/support.go
- tests/utils/exec/occli/cmd_client.go
- tests/utils/profilehandler/profile_handler.go
log:
https://privatebin.corp.redhat.com/?0b978894d249f696#9bzbGrGVpgxtorSWfUetCKFCFtnHJRaVcxwPHmLZ8QuA
> OCM-8285 | test: implement no-cni(cilium) supporting

- cmd/create/cluster/cmd.go
- cmd/describe/cluster/cmd.go
- pkg/ocm/clusters.go
> Revert "OCM-9094 | feat: support multi-arch-enabled parameter"

- tests/ci/labels/features.go
- tests/e2e/test_rosacli_config.go
- tests/utils/exec/rosacli/ocm_resource_service.go
[OCM-8925](https://issues.redhat.com//browse/OCM-8925) | test: automate id:72166 set and get config via rosacli
log : https://privatebin.corp.redhat.com/?458f7ca868bd01d0#9VYMCfxQBosZ3Z7adRv2uhecKHxsNGjaXySnXriJheTD
> OCM-8925 | test: automate id:72166 set and get config via rosacli

- tests/e2e/rosa_autoscaler_test.go
- tests/e2e/test_rosacli_idp_user.go
- tests/utils/exec/rosacli/machinepool_service.go
output log :- https://privatebin.corp.redhat.com/?78a700adc58a9997#5u7ReAc4vu46dTpnzpRkDsUT4s28d458HkJeZzzmETgm
> OCM-9225 | test: fixing id:36128,67348,72195 hcp ci fix

- pkg/info/info.go
https://issues.redhat.com/browse/OCM-9116
> OCM-9116 | chore: update next release to 1.2.43

- tests/e2e/test_rosacli_policy.go
- tests/e2e/test_rosacli_upgrade.go
[OCM-9273](https://issues.redhat.com//browse/OCM-9273) | test: fix id:74225 and id:73731.
Log: https://privatebin.corp.redhat.com/?2a18a1e4a63d8b8f#GzPTFN4VtCxQzUnEMKE3d8LSqh7EpwpNYABMmvV1LV5C
> OCM-9273 | test: fix id:74225 and id:73731

- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/exec/rosacli/machinepool_service.go
Update naming for Additional Security Group IDs in NodePoolDescription structure
`ginkgo run -focus 68173 tests/e2e
2.14.0
Ginkgo CLI.
If you are attempting to …
> OCM-9301 | test: updated case id:68173

- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/test_rosacli_machine_pool.go
- tests/e2e/test_rosacli_operator_roles.go
output log :- https://privatebin.corp.redhat.com/?d3d0355838e8517a#8W8Pu4LwWNREgkrqYwNFtTMiandNE8wSWsUaqZzLreDE
> OCM-9339 | test: fixing id:72195,70859 ci fix

- tests/OWNERS
> OCM-9373 | ci: Add jerichokeyne,jfrazierRH,OAharoni-RedHat to reviewers of tests package

- tests/e2e/test_rosacli_cluster_post.go
- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/common/constants/general.go
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "(38194|55979)" tests/e2e
Running Suite: ROSA CLI e2e tests suite - /Users/lixue/Workspace/rosa/tests/e2e
===============================================================================
Random Seed: 1720429192
Will run 2 of 129 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSStime="2024-07-08 17:00:46" level=info msg="Trying to list subnets of the vpc"
time="2024-07-08 17:00:46" level=info msg="Got 8 subnets"
time="2024-07-08 17:00:46" level=info msg="subnet-02e42f4dd77cbb507\t10.0.4.0/24\tus-west-2c\t"
time="2024-07-08 17:00:46" level=info msg="subnet-07c053ff25b95bfe5\t10.0.3.0/24\tus-west-2b\t"
time="2024-07-08 17:00:46" level=info …
```
> OCM-9406 | test: Automated id:55979,38194

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_machine_pool.go
output log :- https://privatebin.corp.redhat.com/?e6c95cda9d98d4c4#Au7mBM6sBgdnqwE6zcsdoT8jckg75YHt8WxKQZgoUArk
> OCM-9364 | test: automate id:36293,57102,64078

- cmd/create/externalauthprovider/externalauthprovider_suite_test.go
- cmd/create/tuningconfigs/cmd_test.go
- cmd/create/tuningconfigs/spec.json
- cmd/create/tuningconfigs/spec.yaml
- cmd/create/tuningconfigs/tuningconfigs_suite_test.go
- pkg/input/helper.go
https://issues.redhat.com/browse/OCM-5648
> OCM-5648 | feat: support both yaml and json format for tuningconfigs

- pkg/machinepool/machinepool.go
https://issues.redhat.com/browse/OCM-9340
With the new runner + testing refactor, the max-surge/max-unavailable code which was added during the development of the refactor, and was missed during rebasing
> OCM-9340 | fix: Re-add max-surge/max-unavailable code

- tests/e2e/test_rosacli_upgrade.go
[OCM-9602](https://issues.redhat.com//browse/OCM-9602) | test: fix id: 73731 for HCP cluster
> OCM-9602 | test: fix id: 73731 for HCP cluster

- cmd/edit/cmd.go
- cmd/edit/machinepool/cmd.go
- cmd/edit/machinepool/cmd_test.go
- cmd/edit/machinepool/options.go
- cmd/edit/machinepool/options_test.go
- pkg/machinepool/machinepool.go
- pkg/test/helpers.go
https://issues.redhat.com/browse/OCM-7255
> OCM-7255 | feat: Edit machinepool refactored to use new runner

- go.mod
- go.sum
- tests/ci/data/profiles/rosa-hcp.yaml
- tests/e2e/hcp_cluster_test.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_cluster_post.go
- tests/utils/config/cluster.go
- tests/utils/exec/rosacli/cluster_service.go
- tests/utils/profilehandler/data_cleaner.go
- tests/utils/profilehandler/data_preparation.go
- tests/utils/profilehandler/interface.go
- tests/utils/profilehandler/profile_handler.go
- vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/role.go
- vendor/modules.txt
[OCM-8348](https://issues.redhat.com//browse/OCM-8348)
rosa-hcp-advanced cluster preparation log :- https://privatebin.corp.redhat.com/?fdded20b7ed7b5b8#9W9dUWXHXCTk9raDpK9P268fv84NDEy3fq4ZruqEKbRk 
74433 output log :- https://privatebin.corp.redhat.com/?2fce85ae6e8bc946#6SYUBhc3F2ZuVZ2rgxEs1RGs8tZ4bVQfUoxRwZPsbv2Q 
74408|74456 output log :- https://privatebin.corp.redhat.com/?7a5e77951d31640c#DAEx3cJ2tqTMP64amqnRa4ngWYDoJbWVnzm2pUux2udL
> OCM-9152 | test: automate id:74556,74408,74433 create/edit cluster with additional allowed principals

- tests/e2e/test_rosacli_cluster.go
The testing is passed, it covers classic and hcp clusters.
Log: https://privatebin.corp.redhat.com/?64d6b14acbd8cd38#6Mu8DdeKQ9G3Hni5WNc3UoThxzjSimA4p3fP6YcR64hA
> OCM-9294 | test: automate id:53570 create cluster with IAM role path

- go.mod
- tests/e2e/hcp_tuning_config_test.go
- tests/e2e/test_rosacli_node_pool.go
- tests/utils/exec/rosacli/tuning_config_service.go
https://issues.redhat.com/browse/OCM-5648
> OCM-5648 | ci: Update ids:63164,63178,63179

- tests/e2e/test_rosacli_machine_pool.go
- tests/e2e/test_rosacli_node_pool.go
- tests/utils/exec/rosacli/machinepool_upgrade_service.go
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "(67412|57105|59430)" tests/e2e
Running Suite: ROSA CLI e2e tests suite - /Users/lixue/Workspace/rosa/tests/e2e
===============================================================================
Random Seed: 1721386246
Will run 3 of 149 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 149 Specs in 52.093 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 148 Skipped
PASS
Ginkgo ran 1 suite in 59.091257981s
lixue@Xue-Lis-MacBook-Pro rosa % echo $TEST_PROFILE
rosa-advanced
```
> OCM-8988 | test:Automated id:57105,59430,67412

- tests/e2e/hcp_cluster_test.go
ginkgo run -focus 54869 tests/e2e
2.14.0
Ginkgo CLI. …
> OCM-9282 | test: automate case id:54869

- pkg/aws/client_mock.go
- pkg/machinepool/machinepool.go
- pkg/machinepool/machinepool_mock.go
JIRA : https://issues.redhat.com/browse/OCM-9833
> OCM-9833 | fix: remove dot import from machine pools

- tests/e2e/test_rosacli_cluster_post.go
[OCM-9291](https://issues.redhat.com//browse/OCM-9291) | test: automate id:59530 create byo oidc config via rosacli
log: https://privatebin.corp.redhat.com/?162137d24ab55ec4#3xh9NQkwGqhq9VEcRJRqrX54cmzgJd6UFcP3KdBrrFfo
> OCM-9291 | test: automate id:59530 create byo oidc config cluster via rosacli

- tests/e2e/test_rosacli_cluster.go
- tests/utils/common/constants/cluster.go
- tests/utils/exec/rosacli/cluster_service.go
These are excluded until the bug related to OCP-73161 is resolved.
> OCM-9786 | test: automated cases id:73161,74656

- pkg/helper/machinepools/helpers.go
- pkg/helper/machinepools/helpers_suite_test.go
- pkg/helper/machinepools/helpers_test.go
Addressing issues for this ticket: https://issues.redhat.com/browse/OCM-10009
> OCM-10009 | feat: Adding taints effect validation

- cmd/describe/upgrade/cmd.go
- cmd/dlt/upgrade/cmd.go
- cmd/list/upgrade/cmd.go
- cmd/upgrade/machinepool/cmd.go
- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
https://issues.redhat.com/browse/OCM-3704
> OCM-3704 | fix: Update error message for create/describe/list/delete machine pool upgrade policy

- tests/e2e/test_rosacli_account_roles.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_oidc_config.go
- tests/e2e/test_rosacli_operator_roles.go
- tests/utils/common/role.go
- tests/utils/exec/rosacli/cmd_runner.go
57408,43053,74761,60956: in manual mode to create IAM roles, there is no permission on PROW CI server, fix to create temp dir and run command there.
60971: fix one changed error message
logs: https://privatebin.corp.redhat.com/?9fd73edcd716bd94#DGJNu9QdPp3bqYNoBDgKXkDhnMWKyiXcCuE4q9apqh1z
> OCM-10021 | test: fix ids:57408,43053,74761,60956,60971

- tests/utils/profilehandler/profile_handler.go
rosa-hcp-ad profile successfull creation
https://privatebin.corp.redhat.com/?21f178b9e293b6b0#EkvDUZxdtgVHkhQebYdWEN6xrg5SYK2yTbGU6hkyLrGr
> OCM-10024 | ci: fix hcp profile fail

- pkg/upgrade/upgrade.go
- pkg/upgrade/upgrade_test.go
https://issues.redhat.com/browse/OCM-10141
> OCM-10144 | fix: List upgrade for cluster asking machinepool identifier producing error

- cmd/create/cluster/cmd.go
- cmd/list/instancetypes/cmd.go
- pkg/machinepool/machinepool.go
- pkg/ocm/machines.go
[OCM-3303](https://issues.redhat.com//browse/OCM-3303)
> OCM-3303 | fix: a regression caused the external ID not to be forwarded

- tests/e2e/test_rosacli_cluster.go
[OCM-8641](https://issues.redhat.com//browse/OCM-8641) [QE] Automate OCP-68971
https://privatebin.corp.redhat.com/?a0af94b04327d375#BQ2cyp69Sg2bHCjtiUZecCKC7FgSr2Q8rUwXUTGsu7ny
> OCM-8641 | automated case id :68971

- tests/ci/data/profiles/rosa-hcp.yaml
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_cluster_post.go
- tests/utils/common/slice.go
- tests/utils/exec/rosacli/cluster_service.go
- tests/utils/profilehandler/profile_handler.go
> OCM-10274 | ci: Automate ids:75525,75535,75527,75526

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_verify.go
- tests/utils/exec/rosacli/cmd_client.go
- tests/utils/exec/rosacli/verify_service.go
[OCM-10412](https://issues.redhat.com//browse/OCM-10412) | test: automate ids:41824,74620,38851
logs: https://privatebin.corp.redhat.com/?6328769734453ea1#BHwyNamH8G3MGyhA8JfQVRrv93LUyzAHeNkVQkpf9q9M
> OCM-10412 | test: automate ids:41824,74620,38851

- tests/e2e/test_rosacli_upgrade.go
- tests/utils/exec/rosacli/upgrade_service.go
https://privatebin.corp.redhat.com/?f1d31fbe1cf5d953#6azhmYmagw7CiHnPKVE1NPUxF39WXVrbMQLZihez46w6
> OCM-9284 | test: Automate id:64187

- tests/e2e/e2e_setup_test.go
https://privatebin.corp.redhat.com/?6928f4a1036740de#125p1Gdi4S4EGXx2bryyaUKVQE3PYpHktNQ5JxvkrFfV
> OCM-10299 | ci: fix rosa-hcp-external-auth deploy failure

- tests/utils/profilehandler/data_preparation.go
[OCM-10438](https://issues.redhat.com//browse/OCM-10438) | ci: Enhance account-roles list due to a known issue
The cluster preparation step failed sometime as it fails `rosa list account-roles` as some irrelevant roles to the testing is deleted during the query. To make sure the cluster preparation can pass, add 3 try times when that issue happens
The testing with profile which needs to create account-roles is passed on local with this change.
> OCM-10438 | ci: Enhance account-roles list due to a known issue

- tests/e2e/rosa_autoscaler_test.go
- tests/e2e/test_rosacli_upgrade.go
https://privatebin.corp.redhat.com/?9533cf78ea378a6a#AufRcorrpwkAej4icdkTacT3AQMmamwFAoyBTodCrQZ4
> OCM-10479 | ci: fix id:64187,67348

- cmd/describe/upgrade/cmd.go
- cmd/dlt/upgrade/cmd.go
- cmd/edit/machinepool/cmd.go
- cmd/list/upgrade/cmd.go
- cmd/upgrade/machinepool/cmd.go
- pkg/machinepool/args.go
- pkg/machinepool/args_test.go
https://issues.redhat.com/browse/OCM-10375
> OCM-10375 | fix: update edit machinepool error message for missing identifier

- cmd/create/cluster/cmd.go
- pkg/interactive/validation.go
- pkg/interactive/validation_test.go
https://issues.redhat.com/browse/OCM-5445
> OCM-5445 | fix: Interactive installer inconsistency with choosing wrong subnets

- cmd/create/cluster/cmd.go
- cmd/create/oidcconfig/cmd.go
passes in oidc config id to oidc provider creation cmd.
> OCM-10452 | fix: Fix cluster creation with oidc provider

- cmd/create/autoscaler/autoscaler_suite_test.go
- cmd/create/autoscaler/cmd.go
- cmd/create/autoscaler/cmd_test.go
- cmd/create/cmd.go
- cmd/dlt/autoscaler/autoscaler_suite_test.go
- cmd/dlt/autoscaler/cmd.go
- cmd/dlt/autoscaler/cmd_test.go
- cmd/dlt/cmd.go
- cmd/edit/cmd.go
https://issues.redhat.com/browse/OCM-10616
refactoring on `create` and `delete` commands
work for `edit` already completed in https://github.com/openshift/rosa/pull/2376
> OCM-10616 | feat: refactoring on autoscaler commands to use new runner

- cmd/describe/cluster/cmd.go
- cmd/describe/cluster/cmd_test.go
https://issues.redhat.com/browse/OCM-9804
> OCM-9804 | fix: describe etcd KMS key when configure

- tests/e2e/test_rosacli_upgrade.go
[OCM-10633](https://issues.redhat.com//browse/OCM-10633)
> OCM-10633 | test: fix id:73731

- tests/e2e/test_rosacli_token.go
[OCM-10545](https://issues.redhat.com//browse/OCM-10545) | test: fix id: 72162
> OCM-10545 | test: fix id: 72162

- tests/e2e/test_rosacli_policy.go
[OCM-10606](https://issues.redhat.com//browse/OCM-10606) 
$ ginkgo --focus 74402 tests/e2e/
2.11.0
Ginkgo CLI. …
> OCM-10606 | test: fix id:74402

- tests/e2e/test_rosacli_cluster.go
Moving HCP test case into separate case ID.
> OCM-10530 | test: automated cases id:75916

- tests/e2e/test_rosacli_cluster.go
Successfully tested for all HCP profiles. For profile with autoscaling enabled test will not work as specific number of subnets have to be used.
> OCM-9784 | test: automate case id:72538

- pkg/machinepool/machinepool.go
Fix for regression issue https://issues.redhat.com/browse/OCM-10779
> OCM-10779 | fix: Error when setting multi-az true for HCP

- tests/e2e/test_rosacli_cluster_post.go
[OCM-10712](https://issues.redhat.com//browse/OCM-10712) | test: fix id:75210
$ ginkgo --focus 75210 tests/e2e/
2.11.0
Ginkgo CLI.
If you are attempting to test …
> OCM-10712 | test: fix id:75210

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_version.go
- tests/utils/exec/rosacli/version_service.go
https://privatebin.corp.redhat.com/?cab366c9fd23df41#AK7z6bLxqoSnQASRia3fQM4PPz756bBQuDrPFKP5jk2K
> OCM-10638 | test: Automated ids:54864,73672,66761

- tests/e2e/test_rosacli_account_roles.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_ocm_role.go
- tests/e2e/test_rosacli_operator_roles.go
- tests/e2e/test_rosacli_user_role.go
- tests/utils/common/constants/general.go
[OCM-10815](https://issues.redhat.com//browse/OCM-10815) | test: automate ids:75904,75925,75927
And add some checkpoint on 46187, 52419 for new change of [OCM-7551](https://issues.redhat.com//browse/OCM-7551)
logs: https://privatebin.corp.redhat.com/?41aa6c984a0edbe7#5gy7RznoyAf8MLCZ8JZhbx6ZKYFvgDrYT2uK5j3Hp842
> OCM-10815 | test: automated ids:75904,75925,75927

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_user_role.go
[OCM-10866](https://issues.redhat.com//browse/OCM-10866) | test: automated ids:75603,52693
logs: https://privatebin.corp.redhat.com/?6e99afdb2080c386#79rBGxc2Wi7aFLvXNLiJ8xLHq43h4oeGm8sQRQqsbNXa
> OCM-10866 | test: automated ids:75603,52693

- pkg/helper/machinepools/helpers.go
- pkg/helper/machinepools/helpers_test.go
- pkg/machinepool/helper.go
- pkg/machinepool/helper_test.go
- pkg/machinepool/machinepool.go
- pkg/machinepool/machinepool_test.go
Addressing issues in [OCM-10777](https://issues.redhat.com/browse/OCM-10777) + [OCM-10818](https://issues.redhat.com/browse/OCM-10818)
Refactored manageReplicas function + tests
> OCM-10777 | fix: fixing OCM-10777 + OCM-10818

- cmd/describe/cluster/cmd.go
https://issues.redhat.com/browse/OCM-9804
> OCM-9804 | fix: Add etcd to reduce confusion

- cmd/list/machinepool/cmd_test.go
- pkg/machinepool/machinepool.go
- pkg/machinepool/machinepool_test.go
- pkg/ocm/output/nodepools.go
- tests/utils/exec/rosacli/machinepool_service.go
https://issues.redhat.com/browse/OCM-10943
- displays disk size in list node pool cmd
- defaults to "default" which is the same as machinepool
- unit testing
> OCM-10943 | feat: show disk size in output for list node pools

- tests/e2e/classic_tuning_config_test.go
- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/hcp_tuning_config_test.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_node_pool.go
- tests/utils/config/cluster_command.go
- tests/utils/exec/rosacli/machinepool_service.go
- tests/utils/exec/rosacli/tuning_config_service.go
- [OCM-9774](https://issues.redhat.com/browse/OCM-9774)
- [OCM-10962](https://issues.redhat.com/browse/OCM-10962)
- [OCM-10999](https://issues.redhat.com/browse/OCM-11000)
**Logs**
- [54413](https://privatebin.corp.redhat.com/?5163043d0ea77051#D8t5YqmEHFBX8XP4BwMfzBGqQLogEP9e9gxNehyukCoS)
- [56783](https://privatebin.corp.redhat.com/?b41ec4593ed8d5b9#Adnm8uiWsdBgc7dmjNqCoeK7rBavwiWQtf6So6BAiJcx)
- [56786](https://privatebin.corp.redhat.com/?b814dce50532ff37#A1uVamCqd3g7aMC8XSy7dkX8iV1WTSvUmmkK8rYVaTVa)
- [76056](https://privatebin.corp.redhat.com/?37184089f7a3c548#83bgYjArrRoJiiXKNrH426w1U19RGrLBFDUk3Mccp9j5)
- [63169](https://privatebin.corp.redhat.com/?5dbae2cac9ca67f6#7dyvbUe2kfNs85oLTE5DiiqXvJUys9HbSa8oW76rZiB)
- [63174](https://privatebin.corp.redhat.com/?23491dc4a1d02efd#WTKWUYsGpdWA …
> OCM-9774 | ci: Automate ids:54413,56783,56786,63169,63174,76056

- tests/e2e/test_rosacli_account_roles.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_ocm_role.go
- tests/e2e/test_rosacli_operator_roles.go
Adding some missing checks to a few tests to cover new ROSACLI changes. Also fix some typos :).
> OCM-8760 | fix: update test ids: 43070, 74661

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_upgrade.go
https://privatebin.corp.redhat.com/?98af003d3b41c1da#2manFdfRoKZz5nGRP8cSUrNdVQ9cq9rMZi6X5P7gsj74
> OCM-10674 | test: automated ids:59547,62161

- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/exec/rosacli/machinepool_service.go
```
oaharoni-mac:rosa oaharoni$ ginkgo run -focus 38775 tests/e2e
Running Suite: ROSA CLI e2e tests suite - /Users/oaharoni/rosa_workspace/rosa/tests/e2e
Random Seed: 1726001029
Will run 1 of 220 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 220 Specs in 30.703 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 219 Skipped
PASS
Ginkgo ran 1 suite in 36.769029833s
```
> OCM-11026 | test: automate id 38775

- tests/e2e/test_rosacli_cluster.go
[OCM-11097](https://issues.redhat.com//browse/OCM-11097) | test: automated id:76093
log: https://privatebin.corp.redhat.com/?0450c771f234d708#CcZhmPiUStFvXPwt5k4Mm7wNqpARXJSp9hkZopFWUjxZ
> OCM-11097 | test: automated id:76093

- tests/e2e/test_rosacli_node_pool.go
https://issues.redhat.com/browse/OCM-11135
> OCM-11135 | ci: Fix id:67414

- tests/utils/profilehandler/profile_handler.go
https://issues.redhat.com/browse/OCM-11158
> OCM-11158 | ci: Fix id:75150

- tests/e2e/test_rosacli_ingress.go
- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/exec/rosacli/ingress_service.go
- tests/utils/exec/rosacli/machinepool_service.go
```
oaharoni-mac:rosa oaharoni$ ginkgo run -focus 38780 tests/e2e
Running Suite: ROSA CLI e2e tests suite - /Users/oaharoni/rosa_workspace/rosa/tests/e2e
Random Seed: 1726237441
Will run 1 of 225 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 225 Specs in 4.240 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 224 Skipped
PASS
Ginkgo ran 1 suite in 9.97428125s
```
```
oaharoni-mac:rosa oaharoni$ ginkgo run -focus 38783 tests/e2e
Running Suite: ROSA CLI e2e tests suite - …
```
> OCM-11069 | test: Automate OCP-38780 and OCP-38783

- cmd/describe/cluster/cmd.go
- cmd/describe/cluster/cmd_test.go
https://issues.redhat.com/browse/OCM-7315
> OCM-7315 | feat: describe client support for configurable registries

- tests/e2e/test_rosacli_cluster.go
SSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 226 Specs in 608.138 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 225 Skipped
PASS
Ginkgo ran 1 suite in 10m13.9482415s
> OCM-11264 | test: automated cases id:71174

- pkg/aws/policies.go
- pkg/aws/policies_test.go
[OCM-11295](https://issues.redhat.com//browse/OCM-11295)
> OCM-11295 | fix: adjust check for policy tags

- cmd/create/cluster/cmd.go
- cmd/edit/cluster/cmd.go
- cmd/rosa/structure_test/command_args/rosa/create/cluster/command_args.yml
- cmd/rosa/structure_test/command_args/rosa/edit/cluster/command_args.yml
- pkg/clusterregistryconfig/flags.go
- pkg/clusterregistryconfig/flags_test.go
- pkg/clusterregistryconfig/registryconfig_suite_test.go
- pkg/clusterregistryconfig/specRegistryAdditionalTrustedCa.json
- pkg/clusterregistryconfig/specRegistryAdditionalTrustedCaInvalid.json
- pkg/ocm/clusters.go
- pkg/ocm/clusters_test.go
- pkg/ocm/helpers.go
- pkg/ocm/helpers_test.go
- pkg/ocm/registry_config.go
- pkg/ocm/registry_config_test.go
https://issues.redhat.com/browse/OCM-7315
> OCM-7315 | feat: create and edit client support for configurable registries

- pkg/clusterregistryconfig/flags.go
- pkg/clusterregistryconfig/flags_test.go
[OCM-7315](https://issues.redhat.com//browse/OCM-7315)
> OCM-7315 | fix: when classic topology return nil

- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/test_rosacli_cluster.go
- https://issues.redhat.com/browse/OCM-11001
- https://issues.redhat.com/browse/OCM-11002
**Logs**
- [78314](https://privatebin.corp.redhat.com/?9166c2bede646771#87yEFWG6EjzsmNcYj5aF6sEgZHBbKSyAkApFsbyyEvNv)
- [71319](https://privatebin.corp.redhat.com/?9c581fe0918fc43d#5E2p6VJ7KHw397Kev3aai4a9ZVw9ZAYnb4sHUJc2C6Kc)
> OCM-11001 | ci: Automate id:71319,73814

- cmd/describe/ingress/cmd_test.go
- cmd/describe/ingress/options.go
- cmd/dlt/ingress/cmd.go
- cmd/edit/ingress/cmd.go
- tests/e2e/test_rosacli_ingress.go
[OCM-10846](https://issues.redhat.com//browse/OCM-10846)
> OCM-10846 | fix: adjust error message for ingress identifier

- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/test_rosacli_machine_pool.go
- tests/utils/constants/cluster.go
- tests/utils/exec/rosacli/cluster_service.go
- tests/utils/exec/rosacli/machinepool_upgrade_service.go
https://issues.redhat.com/browse/OCM-11000
> OCM-11000 | ci: Automate ids:67149,76200

- tests/e2e/rosa_autoscaler_test.go
https://privatebin.corp.redhat.com/?876ba90cd27f59f7#8QFjRUuHizq3gNWdVbJ1LtzcgXBgQYjjysFVznMFCe9o
> OCM-11350 | ci: fix id:67275

- tests/e2e/test_rosacli_version.go
(ansible-2.9) msmigiel@msmigiel-thinkpadp1gen5:~/Documents/rosa$ ginkgo run -focus 38810 tests/e2e
Running Suite: ROSA CLI e2e tests suite - /home/msmigiel/Documents/rosa/tests/e2e
=================================================================================
Random Seed: 1727175905
Will run 1 of 230 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 230 Specs in 20.817 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 229 Skipped
PASS
Ginkgo ran 1 suite in 24.600103581s
> OCM-11297 | test: automated cases id:38810

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_oidc_provider.go
- tests/e2e/test_rosacli_operator_roles.go
- tests/e2e/test_rosacli_policy.go
- tests/e2e/test_rosacli_user_role.go
[OCM-11464](https://issues.redhat.com//browse/OCM-11464) | ci: update some cases importance
- 74225 C ->M
- 52580 C->M
- 45742 C->M
- 43046 C->M
- 43051 C->M
> OCM-11464 | ci: update some cases importance

- cmd/describe/cluster/cmd.go
- cmd/describe/cluster/cmd_test.go
- cmd/edit/cluster/cmd.go
- pkg/clusterregistryconfig/flags.go
- pkg/ocm/registry_config.go
- pkg/ocm/registry_config_test.go
https://issues.redhat.com/browse/OCM-11413
https://issues.redhat.com/browse/OCM-11405
https://issues.redhat.com/browse/OCM-11402
https://issues.redhat.com/browse/OCM-11404
> OCM-11405 | fix: A few bug fixes for registry config

- cmd/create/cmd.go
- cmd/create/decision/cmd.go
- cmd/create/decision/cmd_test.go
- cmd/create/decision/decision_suite_test.go
- cmd/rosa/structure_test/command_args/rosa/create/decision/command_args.yml
- cmd/rosa/structure_test/command_structure.yml
- go.mod
- pkg/ocm/accessrequests.go
- pkg/test/helpers.go
https://issues.redhat.com/browse/OCM-7780
https://issues.redhat.com/browse/OCM-7781
add `rosa create decision` command to support approve/deny access request
> OCM-7780 | feat: support approve/deny access request in ROSA CLI

- cmd/create/cluster/cmd.go
- cmd/describe/cluster/cmd.go
- cmd/describe/cluster/cmd_test.go
- cmd/edit/cluster/cmd.go
- pkg/clusterregistryconfig/flags.go
- pkg/clusterregistryconfig/flags_test.go
https://issues.redhat.com/browse/OCM-11467
https://issues.redhat.com/browse/OCM-11413
https://issues.redhat.com/browse/OCM-11404
https://issues.redhat.com/browse/OCM-11399
> OCM-11467 | fix: A few more bug fixes for registry config

- pkg/ocm/helpers.go
https://issues.redhat.com/browse/OCM-11484
> OCM-11482 | fix: loosen registry regex check

- cmd/create/cluster/cmd.go
Supports adding SGs to HCP clusters in day 1
Currently, CS has a disabled feature toggle, so this change allows the feature to work, but it will not work until the toggle is enabled
> OCM-6053 | feat: Day1 SG support for HCP

- tests/e2e/hcp_external_auth_test.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_kubelet_config.go
- tests/e2e/test_rosacli_node_pool.go
- tests/e2e/test_rosacli_upgrade.go
https://privatebin.corp.redhat.com/?74e67533b21548ba#CxbboKWiPA7FWh7LT1tpEoANPYjFt6iiPeB4wnwoxSK ---> output_log
> OCM-11553 | ci: fix id:73754,63179,74430,72538,37177,62161,73018

- tests/utils/profilehandler/data_preparation.go
- tests/utils/profilehandler/interface.go
- tests/utils/profilehandler/profile_handler.go
https://issues.redhat.com/browse/OCM-11589
Revert https://github.com/openshift/rosa/pull/2475
> OCM-11589 | ci: Revert 4.17 policy workaround

- tests/e2e/test_rosacli_cluster_post.go
https://issues.redhat.com/browse/OCM-11611
> OCM-11611 | ci: Fix id:75525

- tests/e2e/hcp_cluster_test.go
https://privatebin.corp.redhat.com/?c3213f53676be6f7#ErQ7P2pip2EDwQnxPbMtozhA6JGr5XdZwbzhV51rkJnT
> OCM-10279 | test: automate id:75534

- tests/e2e/hcp_cluster_test.go
- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/rosa_autoscaler_test.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_cluster_post.go
- tests/e2e/test_rosacli_operator_roles.go
- tests/e2e/test_rosacli_upgrade.go
- tests/e2e/test_rosacli_version.go
Closes [OCM-8739](https://issues.redhat.com//browse/OCM-8739)
> OCM-8739 | test: fix for cluster configure file error

- tests/ci/data/profiles/rosa-hcp.yaml
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_cluster_post.go
- tests/utils/exec/rosacli/cluster_service.go
- tests/utils/profilehandler/profile_handler.go
https://privatebin.corp.redhat.com/?b1def00116ed2430#CR4XLQMv1rxJY1dCPq4zw5ettqqbshycHdY3Gm8Y9jkQ 
https://privatebin.corp.redhat.com/?1387d9706913e2e7#7YocMGtV7aJDA2Jq6zza7QbTY352gMcGFTBmHXPs1JYX
> OCM-11609 | test: updated id:68971,68172

- tests/e2e/test_rosacli_region.go
Test output:
```
$ ginkgo run -focus id:34950 tests/e2e/
Running Suite: ROSA CLI e2e tests suite - /home/jericho/work/repos/rosa/tests/e2e
=================================================================================
Random Seed: 1727380075
Will run 1 of 235 specs
SSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 235 Specs in 2.828 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 234 Skipped
PASS
Ginkgo ran 1 suite in 4.13106253s
```
> OCM-9940 | test: automated id:34950 check available regions

- pkg/options/network/create.go
JIRA: [OCM-11707](https://issues.redhat.com/browse/OCM-11707) | Fixing help message typo
> OCM-11707 | fix: Fixing typo

- tests/e2e/test_rosacli_cluster.go
https://privatebin.corp.redhat.com/?7755f067a5cc0d1a#GZwehUhqh3tU3MfFHjVR37cWy7jisGZTsiZjtA7jL6xr
> OCM-11710 | ci: fix id:38770

- cmd/describe/cluster/cmd.go
- cmd/describe/cluster/cmd_test.go
Use tech preview to determine if the describe cluster command should show if a cluster is zero-egress enabled.
> OCM-11565 | fix: include zero egress status in cluster describe command

- pkg/clusterregistryconfig/flags.go
- pkg/clusterregistryconfig/flags_test.go
https://issues.redhat.com/browse/OCM-11496
> OCM-11496 | fix: Change language when updating cluster reg config

- cmd/upgrade/machinepool/cmd.go
- cmd/upgrade/machinepool/cmd_test.go
[OCM-11559](https://issues.redhat.com//browse/OCM-11559)
> OCM-11559 | fix: first check if pool exists

- tests/e2e/test_rosacli_cluster.go
https://privatebin.corp.redhat.com/?075691d0459cf459#ARZVyHCrJVsvDqif7B5dMT7m4UnrDyHuFGj9Kw1AR88K
> OCM-11730 | ci: fix id:75534

- cmd/initialize/cmd.go
https://issues.redhat.com/browse/OCM-6408
> OCM-6408 | fix: fix error in rosa init

- cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
Fixing issue [OCM-11732](https://issues.redhat.com/browse/OCM-11732)
> OCM-11732 | fix: AvailabilityZoneCount creates correct amount of resources

- cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
Reapplying accidentally removed tags to public + private subnets
[OCM-11732](https://issues.redhat.com/browse/OCM-11732)
> OCM-11732 | fix: Reapplying tags

- cmd/create/accountroles/creators_test.go
- cmd/edit/cluster/cmd.go
- cmd/edit/cluster/cmd_test.go
https://issues.redhat.com/browse/OCM-11480
> OCM-11480 | fix: not exit when user choosing N for registry config

- cmd/upgrade/cluster/cmd.go
- cmd/upgrade/operatorroles/cmd.go
- cmd/upgrade/roles/cmd.go
- pkg/helper/roles/helpers.go
- pkg/helper/roles/helpers_test.go
- pkg/ocm/helpers.go
- pkg/test/helpers.go
https://issues.redhat.com/browse/OCM-10874
> OCM-10874 | feat: validate role managed policies for cluster upgrade

- tests/ci/data/profiles/rosa-hcp.yaml
- tests/e2e/hcp_cluster_test.go
- tests/utils/config/cluster.go
- tests/utils/exec/rosacli/cluster_service.go
- tests/utils/helper/certificate.go
- tests/utils/profilehandler/interface.go
- tests/utils/profilehandler/profile_handler.go
https://privatebin.corp.redhat.com/?4b0ec56662225e26#6NPK452LPawA7KqdgsQ68ih8EWB7tmbkPGfHKh6Tqqn
> OCM-10805 | test: automated ids:76394,76395

- cmd/create/network/cmd.go
[OCM-12101](https://issues.redhat.com/browse/OCM-12101)
> OCM-12101 | fix: Adding log outputs for empty values

- cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
[OCM-11969](https://issues.redhat.com/browse/OCM-11969) - Rearranged creation order to fix endpoint subnet connectivity issues
> OCM-11969 | fix: Rearranging creation order to fix endpoint issue

- OWNERS
Adding dmoskale to rosa cli approvers
> OCM-12179 | feat: adding dmoskale to rosa cli approvers

- tests/e2e/hcp_external_auth_test.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_network_verifier.go
https://privatebin.corp.redhat.com/?c85561520da5ae82#37zoiu1zER8VLgAGSYEF3i4MgXdsHcjUjoZxhpifg4Cn
> OCM-12117 | test: automated ids:70370,76396,77149,72602

- cmd/config/get/get.go
- cmd/login/cmd.go
- cmd/whoami/cmd.go
- pkg/config/config.go
- pkg/fedramp/flag.go
Adding extra validation to check the valid fields are present in the ocm.json file verifying the user is logged in.
[OCM-10677](https://issues.redhat.com/browse/OCM-10677)
> OCM-10677 | feat: Adding extra validation to verify user is logged in

- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/test_rosacli_account_roles.go
- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_upgrade.go
- tests/e2e/test_rosacli_user_role.go
- tests/utils/exec/rosacli/machinepool_service.go
- tests/utils/helper/role.go
- tests/utils/profilehandler/interface.go
- tests/utils/profilehandler/profile_handler.go
https://issues.redhat.com/browse/OCM-10273
[Logs](https://privatebin.corp.redhat.com/?de0dd8e28c96789b#3wGapaubzY2LMnsPzF9K7KbwRkg3P8wzyuhXAKUqMHFX)
> OCM-10273 | ci: Automate id:75536

- tests/e2e/test_rosacli_cluster.go
- tests/e2e/test_rosacli_upgrade.go
https://privatebin.corp.redhat.com/?5b8f1b42307ce585#2kXXwkSgJaox3UcnT5u8bdGjQbc9jxe6f6wnSCahszKU
> OCM-11911 | ci: fix id:75927,55883

- cmd/create/network/cmd.go
- pkg/options/network/create.go
[OCM-12479](https://issues.redhat.com/browse/OCM-12479)
> OCM-12479 | fix: Fixed help message for binary builds

- cmd/describe/cluster/cmd_test.go
Tests which have a bug in the backend are blocking merge in ROSA CLI
> OCM-12664 | fix: Disable failing tests which are blocking merge

- pkg/config/config.go
[OCM-12815](https://issues.redhat.com/browse/OCM-12815)
Make sure user can login with Token, SA and auth code
> OCM-12815 | fix: Removing refresh token to be a validation requirement

- cmd/dlt/accountroles/cmd.go
- pkg/aws/policies.go
Relies on https://github.com/openshift/rosa/pull/2656 - cannot merge until this is merged
> OCM-12872 | feat: Manual mode for deleting hcpsharedvpc account role policies

- tests/e2e/test_rosacli_account_roles.go
[OCM-12892](https://issues.redhat.com//browse/OCM-12892) | test: automate id:77829 create and delete shared-vpc acr in auto mode
Log: https://privatebin.corp.redhat.com/?5bb712ccc74c5e4f#7AcS7LMcmZB7Ww1YRLD65myfxst7fe8qr811qRDSN1bB
> OCM-12892 | test: automate id:77829 create and delete shared-vpc acr in auto mode

- cmd/create/network/cmd.go
- cmd/create/network/cmd_test.go
[OCM-13094](https://issues.redhat.com/browse/OCM-13094)
> OCM-13094 | feat: Adding extra info message for user to specify template-dir when calling custom template

- pkg/machinepool/machinepool.go
- pkg/machinepool/machinepool_test.go
[OCM-10147](https://issues.redhat.com/browse/OCM-10147)
> OCM-10147 | feat: removing validation for no changes on np

- pkg/machinepool/machinepool.go
- pkg/machinepool/machinepool_test.go
> Revert "OCM-10147 | feat: removing validation for no changes on np"

- pkg/machinepool/machinepool.go
- pkg/machinepool/machinepool_test.go
Cherry pick of https://github.com/openshift/rosa/pull/2733
> [release_1.2.49] OCM-10147 | feat: removing validation for no changes on np

- tests/e2e/test_rosacli_account_roles.go
- tests/e2e/test_rosacli_cluster_post.go
- tests/e2e/test_rosacli_operator_roles.go
- tests/utils/exec/rosacli/cluster_service.go
- tests/utils/helper/role.go
automate ids:78240,77962,77910,77866 for shared vpc hosted cluster features.
logs:
https://privatebin.corp.redhat.com/?a6a616abc619826e#8PtckaReeVgvyVK1ufyrPkoXXfojcKJ4xQfr4uzagYN6
> OCM-13595 | test: automate ids:78240,77962,77910,77866

- tests/utils/handler/resources_handler_prepare.go
When setup cluster on local, it will fail to create cluster as the dns-domain is not parsed correctly when the rosacli is not the latest version, the warning message of the latest rosacli version makes the parsing failed.
With the fix in PR, it works well now, see the log https://privatebin.corp.redhat.com/?26238d340c8a147c#BK6i3oDAytzBH1L2V48B6qnbkhGdhHrT26Hu9ULL2982
> OCM-14022 | ci: improve the dns-domain parsing in the cluster setup step to avoid failure

- tests/e2e/test_rosacli_cluster.go
Fix the failed cases found in https://redhat-internal.slack.com/archives/C0519LZH1RA/p1739456749806909
- 38770 : skip the profile with autoscaler enabled as the test step in this case will not cover
- 68971: Use the latest OCP version for this case,rather than the hardcode 4.14 version to avoid failure as the EOL version and update one expected error message
> OCM-14054 | test: fix ids: 38770,68971

- cmd/edit/autoscaler/cmd.go
- cmd/edit/autoscaler/cmd_test.go
- pkg/clusterautoscaler/flags.go
- pkg/clusterautoscaler/validation.go
- pkg/ocm/clusterautoscaler.go
Supports the following flags:
```
MaxNodesTotal
maxPodGracePeriod: With default of 600 seconds 
maxNodeProvisionTime: With default of 15 minutes
podPriorityThreshold: default is -10
```
Other flags used will result in an unsupported error from CS.
Tests in place to ensure validation works
> OCM-13947 | feat: Support editing HCP cluster autoscaler

- cmd/create/autoscaler/cmd.go
- cmd/describe/autoscaler/cmd.go
- cmd/dlt/autoscaler/cmd.go
- cmd/edit/autoscaler/cmd.go
- pkg/clusterautoscaler/flags.go
Adds new `Long` help messages for various autoscaler commands to provide info on which ones HCP is supported by
> OCM-14135 | feat: Change help messages for autoscaler cmds

- tests/e2e/rosa_autoscaler_test.go
automate id:79846, the new feature of OCM-12463, autoscaler on hosted-cp cluster.
log is here: https://privatebin.corp.redhat.com/?002cb9c0da6afee4#6pgpV75XrcwRqRozm6xwEvkZjAWV4iRCwe5ZnP1eHxyC
> OCM-14215 | test: automate id:79846 Edit/describe hosted-cp cluster autoscaler and validations for autoscaler operations

- tests/e2e/e2e_setup_test.go
https://privatebin.corp.redhat.com/?205ccfbf365bea65#5rxHCEmdN3iWpppGMdNCpq4uJukHkwqv6TPWd9tYEKdz
> OCPQE-28357 | ci: update the secret value

- tests/e2e/rosa_autoscaler_test.go
automated id:79848 Validation info/error about the MaxNodeLimit and MaxNodeLimitation
log: https://privatebin.corp.redhat.com/?b1a72aa165741ecf#JwrE86xgp1K91zi4DKEX1fTdfKLMdCLFhGkG7bTAndd
> OCM-14250 | test: automated id:79848 Validation info/error about the MaxNodeLimit and MaxNodeLimitation

- cmd/create/cluster/cmd.go
Removes gates on the flag + interactive mode of creating an HCP cluster for govcloud env
> OCM-13383 | feat: Enable creating HCP cluster in govcloud

- tests/e2e/test_rosacli_oidc_config.go
Updated to find the issuer URL when the location doesn't have the full URL present
> OCM-14377 | test: fix id:64620

- tests/e2e/hcp_cluster_test.go
~70370,75504,75536 - Increasing timeouts~
76394 - Replace all spaces with commas, not just the first one (to build the correct list string)
> OCM-14555 | test: fix ids: 76394

- tests/ci/config/config.go
- tests/ci/data/profiles/rosa-classic.yaml
- tests/ci/data/profiles/rosa-hcp.yaml
- tests/ci/labels/runtime.go
- tests/e2e/e2e_setup_test.go
- tests/utils/handler/cluster_handler.go
- tests/utils/handler/interface.go
- tests/utils/handler/profile.go
https://privatebin.corp.redhat.com/?c017c76af01d242d#8NLqy92VJPuGitCV8DETRmYGJ3Q7gQN8WmtjxAYU9aKb
> OCM-13976 | ci: adjust some configures to support OCP E2E jobs

- cmd/create/network/cloudformation.go
- cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
Closes https://issues.redhat.com/browse/OCM-14946
Closes https://issues.redhat.com/browse/OCM-14947
Closes https://issues.redhat.com/browse/OCM-14948
> OCM-14948| fix: Fix AZ conditions

- cmd/edit/cluster/cmd.go
This is to allow automation of migrating many clusters, for customers with large suites still using `SDN OpenShift` network type. The behavior is also slight improved without `-y` - originally you were still always asked twice whether or not you wanted to perform the migration. This was unintended and not great UX. This MR resolves this as well
> OCM-15159 | feat: Introduce `-y` for migrating cluster network type

- tests/e2e/test_rosacli_cluster.go
[OCM-15192](https://issues.redhat.com//browse/OCM-15192) | test: automate id:81399 edit cluster channel group
logs: https://privatebin.corp.redhat.com/?89986fd14524b6a9#8EzCSw9xy9c7SG7nKxC35RDxyq9gXKWbmZyyFNws9L4f
> OCM-15192 | test: automate id:81399 edit cluster channel group

- tests/e2e/e2e_setup_test.go
Add the real external auth provider in release [repo](https://github.com/openshift/release/pull/63327)
Remove the fake one
> OCM-14088 | ci: Remove the fake external auth provider

- cmd/create/accountroles/cmd.go
- cmd/create/accountroles/creators.go
- cmd/create/accountroles/creators_test.go
- cmd/create/cluster/cmd.go
- cmd/create/cluster/validation.go
- cmd/create/cluster/validation_test.go
- cmd/create/operatorroles/by_prefix.go
- cmd/dlt/accountroles/cmd.go
Removes gating for HCP govcloud features and fixes all known problems around it
> OCM-13374 | feat: Enable HCP in govcloud environments

- .tekton/hcp-advanced-e2e-test.yaml
- .tekton/steps/clean-up-step.yaml
- .tekton/steps/run-e2e-day1-step.yaml
- .tekton/steps/run-e2e-day2-step.yaml
- .tekton/tasks/e2e-clean-up-task.yaml
- .tekton/tasks/e2e-task.yaml
- Delete some extra params and add some missing ones
- Update container-image temporarily until "quay.io/redhat-user-workloads/rh-terraform-tenant/rosa:latest" exists
- Fix some params typo
- Some update on the scripts of the steps
> OCM-15880 | ci: Remove extra param service from integration test

- cmd/create/cluster/cmd.go
- cmd/create/cmd.go
- cmd/create/oidcconfig/cmd.go
- cmd/register/oidcconfig/cmd.go
https://issues.redhat.com/browse/OCM-16191
Wrong OIDC Provider import introduced in https://github.com/openshift/rosa/pull/2896
> OCM-16191 | fix: Wrong OIDC Provider import

- pkg/ocm/clusters.go
Only edit's the new `cluster`'s config with `ingresses[0].listening` (default ingress listening method) when HCP + non-fedramp to fix a bug where classic clusters failed to create
> OCM-16303 | fix: Only supply ingresses[0].listening when HCP

- .tekton/hcp-advanced-e2e-test.yaml
- .tekton/steps/clean-up-step.yaml
- .tekton/steps/export-resources-record-step.yaml
- .tekton/steps/run-e2e-day1-step.yaml
- .tekton/steps/run-e2e-day2-step.yaml
- .tekton/tasks/e2e-clean-up-task.yaml
- .tekton/tasks/e2e-task.yaml
-  Share konflux_resources.json via results to be used for cleanup step
- Update scripts by removing steps to setup tools which have included in the image
> OCM-16509 | ci: Some updates for the hcp-advance-e2e-test pipeline

- pkg/info/info.go
> Revert "OCM-15967 | chore: Bump version to 1.2.54"

- tests/e2e/test_rosacli_cluster.go
- 68971 :HCP has no version lower than 4.14.41, removing the checkpoint of HCP;for classic, don't use the fixed version avoid version changed
- 45509: New change, expexted error message should be updated
- 76481: Enhancement to set account-roles in the command to create cluster to avoid failure of account roles
The logs on local is https://privatebin.corp.redhat.com/?232395238cc957fd#HcVLNRQe5v71pkEUPeqP7fSnBQ4CYia7FcFMUaUug4U4
> OCM-16813 | test: fix ids: 68971,45509,76481

- go.mod
- go.sum
- tests/prow_ci.sh
- tests/utils/handler/resources_handler_clean.go
- vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/client.go
- vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/eip.go
- vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/network_interface.go
- vendor/github.com/openshift-online/ocm-common/pkg/test/kms_key/kms.go
- vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/instance.go
- vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/nat_gateway.go
- vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/vpc.go
- vendor/modules.txt
1. [OCM-15737](https://issues.redhat.com//browse/OCM-15737): Add a new func rosa_login_with_clinet() to support login with client id and secret
2. Update ocm-common version
> OCM-15737 | ci: add a new func rosa_login_with_clinet()

- pkg/version/version.go
> Revert "OCM-17058 | feat: Update mirror and base releases folder URI"

- pkg/fedramp/config.go
Fixes bug where URL alias validation for fedramp was broken
> OCM-17311 | fix: Fix broken map for loop

- cmd/create/cluster/cmd.go
- cmd/describe/cluster/cmd.go
- cmd/edit/cluster/cmd.go
- pkg/arguments/arguments.go
- pkg/ocm/clusters.go
- tests/utils/handler/cluster_handler.go
> Revert "OCM-17719 | feat: Deprecate user workload monitoring toggle"

- tests/ci/labels/features.go
- tests/e2e/test_rosacli_image_mirror.go
- tests/utils/exec/rosacli/cmd_client.go
- tests/utils/exec/rosacli/image_mirror_service.go
Automate OCP-84761 for [OCM-17876](https://issues.redhat.com//browse/OCM-17876)
local log: https://privatebin.corp.redhat.com/?6f44c8f861068a89#AjcyR3h6WDsSNadDP7D3SJwfjS6pKxfwTtvrTYicFwJE
> OCM-18510 | test: automate id:84761

- cmd/create/cluster/cmd.go
- tests/e2e/test_rosacli_cluster.go
Reverts openshift/rosa#3033
Accidentally merged an in-progress MR when I meant to merge a finished one from Lucas. Reverting so he can re-make the MR
> Revert "OCM-17465 | fix: created verification to when subnets are not set on proxy"
