cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/cmd.go

This reverts commit 5283ce9191fd7f275a40db9111bd5fcfbabcd353.

Revert "OCM-2653 | fix: Create operator-roles - hide hosted cp managed policies

---

cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/commandbuilder/helper/roles/roles.go
pkg/aws/helpers.go
pkg/aws/sts.go

Update the adequate policy for the shared VPC flow.

OCM-3049 | feat: upgrade operator roles for the shared VPC flow

---

cmd/list/operatorroles/cmd.go
pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/OCM-3152

OCM-3152 | fix: show roles with missing policies and order by prefix

---

cmd/create/operatorroles/by_prefix.go
pkg/aws/helpers.go
pkg/aws/policies.go

Multiple operator roles point to the same policy.
When creating a new set of operator roles with the `--shared-vpc-role-arn` flag provided, 
we need to ensure the ingress operator role is updated with the new policy.

OCM-3143 | Create operator-roles - ensure shared VPC policy

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/cmd.go
cmd/create/machinepool/machinepool.go
cmd/list/machinepool/machinepool.go
pkg/helper/helpers.go
pkg/interactive/validation.go

When creating a new machine pool (during a day 2 operation), we can now
set the size of the root disk.
```
$ rosa list machinepools -c 258idq729qn7g8ltl01vjsiopopf8lmi
ID            AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONES    SUBNETS    SPOT INSTANCES  DISK SIZE
Default       No           2         m5.xlarge                          us-west-2a                       N/A             256 GiB
mp-ocm-15     No           2         m5.xlarge                          us-west-2a                       No              128 GiB
no-disk-size  No           2         m5.xlarge                          us-west-2a                       No              default
```
In the above output:
* Default: represents the default mp and the cluster spec has the size
set to 256
* …

OCM-15 | feat: ability to set machine pool root disk size 

---

pkg/ocm/helpers.go
pkg/ocm/helpers_test.go

When the disk size is parsed with a very large value input by the user it will return 9223372036854775807 which is the largest size of a 64bit integer. This is still valid and should not return an error.
Signed-off-by: Sébastien Han <seb@redhat.com>

OCM-3178 | fix: accept int64 max value for disk size

---

cmd/register/oidcconfig/cmd.go
pkg/aws/helpers.go
pkg/constants/oidc_config.go
pkg/interactive/validation.go

Related issue: https://issues.redhat.com/browse/OCM-2423

OCM-2423 | fix: interactively validate issuer url and secret arn

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-1081
After fix allows to go through but hits preflight from backend
```
E: Creating cluster 'gdb-test' should fail: Role 'arn:aws:iam::xxx:role/ManagedOpenShift-HCP-ROSA-Installer-Role' has hosted CP managed policies. Creating a Classic cluster with hosted CP managed policies isn't allowed. Please create a new set of account roles with Classic ROSA policies
```

OCM-1081 | fix: checks hcp role tag in all flows

---

pkg/aws/policies.go

Related issue: https://issues.redhat.com/browse/OCM-1338

OCM-1338 | fix: use utility function to retrieve acc role suffix

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-1209

OCM-1209 | feat: add warning and prompt to continue when subnets are not found

---

cmd/describe/cluster/cmd.go

We should always show value for http tokens and currently backend (cause of backward compatibility issues) will still return value as empty string

OCM-2892 | fix: Adding default value of http tokens metadata for describe command

---

cmd/dlt/machinepool/machinepool.go
cmd/edit/machinepool/machinepool.go
cmd/list/machinepool/machinepool.go

[OCM-23](https://issues.redhat.com//browse/OCM-23): Removing default pool from rosa cli
Worker pool is added to ocm and it will match cluster nodes values, we should not show default pool anymore

OCM-23 | feat: Removing default pool from rosa cli

---

cmd/create/cluster/cmd.go

[OCM-2906](https://issues.redhat.com//browse/OCM-2906) | fix: ROSA CLI for IMDSv2 - Help displays same prompt instead of anything helpful

OCM-2906 | fix: ROSA CLI for IMDSv2 - Help displays same prompt instead of anything helpful

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/cmd.go

Improve the new flags help messages to provide more info to the user.
```
oadler@fedora:rosa (OCM-3297)$ ./rosa create cluster --help | grep shared-vpc
--shared-vpc-role-arn string                          AWS IAM role ARN with a policy attached, granting permissions necessary to create and manage Route 53 DNS records in private Route 53 hosted zone associated with intended shared VPC.
oadler@fedora:rosa (OCM-3297)$ ./rosa create operator-roles --help | grep shared-vpc
--shared-vpc-role-arn string    AWS IAM role ARN with a policy attached, granting permissions necessary to create and manage Route 53 DNS records in private Route 53 hosted zone associated with intended shared VPC.
oadler@fedora:rosa (OCM-3297)$ ./rosa create cluster --help | grep hosted-zone-id
--private-hosted-zone-id …
```

OCM-3297 | feat: improve help message for the shared VPC flow

---

cmd/create/cluster/cmd.go
cmd/initialize/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-3322

OCM-3322 | fix: add empty default ingress attribute in config for rosa init

---

cmd/edit/ingress/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-3284

OCM-3284 | fix: allow to choose load balancer type for sts clusters

---

cmd/create/operatorroles/cmd.go
pkg/ocm/helpers.go

Related issue: https://issues.redhat.com/browse/OCM-3318

OCM-3318 | fix: use latest policies if user version is empty

---

OWNERS

Remove users outside our org from being approvers and sort usernames.

OCM-3285 | ci: Clean up OWNERS file

---

cmd/dlt/autoscaler/cmd.go
cmd/dlt/cmd.go
pkg/ocm/clusterautoscaler.go

Adresses [OCM-210](https://issues.redhat.com/browse/OCM-210).
This PR should allow for the delete functionality of the cluster autoscaler configuration. This functionality was moved out of #1371 but is related.
/cc @osherdp

OCM-210 | Delete cluster autoscaler functionality

---

cmd/create/machinepool/nodepool.go
cmd/describe/upgrade/cmd.go
cmd/describe/upgrade/cmd_test.go
cmd/describe/upgrade/main_test.go
cmd/dlt/upgrade/cmd.go
cmd/dlt/upgrade/cmd_test.go
cmd/dlt/upgrade/main_test.go
cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/nodepool.go
cmd/list/upgrade/cmd.go
cmd/list/upgrade/cmd_test.go
cmd/list/upgrade/main_test.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/cluster/cmd_test.go
cmd/upgrade/cmd.go
cmd/upgrade/machinepool/cmd.go
cmd/upgrade/machinepool/cmd_test.go
cmd/upgrade/machinepool/main_test.go
pkg/helper/versions/helpers.go
pkg/helper/versions/helpers_test.go
pkg/ocm/hypershift_upgrades.go
pkg/ocm/nodepools_upgrades.go
pkg/test/helpers.go

Adds support for HyperShift node pool upgrades:
- upgrade machinepool
- delete upgrade
- describe upgrade
- list upgrade 
Marking also as deprecated the version change in editing machinepools.
Related: [OCM-954](https://issues.redhat.com//browse/OCM-954)
Upgrade UX design document: https://docs.google.com/document/d/15S3TXJXu6_iUJFDFT-mpcUp2uC4cWVKwZbt_bwgwqZ4/edit#

OCM-954 | Feat: Hypershift node pool upgrades

---

cmd/create/cluster/cmd.go

When using the new autoscaler params, some of them have a default of true. It makes it impossible to distinguish the two states when providing the arguments via CLI (in oppose to the interactive mode).
For example, when running ``rosa create cluster
--autoscaler-balance-similar-node-groups`` or just ``rosa create cluster`` the same result happens, where ``balance-similar-node-groups`` is set to true for the two cases.

OCM-3331 | fix: default values for boolean fields of autoscaler

---

cmd/create/cluster/cmd.go

Because of a redundant check, this parmeters is not configurable from the interactive mode for cases where the user didn't set it via CLI (``--autoscaler-scale-down-utilization-threshold``).
I also fixed the validation because it wasn't actually been tested.
The changes for ``delay-after-*`` parameters are mainly refactoring. If a parameter has not been set it's also necessarily empty so checking ``string == ""`` is pretty much redundant.

OCM-3353 | fix: utilization-threshold missing from interactive mode

---

cmd/create/machinepool/nodepool.go
cmd/upgrade/machinepool/cmd.go

In interactive mode when creating/editing node pools, the version is required.
By default the user will be presented with the cluster version if he didn't specify an existing version, but he can't skip the choice anymore.

OCM-3361 | fix: in interactive mode, version is required for node pools

---

cmd/describe/cluster/cmd.go

[OCM-3336](https://issues.redhat.com//browse/OCM-3336): Describe cluster compute node shows wrong value as we should not look on cluster.nodes.compute anymore

OCM-3336 | fix: Describe cluster compute node shows wrong value as we should not look on cluster.nodes.compute anymore

---

pkg/ocm/versions.go

Related issue: https://issues.redhat.com/browse/OCM-3377

OCM-3377 | fix: only show warning message about EOL if there is an EOL timestamp

---

cmd/create/cluster/cmd.go

Related issue: https://issues.redhat.com/browse/OCM-3390

OCM-3390 | fix: better warning message for RH managed vpc

---

cmd/edit/cluster/cmd.go
cmd/edit/cluster/cmd_test.go
cmd/edit/cluster/main_test.go
pkg/test/helpers.go

When switching cluster visibility to private, also OAuth becomes private and this can impact applications behind the public ingress using OAuth (e.g. OpenShift console). So add a warning for this in case the cluster is HCP and the user has public ingress.
Related: [OCM-1154](https://issues.redhat.com//browse/OCM-1154)
Examples:
non HCP cluster (no change)
```
rosa edit cluster -c 25pc7psbfn5j9juleu6in6857jvs03p2 -i
I: Interactive mode enabled.
Any optional fields can be ignored and will not be updated.
? Restrict master API endpoint to direct, private connectivity. You will not be able to access your cluster until you edit network settings in your cloud provider. To also change the privacy setting of the application router endpoints, use the 'rosa edit ingress' command.
? Private cluster …
```

OCM-1154 | feat: add warning message for public ingress when switching HCP cluster visibility

---

pkg/output/output.go

This change sets a default to the output print function, to catch any non concrete types passed to output. 
https://issues.redhat.com/browse/OCM-3404 
Original issue, of not being able to handle listing operator roles 
```
$ rosa list operator-roles --prefix cse2etests -o json
I: Fetching operator roles
[
{
"Name": "cloud-credential-operator-iam-ro-creds",
"Namespace": "openshift-cloud-credential-operator",
"Version": "4.14",
"RoleName": "cse2etests-openshift-cloud-credential-operator-cloud-credential-",
"RoleARN": "arn:aws:iam::501358428071:role/cse2etests-openshift-cloud-credential-operator-cloud-credential-",
"Policy": [
"oadler-openshift-cloud-credential-operator-cloud-credential-oper"
]
},
{
"Name": "cloud-credentials",
"Namespace": "openshift-cloud-network-config-controller", …
```

OCM-3404 | fix: handle output for listing operator roles

---

cmd/verify/network/cmd.go
cmd/verify/network/cmd_test.go

The `--watch` loop needs to continue on both "pending" and "running"

OCM-3418 | fix: handle verify network 'running' state

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go

Provide more info to the user about the command default flow.

OCM-3439 | fix: add info message to create account roles

---

cmd/edit/cluster/cmd.go

The warning is always displayed in non interactive mode, so this help user discover the possible impacts of this change.
Current form
```
Private cluster (optional): [? for help] (y/N)
```
After this change
```
Private cluster, check this command's help for possible impacts (optional): [? for help] (y/N)
```
Related: [OCM-3428](https://issues.redhat.com//browse/OCM-3428)

OCM-3428 | fix: inform user about visibility change impact in interactive mode

---

cmd/edit/machinepool/nodepool.go

In interactive mode, we should not exit if no upgrade is available but just skip the version part.
Related: [OCM-3444](https://issues.redhat.com//browse/OCM-3444)

OCM-3444 | fix: edit nodepool was broken if no upgrade available

---

cmd/create/cluster/cmd.go

In case of invalid mode, the command will not be run
```
./rosa create cluster --sts --mode atuo
E: Invalid mode. Allowed values are [auto manual]
```

OCM-1478 | fix: Moved getMode to top of cluster creation so it checks mode firstly

---

cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/common_utils.go
pkg/aws/client.go
pkg/aws/policies.go

Operator roles' policies are associated with the installer role prefix. In case the operator role policy already has `sts:AssumeRole` action with shared VPC role ARN, and the user provides a different shared VPC role ARN, error out, and guide the user to use a different account role ARN.
**Note:** Currently the command overrides the shared VPC role ARN value with the value provided by the user.
Examples:
1. User create operator roles outside of the shared VPC scope:
2. User overrides the policy created in [1], while creating operator roles with shared VPC role ARN:
(A new policy version is created with a `sts:AssumeRole` permission)
3. The user tries to create operator roles with the same installer role from [2] with a different **shared-vpc-role-arn** and is prompted to use a different …

OCM-3473 | fix: create operator-roles for shared VPC

---

cmd/create/cluster/cmd.go

We clarify the "usage" description of the flag '--worker-disk-size' to highligh that this is affecting the default worker machine pool.
Signed-off-by: Sébastien Han <seb@redhat.com>

OCM-2898 | fix: more accuracy to --worker-disk-size

---

cmd/upgrade/cluster/cmd.go
cmd/upgrade/cluster/cmd_test.go

we should be able to schedule an automatic control plane upgrade even if no upgrade is currently available.
Improve testing to cover this scenario and remove hardcoded JSON for easier mantainance.
Related: [OCM-3478](https://issues.redhat.com//browse/OCM-3478)

OCM-3478 | fix: automatic control plane upgrade when no update is available

---

cmd/create/cluster/cmd.go
pkg/clusterautoscaler/flags.go
pkg/ocm/clusterautoscaler.go
pkg/ocm/clusters.go
pkg/ocm/validators.go
pkg/ocm/validators_test.go

In order to make code less repetitive when we add day2 support of cluster-autoscaler (and also to reduce the amount of code in ``cmd/create/cluster/cmd.go``), this refactors the code to be placed in new modules that are also more easily imported by new commands.
In the step 2 of this we want to add a ``rosa create autoscaler`` command that will use the new location of the code

OCM-3313 | refactor: extract autoscaler code to new modules

---

cmd/create/cluster/cmd.go
cmd/edit/ingress/cmd.go
pkg/helper/versions/helpers.go
pkg/ocm/clusters.go
pkg/ocm/helpers.go
pkg/ocm/versions.go

Related issue: https://issues.redhat.com/browse/OCM-3381

OCM-3381 | fix: adjust so that it doesn't show new ingress attributes when not supported

---

pkg/clusterautoscaler/flags.go

1000 is way over the number of nodes we're currently supporting in OpenShift (it's rather 180 for most versions).
Changing the value to make it more sensible.

OCM-3535 | fix: set max-nodes-total default value to 180

---

pkg/clusterautoscaler/flags.go

When creating autoscaler interactively, the cores range is being compared wrongly. For example, when given the value 99 it will try to compare it with the default value of 100:
```
$ rosa create cluster 
...
? Maximum number of cores to deploy in cluster: [? for help] (100)
<giving it 99>
X Sorry, your reply was invalid: max value must be greater or equal than
min value 100.
```
FYI @sunzhaohua2 
/cc @gdbranco @ciaranRoche

OCM-3574 | fix: cores range validation

---

cmd/edit/autoscaler/cmd.go
cmd/edit/cmd.go
pkg/clusterautoscaler/flags.go
pkg/interactive/interactive.go
pkg/ocm/clusterautoscaler.go

Adding the option to edit an autoscaler for a cluster as a day2 operation, in two ways:
* Via CLI options, e.g.:
```
rosa edit autoscaler --cluster=mycluster
--balance-similar-node-groups
--log-verbosity 3
...
```
* Interactively. If user used `-i` or `--interactive` or provided no argument of autoscaler configuration, then the different options will be requested one-by-one. For example:
```
$ rosa edit autoscaler --cluster=mycluster
? Balance similar node groups (optional): Yes
? Skip nodes with local storage (optional): [? for help] (y/N)
...
```

OCM-3313 | feat: add 'rosa edit autoscaler' command

---

cmd/describe/cluster/cmd.go

Workload monitoring will either say `Enabled` if it is enabled, `Disabled` if it is disabled, or `Unknown` if the check fails for whatever reason

OCM-3375 | feat: Add 'Workload Monitoring' to describe/cluster

---

cmd/create/machinepool/nodepool.go
cmd/edit/machinepool/nodepool.go
pkg/helper/machinepools/helpers.go
pkg/helper/machinepools/helpers_test.go

As part of https://issues.redhat.com/browse/OCM-2522 backend work.
This PR updates the validation of machine pool replicas for hosted clusters on day 2.
Non autoscaling machine pools support zero replicas, meanwhile, machine pools with autoscaling must validate at least one replica.
Related to https://issues.redhat.com/browse/OCM-3397

OCM-3397 Support machine pools with zero replicas on day two

---

README.md

Updated installation document to work with go1.20
Make sure rosa-cli installs on go1.20

OCM-3280 | fix: Updated installation document

---

hack/build-release.sh

Related issue: https://issues.redhat.com/browse/OCM-2418

OCM-2418 | chore: build arm64 as part of release flow

---

cmd/list/accountroles/cmd.go
cmd/list/addon/cmd.go
cmd/list/instancetypes/cmd.go
cmd/list/machinepool/nodepool.go
cmd/list/ocmroles/cmd.go
cmd/list/oidcprovider/cmd.go
cmd/list/region/cmd.go
cmd/list/upgrade/cmd.go
cmd/list/user/cmd.go
cmd/list/userroles/cmd.go
cmd/list/version/cmd.go
pkg/aws/helpers.go
pkg/ocm/addons.go
pkg/output/output.go

This PR adds support for the `-o` output flag on all `rosa list` commands. The following approach has been taken when working through this:
- When the user specifies the `-o` flag, we prefer to print the raw API response and do not include any interpretation of the data provided by the tabulated output if the user does not use the `-o` flag
- If there are no results returned by the list command, we ensure an empty JSON array or YAML list is returned and not a log message saying "there are no results"

[OCM-2907] Add support for json/yaml output format on all "rosa list" commands

---

cmd/create/accountroles/cmd.go
pkg/aws/client.go

This MR accomplishes 2 things with `create accountroles`:
1. Return an error when AWS caller is a govcloud account
2. Disable prompt for asking if user if they'd like to create HCP roles when AWS caller is a govcloud account

OCM-3609 | feat: Disable prompt & flag for HCP while using a govcloud account

---

cmd/edit/autoscaler/cmd.go

Examples were wrong and were referring to autoscaler creation.

OCM-3641 | fix: edit autoscaler examples

---

pkg/clusterautoscaler/flags.go
pkg/ocm/validators.go
pkg/ocm/validators_test.go

Make it impossible to use negative duration strings, as they are not allowed in our fields.

OCM-3650 | fix: negative durations are allowed

---

cmd/create/autoscaler/cmd.go

Instead of getting the error from the server, we can check for autoscaler existance right at the start.

OCM-3643 | fix: check if autoscaler already exists before creation

---

cmd/create/autoscaler/cmd.go
cmd/create/cluster/cmd.go
cmd/edit/autoscaler/cmd.go
pkg/clusterautoscaler/flags.go

When not enabling autoscaling feature, the cluster-autoscaler is still being created due to us not unsetting the autoscaler configuration for that case.
Also, we were missing including the prefix for the arguments, which made us miss detecting that autoscaler options were used. This should also be fixed now.

OCM-3640 | fix: autoscaler created when not enabled

---

pkg/clusterautoscaler/flags.go

Trying to be more similar to the kubernetes default values, but instead we allow 180 nodes in OCM clusters rather than 5000 in kubernetes.
See: https://github.com/kubernetes/autoscaler/blob/632512c9dfdf18caebd55a9652d455c6c68ad496/cluster-autoscaler/config/const.go#L20-L23

OCM-3616 | fix: resource limits range defaults

---

cmd/create/autoscaler/cmd.go
cmd/create/cluster/cmd.go
cmd/dlt/autoscaler/cmd.go
cmd/edit/autoscaler/cmd.go

When creating a HCP cluster, or when handling it in day2 operations, `rosa`` CLI allows handling of cluster-autoscaler resource even though it's not yet supported.
This displays an error and exits the program for those cases.

OCM-3677 | fix: cluster-autoscaler enabled for HCP

---

pkg/ocm/clusters.go

Previously, the machine type will only be applied if the root disk size was set during cluster creation.

OCM-3614: fix machine type when using disk size

---

pkg/helper/machinepools/helpers.go
pkg/helper/machinepools/helpers_test.go

This PR allows users to remove all existing labels on a MachinePool when using interactive mode on the CLI. It aligns functionality with normal mode where the user passes an empty string  `""` to remove all existing labels e.g `rosa update machinepool -c rblake-test --labels="" mp-1`
Existing labels on a MachinePool can now be removed by the user by entering the `""` string in interactive mode when prompted for the new labels.

OCM-2385 | fix: Allow users to reset machinepool labels in interactive mode

---

cmd/upgrade/roles/cmd.go

This PR updates the help message on the `rosa upgrade role` command to be consistent and not talk about account-wide IAM roles.

OCM-3203 | fix: Update help message on rosa upgrade role command to be consistent

---

cmd/create/machinepool/nodepool.go

HCP control plane version needs to be hcp enabled versions. For HCP node pools instead, node pool version can be any version which is rosa enabled. This is already checked at upgrade time, we now align also the behaviour at creation time.
Related: [OCM-3737](https://issues.redhat.com//browse/OCM-3737)

OCM-3737 | fix: align version computation create machinepool for HCP

---

cmd/create/cluster/cmd.go
pkg/aws/policies.go
pkg/aws/tags/utils.go

Related issue: https://issues.redhat.com/browse/OCM-3392
```
? Install into an existing VPC (optional): Yes
W: The following subnets were excluded because they belong to a VPC that is managed by Red Hat: [subnet-xxx, subnet-xxx, subnet-xx, subnet-xxx, subnet-xxx, subnet-xxx, subnet-xxx, subnet-xxx, subnet-xxx, subnet-xxx, subnet-xxx, subnet-xxx]
W: The following subnets have been excluded because they do not fit into chosen CIDR ranges: [subnet-xxx, subnet-xxx]
```

OCM-3392 | fix: don't show RH managed VPC options when selecting subnets

---

cmd/create/cluster/cmd.go
cmd/create/cluster/shared_vpc.go
pkg/aws/helpers.go

1. If the user didn't provide all the flags for the shared VPC flow, default to interactive mode.
2. Display AWS owner ID alongside the subnet selection.
Subnet selection:
```
? Install into an existing VPC (optional): Yes
W: Some subnets have been excluded because they do not fit into chosen CIDR ranges
? Subnet IDs (optional):  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter, ? for more help]
> [ ]  subnet-0457887d7b27a56d3 ('disktest-bthz8-public-us-east-1a','vpc-04df95f8a614f7851','us-east-1a', Owner ID: '501358428071')
[ ]  subnet-04a42219d1aa4297b ('disktest-bthz8-private-us-east-1a','vpc-04df95f8a614f7851','us-east-1a', Owner ID: '501358428071')
[ ]  subnet-0be38de5605f1c4ad ('','vpc-05c422525aadd0731','us-east-1a', Owner ID: '962993289388')
[ ] …
```

OCM-3267 | feat: Add interactive mode for shared VPC

---

cmd/create/cluster/cmd.go
pkg/interactive/interactive.go

https://issues.redhat.com/browse/OCM-2083
Prompts during interactive mode with a default value should not be called "optional". The only prompt type that was violating this is the "boolean" type (y/n).

OCM-2083 | fix: prompts with default value are not 'optional'

---

cmd/create/cluster/shared_vpc.go

Improve the info message and include a link to documentation.

OCM-3840 | fix: improve create cluster in shared VPC info message

---

cmd/list/cluster/cmd.go
pkg/aws/client.go
pkg/aws/client_test.go
pkg/aws/policies.go
pkg/ocm/clusters.go
pkg/ocm/clusters_test.go

This PR adds the flag `--account-role-arn` to the `rosa list cluster` command to supporting listing clusters that are using the specified role.
When a user specifies the role of an ARN via the flag, we:
1. Lookup the Role to see if it exists
2. If the Role exists, check the `type` of the role
3. Perform a query to the `/api/clusters_mgmt/v1/clusters` endpoint, setting the query string to look for the role based upon the role type

OCM-1625 | feat: Add the ability to list clusters using an Account Role

---

cmd/create/cluster/cmd.go

[OCM-3873](https://issues.redhat.com//browse/OCM-3873) | fix: change references to default machine pool to worker machine pool

OCM-3873 | fix: change references to default machine pool to worker machine pool

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/machinepool.go

Related issue: [OCM-3833](https://issues.redhat.com//browse/OCM-3833)

OCM-3833 | fix: only go interactive on non hcp

---

cmd/create/cluster/cmd.go

Include the AWS client in the error message.
e.g
`E: Could not find the following subnet provided in region 'us-east-1': subnet-0bf9e87908dcc6155`

OCM-1448 | fix: improve subnet not found error message

---

cmd/describe/machinepool/machinepool.go
cmd/list/machinepool/machinepool.go

Related issue: [OCM-4140](https://issues.redhat.com//browse/OCM-4140)

OCM-4140 | fix: use output print slice instead of helper

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/machinepool.go

Related issue: [OCM-4128](https://issues.redhat.com//browse/OCM-4128)

OCM-4128 | fix: validate sgs flag out of byo vpc

---

cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/cmd.go

Adding support to create operator roles after cluster creation. 
The shared VPC role ARN is available as part of the cluster spec.

OCM-3526 | feat: create operator roles for shared VPC with cluster key

---

cmd/create/admin/cmd.go
cmd/create/cluster/cmd.go
cmd/create/idp/htpasswd.go

Covers fixes for both cards:
[OCM-3831](https://issues.redhat.com//browse/OCM-3831), [OCM-3293](https://issues.redhat.com//browse/OCM-3293)
**Initial Issue:**
The `rosa describe admin -c <cluster_id>` command is unable to find the idp that has the admin user, even though the admin user was created previously.
Returned response:
"There is no admin on cluster '%s'. To create it run the following command:\n"+
" rosa create admin -c %s"
Expected response:
"There is an admin on cluster '%s'. To login, run the following command:\n"+
" oc login %s --username %s"
**Reason**
For commands:
`rosa create admin` - always created admin username "cluster-admin" under the htpasswd IDP named "Cluster-Admin"
`rosa create cluster `--cluster-admin-user` - required users to generate admin username not equal …

OCM-3831 | fix: 'rosa describe admin' cannot find 'cluster-admin' htpasswd idp and user (updated)

---

cmd/create/cluster/cmd.go

Please see two separate calls
In Day 1 cluster create, it now properly forces the flag `--enable-autoscaling` if any of the autoscaling flags are used.

OCM-3366 | fix: force --enable-autoscaling flag when autoscaling flags are used

---

cmd/create/cluster/cmd.go
cmd/create/service/cmd.go
pkg/aws/client.go
pkg/aws/client_test.go

This PR updates the `getInitialValidSubnets` function in the `rosa create cluster` command to consider the list of subnets passed as a command line argument by the user via the `--subnet-ids` switch.
The `getInitialValidSubnets` function treats the subnets specified via `--subnet-ids` as the only ones it check, rather than pulling and checking all available subnets (which is the cause of the erroneous warning). The function still checks if any of the subnets specified by the user via `--subnet-ids` are Red Hat managed and will print the warning if they are.

OCM-4123 | fix: Remove unnecessary warning messages about Red Hat owned subnets when user explicitly specifies subnets to use

---

cmd/create/cluster/cmd.go
pkg/ingress/flags.go

Related issue: [OCM-3884](https://issues.redhat.com//browse/OCM-3884)

OCM-3884 | fix: validate version and HCP default ingress attributes

---

cmd/edit/ingress/cmd.go

Related issue: [OCM-4257](https://issues.redhat.com//browse/OCM-4257)
A validation to /labels for HCP clusters was recently added and call needs to be refactored to skip HCP clusters

OCM-4257 | fix: doesn't check /labels for HCP

---

.github/merge_request_template/Default.md

Added a new template for merge request's on the ROSA repo.
[OCM-2864](https://issues.redhat.com/browse/OCM-2864)
example of what it will look like :
Please include a link to the JIRA
Please include a link to the design document if there is one 
associated with these changes
Please describe the changes in this PR
Please describe how to test these changes

OCM-2864 | feat: Added default push request template

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/nodepool.go
cmd/describe/machinepool/cmd_test.go
cmd/describe/upgrade/cmd_test.go
cmd/list/upgrade/cmd.go
cmd/list/upgrade/cmd_test.go
cmd/list/version/cmd.go
cmd/upgrade/cluster/cmd.go
cmd/upgrade/cluster/cmd_test.go
cmd/upgrade/machinepool/cmd.go
cmd/upgrade/machinepool/cmd_test.go
pkg/helper/versions/helpers.go
pkg/helper/versions/helpers_test.go
pkg/ocm/helpers.go
pkg/ocm/versions.go
pkg/test/helpers.go

We need to handle HCP versions in the backend side and they may also depend on the customer.
To obtain this, the current change:
1) introduces the use of an HCP specific version endpoint 
2) switch all the available upgrades calls to what is available in the cluster or the node pool API response, as this is the source of truth. This will ensure that the list is the correct one and reduce the number of calls in the client needed to get the version properties.
Functionally there should be no change.
Improved also the testing to use always SDK objects instead of raw JSON which will help test clarity and mantainence.
Related: [OCM-3911](https://issues.redhat.com//browse/OCM-3911)

OCM-3911 | feat: use HCP specific endpoints for versions and upgrades

---

cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/nodepool.go

Disallow changing the version directly from the edit command as we have now the new flow with rosa upgrade machinepool available for everybody.
The command was already deprecated and it was meant to be a temporary solution.
Related: [OCM-4336](https://issues.redhat.com//browse/OCM-4336)

OCM-4336 | feat: disable edit machinepool --version command

---

pkg/ocm/versions.go
pkg/ocm/versions_test.go

Fixes version validation on upgrade scenarios where cluster upgrades from a prerelease version:
```
$ ./rosa upgrade cluster -c ying-hcp-b --control-plane
? IAM Roles/Policies upgrade mode: auto
? Version: 4.14.0
E: Expected a valid version to upgrade cluster to.
Valid versions: [4.14.0, 4.14.0-rc.5, 4.14.0-rc.6, 4.14.0-rc.7]
```

OCM-4571 | fix: Validate upgrade versions from prerelease scenarios

---

cmd/upgrade/cluster/cmd.go
pkg/ocm/versions.go
pkg/ocm/versions_test.go

Fixing another helper for version validation:
https://issues.redhat.com/browse/OCM-4571?focusedId=23365966&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23365966

OCM-4571 | fix: Fix CheckAndParseVersion when coming from preRelease

---

cmd/create/cluster/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/aws/policies_test.go

When the user creates a cluster in interactive mode and selects classic ROSA topology, the CLI should display only classic account roles. HCP account roles are not compatible with classic ROSA clusters.
```
oadler@fedora:rosa (OCM-4644)$ rosa list account-roles 
I: Fetching account roles
ROLE NAME                                 ROLE TYPE      ROLE ARN                                                                 OPENSHIFT VERSION  AWS Managed
croche-ControlPlane-Role                  Control plane  arn:aws:iam::501358428071:role/croche-ControlPlane-Role                  4.13               No
croche-Installer-Role                     Installer      arn:aws:iam::501358428071:role/croche-Installer-Role                     4.13               No
croche-Support-Role …
```

OCM-4644 | fix: Create cluster - filter classic ROSA account roles

---

cmd/create/cluster/cmd.go

In case there are no version-compatible account roles or an incomplete set, include the desired OCP minor version in the error message.
No version-compatible account roles set found: 
```
oadler@fedora:rosa (OCM-4666)$ rosa create cluster --dry-run true
? Cluster name: oadler
? Deploy cluster with Hosted Control Plane: No
? Create cluster admin user: No
? Deploy cluster using AWS STS: Yes
W: --sts flag won't be necessary if you wish to use STS.
W: --non-sts/--mint-mode flag will be necessary if you do not wish to use STS.
? OpenShift version: 4.14.1
? Configure the use of IMDSv2 for ec2 instances optional/required: optional
W: No compatible account roles with version '4.14' found. You will need to manually …
```

OCM-4666 | fix: Create cluster - improve no account roles found message

---

cmd/dlt/cmd.go
cmd/dlt/kubeletconfig/cmd.go
pkg/interactive/confirm/confirm.go
pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go

This PR adds support for the `rosa delete kubeletconfig` sub-command.

OCM-4376 | feat: Added the `rosa delete kubeletconfig` sub-command

---

cmd/create/cmd.go
cmd/create/kubeletconfig/cmd.go
pkg/interactive/validation.go
pkg/interactive/validation_test.go
pkg/kubeletconfig/consts.go
pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go

This PR adds support for the `rosa create kubeletconfig` sub-command.

OCM-3854 | feat: Added `rosa create kubeletconfig` sub-command

---

cmd/create/cluster/cmd.go
pkg/aws/client.go
pkg/aws/policies.go
pkg/aws/policies_test.go

When the user is creating an HCP cluster in interactive mode, display only roles with HCP-managed policies.
**Note:** The user can still provide classic role ARNs via flags (will be enabled for some organizations in the backend).
```
oadler@fedora:rosa (OCM-4687)$ rosa create cluster --hosted-cp
? Cluster name: oadler-nov-6
? Deploy cluster with Hosted Control Plane: Yes
I: NOTE: Hosted control planes are currently in Technology Preview (https://access.redhat.com/support/offerings/techpreview). Any Technology Preview clusters will need to be destroyed and recreated prior to general availability.
? Billing Account: 765374464689
I: Using '765374464689' as billing account.
? OpenShift version: 4.13.18
? Installer role ARN: …
```

OCM-4687 | feat:Create HCP cluster - filter classic roles

---

cmd/verify/network/cmd.go

Related issue: [OCM-4724](https://issues.redhat.com//browse/OCM-4724)

OCM-4724 | feat: allow non sts clusters to verify network

---

cmd/edit/cmd.go
cmd/edit/kubeletconfig/cmd.go
pkg/kubeletconfig/consts.go
pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go

This PR introduces the `rosa edit kubeletconfig` sub-command.

OCM-4375 | feat: Added `rosa edit kubeletconfig` sub-command

---

pkg/helper/machinepools/helpers.go
pkg/helper/machinepools/helpers_test.go

https://issues.redhat.com/browse/OCM-1323
This PR allows users to remove all existing taints on a MachinePool when using interactive mode on the CLI.

OCM-1323 | fix: Allow users to reset mp taints

---

cmd/create/cluster/cmd.go
cmd/upgrade/accountroles/cmd.go
pkg/ocm/products.go
pkg/ocm/products_test.go

This PR shows the technology preview messages for hcp dynamically.
Two open questions:
- I don't find a good solution for the "Tech preview" messages in the init(), so, I guess the simple solution is to remove them as it is expected this feature will be part of the 1.2.30 release.
- I think we have to decide if the technology preview should be "explicit" meaning that if there is no entry, it can be considered GA (that would simplify the logic).
cc @andreadecorte

OCM-4675 | feat: show dynamically technology preview messages for hcp

---

cmd/create/accountroles/cmd.go

Forgotten in https://github.com/openshift/rosa/pull/1592

OCM-4675 | fix: remove technology preview from command help

---

cmd/create/kubeletconfig/cmd.go
cmd/dlt/kubeletconfig/cmd.go
cmd/edit/kubeletconfig/cmd.go

This PR ensures that we are consistent across all `rosa kubeletconfig` commands to output what the user has entered for the `-c` flag when printing command output. We were previously switching between cluster name e.g `rblake-test` and cluster id, which is slightly confusing.

OCM-4782 | fix: Ensure we display what the user entered for '-c' flag on KubeletConfig command output

---

cmd/create/cluster/cmd.go

This is a hotfix for the ROSA CLI version.
Before the HCP GA, the "--billing-account" should be optional and not requested.
Note that this logic is not removed from master branch, as the 1.2.31 version should be available for HCP GA.

OCM-4792 | fix: do not ask billingAccount for hcp before GA

---

pkg/kubeletconfig/config.go
pkg/kubeletconfig/config_test.go
pkg/kubeletconfig/consts.go

This PR introduces a sensible default for PIDs limit in interactive mode when creating a `KubeletConfig`.
It also sets the default to `0` on `--pod-pids-limit` to remove the confusing `-1` appearing as a default when running `rosa help create/edit kubeletconfig`.

OCM-4812 | fix: Provide sensible default for PIDs limit in interactive mode

---

cmd/create/accountroles/creators.go

Issue was that the default flow for creating account roles became `doubleRolesCreator` -- meaning it created both unmanaged & managed HCP roles. For govcloud, we just want unmanaged, not both. This MR aims to accomplish this.

OCM-2453 | fix: FedRAMP create accountroles fix

---

cmd/create/accountroles/cmd.go

[OCM-4588](https://issues.redhat.com//browse/OCM-4588) | fix: remove suggestion to 'create oidc-config' during 'create account-roles'
Suggestion was to remove prompt to create oidc-config

OCM-4588 | fix: remove suggestion to 'create oidc-config' 

---

cmd/dlt/cluster/cmd.go

https://source.redhat.com/groups/public/ocm_team/ocm_blog/using_the_best_effort_flag_for_enabling_problematic_cluster_deletion

OCM-4505 | fix: elaborate on --best-effort help description

---

cmd/verify/network/cmd.go
cmd/verify/network/cmd_test.go
pkg/ocm/verify_network.go

Adds a `--tags` flag to `rosa verify network` that allows users to supply custom tags to the on-demand network verification API
https://issues.redhat.com/browse/OCM-4767

OCM-4767 | feat: add custom tags flag to rosa verify network

---

cmd/create/cluster/cmd.go

Fedramp was filtering out both non-HCP and HCP versions when using stable as the channel-group
This fix only filters out non-HCP when not creating an HCP cluster

OCM-4877 | fix: Return versions when create cluster in fedramp

---

cmd/create/machinepool/machinepool.go

Related issue: [OCM-4888](https://issues.redhat.com//browse/OCM-4888)

OCM-4888 | fix: only asks for sgs if not been set in interactive

---

cmd/create/oidcconfig/cmd.go
cmd/create/operatorroles/by_prefix.go
cmd/register/oidcconfig/cmd.go
pkg/interactive/roles/roles.go

When the user creates operator roles using prefix and provides an installer role ARN in interactive mode, display only account roles with HCP-managed policies.
```
oadler@fedora:rosa (OCM-4898)$ rosa create operator-roles --oidc-config-id 27jpdr1kb66f6fkpkql6b384ckpqs62q --prefix oadler-nov-20 --hosted-cp
? Role creation mode: auto
? Operator roles prefix: oadler-nov-20
? Create hosted control plane operator roles: Yes
? Installer role ARN:  [Use arrows to move, type to filter, ? for more help]
arn:aws:iam::765374464689:role/ming-local-HCP-ROSA-Installer-Role
arn:aws:iam::765374464689:role/ming-staging-HCP-ROSA-Installer-Role
arn:aws:iam::765374464689:role/new-prefix-HCP-ROSA-Installer-Role
> …
```

OCM-4898 | fix: create HCP operator roles by prefix - filter by policy

---

cmd/create/operatorroles/by_prefix.go

Add an info message guiding the user to use the same installer role for cluster creation.
e.g.
```
oadler@dhcp-0-129:rosa (OCM-4924)$ rosa create operator-roles --prefix oadler-nov-22
? Role creation mode: auto
? Operator roles prefix: oadler-nov-22
? OIDC Configuration ID: 25mar6dtg943vg319du08o2k5bcnmb61 | https://d3gt1gce2zmg3d.cloudfront.net/25mar6dtg943vg319du08o2k5bcnmb61
? Create hosted control plane operator roles: No
? Installer role ARN: arn:aws:iam::765374464689:role/bla/oadler-nov-22-Installer-Role
? Permissions boundary ARN (optional): 
I: ARN path '/bla/' detected in installer role 'arn:aws:iam::765374464689:role/bla/oadler-nov-22-Installer-Role'. This ARN path will be used for subsequent created operator roles and policies.
I: Reusable …
```

OCM-4924 | fix: improve info message for create operator roles

---

cmd/create/cluster/cmd.go

Related issue: [OCM-807](https://issues.redhat.com//browse/OCM-807)

OCM-807 | fix: do not allow fips flag for HCP

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/helpers.go

Separate the function into two new functions, `generateOperatorRolePolicies` and `generateAccountRolePolicies`.
Reduce the number of parameters passed to the function.
**Note:** Previously two booleans were passed to `GeneratePolicyFiles` to generate operator or account roles files, always one of the booleans was set to false.
e.g. 
```
func GeneratePolicyFiles(reporter *rprtr.Object, env string, generateAccountRolePolicies bool,
generateOperatorRolePolicies bool...
```

OCM-5023 | feat: Refactor `GeneratePolicyFiles` to simplify code

---

cmd/create/operatorroles/by_prefix.go

https://issues.redhat.com/browse/OCM-4883
There was an issue where if a use creates a cluster using classic role, but using operator roles that uses hcp roles. There will be a mismatch between managed/unmanaged policies, thus upgrade will fail.
This change will allow the user to create operator roles with classic role if passes '--installer-role-arn string'

OCM-4883 | fix: fetch passed arn in all roles

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/helpers.go

Pass the map of the account roles to the generate policies function. HCP requires only three account roles (excluding control plane) while classic requires all four account roles.
e.g.
```
oadler@dhcp-0-129:rosa (OCM-4896)$ rosa create account-roles --hosted-cp --mode manual -y --prefix oadler-nov-29
I: Logged in as 'oadler.openshift' on 'https://api.stage.openshift.com'
I: Current OpenShift Client Version: 4.11.0
I: Run the …
```

OCM-4896 | fix: Create HCP trust policies in manual mode

---

cmd/verify/network/cmd.go
pkg/ocm/verify_network.go

https://issues.redhat.com/browse/OCM-5018
This issue is caused by the cluster service ignoring the custom tags and by ROSA not sending the custom tags if a cluster is provided. We have a MR in cluster service to process the custom tags properly, and this change fixes ROSA to send the tags if the user provides them.

OCM-5018 | Send custom tags when doing network verify for a cluster

---

cmd/edit/cluster/cmd.go

JIRA : https://issues.redhat.com/browse/OCM-5024 
Validation 
```
rosa edit cluster -h
Edit cluster.
Usage:
rosa edit cluster [flags]
Examples:
rosa edit cluster -c mycluster --private
rosa edit cluster -c mycluster --interactive
Flags:
-c, --cluster string                        Name or ID of the cluster.
-y, --yes                                   Automatically answer yes to confirm operation.
--private                               Restrict master API endpoint to direct, private connectivity.
--disable-workload-monitoring           Enables you to monitor your own projects in isolation from Red Hat Site Reliability Engineer (SRE) platform metrics.
--http-proxy string                     A proxy URL to use for creating HTTP connections outside the cluster. The URL scheme must be http. …
```

OCM-5024 | fix: update example command for rosa edit cluster

---

cmd/describe/cluster/cmd.go

Related issue: [OCM-1189](https://issues.redhat.com//browse/OCM-1189)

OCM-1189 | fix: add subnet info when available

---

cmd/describe/cluster/cmd.go

Related issue: [OCM-5231](https://issues.redhat.com//browse/OCM-5231)

OCM-5231 | fix: use tabs instead of spaces

---

cmd/describe/cluster/cmd.go

Related issue: [OCM-5231](https://issues.redhat.com//browse/OCM-5231)

OCM-5231 | fix: use spaces instead of \t

---

Makefile
hack/codecov.sh

This PR is the first step for adding CodeCov coverage checking to the ROSA CI pipeline. In this PR I'm simply introducing a `Makefile` target and a bash script to upload results to CodeCov. The bash script has been copied from other projects uploading to CodeCov within the `openshift` org, and then slightly adapated to match our project.
Next steps will be to update our `prow` configuration to run this on each PR and then on merges to `master` so that we have a record of our coverage statistics over time.

OCM-5621 | feat: Add codecov to CI pipeline for ROSA

---

cmd/verify/network/cmd.go
cmd/verify/network/cmd_test.go

Example output after fix
```
[davidlee@fedora rosa]$ ./rosa verify network --subnet-ids subnet-08cf62aa5b83225ef,subnet-09ae7dd300d7f9e61 --role-arn arn:aws:iam::765374464689:role/dle-stage-Installer-Role --region us-east-1 --hosted-cp --tags v1:t1
I: Verifying the following subnet IDs are configured correctly: [subnet-08cf62aa5b83225ef subnet-09ae7dd300d7f9e61]
I: subnet-08cf62aa5b83225ef, platform: hostedcluster, tags: {"Name":"osd-network-verifier","osd-network-verifier":"owned","red-hat-managed":"true","v1":"t1"}: pending 
I: subnet-09ae7dd300d7f9e61, platform: hostedcluster, tags: {"Name":"osd-network-verifier","osd-network-verifier":"owned","red-hat-managed":"true","v1":"t1"}: passed 
I: Run the following command to wait for verification to all subnets to complete:
rosa verify …
```

OCM-5312 | fix: Output platform and tags

---

cmd/create/cluster/cmd.go
pkg/interactive/interactive.go

Related issue: [OCM-4646](https://issues.redhat.com//browse/OCM-4646)

OCM-4646 | fix: better messages for options prompts

---

cmd/create/cluster/cmd.go

Related issue: [OCM-5384](https://issues.redhat.com//browse/OCM-5384)

OCM-5384 | fix: show imds param on cluster helper command

---

cmd/create/cluster/cmd.go

Related issue: [OCM-5389](https://issues.redhat.com//browse/OCM-5389)

OCM-5389 | fix: unset httpTokens for HCP

---

cmd/dlt/cluster/cmd.go

Notify the user about cloud resources that may left behind when using the 'best effort' flag.

OCM-5358 | fix: add a warning message when using best effort deletion

---

cmd/create/cluster/cmd.go

Related issue: [OCM-5404](https://issues.redhat.com//browse/OCM-5404)

OCM-5404 | fix: default HCP installer role to 'ManagedOpenshift' prefix

---

cmd/create/cluster/cmd.go

When creating a hosted CP cluster, the user must set the nodes/replicas to a minimal value of 2.
Improve the UX and provide feedback to the client.

OCM-5060 | fix:Validate min replicas for hosted cp clusters

---

pkg/info/info.go

Related issue: [OCM-5100](https://issues.redhat.com//browse/OCM-5100)

OCM-5100 | chore: bump to v1.2.33

---

pkg/aws/client_test.go
pkg/aws/policies.go

It seems like there is a redundant API call to `listPolicies`, the role's policies are fetched from AWS but not used. Removing the policies API call and the `Policy` field from the role struct.
**Note:** This change introduces an improvement when listing the roles in our AWS dev account `real	0m21.995s
-> real	0m15.018s`, we might need another iteration on this ticket.

OCM-1007 | fix: Improve list account-roles runtime

---

cmd/verify/network/cmd.go
pkg/output/output.go

Allow --output flag for  'rosa verify network' :
JSON
YAML

OCM-5400 | fix: --output flag for 'rosa verify network'

---

cmd/create/oidcprovider/cmd.go

Related issue: [OCM-5508](https://issues.redhat.com//browse/OCM-5508)
Currently there's a check if the actual provider already exists or not. Due to that there's no reason to have this condition anymore, also it is blocking customers that mistakenly delete the provider for their account

OCM-5508 | fix: remove condition that checks cluster state when creating oidc provider

---

cmd/create/machinepool/machinepool.go
cmd/verify/network/cmd.go
cmd/verify/network/cmd_test.go
pkg/helper/helpers.go

`rosa network verify` on a non-BYO VPC cluster will error with "no subnets on cluster xyz" which could be a confusing output. This PR adds a check for BYO VPC and a corresponding error, as well as moving a "IsBYOVPC" function to a common file to avoid code duplication and improve readability. There is also a unit test to verify the fix.
https://issues.redhat.com/browse/OCM-4178

OCM-4178 | fix: ROSA CLI N/W Verifier Error Message for IPI VPC Clusters

---

cmd/create/cluster/cmd.go

In rosa interactive mode, add the billing-account parameter for the future command to recreate the same cluster.

OCM-5480 | fix: add billing-account param to last command

---

cmd/list/user/cmd.go

https://issues.redhat.com/browse/OCM-4612
In the current code, the `cluster-admin` user is filtered out in `list users` output. That will lead to confusing since user selects to create that user, but cannot find it. The code is 3 years old and is used to avoid explicitly grant `cluster-admin` user to `cluster-admins` group.
But in latest implementation, the `cluster-admin` user is created and will be injected into `cluster-admins` group by default. And `grant user` command is prevented to update `cluster-admin` user's group. It's better to display `cluster-admin` user to `rosa list users` now.

OCM-4612 | fix: `list users` can list `cluster-admin` user

---

cmd/create/oidcprovider/cmd.go
cmd/create/operatorroles/by_clusterkey.go
pkg/helper/helpers.go

Related issue: [OCM-5571](https://issues.redhat.com//browse/OCM-5571)

OCM-5571 | fix: adjust message when operator roles already exists

---

cmd/create/cluster/cmd.go
pkg/ocm/clusters.go

In Hosted Control Planes, we can disable CNI at creation to let user bring their own.
This change exposes the relevant parameter with a new boolean flag.
There is an existing --network-type parameter, but decision was taken not to reuse this as it is going to be deprecated moving forward and the dedicated parameter is clearer in terms of usage.
Additional validation added in order to ensure the 2 parameters don't collide and are correctly validated.
No breaking change expected compared to the current behavior.
Related: [OCM-5530](https://issues.redhat.com//browse/OCM-5530)

OCM-5530 | feat: add new parameter to disable CNI at cluster creation for HCP

---

cmd/create/oidcprovider/cmd.go

Related issue: [OCM-5560](https://issues.redhat.com//browse/OCM-5560)

OCM-5560 | fix: resort to last cert in cert chain

---

cmd/create/machinepool/machinepool.go

This PR attempts to improve the logging when fetching the list of available instances when creating a Machine Pool.

OCM-5544 | fix: Improve logging when fetching instance type data for creation of machine pools

---

cmd/edit/addon/cmd.go

https://issues.redhat.com/browse/OCM-1305
Invalid flag (`--billing-model`) shows up in `rosa edit addon` error relating to not including the addon ID. This MR makes the help/error message identical to the `rosa edit addon -h` message

OCM-1305 | feat: UX fix for invalid flag showing up in rosa edit addon error

---

cmd/create/operatorroles/by_clusterkey.go

https://issues.redhat.com/browse/OCM-1109
Steps to Reproduce:
1. Login with the latest roascli 
2. Create rosa sts cluster in manual mode by `rosa create cluster --sts --mode manual`
3. Create operator-roles in the manual mode with the aws account which has no enough permission
rosa create operator-roles -c <cluster_id> --mode manual --profile sdqe-no-permission
Actual results:
3. It fails with error message like bellow,
E: Error getting account role version AccessDenied: User: arn:aws:iam::301721915996:user/sdqe-no-permission is not authorized to perform: iam:GetRole on resource: role QEAuto-sts-20221020-Installer-Role because no identity-based policy allows the iam:GetRole action
status code: 403, request id: 27e93c76-7535-40f0-890a-5809f7102d28
Expected results:
3. It should work …

OCM-1109 | feat: Improve create op-role UX by not checking for account role version on manual mode

---

cmd/dlt/autoscaler/cmd.go

*WHAT*
Adds a confirmation to deleting cluster autoscaler
*VALIDATION*
```
$ rosa delete autoscaler -c croche  
? Are you sure you want to delete the cluster autoscaler? Yes
I: Successfully deleted autoscaler configuration for cluster '28q7v5kffen949h6fmvdl755ist8vvmq'
$ rosa delete autoscaler -c croche -y                                                   
I: Successfully deleted autoscaler configuration for cluster '28q7v5kffen949h6fmvdl755ist8vvmq'
```
JIRA - https://issues.redhat.com/browse/OCM-5522

OCM-5522 | fix: add confirmation prompt to deleting cluster autoscaler

---

cmd/create/oidcconfig/cmd.go
cmd/create/operatorroles/cmd.go
cmd/create/operatorroles/common_utils.go
cmd/register/oidcconfig/cmd.go
pkg/arguments/arguments_suite_test.go
pkg/arguments/normalize.go
pkg/arguments/normalize_test.go
pkg/constants/oidc_config.go
pkg/interactive/roles/roles.go

Uses the `SetNormalizeFunc` to support both aligned and depreciated flags.
Validations
```
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-4958●› 
╰─$ rosa create operator-roles --role-arn arn:aws:iam::765374464689:role/15nov-HCP-ROSA-Installer-Role --prefix crtest --oidc-config-id 27meq1dc0i7h6n98fablivf90s686pa1
? Role creation mode: manual
? Operator roles prefix: crtest
? Create hosted control plane operator roles: No
? Installer role ARN:  [Use arrows to move, type to filter, ? for more help]
> arn:aws:iam::765374464689:role/15nov-Installer-Role
arn:aws:iam::765374464689:role/adecorte/ad-path-Installer-Role
arn:aws:iam::765374464689:role/crs3-Installer-Role
arn:aws:iam::765374464689:role/CSE2ETests-Installer-Role …
```

OCM-4985 | fix: align role-arn flag across commands

---

OWNERS

This PR updates the `OWNERS` file in ROSA to reflect the current members of the team. I've taken the following approach:
- All active members of the ROSA squad have been listed as `reviewers`
- I've pruned the `approvers` list to only active members of the ROSA squad
- Inactive members have been moved onto the `emeritus_approvers` list
Reading the docs for Prow OWNERS, I see no mention of the `maintainers` directive: https://www.kubernetes.dev/docs/guide/owners/ . I've therefore removed this from the`OWNERS` file and we can revert this change if it causes any problems.

OCM-5606 | chore: update OWNERS file to reflect current team members

---

cmd/create/accountroles/cmd.go

*WHAT* 
We prompt the user for classic roles if they pass the hosted cp flag. This is legacy behavior from before hosted-cp was created. This change removes the prompt if a user passes the hosted-cp param
*JIRA*
https://issues.redhat.com/browse/OCM-4648

OCM-4648 | fix: remove option to create classic roles if a user passes hosted-cp param

---

cmd/version/cmd.go

https://issues.redhat.com/browse/OCM-5542
In some restricted environments in might not be desirable to have the version command do a network call
This adds a `--client` argument to `rosa version`. The naming of the argument align with other tools like kubectl/oc. In order to preserve current behavior this defaults to `false`.

OCM-5542 | feat: add `--client` argument to `rosa version` command

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go

This PR ensures that we print `--etcd-encryption-kms-arn` and it's value in the command output in interactive mode if the user has requested `--etcd-encryption` and passed a value for `--etcd-encryption-kms-arn`

OCM-1352 | fix: Ensure that --etcd-encryption-kms-arn is printed when set and --etcd-encryption is true

---

cmd/create/cluster/cmd.go
pkg/arguments/normalize.go
pkg/arguments/normalize_test.go

*WHAT*
Adds default-mp-labels to normalize args to worker-mp-labels, this insures both arguements work as expected for adding day 1 labels to the worker pool
*VALIDATION* 
create a cluster with arg `--worker-mp-labels`
```
$ rosa create cluster --cluster-name croche --sts --role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Installer-Role --support-role-arn arn:aws:iam::765374464689:role/ManagedOpenShift-Support-Role --controlplane-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-ControlPlane-Role --worker-iam-role arn:aws:iam::765374464689:role/ManagedOpenShift-Worker-Role --operator-roles-prefix cr-del --region eu-west-1 --version 4.14.1 --replicas 3 --compute-machine-type m5.8xlarge --machine-cidr 10.0.0.0/16 --service-cidr 172.30.0.0/16 --pod-cidr 10.128.0.0/14 …
```

OCM-4165 | fix: update default-mp-labels arg to worker-mp-labels

---

cmd/create/cluster/cmd.go
cmd/install/addon/cmd.go
cmd/login/cmd.go
pkg/ocm/versions.go

Related issue: [OCM-5715](https://issues.redhat.com//browse/OCM-5715)

OCM-5715 | fix: add error message when supplying worker disk size on unsupported version

---

cmd/verify/rosa/cmd.go

Allow inspecting how `rosa version` and `verify rosa-client` check available versions.
Previously --debug did nothing for these commands.
```
> rosa version --debug
1.2.31
time=2023-12-04T12:09:03+02:00 level=debug msg=Request method is GET
time=2023-12-04T12:09:03+02:00 level=debug msg=Request URL is 'https://mirror.openshift.com/pub/openshift-v4/clients/rosa/'
time=2023-12-04T12:09:04+02:00 level=debug msg=Response status is '200 OK'
time=2023-12-04T12:09:04+02:00 level=debug msg=Response header 'Cache-Control' is 'max-age=0'
time=2023-12-04T12:09:04+02:00 level=debug msg=Response header 'Content-Length' is '29044'
time=2023-12-04T12:09:04+02:00 level=debug msg=Response header 'Content-Type' is 'text/html'
time=2023-12-04T12:09:04+02:00 level=debug msg=Response header 'Date' is 'Mon, 04 …
```

version, verify rosa-client: Support --debug

---

Makefile
cmd/version/cmd.go
cmd/version/cmd_test.go
pkg/info/info.go

This PR adds the short Git SHA as a build property into the ROSA CLI. This is then printed as part of the version information when the user runs `rosa version`. This allows us to identify the exact build that the user is working with as we only set the version in `version.go` at the point of release and builds from `master` of our repository can masquerade as the released artifact.
The `build` is set via the `make rosa` command and the use of `-ldflags`. If the user builds the `rosa` binary directly via `go build`, this will default to `local`, again allowing us to determine how the binary a user is working with has been built.
The rationale for this was working with QE when they had not rebuilt their ROSA CLI binary to pickup the latest changes. The version information continued to …

OCM-5782 | feat: Add Git SHA of built binary to version output

---

cmd/create/cluster/cmd.go
cmd/describe/cluster/cmd.go
pkg/arguments/normalize.go
pkg/arguments/normalize_test.go

This PR updates the flags for the `rosa create cluster` command that relate to roles to use the `--arn` suffix for consistency. Support for the old flag names remains as they are mapped to the new flag name via the normalize function, to ensure that we do not break existing users of the ROSA CLI.
Additionally there is a minor modification to the output of the `rosa describe cluster` command to add the `(STS)` to `Role Arn` output.

OCM-824 | fix: Align usage of -arn suffix on role parameters to create cluster command

---

pkg/aws/client.go
pkg/aws/client_test.go

Makes the error message for invalid AWS creds more readable and suggests a fix for users. Also adds a unit test for the `ValidateCredentials` function to verify the fix.
https://issues.redhat.com/browse/OCM-1092

OCM-1092 | fix: improve error message for invalid credentials

---

cmd/link/ocmrole/cmd.go

With AMS update also organization member can add/remove OCM organization lables. Update the error message from `admin` to `member`.

OCM-1576 | feat: update link ocm role error message

---

pkg/helper/versions/helpers.go
pkg/helper/versions/helpers_test.go
pkg/test/helpers.go

Fix a panic caused by the default version being reinitialized at every loop. Add also a safety fallback in case the default version can't be computed.
Related: [OCM-5862](https://issues.redhat.com//browse/OCM-5862)

OCM-5862 | fix: default version computation should be done only once

---

pkg/info/info.go

Update `info.go` to prepare for `1.2.35` release.

OCM-5949 | chore: Prepare 1.2.35 release

---

pkg/aws/client.go
pkg/aws/client_test.go

Example output:
```
time=2024-02-06T10:18:33-05:00 level=warning msg=Throttling Rate limit exceeded. Retrying [ROSA-Request-Id: 9d86f340-680d-47e9-b43c-1ed6f63132a2 / POST iam.amazonaws.com]: 9/12
time=2024-02-06T10:18:33-05:00 level=warning msg=Throttling Rate limit exceeded. Retrying [ROSA-Request-Id: 145622bf-81b8-4d35-9c31-9e858beba628 / POST iam.amazonaws.com]: 1/12
time=2024-02-06T10:18:33-05:00 level=warning msg=Throttling Rate limit exceeded. Retrying [ROSA-Request-Id: 7c47084b-be85-47b3-ad7d-de5cea4359fa / POST iam.amazonaws.com]: 2/12
```

OCM-5827 | fix: detailed throttle retry message

---

Makefile

This PR ensures that `rosa` remains the default Makefile target which is the main workflow for the vast majority of people working on the project.

OCM-5978 | fix: Ensure rosa is the default Makefile target

---

Makefile

This PR fixes my previous PR 🙄 #1766  It should be `DEFAULT_GOAL` and not `DEFAULT_TARGET`

OCM-5978 | fix: Make rosa the default goal in the Makefile

---

cmd/create/operatorroles/by_clusterkey.go

[OCM-1109](https://issues.redhat.com//browse/OCM-1109) - move all logic that is only needed for auto mode into the `ModeAuto` check to allow the least amount of permissions possible, hopefully no permissions will work with this change, but we need to check for the account role name. So maybe that one permission is needed by default.

OCM-1109 | fix: Move logic only related to auto into ModeAuto check

---

pkg/ocm/idps.go

OAuth in HCP local dev now behaves like all the other environments. So ROSA CLI is able to compute it correctly.
Relevant TODO should be removed from ROSA CLI.
Related: [OCM-5983](https://issues.redhat.com//browse/OCM-5983)

OCM-5983 | chore: clean up old TODO

---

cmd/create/machinepool/machinepool.go
codecov.yml

Tiny fix to ensure we're using the correct parameter in the log message when fetching instance types for creation of a Machine Pool.

OCM-5828 | fix: Correct the message shown in interactive mode when creating a MachinePool

---

codecov.yml

This PR ensures our codecov reporting is being generated for `master` branch.

OCM-6057 | fix: Ensure codecov reports are being published for master

---

cmd/create/cluster/cmd.go

Mark the --no-cni as hidden as we want to expose it gradually to customers

OCM-6120 | fix: mark --no-cni flag as hidden

---

pkg/ocm/regions.go
pkg/rosa/runtime.go

Related issue: [OCM-6243](https://issues.redhat.com//browse/OCM-6243)
```
rosa list cluster --region avocado
E: Unsupported region 'avocado', available regions: [ap-east-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, us-east-1, us-east-2, us-west-1, us-west-2, af-south-1, ap-south-1, ap-south-2, eu-north-1, eu-south-1, eu-south-2, me-south-1, ca-central-1, eu-central-1, eu-central-2, il-central-1, me-central-1, us-gov-east-1, us-gov-west-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-southeast-1, ap-southeast-2, ap-southeast-3, ap-southeast-4]
```

OCM-6243 | fix: validate aws region within .WithAWS

---

cmd/list/oidcprovider/cmd.go
pkg/aws/client.go
pkg/aws/client_test.go
pkg/aws/mock_client.go
pkg/aws/sts.go
pkg/aws/test_helpers.go

https://issues.redhat.com/browse/OCM-1012
Lists OIDC providers by config ID (as long as that config exists in OCM)
Below are examples of the new flag:

OCM-1012 | feat: Add filtering by config ID for `list oidc-providers`

---

cmd/describe/machinepool/cmd_test.go
cmd/describe/machinepool/nodepool.go
pkg/ocm/output/nodepools.go

Print additional security group IDs if available.
e.g.
```
oadler@fedora:rosa (OCM-6055)$ rosa describe machinepool -c 29id32fv1u4mjav5jqkd4d9n6k7o9e9v test10
ID:                         test10
Cluster ID:                 29id32fv1u4mjav5jqkd4d9n6k7o9e9v
Autoscaling:                No
Desired replicas:           1
Current replicas:           1
Instance type:              m5.xlarge
Labels:                     
Taints:                     
Availability zone:          us-west-2a
Subnet:                     subnet-0e3a4046c1c2f1078
Version:                    4.14.6
Autorepair:                 Yes
Tuning configs:             
Message:                    
Security Group IDs:         sg-099ede74e05b84790, sg-0061db738d1f88702, sg-0087541ff27d09d6b
```

OCM-6055 | feat: describe node pools with additional security groups

---

cmd/version/cmd.go
cmd/version/cmd_test.go

This PR temporarily removes the `(Build: $GIT_SHA)` output from the `rosa version` command due to the fact that we are not reliably setting this on internal build systems for productised releases. We need to align on our approach throughout all build systems to ensure this is applied consistently, but for now, we remove the output from `rosa version` to reduce confusion for our customers.

OCM-6279 | fix: Temporarily remove build output from rosa version command

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go

https://issues.redhat.com/browse/OCM-5963
```
./rosa create cluster -c tzhou --hosted-cp --billing-account 123
E: Billing account is invalid. Run the command again with a valid billing account. To see the list of billing account options, you can use interactive mode by passing '-i'.
```

OCM-5963 | fix: align error messages for billing accounts

---

pkg/info/info.go

Update `info.go` to prepare for `1.2.36` release.

OCM-6351 | chore: Prepare 1.2.36 release

---

CONTRIBUTING.md
cmd/create/operatorroles/cmd.go
cmd/dlt/ocmrole/cmd.go
cmd/link/ocmrole/cmd.go
cmd/link/userrole/cmd.go
cmd/unlink/ocmrole/cmd.go
cmd/unlink/userrole/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/operatorroles/cmd.go
cmd/upgrade/roles/cmd.go
cmd/verify/quota/cmd.go

[JIRA](https://issues.redhat.com/browse/OCM-5829) Suppressing help message when error is shown from linking multiple roles to the same org

OCM-5829 | feat: Supressing help message when error is thrown

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/userrole/cmd.go
cmd/dlt/ocmrole/cmd.go
cmd/dlt/userrole/cmd.go
cmd/initialize/cmd.go
cmd/upgrade/cluster/cmd.go

https://github.com/openshift/rosa/pull/1779 changed any `RunE` calls to just use `Run`, which means that any other commands calling those `RunE` functions would now panic due to calling a nil function. This PR changes those calls to use the new `Run`.

Change 'RunE' calls to just 'Run'

---

cmd/config/cmd.go
cmd/config/cmd_test.go
cmd/config/get/get.go
cmd/config/set/set.go
cmd/rosa/main.go
cmd/token/cmd.go
cmd/token/cmd_test.go
pkg/config/config.go
pkg/ocm/client.go

**Changed**
- Add token command (similar to [OCM CLI](https://github.com/openshift-online/ocm-cli/blob/main/cmd/ocm/token/cmd.go))
- Add config command with get and set subcommands (similar to [OCM CLI](https://github.com/openshift-online/ocm-cli/blob/main/cmd/ocm/config/cmd.go))

OCM-5804 | feat: Add token and config commands

---

cmd/list/oidcprovider/cmd.go

Originally was using `-i` which made sense for `id`, but it is shared with `--interactive`. I cannot think of a better shorthand to use here, and there is no real reason to have one, so removing it to fix [OCM-6376](https://issues.redhat.com//browse/OCM-6376)
https://issues.redhat.com/browse/OCM-6376

OCM-6376 | feat: Remove shorthand for --oidc-config-id

---

go.mod

Remove toolchain from go.mod as it causes build issues in CPaaS

OCM-5935 | fix: remove toolchain from go.mod

---

cmd/create/machinepool/helper.go
cmd/create/machinepool/helper_test.go
cmd/create/machinepool/machinepool.go
cmd/create/machinepool/nodepool.go

- Allow the user to pass SG IDs when creating machine pool for HCP.
- Reuse validation from classic.
- Pass the values to the backend.

OCM-6054 | feat: Create node pool with SG IDs

---

CONTRIBUTING.md
cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go
cmd/describe/cluster/cmd.go
cmd/upgrade/cluster/cmd_test.go
pkg/ocm/clusters.go
pkg/ocm/helpers.go
pkg/ocm/helpers_test.go

The changes does the following:
- Bump the SDK to latest version 
- Update the `describe cluster ` command to show the domain prefix and changes how the DNS is constructed by using this field
- Update the `create cluster` command to allow; name to be <= 54 chars, domain-prefix <= 15 with their associated DNS label validation
- Update `FetchCluster(key,creator)` to remove the no longer valid fact that name <= 15 and only perform the backend search that covered for all cases i.e name, id, external_id 
Example output of the describe command (notice the name and the domain prefix):
```
./rosa describe cluster -c very-long-name-for-machi-cluster                                              
Name:                       very-long-name-for-machi-cluster
Domain Prefix:              machi
Display …
```

Allow longer cluster names up to 54 chars and an optional domain-prefix to customize the DNS

---

cmd/login/cmd.go

https://issues.redhat.com/browse/OCM-5736
**Changed**
- Make auth and device code flags visible
**Tested**
- Flags should be visible in `rosa login --help` : tested

OCM-5736 | feat: Make auth and device code flags visible

---

cmd/describe/machinepool/cmd_test.go
cmd/describe/machinepool/nodepool.go

Add `Additional` to the security group IDs field.

OCM-6468 | fix: change describe node pool output

---

cmd/create/cluster/cmd.go
cmd/create/service/cmd.go
pkg/helper/helpers_test.go
pkg/helper/roles/helpers.go

A valid operator role prefix has at most 32 characters, but the cluster name can have up to 54 characters this was causing errors as the one reported in https://issues.redhat.com/browse/OCM-6484. To fix this issue, we use only the first 27 characters of the name if the name is longer than 27 characters.

OCM-6484 | fix: generates a valid operator role prefix from the cluster name

---

cmd/install/addon/cmd.go

[JIRA](https://issues.redhat.com/browse/OCM-1032)
CHANGES:
- made billing mode "standard" the default when none is specified avoiding going into interactive mode

OCM-1032 | feat: making billing-mode standard default

---

cmd/download/oc/cmd.go
cmd/download/rosa/cmd.go
cmd/logout/cmd.go
cmd/verify/oc/cmd.go
cmd/verify/rosa/cmd.go
pkg/color/flag.go
pkg/debug/flag.go
pkg/ocm/clusters.go
pkg/reporter/reporter.go
pkg/reporter/reporter_test.go
pkg/rosa/runtime.go

This PR removes the `error` from the `reporter.Builder.Build()` method signature as it was not used and lead to unnecessary error handling and propagation. Instead, replaced with a single `reporter.CreateReporter` function and removed the `Builder` functionality completely.

OCM-6496 | chore: Remove error from reporter.Builder.Build method signature

---

cmd/create/oidcprovider/cmd.go

Indicate to users that passing / using the region flag is not allowed when creating the OIDC provider.

OCM-6119 | fix: block users from passing region flag when creating an oidc provider

---

cmd/token/cmd.go

**Changed**
- Removed output flag from rosa token command since we only have string output in this case
https://issues.redhat.com/browse/OCM-6515

OCM-6515 | fix: Removed output flag from rosa token command

---

cmd/login/cmd.go

**Changed**
- Add validation to not pass token or fedramp flag for OAuth login
https://issues.redhat.com/browse/OCM-4969

OCM-4969 | fix: Add validation to not pass token or fedramp flag for OAuth login

---

cmd/create/machinepool/cmd.go
cmd/create/machinepool/nodepool.go
cmd/describe/machinepool/cmd_test.go
cmd/describe/machinepool/nodepool.go
cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/nodepool.go
pkg/helper/machinepools/helpers.go
pkg/helper/machinepools/helpers_test.go
pkg/ocm/output/nodepools.go
pkg/ocm/output/nodepools_test.go

Support node drain grace period for NodePools of HyperShift-enabled clusters. The node drain grace period is supported for these operations:
- Create machinepool (nodepool)
- Update machinepool
- Describe machinepool
https://issues.redhat.com/browse/OCM-6106

OCM-6106 | node drain grace period for hosted control planes

---

codecov.yml

This PR makes our Codecov reporting informative. This places greater emphasis on PR reviewers to request unit testing and make suggestions around code layout to ensure new additions are testable.

OCM-6668 | chore: Make all codecov reporting informational

---

pkg/helper/versions/helpers.go
pkg/ocm/versions.go
pkg/ocm/versions_test.go

Issue with nightly versions being evaluated as prelease versions.
This caused cluster create issues with openshift nightly versions greater than 4.14.0.
The minimum versions for HCP required is 4.14.0
With command:
`./rosa create cluster --hosted-cp --channel-group=nightly`
Interactive List before fix (rosa create cluster) [only shows 4.15.0+ nightly versions]
Interactive List after fix (rosa create cluster)
Confirming fix includes all nightly versions meeting 4.14.0 version requirement.

OCM-6687 | fix: 4.14 nightly version not compatible with ROSA HCP

---

pkg/aws/client.go
pkg/interactive/securitygroups/security_groups.go
pkg/interactive/securitygroups/security_groups_test.go

For interactive mode, filter out security groups with `red-hat-managed` tag and with name `default`.
Improve the UX, to prevent an error returned from the backend.

OCM-6768 | fix: Create machine pool with security group - filter options

---

cmd/describe/machinepool/cmd_test.go
cmd/describe/machinepool/nodepool.go

Add more spaces for schedule nodepool upgrade prompt.
e.g.
```
oadler@dhcp-1-179:rosa (OCM-6767)$ rosa describe machinepool -c oadler-mar-8 test4
ID:                                    test4
Cluster ID:                            2a279k19s61nr623etadtgnqblcnrrrl
Autoscaling:                           No
Desired replicas:                      1
Current replicas:                      1
Instance type:                         m5.xlarge
Labels:                                
Taints:                                
Availability zone:                     us-west-2a
Subnet:                                subnet-0e3a4046c1c2f1078
Version:                               4.15.0
Autorepair:                            Yes
Tuning configs:                        
Additional security group IDs: …
```

OCM-6767 | fix: describe node pool - adjust output

---

CONTRIBUTING.md
cmd/create/machinepool/helper_test.go
cmd/create/machinepool/nodepool.go
pkg/helper/features/features.go
pkg/ocm/versions.go

For interactive mode, check the node pool version and prompt for additional security groups accordingly.

OCM-6648 | fix: create node pool with security group - check version

---

cmd/list/cmd.go
cmd/list/rhRegion/cmd.go
cmd/list/rhRegion/cmd_test.go
cmd/login/cmd.go
pkg/arguments/normalize.go
pkg/arguments/normalize_test.go
pkg/ocm/config.go
pkg/ocm/config_test.go

Issue : https://issues.redhat.com/browse/OCM-3594
**Changed**
- Add hidden flag rhRegion to rosa login command
- Add list rh-region command to list regions
- Add unit tests
**Tested**
This MR tweaks the `rosa login --env` resolution algorithm to try to reuse `cfg.URL` before falling back to "api.openshift.com". New `--env` resolution algorithm (from highest priority to lowest priority):
1. runtime `--env` cli arg (key found in `URLAliases`)
2. runtime `--env` cli arg (non-empty string)
3. [NEW] config file `URL` value (non-empty string)
4. sdk.DefaultURL
`rosa list rh-region`:
* show discovery URL used
* add optional `--discovery-url` flag with the same url resolution behavior as `ocm login`
* display region name and its associated url rather than just region name

OCM-3594 | Feat | Add rhRegion flag to rosa login command

---

cmd/login/cmd.go
cmd/login/cmd_test.go
cmd/login/login_suite_test.go

[OCM-5718](https://issues.redhat.com//browse/OCM-5718) describes a bug where if a user attempts to log in supplying all commercial values, except passing in `--govcloud` flag, ROSA will be in 'fedramp mode' and will attempt to run commands on the wrong API endpoint. This MR makes sure users are meaning to log into govcloud by requiring a govcloud region upon logging in.
All other logic is kept the same, so if you _only_ supply a govcloud region, or an encrypted token, etc, you will still log into fedramp. But, the `--govcloud` flag bug is solved by requiring the region upon passing the flag. If you pass `--govcloud` without meaning to (I.E. not providing a govcloud region), you will face an error. Other safeguard in this case already exists, where you must pass in a fedramp token to log …

OCM-5718 | feat: Display login error if `--govcloud` supplied with commercial region

---

cmd/describe/externalauthprovider/cmd.go
cmd/dlt/externalauthprovider/cmd.go
cmd/list/externalauthprovider/cmd.go
pkg/externalauthprovider/flags.go
pkg/externalauthprovider/flags_test.go

https://issues.redhat.com/browse/OCM-6822

OCM-6822 | fix: add validations for external auth

---

cmd/create/cluster/cmd.go
cmd/create/idp/htpasswd.go
cmd/create/idp/htpasswd_test.go

OCM-6879 | fix: allow user specify `cluster-admin` as admin username in day-1

---

cmd/create/machinepool/nodepool.go
pkg/helper/machinepools/helpers.go
pkg/helper/machinepools/helpers_test.go

Add validator to check the value of the node drain grace period in interactive mode.

OCM-6858 | Add validator for node drain grace period in interactive mode

---

cmd/dlt/cluster/cmd.go

https://docs.openshift.com/rosa/cli_reference/rosa_cli/rosa-manage-objects-cli.html#rosa-delete-cluster_rosa-managing-objects-cli

OCM-6652 | task: update --best-effort help message

---

pkg/ocm/config.go
pkg/ocm/config_test.go

https://issues.redhat.com/browse/OCM-6926
**Changed**
- Added complete URL check as a fallback mechanism for GetEnv() in case of specific local or other URLs
- Added test case to confirm the behavior
**Tested**
- Local env should be supported in GetEnv() : tested

OCM-6926 | fix: Support local envs in GetEnv()

---

pkg/ocm/config.go
pkg/ocm/config_test.go

[OCM-6926](https://issues.redhat.com//browse/OCM-6926)

OCM-6926 | fix: needs to also go through admin fedramp url aliases

---

cmd/create/admin/cmd.go
cmd/describe/admin/cmd.go
cmd/dlt/admin/cmd.go

https://issues.redhat.com/browse/OCM-6883
In this PR, `rosa describe admin` will list out all users in `cluster-admins` group.
For the commands `rosa create admin` and `rosa delete admin`, they continue to only handle the `cluster-admin` user in `cluster-admins` group. Update help messages for those commands to make this more clear

OCM-6883 | fix: rosa describe admin can list the admin with custom name

---

pkg/ocm/managedservice.go
pkg/ocm/managedservice_test.go

https://issues.redhat.com/browse/OCM-5549
This MR makes it so when you are logged into FedRAMP envs, you cannot list managed services. Prevents a strange, and confusing error to the user.

OCM-5549 | feat: Disable listing services while using FedRAMP login

---

cmd/create/breakglasscredential/breakglasscredential_suite_test.go
cmd/create/breakglasscredential/cmd.go
cmd/create/breakglasscredential/cmd_test.go
cmd/create/cmd.go
cmd/describe/breakglasscredential/cmd.go
cmd/describe/breakglasscredential/cmd_test.go
cmd/describe/breakglasscredential/main_test.go
cmd/describe/cmd.go
cmd/list/breakglasscredential/cmd.go
cmd/list/cmd.go
cmd/revoke/breakglasscredential/cmd.go
cmd/revoke/cmd.go
pkg/breakglasscredential/breakglasscredential_test.go
pkg/breakglasscredential/flags.go
pkg/breakglasscredential/flags_test.go
pkg/ocm/break_glass_credential.go
pkg/ocm/break_glass_credential_test.go
pkg/output/output.go
pkg/test/helpers.go

https://issues.redhat.com/browse/OCM-4460

OCM-4460 | feat: Add actions for break glass credential

---

cmd/edit/ingress/cmd_test.go
cmd/edit/ingress/flags.go

[OCM-7047](https://issues.redhat.com//browse/OCM-7047)

OCM-7047 | fix: panic when not supplying '=' delimiter component routes

---

cmd/create/externalauthprovider/cmd.go
pkg/externalauthprovider/flags.go

https://issues.redhat.com/browse/OCM-6822
Error now shows the cluster name instead of cluster id:
```
E: failed to create an external authentication provider for cluster 'magchen-hcp': external_auth.issuer.audiences must contain at least one audience
```

OCM-6822 | fix: use cluster name in error message

---

cmd/create/admin/cmd.go
cmd/create/idp/cmd.go
cmd/describe/admin/cmd.go
cmd/dlt/admin/cmd.go
cmd/dlt/idp/cmd.go
cmd/list/idp/cmd.go
cmd/list/user/cmd.go

https://issues.redhat.com/browse/OCM-6375

OCM-6375 | fix: error out if cluster is enabled with external auth

---

hack/commit-msg-verify.sh

[https://issues.redhat.com/browse/OCM-6302](https://issues.redhat.com/browse/OCM-6302)
Updates the hack script, ran by prow, which checks PR commit msgs to also check PR author

OCM-6302 | ci: Prow job update to check PR author in commit check

---

cmd/create/cluster/cmd.go

disable the feature for 1.2.37 to avoid the conflicts with rosa admin commands

OCM-6883 | fix: disable the feature for custom username of cluster admin

---

cmd/create/oidcprovider/cmd.go

Revert "OCM-6119 | fix: block users from passing region flag when creating an oidc provider"

---

cmd/login/cmd.go
cmd/login/cmd_test.go

**Changed**
- Added back the condition to check for empty env flag
**Tested**
- FedRAMP login flow should work as expected : tested

OCM-6926 | fix: Added back the condition to check for empty env flag

---

pkg/externalauthprovider/flags.go
pkg/externalauthprovider/flags_test.go

https://issues.redhat.com/browse/OCM-6820

OCM-6820 | fix: add checks for mandatory parameters

---

cmd/create/idp/github.go
go.mod
pkg/interactive/validation.go
pkg/interactive/validation_test.go

Switch from URI validation to the DNS1123 validation. The openshift does not accept the URI format of domains. So when user specifies some address with prefix https:// it will fail.

OCM-7110 | fix: GitHub IDP validation

---

cmd/create/externalauthprovider/cmd.go

https://issues.redhat.com/browse/OCM-6955

OCM-6955 | fix: provide better message for external auth creation

---

cmd/describe/cluster/cmd.go
cmd/edit/cluster/cmd.go
pkg/input/consts.go
pkg/ocm/clusters.go

This change allows a user to edit delete protection on clusters, and adds the delete protection to the describe output. 
This change lacks tests due to the size of the refactors needed to make this easy to test. Happy to follow up with refactors after
JIRA - https://issues.redhat.com/browse/OCM-5942
Validation
```
╭─croche@fedora ~/Work/ocm/rosa ‹OCM-5942› 
╰─$ rosa describe cluster -c croche                             
Name:                       croche
Domain Prefix:              croche
Display Name:               croche
ID:                         2a874cc5sm2o72h5h9fdq8ciafr0h8tq
External ID:                790b1651-7566-4e32-8c2f-f290592b6665
Control Plane:              Customer Hosted
OpenShift Version:          4.14.12
DNS: …
```

OCM-5942 | feat: allow users set delete protection on cluster

---

cmd/describe/cluster/cmd.go

Billing accounts can now be set on ROSA Classic clusters (rather than just HCP clusters) and should be included in `rosa describe cluster` accordingly.

Display AWS Billing Account on non-HCP

---

cmd/create/breakglasscredential/cmd.go
pkg/breakglasscredential/flags.go
pkg/breakglasscredential/flags_test.go

https://issues.redhat.com/browse/OCM-7136

OCM-7136 | fix: support create breakglasscredential without optional flags

---

cmd/upgrade/roles/cmd.go
cmd/upgrade/roles/cmd_test.go

In [PR](https://github.com/openshift/rosa/pull/1806/files#diff-0422b55e643b32d83ec9a053112d37486dfe3471aa851274e75e49931c88b013L500-L503), some of the error handlings were removed. I've gone through each one of them and brought back the one that should be present: upgrade role error handling when invoke from upgrade cluster.
[Jira ref](https://issues.redhat.com/browse/OCM-6697)

OCM-6697 | fix: upgrade role error should print extra info when invoke from upgrade cluster

---

tests/e2e/e2e_suite_test.go
tests/e2e/hcp_machine_pool_test.go
tests/utils/common/file.go
tests/utils/exec/rosacli/machinepool_service.go

```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "with additional security group IDs" tests/e2e
Random Seed: 1712152071
Will run 1 of 2 specs
time="2024-04-03T21:47:53+08:00" level=info msg="Running command: rosa create machinepool --additional-security-group-ids sg-0497af1a40908d82b,sg-0fff00cf3ca25b0c8,sg-058b2374174cfd370,sg-0f953b1e74639a371 --replicas 1 -y -c 2add20bo15cedljf52rppgq0f52jo3aj --name mp-72195"
time="2024-04-03T21:48:08+08:00" level=info msg="Get Combining Stdout and Stder is :\nINFO: Machine pool 'mp-72195' created successfully on hosted cluster '2add20bo15cedljf52rppgq0f52jo3aj'\nINFO: To view the machine pool details, run …
```

OCM-6161 | ci: Automate HCP machinepool creation with security groups

---

cmd/create/breakglasscredential/cmd.go
cmd/describe/breakglasscredential/cmd.go
cmd/describe/breakglasscredential/cmd_test.go
cmd/list/externalauthprovider/cmd.go
cmd/list/externalauthprovider/cmd_test.go
pkg/test/helpers.go

https://issues.redhat.com/browse/OCM-7168

OCM-7168 | fix: Add info after successfully created breakglasscredentials

---

hack/release-list-jiras.sh

We dont want to include reverts in a release, this checks for the revert prefix and omits it.

OCM-7318 | chore: update the list jira helper to ignore reverts when listing release jiras

---

cmd/describe/breakglasscredential/cmd.go
cmd/describe/breakglasscredential/cmd_test.go

https://issues.redhat.com/browse/OCM-7169

OCM-7169 | fix: error message when describe credential that status is revoked

---

pkg/info/info.go

Release branch version: 1.2.38.RC1 (as of April 9, 2024)
To be Master branch version: 1.2.39

OCM-7346 | chore: increment master version (to 1.2.39)

---

cmd/create/cmd.go
cmd/describe/cmd.go
cmd/dlt/cmd.go
cmd/edit/cmd.go
cmd/grant/cmd.go
cmd/install/cmd.go
cmd/link/cmd.go
cmd/list/cmd.go
cmd/logs/cmd.go
cmd/register/cmd.go
cmd/revoke/cmd.go
cmd/uninstall/cmd.go
cmd/unlink/cmd.go
cmd/upgrade/cmd.go
pkg/arguments/arguments.go
pkg/arguments/arguments_test.go
pkg/aws/region/flag.go

https://issues.redhat.com/browse/OCM-6391
We put the region flag in almost every overarching command (`create`, `delete`, `list`, etc) -- yet many of the subcommands do _not_ use region. This can lead to confusion for users. As a solution, I have made a function in the same package following the same naming scheme as the function which adds the region flag. This way, we can disable using the region flag in any command we want with a single line.

OCM-6391 | feat: Deprecate the region flag in commands which do not utilize it

---

pkg/interactive/validation.go
pkg/interactive/validation_test.go

The openshfit validates the GitHub hostname and it can not match the [*.]github.com If the user would put the hostname 'github.com' the hive idp sync would fail as the admission controller would not allow to update the oauth cr

OCM-7188: GitHub IDP Add hostname validation

---

cmd/describe/cluster/cmd.go

Inverts the check for the delete protection output. This was a regression introduced when changing output from yes/no to enabled/disabled
```
$ rosa describe cluster -c croche
Name:                       croche
Domain Prefix:              croche
Display Name:               croche
ID:                         2ai5ok6qebvc8jk442pnsoci2ob00fmn
External ID:                cd7d5abb-c099-417e-8e5b-b84069c1e6bd
Control Plane:              Customer Hosted
OpenShift Version:          4.15.6
DNS:                        croche.cgbh.s1.devshift.org
AWS Account:                765374464689
API URL:                    https://api.croche.cgbh.s1.devshift.org:6443
Console URL:                https://console-openshift-console.apps.croche.cgbh.s1.devshift.org
Region: …
```

OCM-7358 | fix: invert describe out for cluster delete protection

---

pkg/interactive/validation.go
pkg/interactive/validation_test.go

[OCM-7401](https://issues.redhat.com//browse/OCM-7401) | fix: allow empty GitHub IDP hostname

OCM-7401 | fix: allow empty GitHub IDP hostname

---

tests/e2e/test_rosacli_iam_roles.go
tests/e2e/test_rosacli_idp.go
tests/e2e/test_rosacli_oidc_config.go
tests/e2e/test_rosacli_oidc_provider.go
tests/e2e/test_rosacli_verify.go

[Log](https://privatebin.corp.redhat.com/?b769766da85cc2ff#ABFS3XhaAqEoY9Mv3VZe8pVbnDHHtszt3Dreb85bC73L) for 43051|57441|62083|52580|43046|66359|57056
[Log](https://privatebin.corp.redhat.com/?dcaf353f4523694b#HKfCTzU3BjUhTVCLYJJuTpAfqYKPhwVPbk7ru9Z3DXXy) for 57570

OCM-6309 | ci: Verify test case(s) 43051|57441|62083|52580|43046|66359|57056|57570

---

tests/ci/data/profiles/rosa-classic.yaml
tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_iam_roles.go
tests/e2e/test_rosacli_idp.go
tests/e2e/test_rosacli_user.go
tests/utils/log/constants.go
tests/utils/log/logger.go

Here is the log https://privatebin.corp.redhat.com/?5575217bfbaec3ee#7dSdFKmDgqGyYznqLkBNA5xq5rhcjcQ2VtDjeVaANq2e

OCM-6309 | ci: Verify test case(s) 45161|35878|35896|49137|46187|38850|34102|66362|36128

---

cmd/describe/machinepool/cmd_test.go
pkg/machinepool/output.go
pkg/machinepool/output_test.go

Change to additional security groups ids to match the flag name.
e.g.
```
oadler@fedora:rosa (OCM-6501)$ rosa describe machinepool -c croche worker
ID:                                    worker
Cluster ID:                            2ai5ok6qebvc8jk442pnsoci2ob00fmn
Autoscaling:                           No
Replicas:                              2
Instance type:                         m5.xlarge
Labels:                                
Taints:                                
Availability zones:                    eu-west-1a
Subnets:                               
Spot instances:                        No
Disk size:                             300 GiB
Additional Security Group IDs:         123
```

OCM-6501 | fix: Adjust describe machine pool output

---

cmd/create/cmd.go
pkg/arguments/arguments.go
pkg/arguments/arguments_test.go

[OCM-6391](https://issues.redhat.com//browse/OCM-6391) is a previously finished ticket which had a small bug, it is now fixed. The deprecation msg was showing up in parent cmds, when it was only meant to show up in certain subcommands. This MR fixes that

OCM-6391 | fix: Fixed bug where deprecation shows for parent cmd

---

pkg/arguments/arguments.go
pkg/arguments/arguments_test.go

[OCM-6391](https://issues.redhat.com//browse/OCM-6391)

OCM-6391 | fix: only show message when region is changed and no output mode set

---

images/Dockerfile.e2e

As we [migrated Dockerfile from the repository release to rosa](https://github.com/openshift/rosa/pull/1934), on Prow CI, we will use docker_path instead of docker_literal(https://github.com/openshift/release/pull/50960). The docker_path method requires uploading the repository source code from the build context into an image layer.

OCM-6199 | ci: fix can not find go.mod

---

tests/e2e/test_rosacli_node_pool.go

output log https://privatebin.corp.redhat.com/?5c7d5a2d92408172#4V2g1eGzihHX6qMFZGoGgWik5iy7iWzVz9vPsAsyKYZc

OCM-7451 | test: automate id:OCP-63179  create nodepool with tuning config will validate well

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/helper.go
pkg/interactive/securitygroups/security_groups.go
pkg/interactive/securitygroups/security_groups_test.go

Checking if the security group has a cluster tag, and filter accordingly.
Improve UX by preventing an error returned from the backend, for the same validation.

OCM-7079 | feat: select security groups interactive - filtering

---

cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/machinepool.go
cmd/edit/machinepool/machinepool_test.go
cmd/edit/machinepool/main_test.go
cmd/edit/machinepool/nodepool.go
cmd/edit/machinepool/nodepool_test.go

https://issues.redhat.com/browse/OCM-5186
https://issues.redhat.com/browse/OCM-4597

OCM-5186 | fix: align nodepool actions with machinepools

---

cmd/describe/cmd.go
cmd/describe/machinepool/cmd.go
cmd/describe/machinepool/cmd_test.go
cmd/describe/machinepool/options.go
cmd/describe/machinepool/options_test.go
pkg/machinepool/machinepool_test.go
pkg/test/helpers.go
pkg/test/helpers_suite_test.go
pkg/test/helpers_test.go

[OCM-7253](https://issues.redhat.com//browse/OCM-7253)
Pt 2 to the RCI Milestone 2 for `describe machine-pool`
Refactors the command to use new default runner, and refactors tests
DoD:
Command uses new default runner
Command has at least 70% unit test coverage

OCM-7253 | feat: Refactor describe machine pool cmd to use new default runner

---

images/Dockerfile.release

The prow CI jobs are [51184](https://github.com/openshift/release/pull/51184)

OCM-7533 | ci: add Dockerfile for rosa-aws-cli:release

---

cmd/describe/cmd.go
cmd/describe/ingress/cmd.go
cmd/describe/ingress/cmd_test.go
cmd/describe/ingress/main_test.go
cmd/describe/ingress/options.go
cmd/edit/ingress/cmd.go
pkg/ingress/ingress.go
pkg/ingress/ingress_test.go
pkg/ocm/ingresses.go
pkg/output/output.go

[OCM-6527](https://issues.redhat.com//browse/OCM-6527)

OCM-6527 | feat: add describe ingress command

---

cmd/create/machinepool/cmd.go
cmd/create/machinepool/helper_test.go
cmd/create/machinepool/machinepool.go
cmd/create/machinepool/nodepool.go
pkg/helper/machinepools/helpers.go

[OCM-6723](https://issues.redhat.com//browse/OCM-6723)

OCM-6723 | feat: allow to supply user tags on creation of hcp machine pool

---

cmd/edit/ingress/cmd.go
cmd/edit/ingress/flags.go

[OCM-7307](https://issues.redhat.com//browse/OCM-7307)
Remove older attributes as they are not to be used. Favor `--component-routes` attribute

OCM-7307 | fix: remove older attributes for component routes

---

cmd/create/cluster/cmd.go
pkg/helper/helpers.go
pkg/helper/helpers_test.go

https://issues.redhat.com/browse/OCM-1308

OCM-1308 | fix: filter empty subnet id

---

tests/e2e/test_rosacli_user.go

output log:- https://privatebin.corp.redhat.com/?383891ea8e850470#3CYKehGgb3Q93EyCm28WkMgxvwUuBZhdpNcUW7YVhvNE

OCM-7593 | test: automate id:OCP-36128 Updated a new checkpoint

---

cmd/detach/cmd.go
cmd/detach/policy/cmd.go
cmd/detach/policy/cmd_test.go
cmd/rosa/main.go
pkg/aws/client.go
pkg/aws/mock_client.go
pkg/policy/policy_service.go
pkg/policy/policy_service_test.go

https://issues.redhat.com/browse/OCM-6543

OCM-6543 | feat: detach cmd to detach policy

---

cmd/create/cluster/cmd.go
pkg/arguments/arguments.go
pkg/arguments/arguments_test.go

[OCM-6391](https://issues.redhat.com//browse/OCM-6391)
When a nested cmd which deprecates region flag is ran (create cluster with describe cluster running from the create's `Run` func), it showed the deprecation msg of the nested cmd. This MR allows a bypass for the deprecation warning

OCM-6391 | fix: Ability to disable region flag deprecation manually

---

cmd/attach/policy/cmd.go
cmd/attach/policy/cmd_test.go
cmd/detach/policy/cmd.go
cmd/detach/policy/cmd_test.go
pkg/aws/helpers.go
pkg/policy/policy_service.go
pkg/policy/policy_service_test.go

https://issues.redhat.com/browse/OCM-7669
https://issues.redhat.com/browse/OCM-7668

OCM-7669 | fix: valide rolename and policyarn in rosa attach/detach cmd

---

tests/e2e/test_rosacli_machine_pool.go
tests/utils/exec/rosacli/break_glass_credential_service.go
tests/utils/exec/rosacli/machinepool_service.go

Here is the running log
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus 73469 tests/e2e
2.13.2
2.13.0 used by e2e
Ginkgo CLI. …
```

OCM-7619 | ci: Automated 73469 for tags supporting on classic

---

images/Dockerfile.e2e
tests/e2e/e2e_pre_check_test.go
tests/utils/exec/rosacli/pr_check.go

The [output](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_rosa/1965/pull-ci-openshift-rosa-master-images-images/1783425580914446336/artifacts/build-logs/rosa-aws-cli-amd64.log) is like:
`The lastest commit updates the test: 11111|11112|21111|21112`

OCM-7614 | fix: Get the merged commit but not the pull request commit

---

cmd/create/cluster/cmd.go

[OCM-6391](https://issues.redhat.com//browse/OCM-6391) - deprecates the use of the region flag in each command that it is not needed in. There are plans to remove it in the future from these commands

OCM-6391 | fix: Fix deprecation warn printing when creating cluster

---

cmd/rosa/main.go
cmd/version/cmd_test.go
cmd/version/options.go

*WHAT*
When calling BindAndValidate the option args were not initialized, this changes ensures the args are initialized on `NewRosaVersionOptions`
This change also sets the checkVersion to debug in the case of any failures while trying to check the CLI version. Only when we successfully validate the version will we warn the user if its out of date.
JIRA - https://issues.redhat.com/browse/OCM-7573

OCM-7573 | fix: ensure version option args are initialised

---

cmd/detach/policy/cmd.go
pkg/aws/client.go
pkg/aws/mock_client.go
pkg/aws/policies.go
pkg/policy/policy_service.go
pkg/policy/policy_service_test.go

https://issues.redhat.com/browse/OCM-7729
https://issues.redhat.com/browse/OCM-7730

OCM-7729 | fix: check policy attached in detach manual mode

---

cmd/create/cluster/cmd.go

[OCM-6391](https://issues.redhat.com//browse/OCM-6391)
Hypershift clusters would print the warning later in the command unintentionally, this MR covers every possible point in which this can be printed in `create cluster`

OCM-6391 | fix: Add final disablement on final command in create cluster for region flag

---

cmd/login/cmd.go

Issue:
Currently for FedRAMP, any attempts to provide a client-id and secret fail due to the client-id being overwritten with values defined in [FedRAMP config](https://github.com/openshift/rosa/blob/master/pkg/fedramp/config.go#L95). This prevents us from using clients configured in our IDP to grant service account access to automated processes.
What this PR fixes:
* adds a quick check to make sure client-id wasn't provided, and if it was, sets it to that value instead of overwriting it.
Notes:
The reason for the override is because our default client does not match commercials. Furthermore, the clients used with Cognito are unique, where as the ones with Keycloak are not, so potentially we can improve this by defining a default for FedRAMP when not using admin CLI. 
For now, this is …

prevents overwriting the client id if set for fedramp with keycloak

---

cmd/create/cluster/cmd.go
cmd/create/ocmrole/cmd.go
cmd/create/oidcconfig/cmd.go
cmd/create/userrole/cmd.go
cmd/dlt/cluster/cmd.go
cmd/dlt/ocmrole/cmd.go
cmd/dlt/oidcconfig/cmd.go
cmd/dlt/userrole/cmd.go
cmd/register/oidcconfig/cmd.go
cmd/upgrade/cluster/cmd.go
pkg/arguments/arguments.go

[OCM-6391](https://issues.redhat.com//browse/OCM-6391)
is a ticket where we temporarily deprecate the region flag before removing it from commands which do not use it. This is a bug fix for the create cluster command, which housed 4 commands that have this deprecation.

OCM-6391 | fix: Add region deprecation disablement to sub-commands

---

tests/e2e/dummy_test.go
tests/utils/exec/rosacli/cmd_client.go
tests/utils/exec/rosacli/cmd_runner.go
tests/utils/log/constants.go
tests/utils/log/logger.go

There were too much log show in the output of the CI. This PR will improve it to avoid some noise
When case is passed there will be no log output
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus 68828 tests/e2e
Random Seed: 1714992769
Will run 1 of 58 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSS
Ran 1 of 58 Specs in 23.412 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 57 Skipped
PASS
Ginkgo ran 1 suite in 29.26163914s
```
But when case failed all details will show
```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus 68828 tests/e2e …
```

OCM-7738 | ci: Enhance the output of rosacli e2e testing

---

go.mod
tests/e2e/test_rosacli_network_verifier.go
tests/e2e/test_rosacli_oidc_provider.go
tests/e2e/test_rosacli_user.go
tests/utils/common/idp.go
tests/utils/config/cluster_command.go

[OCM-7537](https://issues.redhat.com//browse/OCM-7537) | ci: fix id:45161,id:49137,id:66362,id:36128,id:43046
fix 45161 trim the command with the space then add the flag at func (c *command) AddFlags(flags ...string)
fix 49137 dont use htpasswd banary  at GenerateMultipleHtpasswdPairs and GenerateHtpasswdPair
fix 66362 it supports on Hosted-cp cluster, remove the original checkpoint
fix 36128 Add condition for the empty user list step
fix 43046 update the message condition as the design change
The log is here,https://privatebin.corp.redhat.com/?2bd4121c47d1d65d#CT3jmB9AmcSJqwweCAuDReiupY8ts6PV5Sb9jEjxp9yA

OCM-7537 | ci: fix 45161,49137,66362,36128,43046

---

cmd/create/cmd.go

There was an extra addition of the oidcprovider command in a region deprecation call. Removed here.

OCM-6391 | fix: Remove duplicate oidcprovider cmd call

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go

https://issues.redhat.com/browse/OCM-7870

OCM-7870 | fix: Display external-auth-providers-enabled flag

---

tests/e2e/dummy_test.go
tests/utils/exec/rosacli/ingress_service.go

```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus IngressServiceTesting tests/e2e     
Random Seed: 1715234948
Will run 1 of 59 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSS
Ran 1 of 59 Specs in 3.484 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 58 Skipped
PASS
Ginkgo ran 1 suite in 9.257267263s
```

OCM-7925 | ci: Fix ingress list result cannot be reflect issue

---

cmd/upgrade/accountroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/commandbuilder/helper/roles/roles.go
pkg/aws/mock_client.go
pkg/aws/policies.go
pkg/helper/rolepolicybindings/helpers.go
pkg/helper/rolepolicybindings/helpers_test.go
pkg/ocm/rolepolicybinding.go

https://issues.redhat.com/browse/OCM-7415
https://issues.redhat.com/browse/OCM-1752

OCM-7415 | feat: Ensure account roles have expected attached policies

---

tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_idp.go

```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "(35878|35896|49137)" tests/e2e
Random Seed: 1715268241
Will run 3 of 59 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSS•••SSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 3 of 59 Specs in 351.317 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 56 Skipped
PASS
Ginkgo ran 1 suite in 6m1.418792847s
```

OCM-7801 | ci: Remove redundant cleaner to fix resource clean issue

---

tests/ci/labels/runtime.go
tests/e2e/e2e_report.go
tests/utils/exec/rosacli/report_portal.go

This change does:
1. Analyze the `.xml` files under the `$SHRED_DIR` and generate the new one under the `$ARTIFACT_DIR/junit` directory with the new format to fit the report portal requirement.
2. Generate the `$ARTIFACT_DIR/e2e-test-results.json` for prow CI testing result analysis.
On prow CI, the usage is:
```
rosatest --ginkgo.v --ginkgo.no-color --ginkgo.timeout "10m" --ginkgo.label-filter "e2e-report"
failures=$(cat $ARTIFACT_DIR/e2e-test-results.json) | jq -r '.failures'
... ...
```
The Example new junit.xml under the `$ARTIFACT_DIR/junit` directory is:
```
<testsuite name="ams-basic-e2e-staging-main_050806" package="/Users/ymsun/Documents/workspace/src/gitlab.cee.redhat.com/service/ocm-backend-tests" tests="4" disabled="0" skipped="0" errors="0" failures="2" time="0.007820417" …
```

OCM-7927 | ci: Generate the junit file for report portal

---

go.mod
go.sum
tests/ci/config/config.go
tests/ci/data/profiles/rosa-classic.yaml
tests/e2e/dummy_test.go
tests/utils/profilehandler/data_preparation.go
tests/utils/profilehandler/profile_handler.go
vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/image.go
vendor/github.com/openshift-online/ocm-common/pkg/aws/consts/consts.go
vendor/github.com/openshift-online/ocm-common/pkg/file/file.go
vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/bastion.go
vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/instance.go
vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/key_pair.go
vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/proxy.go
vendor/modules.txt

```
lixue@Xue-Lis-MacBook-Pro rosa % export REGION=ap-northeast-1
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo run --label-filter day1-prepare tests/e2e
Random Seed: 1715321526
Will run 1 of 59 specs
SSSSSSSSSSSSStime="2024-05-10 14:14:46" level=info msg="Going to prepare a vpc with name xueli-ezzmx0aqk2zzcv, on region ap-northeast-1, with cidr 10.0.0.0/16 "
time="2024-05-10 14:14:46" level=info msg="Going to create vpc and the follow resources on zones: "
time="2024-05-10 14:14:47" level=info msg="Create vpc success vpc-0e17b9398f9eb6a5c"
time="2024-05-10 14:14:48" level=info msg="Tag resource vpc-0e17b9398f9eb6a5c successfully"
time="2024-05-10 …
```

OCM-7902 | ci: Bump ocm-common to support intellegient proxy

---

cmd/describe/machinepool/cmd.go
cmd/list/cmd.go
cmd/list/machinepool/cmd.go
cmd/list/machinepool/cmd_test.go
cmd/list/machinepool/main_test.go

Changes `list machinepools` to use the new default runner (created for `describe machinepool`. This also includes a suite of testing for the command itself, mocking API calls.

OCM-7257 | feat: Refactor list machine pool cmd to use new default runner

---

cmd/edit/machinepool/machinepool.go
cmd/edit/machinepool/machinepool_test.go

Able to set autoscaling min replicas to 0 for machine pools (classic) after fix:

OCM-7937 | fix: allow 0 min replicas for classic cluster autoscaling mp

---

cmd/describe/machinepool/cmd_test.go
pkg/machinepool/output.go
pkg/machinepool/output_test.go
pkg/ocm/output/nodepools.go

This updates the output for `rosa describe machinepool` to include the list of `kubelet_configs` associated with the HCP MachinePool.

OCM-7269 | feat: Added list of kubeletconfigs to describe HCP machinepool output

---

cmd/list/cmd.go
cmd/list/kubeletconfig/cmd.go
cmd/list/kubeletconfig/cmd_suite_test.go
cmd/list/kubeletconfig/cmd_test.go
pkg/kubeletconfig/output.go
pkg/kubeletconfig/output_test.go
pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go
pkg/output/output.go
pkg/test/helpers.go

This PR adds support for the `rosa list kubeletconfigs` command. This supports KubeletConfigs on ROSA HCP clusters where it is possible to create one or more KubeletConfigs.
This command works for both HCP and Classic clusters. For Classic, there will only ever be one KubeletConfig.

OCM-7263 | feat: Add the ability to list KubeletConfigs for a cluster

---

tests/utils/exec/rosacli/report_portal.go

The step [rosa-test-e2e](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/51873/rehearse-51873-periodic-ci-openshift-openshift-tests-private-master-rosacli-aws-rosa-hcp-e2e-f3/1789151228039532544) always fails
```
error: failed to create/update secret: failed to update secret: Secret "aws-rosa-hcp-e2e-f3" is invalid: data: Too long: must have at most 1048576 bytes
```
The reason is that we should not put *.xml under the SHARED_DIR.

OCM-7927 | fix: Get the orgin junit file from ArtifactDir

---

tests/e2e/e2e_tear_down_test.go
tests/utils/exec/rosacli/cluster_service.go
tests/utils/profilehandler/data_cleaner.go
tests/utils/profilehandler/parse_info.go
tests/utils/profilehandler/profile_handler.go

[OCM-6318](https://issues.redhat.com//browse/OCM-6318) | ci: Build up deprovision step

OCM-6318 | ci: Build up deprovision step

---

cmd/list/machinepool/cmd_test.go
pkg/machinepool/machinepool.go
pkg/ocm/output/nodepools.go
pkg/ocm/output/nodepools_test.go
pkg/ocm/output/output_test.go

https://issues.redhat.com/browse/OCM-7924
```
➜  rosa git:(OCM-7924) ✗ ./rosa list machinepools -c magchen-hcp
ID       AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONE  SUBNET                    VERSION  AUTOREPAIR  
workers  Yes          2/2-5     m5.xlarge                          us-west-2a         subnet-0e1835a4c861e6a98  4.15.8   Yes         
```

OCM-7924 | fix: list machinepool should show inline

---

cmd/create/kubeletconfig/cmd.go
cmd/describe/kubeletconfig/cmd.go
cmd/edit/cmd.go
cmd/edit/kubeletconfig/cmd.go
cmd/edit/kubeletconfig/cmd_test.go
cmd/edit/kubeletconfig/kubeletconfig_suite_test.go
pkg/kubeletconfig/config.go
pkg/kubeletconfig/consts.go
pkg/kubeletconfig/options.go
pkg/kubeletconfig/options_test.go
pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go

This PR adds the ability to edit KubeletConfig for HCP clusters.

OCM-7265 | feat: Added the ability to edit KubeletConfigs for HCP clusters

---

cmd/edit/machinepool/machinepool.go
cmd/edit/machinepool/machinepool_test.go

FIXED:
A. min and max replicas set at 3
B. edit min replicas only to 0
C. result

OCM-7990 | fix: allow min_replicas 0 with edit machinepools

---

cmd/create/kubeletconfig/cmd.go
cmd/dlt/cmd.go
cmd/dlt/kubeletconfig/cmd.go
cmd/dlt/kubeletconfig/cmd_test.go
cmd/dlt/kubeletconfig/kubeletconfig_suite_test.go
cmd/edit/kubeletconfig/cmd.go
pkg/kubeletconfig/input.go
pkg/kubeletconfig/input_test.go
pkg/kubeletconfig/options.go
pkg/kubeletconfig/options_test.go
pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go

This PR updates `rosa delete kubeletconfig` with support for HCP clusters.

OCM-7266 | feat: Added support for delete of KubeletConfig for HCP clusters

---

tests/README.md

The [presubmit jobs]((https://github.com/openshift/release/blob/master/ci-operator/config/openshift/rosa/openshift-rosa-master__e2e-presubmits.yaml)) are used for validating the changes in the pull request before merging. The lifecycle of a presubmit job is `create a cluster` -> `do testing` -> `release resources`. The tester needs to select the corresponding configuration to trigger the job manually. These jobs are set to `optional: true` which means even if it is failed, it is not considered as a merging blocker.
Regularly, `do testing` focuses on the test case IDs that are gotten from the commit title in the format `<card id> | test: automated cases id:123456,123457`. If there is no test case ID, it will pick up the `Critical` ones. The testing results will be recorded in a junit.xml …

OCM-8012 | docs: Add presubmit readme for rosa CLI testing

---

pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go

The `--name` arg is optional when creating a `KubeletConfig`. If omitted, it will be generated on the server-side. We need to ensure we do not send an empty string as the name if the user has not supplied the arg.

OCM-7264 | fix: Ensured that name is optional when creating a KubeletConfig

---

cmd/dlt/accountroles/cmd.go
cmd/dlt/operatorrole/cmd.go
pkg/aws/client.go
pkg/aws/mock_client.go
pkg/aws/policies.go
pkg/aws/policies_test.go

[OCM-7860](https://issues.redhat.com//browse/OCM-7860) | fix: add detach commands for arbitrary policies in rosa delete roles commands
https://issues.redhat.com/browse/OCM-7860

OCM-7860 | fix: add detach commands for arbitrary policies

---

cmd/create/machinepool/cmd.go
cmd/create/machinepool/nodepool.go
pkg/ocm/kubeletconfig.go
pkg/ocm/kubeletconfig_test.go

This PR updates the `rosa create machinepool` command with support for the `--kubelet-configs` option, that allows the user to specify a list of KubeletConfig `name` to attach to a specific HCP MachinePool.

OCM-7268 | feat: Update create machinepool command to support kubeletconfigs

---

cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/nodepool.go

This PR adds the `--kubelet-configs` flag to the `rosa edit machinepool` command.

OCM-8020 | feat: Update rosa edit machinepool command for kubeletconfig support

---

tests/e2e/test_rosacli_node_pool.go
tests/utils/common/string.go
tests/utils/exec/rosacli/machinepool_service.go
tests/utils/exec/rosacli/ocm_resource_service.go

[OCM-7857](https://issues.redhat.com//browse/OCM-7857)
$ ginkgo --focus 73492 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-6729 | test: automate id:OCP-73492 create/describe nodepool with tags

---

cmd/create/kubeletconfig/cmd.go
cmd/create/kubeletconfig/cmd_test.go
cmd/describe/kubeletconfig/cmd.go
cmd/describe/kubeletconfig/cmd_test.go
cmd/dlt/kubeletconfig/cmd.go
cmd/dlt/kubeletconfig/cmd_test.go
cmd/edit/kubeletconfig/cmd.go
cmd/edit/kubeletconfig/cmd_test.go
pkg/kubeletconfig/config.go
pkg/kubeletconfig/consts.go

Without the `--name` option, we rely on the generated name from the server-side which can be a little cumbersome. This enforces a better practice in `rosa` where we encourage customers to explicitly name their `KubeletConfig` for better readability.

OCM-8058 | fix: Ensure --name option is required for working with KubeletConfigs on HCP clusters

---

pkg/kubeletconfig/output.go
pkg/kubeletconfig/output_test.go

Ensure we print the `ID` of the `KubeletConfig` in `rosa describe kubeletconfig`.

OCM-8057 | fix: Ensure the ID of the KubeletConfig is printed by `rosa describe kubeletconfig`

---

cmd/create/machinepool/cmd.go
cmd/create/machinepool/nodepool.go
cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/nodepool.go
pkg/machinepool/validation.go
pkg/machinepool/validation_test.go

This PR tidies up the presentation and validation of the allowed kubelet-configs for a HCP machinepool. Currently whilst the flag is named `--kubelet-configs`, we only support a single entry. This allows us to proceed without having to rename the flag in the future, but makes it much clearer to the user, that at this time, a single kubeletconfig is supported.
This is enforced on the backend, but this provides a better UX for customers using `rosa`.

OCM-8075 | fix: Ensure users can only supply a single kubeletconfig for HCP MachinePools

---

cmd/edit/machinepool/nodepool.go
cmd/edit/machinepool/nodepool_test.go
pkg/kubeletconfig/input.go

When a user edits the `kubeletconfigs` on their HCP `Machinepool`, we must show them a warning as this will cause all nodes in the nodepool to be recreated to adjust to the new PIDs limit.

OCM-8076 | fix: Ensure the user is prompted if they change the kubeletconfig on their HCP MachinePool

---

cmd/describe/kubeletconfig/cmd.go
cmd/describe/kubeletconfig/cmd_test.go
cmd/dlt/kubeletconfig/cmd.go
cmd/edit/kubeletconfig/cmd.go
cmd/edit/kubeletconfig/cmd_test.go

For ROSA Classic clusters, the user does not need to pass the `--name` flag to any of the `rosa kubeletconfig` command e.g `rosa create kubeletconfig` because there is only ever a single KubeletConfig for ROSA classic.
However, if the user does decide to pass the `--name` flag, we should verify the KubeletConfig matches so that they get the correct failure and we don't just change things that don't meet their expectations.

OCM-8055 | fix: Check kubeletconfig exists by name if user specifies it for Classic cluster

---

cmd/revoke/breakglasscredential/breakglasscredential_suite_test.go
cmd/revoke/breakglasscredential/cmd.go
cmd/revoke/breakglasscredential/cmd_test.go

```
./rosa revoke break-glass-credentials -c magchen-hcp2
I: There are no break glass credentials for cluster 'magchen-hcp2'
```

OCM-7855 | fix: return message if there is no breakglass can be revoked

---

cmd/create/kubeletconfig/cmd.go
cmd/describe/kubeletconfig/cmd.go
cmd/dlt/kubeletconfig/cmd.go
cmd/edit/kubeletconfig/cmd.go
pkg/kubeletconfig/options.go
pkg/kubeletconfig/options_test.go

This PR updates the `rosa create kubeletconfig`, `rosa edit kubeletconfig`, `rosa delete kubeletconfig` and `rosa describe kubeletconfig` commands to allow the user to specify the name of the kubeletconfig as a positional arg on the command line.
With this change, the following is now valid as an example:
- `rosa describe kubeletconfig -c mycluster high-pids`
The `--name` flag will always take precedence, so in the following, the name of the kubeletconfig will be `foo`
- `rosa create kubeletconfig -c mycluster --name foo bob`
This aligns us with the UX of other commands.

OCM-8059 | fix: Allow users to use positional args for specifying the name of kubeletconfig

---

cmd/describe/breakglasscredential/cmd.go
cmd/describe/breakglasscredential/cmd_test.go

https://issues.redhat.com/browse/OCM-8121
```
➜  rosa git:(OCM-8121) ✗ ./rosa list break-glass-credentials -c magchen-hcp2
ID                                USERNAME                              STATUS
2baig810g13ubbnspfehadar43v1jdou  39ceefd8-1461-11ef-a9e0-1eb8df358bc1  expired
➜  rosa git:(OCM-8121) ✗ ./rosa describe break-glass-credential 2baig810g13ubbnspfehadar43v1jdou -c magchen-hcp2 --kubeconfig
W: Break glass credential '2baig810g13ubbnspfehadar43v1jdou' for cluster 'magchen-hcp2' is now expired.
➜  rosa git:(OCM-8121) ✗ 
```

OCM-8121 | fix: Show correct describe message for expired breakglass

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
pkg/ocm/helpers.go

https://issues.redhat.com/browse/OCM-6569

OCM-6569 | fix: Hide the duplicate output of operator roles

---

pkg/info/info.go

*WHAT*
Bumping version to current release +1 for master branch

OCM-6900 | chore: bump version to 1.2.41

---

tests/e2e/test_rosacli_kubelet_config.go
tests/e2e/test_rosacli_node_pool.go
tests/utils/exec/rosacli/machinepool_service.go

```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -focus "(73766|73765)" tests/e2e
Random Seed: 1715860725
Will run 2 of 76 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS••S
Ran 2 of 76 Specs in 146.539 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 74 Skipped
PASS
Ginkgo ran 1 suite in 2m33.920982807s
```

OCM-8045 | test: automated ids:73765,73766 to support machinepool with kubeletconfig

---

tests/e2e/test_rosacli_node_pool.go

$ ginkgo --focus 56782 tests/e2e/
2.14.0
Ginkgo CLI. …

SDA-7166 | test: automate id:56782 removed validation checkpoint

---

cmd/upgrade/accountroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/commandbuilder/helper/roles/roles.go
pkg/aws/sts.go

fixed two problems in current upgrade flow:
1. for manual mode, add the attach policy command if the policy not attache to the target role
2. always find the account/operator-role's default policy by awsClient's function: GetAccountRoleDefaultPolicy/GetOperatorRoleDefaultPolicy. Current logic will regard the only attached policy as the default policy and upgrade it.
https://issues.redhat.com/browse/OCM-7985
https://issues.redhat.com/browse/OCM-7986
https://issues.redhat.com/browse/OCM-7987

OCM-7985 | fix: add attach policy command for rosa upgrade roles

---

cmd/dlt/operatorrole/cmd.go

https://issues.redhat.com/browse/OCM-8080
in current logic, the commands to detach arbitrary poclies will overwrite the command to detach managed policy. Fix this problem in this pr

OCM-8080 | fix: fix problem in delete operator roles manual mode

---

tests/e2e/test_rosacli_machine_pool.go

output:
```
$ CLUSTER_ID=2b99vnpc3u6ktad4ad28ana0m67o7j7f ginkgo -focus 43252 tests/e2e/
Running Suite: e2e tests suite - /home/jericho/work/repos/rosa/tests/e2e
========================================================================
Random Seed: 1715798790
Will run 1 of 67 specs
SSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 67 Specs in 4.411 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 66 Skipped
PASS
Ginkgo ran 1 suite in 5.371714118s
```

OCM-8053 | test: Automated id:43252 validating inputs for creating spot machinepools

---

tests/ci/data/profiles/rosa-classic.yaml
tests/utils/profilehandler/profile_handler.go

```
2024-05-21T19:26:54+08:00 - INFO : Running command: rosa describe cluster -c 2bd2l8jg9tofg8eufp4d79tcvsjptivv
Got need redacted string from log match regex (arn:aws:[a-z]+:[a-z0-9-]*:)([0-9]{12})(:)
Got need redacted string from log match regex (AWS Account:\s*)([0-9]{12})([\n\\n].)
2024-05-21T19:26:59+08:00 - DEBUG : Get Combining Stdout and Stder is :
Name:                       xueli-wiahroj31
Domain Prefix:              xueli-wiahroj31
Display Name:               xueli-wiahroj31
ID:                         2bd2l8jg9tofg8eufp4d79tcvsjptivv
External ID:                
Control Plane:              Customer Hosted
OpenShift Version:          
Channel Group:              candidate
DNS:                        Not ready
AWS Account:                *************
API URL: …
```

OCM-8142 | test: Fix the rosa-private-link and rosa-non-sts-advanced creation issue

---

cmd/describe/breakglasscredential/cmd_test.go
cmd/dlt/machinepool/cmd.go

```
./rosa delete machinepool -c magchen-hcp workers -y
E: Error deleting machinepool: Failed to delete machine pool 'workers' on hosted cluster 'magchen-hcp': The last node pool can not be deleted from a cluster.
echo $?
1
```
https://issues.redhat.com/browse/OCM-8136

OCM-8136 | fix: Delete should exit 1 if fails

---

cmd/describe/machinepool/cmd.go
cmd/describe/machinepool/cmd_test.go
cmd/describe/machinepool/options.go
cmd/describe/machinepool/options_test.go
cmd/dlt/cmd.go
cmd/dlt/machinepool/cmd.go
cmd/dlt/machinepool/cmd_test.go
cmd/dlt/machinepool/main_test.go
cmd/dlt/machinepool/options.go
cmd/dlt/machinepool/options_test.go

[OCM-7259](https://issues.redhat.com//browse/OCM-7259)
---
* E2E tests for high coverage of command + associated functions
* Every route covered AFAIK
* Testing of new options files + validations including regex validation for both hypershift and classic
* New runner for `delete machinepool` command

OCM-7259 | feat: E2E delete machinepool cmd tests; new runner

---

pkg/aws/policies.go
pkg/aws/policies_test.go

[OCM-8276](https://issues.redhat.com//browse/OCM-8276)

OCM-8276 | fix: don't show empty lines when filtering version on acc roles

---

tests/e2e/dummy_test.go
tests/e2e/test_rosacli_verify.go

Tests succeed locally on clusters that have the prerequisites and fail on clusters that do not:
##Success for 60082 with kms key cluster##
```
oaharoni-mac:rosa oaharoni$ export CLUSTER_ID=oa-byok3
oaharoni-mac:rosa oaharoni$ ginkgo -focus id:60082 tests/e2e/
Running Suite: e2e tests suite - /Users/oaharoni/rosa_workspace/rosa/tests/e2e
==============================================================================
Random Seed: 1716392444
Will run 1 of 79 specs
SSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 79 Specs in 0.900 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 78 Skipped
PASS
Ginkgo ran 1 suite in 4.311993292s
```
##Failure for 60082 with non-kms key cluster##
```
oaharoni-mac:rosa oaharoni$ export …
```

OCM-8072 | test: automated ids:60082,42188

---

tests/ci/config/config.go
tests/e2e/e2e_setup_test.go
tests/utils/exec/rosacli/cmd_runner.go
tests/utils/log/logger.go
tests/utils/profilehandler/data_preparation.go
tests/utils/profilehandler/profile_handler.go

What I did in the PR
When set `WAIT_SETUP_CLUSTER_READY=false` then the cluster preparation will only create the cluster and exit without waiting for cluster ready.
If want to wait for cluster ready after cluster is prepared run command `ginkgo -focus WaitClusterReady tests/e2e`
I split out the resources recording, so any resources need to be pass to destroy step will be recorded once created. It will make the risk of resource leak to the lowest for destroy

OCM-8257 | ci: Split creation out and split cluster waiting out and make autoscaler value to 10

---

tests/e2e/test_rosacli_idp.go

[OCM-8299](https://issues.redhat.com/browse/OCM-8299) 
$ ginkgo --focus 53031 tests/e2e
2.11.0
Ginkgo CLI. …

SDA-4924 | fix: error message for invalid username validation for idp creation

---

cmd/edit/machinepool/nodepool.go

[OCM-8283 ](https://issues.redhat.com/browse/OCM-8283)- Fixing bug to stop kubelet-config warning showing up when kubelet configs are not specified.

OCM-8283 | fix: kubelet-config edit prompt no longer shows up when kubelet-configs are not targeted

---

tests/e2e/test_rosacli_cluster.go
tests/utils/exec/rosacli/cluster_service.go

$ ginkgo --focus 73725 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-5530 | test: automate id:73725,73814 validation of network type for hcp cluster creation

---

pkg/aws/policies.go

https://issues.redhat.com/browse/OCM-8336
Don't check arbitrary policies when checking whether a roles needs to be upgraded or not

OCM-8336 | fix: only check redhat managed policies when upgrade roles

---

cmd/describe/breakglasscredential/cmd.go
cmd/describe/breakglasscredential/cmd_test.go

https://issues.redhat.com/browse/OCM-8129

OCM-8129 | fix: hide unnecessary kubeconfig info

---

tests/e2e/test_rosacli_network_verifier.go

```
[yingzhan@localhost rosa]$ ginkgo -focus 68751 tests/e2e/
Running Suite: e2e tests suite - /home/yingzhan/autotest/rosa/tests/e2e
=======================================================================
Random Seed: 1717061657
Will run 1 of 92 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 92 Specs in 25.090 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 91 Skipped
PASS
Ginkgo ran 1 suite in 27.801842499s
```

OCM-8332 | test: automated id:68751

---

tests/e2e/test_rosacli_verify.go
tests/utils/profilehandler/profile_handler.go

`$ ginkgo --focus 60082 tests/e2e/
2.14.0
Ginkgo CLI.
version of the Ginkgo library …

OCM-8072 | test: fixing id:60082,42188 ci failures

---

tests/e2e/test_rosacli_idp.go

[OCM-8299](https://issues.redhat.com//browse/OCM-8299)
$ ginkgo --focus 53031 tests/e2e
2.11.0
Ginkgo CLI. …

OCM-8299 | fix: id:53031 update the error message

---

tests/e2e/hcp_external_auth_test.go
tests/utils/exec/rosacli/cmd_client.go
tests/utils/exec/rosacli/external_auth_provider_service.go

$ ginkgo --focus 72536 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-4459 | test: automate id:72536 create/list/describe/delete external_auth_provider for hcp cluster

---

tests/README.md
tests/e2e/dummy_test.go
tests/e2e/e2e_tear_down_test.go
tests/utils/log/constants.go
tests/utils/log/logger.go
tests/utils/log/sensitive_hook.go

aka logrus instead of ocm-sdk logging
and added a sensitive hook to filter out sensitive data
https://issues.redhat.com/browse/OCM-6706
<details>
<summary>Logs</summary>
$ ginkgo -focus logstreamsensitivedata tests/e2e/
[...]
ROSA CLI Test logstreamsensitivedata [It] 
/home/tradisso/projects/openshift/rosa/tests/e2e/dummy_test.go:101
Timeline >>
time=2024-06-03T14:40:53+02:00 level=info msg=rosa create cluster --billing-account *************
time=2024-06-03T14:40:53+02:00 level=info msg=--password ************* endofpassword
time=2024-06-03T14:40:53+02:00 level=info msg=beginning --client-id ************* end
</details>

OCM-6706 | ci: Use CLI logger

---

tests/utils/exec/rosacli/cluster_service.go
tests/utils/exec/rosacli/version_service.go
tests/utils/profilehandler/data_preparation.go
tests/utils/profilehandler/profile_handler.go

```
lixue@Xue-Lis-MacBook-Pro rosa % ginkgo -label-filter day1-prepare tests/e2e
Random Seed: 1717415423
Will run 1 of 91 specs
SSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 91 Specs in 2542.600 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 90 Skipped
PASS
Ginkgo ran 1 suite in 42m29.657290157s
```
And cluster is in version of
```
{
"kind": "Version",
"id": "openshift-v4.15.11-candidate",
"href": "/api/clusters_mgmt/v1/versions/openshift-v4.15.11-candidate",
"raw_id": "4.15.11",
"channel_group": "candidate",
"available_upgrades": [
"4.15.12",
"4.15.13",
"4.15.14", …
```

OCM-8145 | test: Fix the non-oidc cluster preparation issue due to parser error

---

tests/e2e/test_rosacli_idp.go

$ ginkgo --focus 35878 tests/e2e/
2.14.0
Ginkgo CLI. …

SDA-2922 | test: fixing id:35878 ci failures

---

tests/ci/data/profiles/rosa-hcp.yaml

[OCM-8145](https://issues.redhat.com//browse/OCM-8145) | test: Fix account role path in profile.
The CI would fail with the previous path config, https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/52699/rehearse-52699-periodic-ci-openshift-rosa-master-e2e-rosa-hcp-private-link-f3/1797601791043440640/artifacts/rosa-hcp-private-link-f3/rosa-cluster-setup/build-log.txt
$ ./rosa create account-roles --prefix yw0604acr --mode auto -y --path /test/hcp/ 
I: Logged in as 'sdqe-regular02' on 'https://api.stage.openshift.com'
I: AWS quota ok. If cluster installation fails, validate actual AWS resource usage against …

OCM-8145 | test: Fix account role path in profile

---

cmd/edit/machinepool/nodepool.go
cmd/edit/machinepool/nodepool_test.go

We always pass the replicas when editing a machinepool, even if the value has not changed, as this will then be a no-op. Right now we are not setting replicas if they are the same as the current value and this result in an error returned to the user.
Related: [OCM-8337](https://issues.redhat.com//browse/OCM-8337)

OCM-8337 | fix: [HCP] always set replicas when updating machinepools

---

cmd/list/operatorroles/cmd.go

[OCM-7587](https://issues.redhat.com/browse/OCM-7587) Removing prefix prompt if not in interactive mode

OCM-7587 | feat: removing interactive mode as default for prefix prompt

---

pkg/clusterautoscaler/output.go
pkg/clusterautoscaler/output_test.go

```
$ rosa describe autoscaler -c 2bndda12o4i1neutfftama44j5ke87v1
Balance Similar Node Groups: Yes
Skip Nodes With Local Storage: Yes
Log Verbosity: 4
Labels Ignored For Node Balancing: aaa
Ignore DaemonSets Utilization: Yes
Maximum Node Provision Time: 10m
Maximum Pod Grace Period: 0
Pod Priority Threshold: 0
Resource Limits:
Maximum Nodes: 1000
Minimum Number of Cores: 0
Maximum Number of Cores: 100
Minimum Memory (GiB): 0
Maximum Memory (GiB): 4096
GPU Limitations:
Type: nvidia.com/gpu
Min: 0
Max: 10
Type: amd.com/gpu
Min: 1
Max: 5
Scale Down:
Enabled: Yes
Node Unneeded Time: 10s
Node Utilization Threshold: 0.500000
Delay After Node Added: 10s
Delay After Node Deleted: 10s
Delay After Node Deletion Failure: 10s
```

OCM-8587 | fix: colon not present in some field for describing autoscaler to a cluster

---

pkg/aws/helpers.go
pkg/aws/helpers_test.go

In https://issues.redhat.com/browse/OCM-7918 the code is working as intended, it just parses the tag as having too many delimiters because the value is not separated by a space. Since spaces are not allowed in tag key/values but `:` is, it makes more sense to use a space as a delimiter in the error message to avoid confusion on how the tags are parsed.

OCM-7918 | fix: use space delimiter in AWS tags error msg to avoid confusion

---

tests/e2e/rosa_autoscaler_test.go
tests/utils/exec/rosacli/autoscaler_service.go
tests/utils/exec/rosacli/cmd_client.go

$ ginkgo --focus 67275 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-8636 | test: automate id:67275 create/describe/edit/delete cluster autoscaler by rosacli

---

tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_network_verifier.go
tests/e2e/test_rosacli_node_pool.go

$ ginkgo --focus "(45161|68751|73492)" tests/e2e/
2.14.0
Ginkgo CLI.
version of the …

OCM-8662 | test: fixing id:45161,68751,73492 ci failures

---

cmd/version/cmd.go

[OCM-8680](https://issues.redhat.com//browse/OCM-8680)

OCM-8680 | fix: err not being caught on rosa version

---

cmd/create/cluster/cmd.go
cmd/describe/cluster/cmd.go
cmd/describe/cluster/cmd_test.go
cmd/edit/cluster/cmd.go
pkg/helper/roles/helpers.go
pkg/helper/roles/helpers_test.go
pkg/ocm/clusters.go

https://issues.redhat.com/browse/OCM-8315
Expose a new param: additional-allowed-principals for hcp create/edit clusters. This param allows users to set the additional allowed principals for their HCP.

OCM-8315 | feat: add additional allowed principals config for hcp clusters

---

tests/e2e/e2e_setup_test.go

output:
```
$ TEST_PROFILE=rosa-upgrade-z-stream ginkgo -focus 66372 tests/e2e/
Running Suite: e2e tests suite - /home/jericho/work/repos/rosa/tests/e2e
========================================================================
Random Seed: 1716222234
Will run 1 of 78 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 78 Specs in 124.927 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 77 Skipped
PASS
Ginkgo ran 1 suite in 2m9.195225649s
```

OCM-8051 | test: Automated id:66372 create cluster with invalid volume sizes

---

tests/ci/data/profiles/rosa-classic.yaml
tests/e2e/test_rosacli_cluster.go

zhewang@fedora:~/go/src/rosa$ ginkgo -focus 52691 tests/e2e/
2.14.0
Ginkgo CLI.
version …

OCM-8220 | test: Automated case id:52691 User can set availability zones

---

cmd/create/machinepool/cmd.go
cmd/create/machinepool/nodepool.go
cmd/describe/machinepool/cmd_test.go
cmd/edit/machinepool/cmd.go
cmd/edit/machinepool/nodepool.go
pkg/helper/machinepools/helpers.go
pkg/helper/machinepools/helpers_test.go
pkg/machinepool/output.go
pkg/machinepool/output_test.go
pkg/ocm/output/nodepools.go
pkg/ocm/output/nodepools_test.go

Adding back PR after it was reverted: https://github.com/openshift/rosa/pull/2140
Interactive only prompts for maxSurge and maxUnavailable if values are set as a command line property

OCM-7289 | feat: create/update of maxUnavailable and maxSurge for HCP nodepools

---

.gitignore
cmd/list/operatorroles/cmd.go
pkg/aws/client.go
pkg/aws/client_mock.go
pkg/aws/policies.go
pkg/aws/policies_test.go

[OCM-8867](https://issues.redhat.com//browse/OCM-8867)

OCM-8867 | fix: include prefix check for clusters running registered oidc configs

---

tests/e2e/rosa_autoscaler_test.go
tests/utils/exec/rosacli/autoscaler_service.go

$ ginkgo --focus 67275 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-8796 | test: fixing id:67275 test case enhancement

---

cmd/create/cluster/cmd.go

This was added as a way to let users know before attempting a deployment, that FIPS is not available for hosted control plane at this time.  This can be removed at a time when hosted control plane is FIPS validated.  See https://docs.aws.amazon.com/rosa/latest/userguide/rosa-deployment-options.html#rosa-deployment-model-differences for more details.

OCM-7961 | chore: update the fips flag description

---

tests/utils/log/constants.go

[OCM-8957](https://issues.redhat.com/browse/OCM-8957)  Mask the AWS billing account number in cluster installation error log message

Hide the aws billing account getting exposed in cluster installation log

---

tests/e2e/test_rosacli_idp.go

[OCM-8952](https://issues.redhat.com//browse/OCM-8952) 
$ ginkgo --focus 35878 tests/e2e
2.11.0
Ginkgo CLI. …

OCM-8952 | test: fixing id:35878

---

pkg/interactive/mode.go

https://issues.redhat.com/browse/OCM-5092

OCM-5092 | fix: remove empty line between mode descriptions in -h output

---

cmd/link/ocmrole/cmd.go
cmd/link/userrole/cmd.go

https://issues.redhat.com/browse/OCM-2730

OCM-2730 | fix: Update error message for linking ocm-role/user-role with not existed entries

---

cmd/describe/upgrade/cmd.go
cmd/describe/upgrade/cmd_test.go

Added status info in state description as part of https://issues.redhat.com/browse/OCM-6654. Need to expose the state description for HCP upgrade policies.

COM-7477 | feat: show state description for HCP upgrade policies

---

cmd/edit/machinepool/nodepool.go

This makes the CLI tests easier to automate, so that interactive mode does not need to be enabled to update max-surge/max-unavailable.
https://issues.redhat.com/browse/OCM-9140

OCM-9140 | fix: Do not enable interactive for max-surge and max-available

---

cmd/create/operatorroles/cmd.go

https://issues.redhat.com/browse/OCM-7851

OCM-7851 | fix: rosa create operator-roles should not support --cluster and --oidc-config-id at the same time

---

cmd/edit/machinepool/nodepool.go

https://issues.redhat.com/browse/OCM-7563

OCM-7563 | fix: validate node drain grace period when edit node pools

---

tests/e2e/test_rosacli_node_pool.go
tests/utils/exec/rosacli/machinepool_service.go

`$ ginkgo --focus "(74430|74387)" tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-9178 | test: automate id:74430,74387 create/edit/describe nodepool with maxsurge/maxunavailable

---

tests/utils/exec/rosacli/cmd_runner.go

Fix typo in info logger message in runner

OCM-9191 | fix: typo in logger info message for output of command

---

cmd/create/cluster/cmd.go
cmd/create/cluster/cmd_test.go

Example output after fix:
Originally intended to import over IAM duplicate check function (https://github.com/openshift-online/ocm-common/commit/35b747cbb4b66396d4f6e650210dcc62b08713aa)  from ocm-common; however,
decided not to do this, due to needing to eval the IAM roles prior to the create request being sent.

OCM-9166 | fix: prevent same role arns for IAM roles of the same cluster

---

tests/e2e/rosa_autoscaler_test.go
tests/utils/config/support.go
tests/utils/exec/rosacli/autoscaler_service.go

[OCM-9242](https://issues.redhat.com//browse/OCM-9242)
rosa-hcp-external-auth-profile ouput log :- https://privatebin.corp.redhat.com/?3dba00b04ae84ce3#D6nobqyF6TCoUVizR7uiif8NYAifp5JCkvJ4kdQajdkB 
67275 output log :- 
$ ginkgo --focus 67275 tests/e2e/
2.14.0
go run …

OCM-9225 | test: fixing id:67275 ci fix

---

cmd/create/machinepool/nodepool.go

https://issues.redhat.com/browse/OCM-8453

OCM-8453 | fix: --multi-availability-zone flag must not be supported for HCP cluster while creating nodepool

---

tests/utils/exec/rosacli/machinepool_service.go

Update naming for Subnets in Machinepool structure. 
`ginkgo run -focus 52764 tests/e2e
2.14.0
Ginkgo CLI. …

OCM-9301 | test: fixing id 52764

---

hack/release-list-jiras.sh

the regex '\s' for white space does not work in bash of Macos, replace it with '[[:space:]]' to make the script can work well ono both Fedora and Macos

OCM-9116 | fix: make regex match works on bash

---

tests/e2e/test_rosacli_idp.go

[ocm-9240](https://issues.redhat.com//browse/ocm-9240) [CI]Debug and fix: 49137, 53031
$ ginkgo --focus "(53031|49137)" tests/e2e/
2.11.0
Ginkgo CLI.
If you are …

OCM-9240 | test: fixing id:49137,53031

---

tests/e2e/test_rosacli_ocm_role.go
tests/e2e/test_rosacli_oidc_config.go
tests/utils/common/oidc.go
tests/utils/exec/rosacli/ocm_resource_service.go

[OCM-9409](https://issues.redhat.com//browse/OCM-9409) | test: automate id:52106,64620
logs: https://privatebin.corp.redhat.com/?b62fe62ded1eb759#7pMG4yBTU1bXNGKLA5KekJGNDndC2RsMBtP27M7NNKLy
52106 is checking and removing ocm-role and user-role to make sure the operation via rosacli should work well without the linked ocm-role and user -role.
64620: test for registering unmanaged oidc-config

OCM-9409 | test: automate id:52106,64620

---

cmd/create/machinepool/nodepool.go
pkg/machinepool/machinepool.go

Expose maxSurge and maxUnavailable in interactive mode without both being specified in the args, which was intentionally done to make it less accessible until it's been in production for a while.
https://issues.redhat.com/browse/OCM-9139

OCM-9139 | fix: Enable maxSurge and maxUnavailable for interactive mode

---

tests/e2e/test_rosacli_oidc_config.go
tests/e2e/test_rosacli_token.go
tests/utils/exec/rosacli/cmd_runner.go

[OCM-9596](https://issues.redhat.com//browse/OCM-9596) | test: fix ids:72162,64620 fix failures on PROW CI testing
72162: use '-d' as the original '-D' only supports on MacOS
64620: Add function and to run command in manual mode in tmp dir to avoid the failure of missing permission
Logs are here,https://privatebin.corp.redhat.com/?6de329c37662c528#DLdY23pjwPy7gV13Lh8tP2B5KDgfaTkbHG4rPgbXmZHr

OCM-9596 | test: fix ids:72162,64620 fix failures on PROW CI testing

---

cmd/login/cmd.go
pkg/fedramp/config.go

Client ID used for keycloak auth is the same for all envs, no need to define it multiple times depending on env
Updates logic to set the appropriate client id when FedRAMP is enabled  and the `--admin` flag is not passed
Changes are mostly for code cleanliness

OSD-22376 | refactor: updates fedramp client id configuration

---

tests/e2e/test_rosacli_account_roles.go
tests/e2e/test_rosacli_operator_roles.go
tests/utils/common/role.go

OCP-57408 - Create/Delete/List account-roles with managed account-roles policies
OCP-60956 - Delete BYO operator-roles/oidc via rosacli by command
OCP-74761 - Delete in-used BYO operator-roles/oidc via rosacli by command 
logs:  https://privatebin.corp.redhat.com/?3741e71914dc73e1#7KaAHJRzix1edFUYYwKae5iuZKzmCymzDGPXowfkShCd

OCM-9293 | test: automate id:60956,57408,74761

---

tests/e2e/test_rosacli_network_verifier.go
tests/utils/config/support.go

$ ginkgo --focus 64917 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-9618 | test: fixing id:64917 hcp ci fix

---

cmd/create/breakglasscredential/cmd.go
pkg/ocm/break_glass_credential.go
pkg/ocm/break_glass_credential_test.go

This PR updates the break glass credential implementation to allow the caller to specify the poll interval and timeout. This allows us more control in the tests to avoid the long timeouts.

OCM-9626 | fix: Fixed slow tests for break glass credential implementation

---

cmd/create/machinepool/cmd.go

maxSurge and maxUnavailable for create HCP NPs were accidentally removed in MR: 
https://github.com/openshift/rosa/pull/2142
Adding it back.
Jira: https://issues.redhat.com/browse/OCM-9645

OCM-9645 | fix: Add back maxSurge and maxUnavailabe for create HCP NPs

---

tests/ci/labels/features.go
tests/ci/labels/runtime.go
tests/e2e/test_rosacli_hibernate.go
tests/utils/exec/rosacli/cluster_service.go
tests/utils/exec/rosacli/cmd_runner.go

[OCM-9653](https://issues.redhat.com//browse/OCM-9653) | test: automate id:42832 hibernate and resume then delete cluster via rosacli
Logs: https://privatebin.corp.redhat.com/?c2f3d22d760d093a#HT8AbcXPmEdXGFCaqqfSZ554TVpj1gCCYHbz1qKQwx98

OCM-9653 | test: automate id:42832 hibernate and resume then delete cluster via rosacli

---

cmd/create/machinepool/cmd.go

Fixes: 
- https://issues.redhat.com/browse/OCM-9655
- https://issues.redhat.com/browse/OCM-9620
- https://issues.redhat.com/browse/OCM-9654
- https://issues.redhat.com/browse/OCM-9625
Fixing regression changes

OCM-7184 | fix: Fixing regression problems for OCM-9620,OCM-9655,OCM-9654,OCM-9625

---

cmd/create/cluster/cmd.go
cmd/create/machinepool/cmd.go
cmd/describe/machinepool/cmd_test.go
pkg/machinepool/helper.go
pkg/machinepool/helper_test.go
pkg/machinepool/machine_pool_args.go
pkg/machinepool/machinepool.go
pkg/machinepool/output.go
pkg/machinepool/output_test.go
pkg/ocm/output/nodepools.go

several changes:
- update cluster creation flow to allow set ec2metadatahttptokens for hcp cluster(https://issues.redhat.com/browse/OCM-9159)
- add ec2metadatahttptokens flag and following support in machinepool creation(https://issues.redhat.com/browse/OCM-9176)
- print out the ec2metadatahttptokens info in machinepool describe command(https://issues.redhat.com/browse/OCM-9160)
this PR should be hold until CS side change is merged: https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/8229

OCM-8930 | feat: support IMDSv2 in HCP

---

tests/ci/config/config.go
tests/e2e/test_rosacli_cluster_post.go
tests/utils/profilehandler/profile_handler.go

https://issues.redhat.com/browse/OCM-9705
```
Healthy check cluster is multiarch - [id:75108] [feature-cluster, day1-post, High]
/home/tradisso/projects/openshift/rosa/tests/e2e/test_rosacli_cluster_post.go:310
STEP: Get the cluster @ 07/19/24 15:12:35.713
STEP: Init the client @ 07/19/24 15:12:35.713
time=2024-07-19T15:12:35+02:00 level=info msg=Loaded cluster profile configuration from original profile rosa-hcp-arm : {candidate rosa-hcp-arm  us-west-2 latest 0xc0010d1680 0xc001164410}
time=2024-07-19T15:12:35+02:00 level=info msg=Loaded cluster profile configuration from original cluster rosa-hcp-arm : {  m6g.xlarge  managed   0 0 0 0 0 false false false false false true false false false false false false false true false false false true false false false false true false false } …
```

OCM-9705 | ci: Setup COMPUTE_MACHINE_TYPE global env

---

tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_node_pool.go

[OCM-8933](https://issues.redhat.com//browse/OCM-8933)
$ ginkgo --focus 74387 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-9690 | test: update id:74387,64078

---

tests/utils/exec/rosacli/ocm_resource_service.go

[OCM-9769](https://issues.redhat.com//browse/OCM-9769) [CI] Debug and fix: create account-role needs timeout before returning.
$ export TEST_PROFILE=rosa-upgrade-z-stream
$ ginkgo run -label-filter day1 --timeout 2h tests/e2e
2.11.0
from a …

OCM-9769 | test: fix Add timeout after creating account-roles

---

pkg/machinepool/machinepool.go

[OCM-9617](https://issues.redhat.com//browse/OCM-9617) Adding version validation before validating httpToken to avoid panic when version is empty

OCM-9617 | feat: adding extra validation to fix panic introduced with httpTokens

---

cmd/create/operatorroles/cmd.go

https://issues.redhat.com/browse/OCM-7875

OCM-7875 | fix: Do not allow creating operator roles with managed policies role arn but no --hosted-cp flag 

---

tests/e2e/test_rosacli_cluster_post.go
tests/utils/common/constants/cluster.go

$ ginkgo --focus 75150 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-9865 | test: fix id:75150

---

tests/e2e/test_rosacli_cluster.go
tests/utils/common/string.go

[OCM-9288](https://issues.redhat.com//browse/OCM-9288) | test: automate id:60688 reuse operator-roles and oidc config
Log:https://privatebin.corp.redhat.com/?7e86348b7c31c68e#GEvGyKHSSY3tk9F97CZbya3bfCnjMnrcPzhCUeyCHWv1

OCM-9288 | test: automate id:60688 reuse operator-roles and oidc config

---

tests/ci/data/profiles/rosa-hcp.yaml

[aaraj@aaraj-thinkpadt14sgen1 rosa]$ rosa describe cluster -c 2cnqgcdb1r3fkhstogr7k9hc25e8g7mc -o json | jq -r .aws.ec2_metadata_http_tokens
required

OCM-8932 | ci: add support for imdsv2 for hcp cluster

---

cmd/edit/machinepool/cmd_test.go
cmd/edit/machinepool/options.go
cmd/edit/machinepool/options_test.go
pkg/machinepool/machinepool.go

Min/Max replicas were not validated properly, moved it to the options binding to allow for 0 command execution if input is invalid
Added test cases for each issue

OCM-9917 | fix: Bug related to editing min/max replicas (machinepools)

---

tests/e2e/test_rosacli_cluster_post.go
tests/utils/common/oidc.go
tests/utils/profilehandler/interface.go
tests/utils/profilehandler/profile_handler.go

Automate [OCM-9817](https://issues.redhat.com//browse/OCM-9817) | test: automate id:75210 delete byo oidc config via rosacli
Add OIDC Endpoint URL in the cluster_detail json file to be used by case
log : https://privatebin.corp.redhat.com/?0f1091b94db14286#GGEnV2oZ7wqiTsapzXYr8YFKi7MDrZh7yKAye6SwpFdP

OCM-9817 | test: automate id:75210 delete byo oidc config cluster via rosacli

---

tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_upgrade.go

60688,73731 to use cluster service to confirm if the cluster is HCP

OCM-9935 | test: fix ids: 60688,73731 to use cluster service to confirm if the cluster is HCP

---

tests/e2e/test_rosacli_cluster_post.go
tests/e2e/test_rosacli_node_pool.go
tests/utils/common/constants/general.go
tests/utils/config/support.go
tests/utils/exec/rosacli/machinepool_service.go

`$ ginkgo --focus "(75114|75227|56782)" tests/e2e/
2.14.0
Ginkgo CLI.
version of the …

OCM-8933 | test: automate id:75114,75227 hcp cluster/machinepool creation supports imdsv2

---

cmd/edit/machinepool/cmd_test.go
cmd/edit/machinepool/options.go
pkg/machinepool/machinepool.go
pkg/machinepool/validation.go
pkg/machinepool/validation_test.go

Replicas must be  >= 0
Can't set replicas when autoscaling enabled
interactive min/max replicas fix

OCM-9917 | fix: Issue with interactive + replicas edit machinepool

---

tests/ci/config/config.go
tests/e2e/test_rosacli_cluster_post.go
tests/e2e/test_rosacli_node_pool.go
tests/e2e/test_rosacli_upgrade.go

$ ginkgo --focus "(73492|75150)" tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-9967 | ci: fix id:73731,75150,73492

---

pkg/machinepool/validation.go
pkg/machinepool/validation_test.go

* Changed the minimum for max/min/non-autoscaling replicas to `0`, rather than `-1`, when editing machinepools
* Updated validation unit tests to use `-1` instead of `0`

OCM-9984 | fix: Change replica (min, max, and normal) minimum to 0

---

tests/e2e/test_rosacli_cluster_post.go
tests/e2e/test_rosacli_node_pool.go

$ ginkgo --focus "(59530|73492)" tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-9967 | ci: fix id:59530,73492

---

tests/e2e/test_rosacli_cluster_post.go
tests/utils/profilehandler/interface.go
tests/utils/profilehandler/profile_handler.go

Add OperatorRoleArn info in cluster-detail file for testing.
Automate 41822,75256 Create/Delete STS cluster successfully via rosacli

OCM-9296 | test: automate ids:41822,75256 Create/Delete STS cluster successfully via rosacli

---

tests/e2e/rosa_autoscaler_test.go

$ ginkgo --focus 67275 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-10024 | ci: fix id:67275

---

tests/e2e/test_rosacli_ingress.go

`jfrazier@jfrazier-mac  ~/workspace/rosa   jf_73538 ±  ginkgo run -focus 73538 tests/e2e
2.11.0
Ginkgo CLI. …

OCM-10011 | test: automated cases id:73538

---

tests/e2e/test_rosacli_machine_pool.go
tests/utils/exec/rosacli/ocm_resource_service.go

```
jfrazier@jfrazier-mac  ~/workspace/rosa   jf_72174 ±  ginkgo run -focus 72174 tests/e2e
2.11.0
Ginkgo CLI. …
```

OCM-9904 | test: automated cases id:72174

---

tests/e2e/test_rosacli_idp.go

[OCM-10020](https://issues.redhat.com//browse/OCM-10020) 
$ ginkgo --focus "(49137|53031)" tests/e2e/
2.11.0
Ginkgo CLI.
If you are attempting to test multiple …

OCM-10020 | test: fix id:49137,53031

---

tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_cluster_post.go
tests/e2e/test_rosacli_operator_roles.go

60688: the cluster version was not syncronized to ‘rosa describe cluster’ output, will enhance it to get the cluster version from the cluster config;
And it should skip to recover the role for HCP in AfterEach;
And change the domain-prefix in the dry-run command
59530: It should skip on NON-STS and NON-BYO-OIDC jobs, will fix later
74761: It failed as the region is not the aws default configured one, will fix by add region on `rosa delete oidc-config`
the log is here https://privatebin.corp.redhat.com/?45d42710aee1b787#A8cfxNR8vRxSUNneP4y7onD8vWM1sSvHbqTfpaxxrwXV

OCM-10143 | test: fix ids:60688,59530,74761

---

cmd/edit/machinepool/options.go
cmd/edit/machinepool/options_test.go

In the fix for [OCM-9974](https://issues.redhat.com//browse/OCM-9974), I had forgotten to also fix the options validations. This change is included here + updated tests

OCM-9974 | fix: Change options validations to allow 0 min replicas as well

---

tests/e2e/test_rosacli_machine_pool.go

[OCM-10175](https://issues.redhat.com//browse/OCM-10175) 
$ ginkgo --focus 67057 tests/e2e/
2.11.0
Ginkgo CLI. …

OCM-10175 | test: fix id:67057

---

cmd/version/cmd.go
cmd/version/cmd_test.go
cmd/version/options.go
cmd/version/options_test.go

The `--client` and `--verbose` arguments currently do nothing as they are always evaluated as `false`
When executing *rosa version* he *--client* and *--verbose* arguments do nothing as they are always evaluated as *false*
**Current**
```sh
I: 1.2.43
I: Your ROSA CLI is up to date.
I: 1.2.43
I: Your ROSA CLI is up to date.
```
**Expected**
```sh
I: 1.2.43
I: Information and download locations:
https://console.redhat.com/openshift/downloads#tool-rosa
https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/
I: Your ROSA CLI is up to date.
I: 1.2.43
```
This PR fixes the issue

OCM-10195 | fix: cmd/version arguments not being passed

---

cmd/dlt/accountroles/cmd.go

https://issues.redhat.com/browse/OCM-2394

OCM-2394 | fix: Delete classic and hosted-cp account roles automatically if -y flag is set

---

tests/e2e/test_rosacli_upgrade.go

`$ ginkgo --focus 57094 tests/e2e/
2.14.0
Ginkgo CLI.
version of the Ginkgo library …

OCM-10263 | ci: fix id:57094

---

cmd/edit/cluster/cmd.go

There was confusion around how to use this boolean flag and some users believed that it could only be disabled.
[OSDOCS-11559](https://issues.redhat.com//browse/OSDOCS-11559)

OSDOCS-11559 | docs: Add example for enabling UWM day-2

---

tests/e2e/test_rosacli_idp.go
tests/e2e/test_rosacli_node_pool.go

`$ ginkgo --focus "(73391|65160)" tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-10298 | ci: fix id:73391,65160

---

tests/e2e/test_rosacli_cluster_post.go
tests/e2e/test_rosacli_machine_pool.go
tests/e2e/test_rosacli_region.go

`$ ginkgo --focus "(75527|72174)" tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-10331 | ci: fix id:72174,75527

---

cmd/create/cluster/cmd.go

Unhide the flag as the feature is ready for release
Related: [OCM-10303](https://issues.redhat.com//browse/OCM-10303)

OCM-10303 | feat: unhide no-cni flag at cluster creation

---

cmd/logs/install/cmd.go
cmd/logs/uninstall/cmd.go
pkg/config/config.go
pkg/config/config_test.go
pkg/ocm/client.go
pkg/ocm/client_test.go

Modifies the behavior for token management in ROSA
* **Before**: When the initial access token is expired, new access tokens would not be persisted to the config, ROSA would use the refresh token to get a new access token on every request
* **Now**: New tokens are always persisted to the OCM configuration. This will allow the SDK to use valid tokens more often and prevent additional round-trips to SSO
* **On log polling**: On every callback request from getting updated logs during a watch, tokens will now be refreshed. This is required for environments with short-lived refresh tokens such as FedRAMP.

OCM-9704 | feat: persist refreshed tokens

---

cmd/create/oidcprovider/cmd.go
pkg/ocm/oidc_config.go

https://issues.redhat.com/browse/OCM-6419
Replaces ROSA based fetching for thumbprint with backend (CS) API calls to circumvent inability to fetch thumbprints when users use a proxy

OCM-6419 | feat: Move fetching thumbprint from ROSA to backend

---

cmd/edit/ingress/cmd_test.go
cmd/edit/ingress/flags.go

[OCM-10459](https://issues.redhat.com//browse/OCM-10459)

OCM-10459 | fix: trim double quotes of component route parameter

---

cmd/create/accountroles/creators.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/by_clusterkey.go
cmd/create/operatorroles/by_prefix.go
cmd/create/userrole/cmd.go
cmd/install/addon/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/client_mock.go
pkg/aws/policies.go
pkg/helper/roles/helpers.go

https://issues.redhat.com/browse/OCM-7551
sample output when creating account-roles
```
I: Creating classic account roles using 'arn:aws:iam::765374464689:user/llan@redhat.com'
I: Attached trust policy to role 'test-Support-Role': {"Version": "2012-10-17", "Statement": [{"Action": ["sts:AssumeRole"], "Effect": "Allow", "Principal": {"AWS": ["arn:aws:iam::644306948063:role/RH-Technical-Support-12541229"]}}]}
I: Created role 'test-Support-Role' with ARN 'arn:aws:iam::765374464689:role/test-Support-Role'
I: Attached policy 'arn:aws:iam::765374464689:policy/test-Support-Role-Policy' to role 'test-Support-Role'
I: Attached trust policy to role 'test-Installer-Role': {"Version": "2012-10-17", "Statement": [{"Action": ["sts:AssumeRole"], "Effect": "Allow", "Principal": {"AWS": …
```

OCM-7551 | feat: output content of trust policy attached to a role

---

tests/e2e/hcp_machine_pool_test.go

`jfrazier@jfrazier-mac  ~/workspace/rosa   jf_73638 ±  ginkgo run -focus 73638 tests/e2e
2.11.0
Ginkgo CLI. …

OCM-10506 | test: automated cases id:73638

---

pkg/aws/policies.go
pkg/aws/policies_test.go

*WHAT*
Roles with a large prefix and large operator-namespace lead to the role name being trimed to AWS conventions. This results in a regression in our filtering where we expect the role name to contain the operator-namespace. 
This change fetches the role tags and uses the tags to verify the operator namespace. The old check on the naming convention still remains if the operator-namespace tag is not found. 
*Verification* 
```
─ ~/Work/ocm/rosa  on OCM-10511 ···································································· ✔  took 24s  default eu-west-1    at 13:19:38 
╰─ aws iam list-roles --query "Roles[?starts_with(RoleName, 'rosacli-ci-y7tigturtqczcjrvyodmm')].RoleName"  | jq
[
"rosacli-ci-y7tigturtqczcjrvyodmm-openshift-cloud-credential-oper", …
```

OCM-10511 | fix: missing operator roles when filtering due to extended naming cutting the postfix

---

pkg/aws/policies.go

https://issues.redhat.com/browse/OCM-7551
https://issues.redhat.com/browse/OCM-7552
sample output when create account-roles
```I: Creating classic account roles using 'arn:aws:iam::765374464689:user/llan@redhat.com'
I: Attached trust policy to role 'testrole-Installer-Role(https://console.aws.amazon.com/iam/home?#/roles/testrole-Installer-Role)': {"Version": "2012-10-17", "Statement": [{"Action": ["sts:AssumeRole"], "Effect": "Allow", "Principal": {"AWS": ["arn:aws:iam::644306948063:role/RH-Managed-OpenShift-Installer"]}}]}
I: Created role 'testrole-Installer-Role' with ARN 'arn:aws:iam::765374464689:role/testrole-Installer-Role'
I: Attached policy 'arn:aws:iam::765374464689:policy/testrole-Installer-Role-Policy' to role 'testrole-Installer-Role(https://console.aws.amazon.com/iam/home?#/ro …
```

OCM-7551 | feat: add role console url in the output for policy attach

---

cmd/create/service/cmd.go
cmd/rosa/main.go
cmd/verify/rosa/cmd.go
cmd/version/cmd_test.go
cmd/version/options.go
pkg/aws/client.go
pkg/config/config.go
pkg/config/config_test.go
pkg/info/info.go
pkg/ocm/client.go
pkg/ocm/clusters.go
tests/e2e/test_rosacli_version.go

This is needed by arbitrary services which use the client package to communicate with ocm / rosa.

OCM-10455 | feat: Add a configuration for a custom user agent

---

cmd/create/oidcconfig/cmd.go
cmd/create/oidcprovider/cmd.go

Fixes issue where oidc provider was not automatically created when creating an oidc config due to neither an oidc config id, nor a cluster id being passed in

OCM-10450 | fix: Pass in OIDC Config ID when creating oidcprovider from create/oidcconfig

---

cmd/edit/autoscaler/autoscaler_suite_test.go
cmd/edit/autoscaler/cmd.go
cmd/edit/autoscaler/cmd_test.go
cmd/edit/cmd.go
pkg/clusterautoscaler/flags.go
pkg/clusterautoscaler/flags_test.go

https://issues.redhat.com/browse/OCM-10460
this pr also includes refactoring on the autoscaler command to use the new runner pattern.

OCM-10460 | fix: don't overwrite existing autoscaler value in edit flow

---

tests/e2e/hcp_machine_pool_test.go
tests/e2e/test_rosacli_cluster.go
tests/e2e/utils.go
tests/utils/common/constants/cluster.go
tests/utils/config/cluster.go
tests/utils/exec/rosacli/cluster_service.go
tests/utils/exec/rosacli/machinepool_service.go

Note: 
1. It doesn't check whether node pool instances ready **in default**. And if needed. pls set ENV `export CLUSTER_NODE_POOL_GLOBAL_CHECK=true`, then it will wait and check whether node pool instances ready until timeout.

OCM-9805 | test:  Automate id:60278 [Scaling up/down node pool on rosa hcp cluster]

---

tests/e2e/test_rosacli_cluster_post.go

[ocm-10477](https://issues.redhat.com//browse/ocm-10477) 
$ ginkgo --focus 75210 tests/e2e/
2.11.0
Ginkgo CLI. …

OCM-10477 | test: fix id:75210

---

cmd/describe/cluster/cmd.go

It appears the previous staging envs Detail page url using "qaprodauth.console.redhat.com" is no longer valid?
This PR changes the details page url to use "console.dev.redhat.com" instead. 
https://issues.redhat.com/browse/OCM-10532

OCM-10532: Update staging qaprodauth console url for details page

---

cmd/create/cluster/cmd.go

Adds back cluster key passing to create/oidcprovider cmd in create/cluster to fix regression from removing it

OCM-10452 | fix: Add cluster key back to oidcprovider create/cluster call

---

tests/e2e/hcp_cluster_test.go

$ ginkgo --focus 71050 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-10507 | ci: fix id:71050

---

tests/e2e/test_rosacli_account_roles.go
tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_operator_roles.go
tests/e2e/test_rosacli_upgrade.go
tests/utils/common/oidc.go

[OCM-10543](https://issues.redhat.com//browse/OCM-10543) | test: fix ids: 75210,73731,57408,38770,74661,60688 some failures on rosacli ci
75210: update ExtractOIDCProviderFromOidcUrl to support the not-classic oidc config
73731: update expected output for hosted-cp cluster
57408: add one minute to wait time
38770: add condition for not autoscaling enabled cluster
74661: update the role matcher to adapt the long cluster prefix
60688: skip on share vpc clusters as the base domain cannot be reused

OCM-10543 | test: fix ids: 75210,73731,57408,38770,74661,60688 some failures

---

pkg/info/info.go

*WHAT*
Bumps version for 1.2.44

OCM-9503 | chore: bump version for 1.2.44

---

cmd/create/cluster/cmd.go

Manually setting the cluster ID caused the command to not be 'programmatically called', removed 2 lines to fix this

OCM-10676 | fix: Remove manual cluster ID flag update for create/oidcprovider

---

tests/e2e/test_rosacli_policy.go

[OCM-10711](https://issues.redhat.com//browse/OCM-10711)
$ ginkgo --focus "(73449|74403)" tests/e2e/
2.11.0
from a path that contains a go.mod file. Alternatively you can use
Ginkgo CLI.
If you are attempting to test multiple …

OCM-10711 | test: fix ids:73449, 74403

---

cmd/describe/autoscaler/cmd.go
cmd/dlt/autoscaler/cmd.go

https://issues.redhat.com/browse/OCM-10756

OCM-10756 | fix: add missing aliases for describe/delete autoscaler commands

---

pkg/clusterautoscaler/flags.go
pkg/ocm/validators.go
pkg/ocm/validators_test.go

https://issues.redhat.com/browse/OCM-10754

OCM-10754 | fix: validate int32 for user input in autoscaler attributes

---

tests/e2e/test_rosacli_cluster_post.go

[OCM-10712](https://issues.redhat.com//browse/OCM-10712) | tests: fix id:75210
$ ginkgo --focus 75210 tests/e2e/
2.11.0
Ginkgo CLI.
If you are attempting to test …

OCM-10712 | tests: fix id:75210

---

.goreleaser.yaml

**WHAT**
Excludes merge commits from change log
JIRA - https://issues.redhat.com/browse/OCM-10636

OCM-10636 | chore: update goreleaser config to ignore merge commits

---

cmd/create/oidcprovider/cmd.go

Assigns cluster ID flag to the right var to be used when creating an OIDC provider

OCM-10676 | fix: Assign cluster ID var in create/oidc_provider

---

tests/e2e/test_rosacli_upgrade.go

[OCM-10856](https://issues.redhat.com//browse/OCM-10856) | test: fix id:55883
$ echo $TEST_PROFILE
rosa-upgrade-y-stream
$ ginkgo run --label-filter day1 tests/e2e --timeout 2h
2.11.0
from a path that contains a go.mod file to invoke the …

OCM-10856 | test: fix id:55883 fixes ci job "e2e-rosa-sts-upgrade-y-stream-prod-f3"

---

tests/e2e/test_rosacli_machine_pool.go

original ticket: https://issues.redhat.com/browse/OCM-10512
```
oaharoni-mac:rosa oaharoni$ ginkgo run -focus 55979 tests/e2e
Running Suite: ROSA CLI e2e tests suite - /Users/oaharoni/rosa_workspace/rosa/tests/e2e
Random Seed: 1725472885
Will run 1 of 208 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSStime="2024-09-04 14:01:36" level=info msg="Trying to list subnets of the vpc"
time="2024-09-04 14:01:36" level=info msg="Got 6 subnets"
time="2024-09-04 14:01:36" level=info msg="subnet-08fcb10ff2e65f926\t10.0.1.0/24\tus-west-2a\t"
time="2024-09-04 14:01:36" level=info …
```

OCM-10512 | fix: Fixing OCM-10512 bug

---

pkg/machinepool/output.go
pkg/machinepool/output_test.go

https://issues.redhat.com/browse/OCM-9882
adds disk size to describe machinepool output for node pools if the disk size is returned from the API
note: this includes a check that the disk size is actually set because the API work for this still needs to be enabled. In the future we will be able to remove this check.

OCM-9882 | feat: print custom worker disk size in describe nodepool

---

cmd/describe/cluster/cmd.go

https://issues.redhat.com/browse/OCM-9804

OCM-9804 | fix: Fix etcd kms key arn space

---

tests/e2e/test_rosacli_machine_pool.go

[OCM-10990](https://issues.redhat.com//browse/OCM-10990) | test: fix id:67057
$ ginkgo --focus 67057 tests/e2e/
2.11.0
Ginkgo CLI.
If you are attempting to test …

OCM-10990 | test: fix id:67057

---

cmd/create/cluster/cmd.go

Clarify that when creating a cluster, the `billing-account` param expects an account ID and not an ARN or other identifier. 
Resolves [OCM-7568](https://issues.redhat.com//browse/OCM-7568).

OCM-7568 | feat: Clarify that 'billing-account' expects an account ID

---

tests/e2e/test_rosacli_cluster.go
tests/utils/common/constants/general.go
tests/utils/common/helper.go

$ ginkgo --focus 34102 tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-10690 | test: updated id:34102

---

cmd/create/oidcprovider/cmd.go

https://issues.redhat.com/browse/OCM-11019
Works with:
- HCP cluster
- Classic cluster
- OIDC provider creation
Issue was that, when creating a cluster and providing an oidc config id, it would send both, causing a failure
There was a secondary issue, where when creating an HCP cluster, it does not technically exist at the time of creating a provider, which differs from classic. This was fixed by only supplying the OIDC ID in this situation. If you only supply cluster ID, it will fail due to non-existent HCP cluster

OCM-11019 | fix: Do not accept clusterID for thumbprint if programmatic

---

pkg/ocm/limited_support.go

Right now we have new override parameters in the LSR so we can keep the LSR visible to the SRE but it can be overriden when there is support exception. The cluster status shows only active LSR, without the override.
Depends on: https://github.com/openshift/rosa/pull/2350

OCM-10374 | fix: Add Limited Support Reason Override support

---

cmd/create/oidcprovider/cmd.go

Missing empty check allowed no inputs to be passed into the thumbprint fetch in one situation only
Manually verified every situation surrounding this

OCM-11019 | fix: Fix issue with classic clusters without --oidc-config-id flag

---

cmd/describe/machinepool/cmd_test.go
pkg/machinepool/output.go
pkg/machinepool/output_test.go

for https://issues.redhat.com/browse/OCM-11054
- forgot to add the unit when displaying the node pool root disk size as part of the `rosa describe` command, this MR adds it
- also removes a check to verify the value is set before displaying - CS changes are merged and the value has a default in the DB so it will always be set, that check was just included initially because I added the ROSA changes before the CS changes

OCM-11054 | fix: add unit to disk size on describe nodepool

---

go.mod
go.sum
vendor/github.com/openshift-online/ocm-common/pkg/machinepool/validations/disk_size.go
vendor/modules.txt

bumps ocm-common version to include https://github.com/openshift-online/ocm-common/commit/8a39738ecf9dc231357f1302e1a8f7f202a64fec

OCM-11113 | feat: bump ocm-common to lower np min disk size to 75

---

tests/e2e/test_rosacli_cluster.go

[OCM-11156](https://issues.redhat.com/browse/OCM-11156) | [CI] Debug and fix: id 60275
$ ginkgo --focus 60275 tests/e2e/
2.11.0
Ginkgo CLI.
If you are attempting …

OCM-11156 | test: fix id:60275

---

pkg/aws/client.go

After #2356 there were a few places where the default user agent was hardcoded and needed to be fixed

OCM-10679 | fix: use default user agent

---

tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_idp.go

[OCM-11198](https://issues.redhat.com//browse/OCM-11198)
$ ginkgo --focus "(46310|38788|38850)" tests/e2e/
2.11.0
Ginkgo CLI.
If you are attempting to test …

OCM-11198 | test: fix ids:46310,38788,38850

---

Makefile

**WHAT**
At the moment release target creates a snapshot, this change removes the `--snapshot` param ensuring the the release is built and published to github
JIRA - https://issues.redhat.com/browse/OCM-11201

OCM-11201 | fix : fix make target ensuring release builds and publishes to github

---

tests/e2e/test_rosacli_machine_pool.go

For test 36293, the description said that it was doing a delete, but from looking at the code, no delete was happening, so I updated the description to only mention that it was only creating and listing the machine pools.

OCM-11241 | fix: update description for 36293

---

pkg/info/info.go

**WHAT**
Bumps version to 1.2.46 on master. Release branch is created for 1.2.45
**Validation**
```
╭─ ~/Work/ocm/rosa  on OCM-9508 *7 ························································································································································································································································· ✔  at 11:00:39 
╰─ make clean rosa
rm -rf \
./cover.out \
rosa \
rosa-darwin-amd64 \
rosa-darwin-arm64 \
rosa-linux-amd64 \
rosa-linux-arm64 \
rosa-windows-amd64.exe \
*.sha256 \
go build -ldflags="-X github.com/openshift/rosa/pkg/info.Build=19b332e4" ./cmd/rosa
╭─ ~/Work/ocm/rosa  on OCM-9508 *7 ············································································································ …
```

OCM-9508 | chore: bump version info to 1.2.46

---

hack/release-list-jiras.sh

**WHAT**
As we require a list of JIRAs for Errata, this adds the output to the release list script 
**Validation**
```
./hack/release-list-jiras.sh 1.2.45 1.2.44
List of JIRA's to be used in Errata 
OCM-7552  OCM-6419  OCM-10341  OCM-3704  OCM-9503  OCM-10333  OCM-7551  OCM-10412  OCM-10221  OCM-9284  OCM-10455  OCM-10299  OCM-10459  OCM-10455  OCM-10438  OCM-10485  OCM-10506  OCM-10299  OCM-10507  OCM-9805  OCM-10511  OCM-7551  OCM-10532  OCM-10479  OCM-10538  OCM-10450  OCM-5445  OCM-10543  OCM-10477  OCM-10545  OCM-10606  OCM-10460  OCM-10452  OCM-9804  OCM-10616  OCM-10631  OCM-10633  OCM-10636  OCM-10406  OCM-10452  OCM-10676  OCM-10467  OCM-10711  OCM-9784  OCM-7184  OCM-7186  OCM-10489  OCM-10756  OCM-10754  OCM-10530  OCM-10712  OCM-10779  OCM-10676  OCM-9876  OCM-9773  OCM-10812 …
```

OCM-11202 | chore : add output to release script for errata jira list

---

pkg/machinepool/helper.go
pkg/machinepool/helper_test.go
pkg/machinepool/machinepool.go
pkg/machinepool/machinepool_test.go

Fix for issue customer faced after 1.2.45 released
Logic which checked # of min replicas for newly created machinepools was applied to both HCP and classic- though there is a difference between what is supported (when autoscaling is enabled)
for HCP, >0 min replicas
for classic, >=0 min replicas
This fix adds different logic paths in the validation + fixes unit tests

OCM-11364 | fix: Regression, HCP nodepool creation validation used for classic

---

.goreleaser.yaml

Allows to run goreleaser from fork

OCM-9515 | chore: adjust goreleaser to use openshift/rosa

---

pkg/machinepool/machinepool.go
pkg/machinepool/machinepool_test.go

Error msg was wrong for editing HCP nodepool with autoscaling + <1 replicas. Changed to correct msg and tested

OCM-11407 | fix: Error msg for editing nodepool; autoscaling+ 0 replicas

---

pkg/machinepool/machinepool.go

Before this fix, no err message was shown
`$ rosa edit machinepool -c 2e0i256vrlvnjcc9rn63orr4fljal6gv test --min-replicas 0 --max-replicas 2 --enable-autoscaling`
After the fix
$ rosa edit machinepool -c 2e0i256vrlvnjcc9rn63orr4fljal6gv test --min-replicas 0 --max-replicas 2 --enable-autoscaling
E: min-replicas must be greater than zero.
Closes [OCM-11407](https://issues.redhat.com//browse/OCM-11407)

OCM-11407 | ci: fix nil value return for editNodepoolValidation

---

tests/e2e/test_rosacli_machine_pool.go

[OCM-11199](https://issues.redhat.com//browse/OCM-11199)
$ ginkgo --focus 38775 tests/e2e/
2.11.0
Ginkgo CLI. …

OCM-11199 | test: fix id:38775

---

tests/e2e/hcp_machine_pool_test.go
tests/e2e/test_rosacli_policy.go

`$ ginkgo --focus '(74225|73449)' tests/e2e/
2.14.0
Ginkgo CLI. …

OCM-11429 | ci: fix id:74225,73449,60278,74403

---

cmd/describe/cluster/cmd_test.go

https://issues.redhat.com/browse/OCM-11556

OCM-11556 | fix: remove multiple ca tests from getClusterRegistryConfig

---

cmd/rosa/main.go

If my zshrc has following
```bash
if [ $(command -v rosa) ]; then
source <(rosa completion zsh)
compdef _rosa rosa
fi
```
On startup of zsh shell I can observe following, which is not helpful.
```
Last login: Tue Sep 24 11:17:26 on ttys011
WARN: The current version (1.2.44) is not up to date with latest released version (1.2.45).                                                                     
WARN: It is recommended that you update to the latest version.
```

OCM-11446 | feat: Add "rosa cli" to !latest error main.go

---

cmd/edit/cluster/cmd.go

Specifying `--registry-config-allowed-registries-for-import` flag when editing a cluster should not enable interactive mode.
https://issues.redhat.com/browse/OCM-11484

OCM-11484 | fix: registry config allowed for import flag should not enable interactive mode

---

tests/e2e/rosa_autoscaler_test.go

ocm-67348
$ ginkgo --focus 67348 tests/e2e/
2.11.0
Ginkgo CLI. …

OCM-67348 | test: fix id:67348

---

cmd/create/decision/cmd.go
cmd/describe/accessrequest/accessrequest_suite_test.go
cmd/describe/accessrequest/cmd.go
cmd/describe/accessrequest/cmd_test.go
cmd/describe/cmd.go
cmd/rosa/structure_test/command_args/rosa/describe/accessrequest/command_args.yml
cmd/rosa/structure_test/command_structure.yml
pkg/ocm/accessrequests.go
pkg/output/output.go
pkg/test/helpers.go

https://issues.redhat.com/browse/OCM-7783
samples:
```
bash-5.2$ ./rosa describe accessrequest --id 2msh3sGFmkhzAXf3j56faQvESMO
ID:                                2msh3sGFmkhzAXf3j56faQvESMO
Subscription ID:                   2msfSLdXe59mjR8VcMVl3KoCGU3
Cluster ID:                        2e5edtubdsalag01sg2mp9lnrt58fef7
Support Case ID:                   
Requested By:                      llan.openshift
Created At:                        Wed Oct  2 12:09:54 UTC 2024
Respond By:                        Sat Oct  5 12:09:54 UTC 2024
Request Duration:                  8h
Justification:                     test
Status:                            Denied
Decisions:                           
- Decision:                      Denied
Decided By:                    llan.openshift
Created At: …
```

OCM-7783 | feat: add rosa describe accessrequest command

---

pkg/helper/machinepools/helpers.go
pkg/helper/machinepools/helpers_test.go

[OCM-11560](https://issues.redhat.com//browse/OCM-11560)

OCM-11560 | fix: allow trailing comma for taints/labels

---

cmd/describe/cluster/cmd.go

https://issues.redhat.com/browse/OCM-11045

OCM-11045 | fix: etcd encryption describe should be shared between hcp and classic

---

cmd/create/network/cmd.go
pkg/options/network/create.go

Adding a default template if no template is specified in the `rosa create network` command
[OCM-11711](https://issues.redhat.com/browse/OCM-11711)

OCM-11711 | fix: Adding a default template if no template is specified

---

cmd/describe/cluster/cmd.go
cmd/describe/cluster/cmd_test.go

https://issues.redhat.com/browse/OCM-11556

OCM-11556 | fix: refactor multiple ca tests from getClusterRegistryConfig

---

pkg/info/info.go

Bumps version to cut release branch

OCM-11943 | chore: bump version to 1.2.47-RC1

---

pkg/aws/helpers.go
pkg/aws/helpers_test.go

Breaks creation of account-roles for orgs that do not have the zero-egress feature enabled.

OCM-10017 | fix: revert adding EC2 policy to worker role

---

cmd/create/network/cmd.go
cmd/create/network/cmd_test.go
cmd/login/cmd.go
cmd/rosa/structure_test/command_args/rosa/create/network/command_args.yml
pkg/aws/region/flag.go
pkg/config/config.go
pkg/constants/config.go
pkg/network/helper.go
pkg/network/helper_test.go
pkg/options/network/create.go
pkg/options/network/create_test.go
pkg/options/network/suite_test.go

Adding the TEMPLATE_DIR env variable along with the --template-dir flag to allow the user to point to the template directory path
[OCM-11868](https://issues.redhat.com/browse/OCM-11868)

OCM-11868 | feat: Adding --template-dir flag & TEMPLATE_DIR env var

---

tests/ci/config/config.go
tests/e2e/dummy_test.go
tests/e2e/e2e_setup_test.go
tests/utils/config/support.go
tests/utils/exec/occli/cmd_client.go

Function GetKubeconfigDummyFunc(), in file tests/utils/config/support.go, is being blocked by import error `Import cycle not allowed` because of import of module `github.com/openshift/rosa/tests/utils/exec/rosacli`.

OCM-9183 | test: Get kubeconfig from env

---

cmd/create/oidcconfig/cmd.go

Bug with create/oidcconfig occurred when using manual mode, it would attempt creation after spitting out the commands for the user to run. This introduction of an if statement fixes this problem

OCM-12100 | fix: Only run oidcprovider command when mode=auto

---

cmd/register/oidcconfig/cmd.go
pkg/constants/oidc_config.go

Regression occurred with using `rosa register oidcconfig` due to the new thumbprint fetching using OIDC config ID or Cluster ID. This change forces the use of an OIDC config ID and gives a warning if somehow it is not supplied (error is bubbled up later from the OIDC thumbprint fetch)

OCM-12118 | fix: Ask for oidc config ID for register/oidcconfig

---

cmd/create/network/cmd.go
cmd/create/network/options.go
pkg/options/network/create.go
pkg/options/network/create_test.go

Unable to use env var for template dir (if flag is not desired) before this MR. This MR checks 1) if the env var is set, 2) if the `template-dir` flag is used
If both are true, it uses the `template-dir` flag. If the `template-dir` flag is not set, it will use the env var instead (sanitizing """" to "")
Also fixes un-discovered bug where when using an extra `/` in env var or `template-dir` flag, the command would not remove and it would result in a template dirpath which looked like `path/to/dir//here/`

OCM-12119 | fix: Env var regression with create/network

---

pkg/aws/policies.go
pkg/aws/policies_test.go

Simiar to https://issues.redhat.com/browse/OCM-12012 where we skip validations for the EC2 container registry policy when creating account-roles. We also need to skip it in the cluster create validation.

OCM-11578 | fix: skip validation of container registry policy for create cluster

---

tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_cluster_post.go
tests/e2e/test_rosacli_upgrade.go
tests/utils/exec/rosacli/upgrade_service.go

Running Suite: ROSA CLI e2e tests suite - /home/zhewang/go/src/rosa/tests/e2e
=============================================================================
Random Seed: 1729838995
Will run 1 of 242 specs
------------------------------
Sts cluster creation supplemental testing rosacli makes STS cluster by default - [id:55701] [feature-cluster, Medium, day1-supplemental]
/home/zhewang/go/src/rosa/tests/e2e/test_rosacli_cluster.go:3783
STEP: Init the client @ 10/25/24 14:49:55.172
STEP: Get AWS account id @ 10/25/24 14:49:55.172
STEP: Prepare custom profile @ 10/25/24 14:49:55.172
STEP: Check the help message of 'rosa describe upgrade -h' @ 10/25/24 14:49:55.173
time=2024-10-25T14:49:55+08:00 level=info msg=Running command: rosa create cluster -c ocp55701 --help
……
STEP: Delete account-roles …

OCM-12036 | test: automated ids:38827,38829,35894,55701

---

cmd/create/dnsdomains/cmd.go
cmd/create/dnsdomains/cmd_test.go
cmd/create/dnsdomains/suite_test.go
cmd/rosa/structure_test/command_args/rosa/create/dns-domain/command_args.yml
pkg/ocm/dns_domain.go

Allows passing of `--hosted-cp` flag into `rosa create dns-domain` as well as actually creates DNS domain for either HCP or classic cluster architecture
Tested output here:
```
hkepley@hkepley-mac  ~/Documents/programming/rosa   ocm-12302 ±  ./rosa create dns-domain --hosted-cp
I: DNS domain ‘ziaa.i3.devshift.org’ has been created.
I: To view all DNS domains, run 'rosa list dns-domains
hkepley@hkepley-mac  ~/Documents/programming/rosa   ocm-12302 ±  ./rosa create dns-domain           
I: DNS domain ‘kmiz.i1.devshift.org’ has been created.
I: To view all DNS domains, run 'rosa list dns-domains
```
```
./rosa create dns-domain
I: DNS domain ‘1r3d.i1.devshift.org’ has been created.
I: To view all DNS domains, run 'rosa list dns-domains
```
```
./rosa list dns-domains
ID …
```

OCM-12302 | feat: Add `--hosted-cp` functionality to create/dns-domain

---

cmd/create/accountroles/creators.go

Creating account roles with `mode=manual` resulted in multiple commands to create worker role when the worker role had >1 policy. This fixes that by only printing the role creation command once before the policy loop.

OCM-12379 | fix: Duplicate commands when manual create/accountroles

---

cmd/create/network/cmd.go
cmd/create/network/cmd_test.go

[OCM-12435](https://issues.redhat.com/browse/OCM-12435)

OCM-12435 | fix: Updated info message for when no template is specified

---

pkg/options/network/create.go

[OCM-12438](https://issues.redhat.com/browse/OCM-12438)

OCM-12438 | fix: changing default template dir in help message

---

cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/cmd.go
cmd/create/operatorroles/suite_test.go
cmd/create/operatorroles/validation.go
cmd/create/operatorroles/validation_test.go
cmd/rosa/structure_test/command_args/rosa/create/operator-roles/command_args.yml
pkg/aws/policies.go

* rosa create operator-roles [–oidc-config-id xxx] [-c xxx] –cross-account-hosted-zone-role-arn xxx –cross-account-vpc-endpoint-service-role-arn xxx
* The new parameter in bold is necessary to indicate the change to include permissions to assume role for both the control plane and ingress operator roles
The flag names above in the requirements were renamed to `route53-role-arn` and `vpc-endpoint-role-arn`
`vpc-endpoint-role-arn` deprecates `shared-vpc-role-arn` which is used currently for classic. This flag is still usable, but will print a deprecation warning when used instead of `route53-role-arn`
Output of commands surrounding operator roles:
**VALIDATION**:
```
> rosa create operator-roles --prefix hktest --route53-role-arn a
? Role creation mode:  [Use arrows to move, type to filter, …
```

OCM-12363 | feat: HCP sharedVPC functionality to create/operatoroles

---

cmd/create/network/cloudformation.go
cmd/create/network/cmd.go

[OCM-12486](https://issues.redhat.com/browse/OCM-12486)

OCM-12486 | fix: Fixed network custom templates runner

---

cmd/create/network/cmd.go

[OCM-12480](https://issues.redhat.com/browse/OCM-12480)

OCM-12480 | fix: Fixed default name in info message

---

pkg/options/network/create.go

[OCM-12482](https://issues.redhat.com/browse/OCM-12482)

OCM-12482 | fix: Fixed tempalte dir env var to work

---

cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/common_utils.go
cmd/create/operatorroles/common_utils_test.go
cmd/dlt/operatorrole/cmd.go
pkg/aws/policies.go

Allows `--mode manual` for creating and deleting operator roles with the created&attached HCP SharedVPC policies.

OCM-12538 | feat: Manual mode for create&delete operator-roles with hcp sharedvpc

---

cmd/list/dnsdomains/cmd.go
cmd/list/dnsdomains/cmd_test.go
cmd/list/dnsdomains/suite_test.go
cmd/rosa/structure_test/command_args/rosa/list/dns-domain/command_args.yml

Also adds `ARCHITECTURE` column
```
./rosa list dns-domains --hosted-cp
ID                    CLUSTER ID  RESERVED TIME         USER DEFINED  ARCHITECTURE
XXX.devshift.org              0001-01-01T00:00:00Z  Yes           hcp
XXX.devshift.org              0001-01-01T00:00:00Z  Yes           hcp
XXX.devshift.org              0001-01-01T00:00:00Z  Yes           hcp
```
^ Run with `--hosted-cp`
```
/rosa list dns-domains   
ID                    CLUSTER ID  RESERVED TIME         USER DEFINED  ARCHITECTURE
XXX.devshift.org              2024-08-26T19:44:26Z  Yes           classic
XXX.devshift.org              0001-01-01T00:00:00Z  Yes           hcp
XXX.devshift.org              0001-01-01T00:00:00Z  Yes           hcp
XXX.devshift.org              0001-01-01T00:00:00Z  Yes           classic …
```

OCM-12351 | feat: --hosted-cp functionality for rosa list dns-domains

---

cmd/create/operatorroles/validation.go

Fixes logic which would return `true` when using classic and roles for sharedvpc

OCM-12689 | fix: Creation of operator roles for classic fixes

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/cmd.go

Adds validation for sharedvpc flags associated with HCP (account + op roles) before resources are created

OCM-12694 | fix: Pre-command validation for shared vpc flags

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go
cmd/create/accountroles/creators_test.go
cmd/create/ocmrole/cmd.go
cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/common_utils.go
cmd/create/operatorroles/common_utils_test.go
cmd/dlt/operatorrole/cmd.go
cmd/upgrade/accountroles/cmd.go
cmd/upgrade/roles/cmd.go
pkg/aws/client.go
pkg/aws/client_mock.go
pkg/aws/helpers.go
pkg/aws/policies.go
pkg/rosa/helpers.go

Adds route53 assume role policy to control plane + gets rid of needless func for EnsurePolicyWithName + refactors a couple of things (fixing a bug)

OCM-12660 | feat: Refactor op + acc roles sharedvpc policies

---

cmd/create/accountroles/cmd.go

`--mode auto` creates all account roles even without `-y` specified, so we must account for this when checking for HCP only flags for HCP sharedvpc

OCM-12693 | fix: Only check for HCP only flags when not using `--mode auto`

---

cmd/create/network/cmd.go

Updating the naming to follow naming conventions
[OCM-12803](https://issues.redhat.com/browse/OCM-12803)

OCM-12803 | fix: Updating naming for Rosa create network log events

---

cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/common_utils.go
cmd/create/operatorroles/common_utils_test.go

Adds both policies to control plane op role (originally the ask was for 1 of the new policies to be added to this role, but that has changed)

OCM-12805 | fix: Refactor manual mode for create/oproles

---

tests/ci/labels/features.go
tests/e2e/test_rosacli_network_resources.go
tests/utils/exec/rosacli/cmd_client.go
tests/utils/exec/rosacli/network_resource_service.go
tests/utils/exec/rosacli/ocm_resource_service.go
tests/utils/helper/file.go
tests/utils/helper/network.go

$ ginkgo --focus '(77140|77159)' tests/e2e/
2.15.0
Ginkgo CLI. …

OCM-9994 | test: automated id:77159,77140

---

cmd/create/operatorroles/by_prefix.go
cmd/create/operatorroles/common_utils.go
cmd/create/operatorroles/common_utils_test.go

for manual mode, operator roles would give commands to create policies even if they exist, resulting in needless errors and potential confusion for users (even though it worked)
This change makes it so that it only adds the commands to create the policies when they don't exist. No matter what, attachment commands are printed to the user

OCM-12827 | fix: Dont create policies for op roles when they exist

---

cmd/create/accountroles/cmd.go
cmd/create/operatorroles/cmd.go

HCP shared VPC policies still are created and attached when the answer to whether or not to create them is `No` when the flags are supplied. It doesn't matter if the flags are supplied, they should not be created in this situation

OCM-12866 | fix: Do not create sharedvpc policies when answer is No

---

cmd/dlt/accountroles/cmd.go
cmd/dlt/operatorrole/cmd.go
pkg/aws/client.go
pkg/aws/client_mock.go
pkg/aws/policies.go
pkg/aws/policies_test.go
pkg/roles/utils.go

There is a map which we return from the function which merges with maps from the last call (deleteOperatorRole is called once per role so we must merge these, and only print out warnings that we could not delete the policies ONCE PER POLICY). The issue is that, without this, you will get prints 1) if they are deleted in the end and 2) multiple times for the route53 policy
With these changes, it only prints the warning when it is unable to delete the policy one time. One role may be unable to delete a policy (controlplane) if the other still has the role attached (ingress). We cannot do this before or after function calls because it is designed to ask the user per every oprole if they want to delete the role.
There is an extra change to account roles which makes sure you are using …

OCM-12806 | feat: Delete operator roles auto mode (and changes to account roles)

---

cmd/create/network/cmd.go
pkg/network/helper.go
pkg/network/helper_test.go
pkg/network/network.go

[OCM-12922](https://issues.redhat.com/browse/OCM-12922)
Fixing manual mode output to not output the whole cf file
Fixing log events to track if default was used through boolean

OCM-12922 | fix: Fixing manual-mode + log event output

---

cmd/dlt/accountroles/cmd.go
cmd/dlt/operatorrole/cmd.go

Also fixes bug with multiple printouts of manual mode for deleting the hcp sharedvpc policies for accountroles

OCM-12871 | feat: Add manual mode for deleting hcp sharedvpc policies [oproles]

---

cmd/create/cluster/cmd.go
cmd/create/operatorroles/cmd.go
cmd/rosa/structure_test/command_args/rosa/create/cluster/command_args.yml

Functional MR in progress, this is to save time in review by getting the customer-facing flags and deprecations reviewed first

OCM-12364 | feat: Add hcpsharedvpc flags + deprecation warnings to create/cluster

---

cmd/create/cluster/cmd.go
pkg/ocm/clusters.go

Initial support for `create/cluster` for HCP shared VPC clusters
Next MR will include manual + interactive mode changes (better UX than just passing in flags), this MR purely opens up support

OCM-12364 | feat: create/cluster support for HCP shared VPC

---

tests/utils/handler/resources_handler_clean.go

[OCM-12963](https://issues.redhat.com//browse/OCM-12963) | ci: fix the VPC leak during the CI jobs
logs:
https://privatebin.corp.redhat.com/?e361d97efb6602cc#E3h6s82F8Se1hUgXn1j7Bd92qh4QqLHwRMYdNnhvUXVt

OCM-12963 | ci: fix the VPC leak during the CI jobs

---

cmd/dlt/accountroles/cmd.go
cmd/dlt/operatorrole/cmd.go
cmd/rosa/structure_test/command_args/rosa/delete/account-roles/command_args.yml
cmd/rosa/structure_test/command_args/rosa/delete/operator-roles/command_args.yml

Allows use of script with manual mode, and skipping of prompt when using auto/interactive when deleting hcp shared vpc policies

OCM-12964 | feat: Allow use of flag for deleting hcpsharedvpc policies

---

cmd/create/cluster/cmd.go

Without this MR, the output when running the generated cluster command to recreate the same cluster always printed deprecation warnings:
```
Flag --private-hosted-zone-id has been deprecated, '--private-hosted-zone-id' will be replaced with '--ingress-private-hosted-zone-id' in future versions of ROSA.
Flag --shared-vpc-role-arn has been deprecated, '--shared-vpc-role-arn' will be replaced with '--route53-role-arn' in future versions of ROSA.
```

OCM-13044 | fix: Replace deprecated flags when building cluster cmd

---

cmd/dlt/accountroles/cmd.go

```
I: Deleting classic account roles
I: Deleting account role 'yw1209svpc1-Installer-Role'
I: Successfully deleted the classic  account roles
I: Deleting account role 'yw1209svpc1-ControlPlane-Role'
I: Successfully deleted the classic  account roles
I: Deleting account role 'yw1209svpc1-Worker-Role'
I: Successfully deleted the classic  account roles
I: Deleting account role 'yw1209svpc1-Support-Role'
I: Successfully deleted the classic  account roles
I: Deleting hosted CP account roles
I: Deleting account role 'yw1209svpc1-HCP-ROSA-Installer-Role'
I: Successfully deleted the hosted CP  account roles
I: Deleting account role 'yw1209svpc1-HCP-ROSA-Support-Role'
I: Successfully deleted the hosted CP  account roles
I: Deleting account role 'yw1209svpc1-HCP-ROSA-Worker-Role'
I: Successfully …
```

OCM-13048 | fix: Output formatting for deleting account roles

---

cmd/create/cluster/cmd.go

These 2 prompts were prompted when making a classic cluster, they are meant only for HCP

OCM-13126 | fix: Make vpcendpointrolearn and hcp HZID prompts hcp only

---

cmd/create/cluster/cmd.go
cmd/create/cluster/shared_vpc.go

When making a hosted control plane cluster, filter DNS domains in interactive mode and return only hostedCP dns domains (using the new `ClusterArch` field)

OCM-13193 | fix: Filter DNS domains when create/cluster if hosted CP

---

cmd/edit/cluster/cmd.go

This is an interesting issue, which stems from editing a cluster's `https-proxy`/`http-proxy`/`no-proxy`
It says for the user to enter `""`  by itself if they want to 'delete' one of these values. If you do this in interactive, nothing happens
Removed a validator specific to `http-proxy` and `https-proxy` - which fixed the issue
The result is the expected results in `edit cluster`'s interactive mode.
Output:
```
./rosa edit cluster -c hk --https-proxy http://10.0.0.210:8080 --profile vpc-cluster -i
I: Interactive mode enabled.
Any optional fields can be ignored and will not be updated.
? Private cluster, check this command's help for possible impacts: No
? Disable Workload monitoring: No
? To remove any existing cluster-wide proxy value or an existing additional-trust-bundle value, enter …
```

OCM-10030 | fix: Remove empty string checks for http/https proxy

---

tests/ci/data/profiles/rosa-hcp.yaml
tests/e2e/hcp_machine_pool_test.go
tests/e2e/test_rosacli_kubelet_config.go
tests/e2e/test_rosacli_machine_pool.go
tests/utils/handler/cluster_handler.go

- fix failed cases :56786,73754,38775, they are failed as the error message has changed.
- Fix the failure that prepare shared-vpc hcp cluster with proxy configuration. Before the steps creates proxy then create shared-resource that make the failure.
- Disable the additional security group in the share-vpc-hcp profile
The security group needs to added in the share resources, will support that in coming PR.
Logs for creating cluster with updated shared-vpc hcp profile:https://privatebin.corp.redhat.com/?0dbf0ae15e9c7425#AJRiRKJLvacApgoncsNsC14Ph7DcruWrq9SR2XVgqAYS
logs for the fixed cases: https://privatebin.corp.redhat.com/?126de46da8d8bc81#6rDZs8ePVgonsefsc3BnpdxAxNj46LPHsGHYJP6cyPZq

OCM-13423 | test: fix ids:56786,73754,38775 and shared-vpc hcp preparation

---

pkg/ocm/client.go

Issue stems from: https://github.com/openshift/rosa/pull/2340
The associated ticket ([OCM-10908](https://issues.redhat.com//browse/OCM-10908)) has context in a slack thread link about the issue
Pretty much, when running ROSACLI on a container, the files created (At least for Kubernetes) are read-only
This means that, when saving the refresh token (a new feature) to the OCM config file, ROSA would error out and exit. This means about every time credentials/tokens are checked, ROSA will exit abruptly in the middle of a task for those using ROSA in a containerized environment.
This 'fix' skips the exit which comes from this recently introduced function, and rather warns the user that the refresh token was not saved to the config file. This way the user may continue using ROSACLI.
The refresh …

OCM-10908 | fix: Do not exit when unable to save refresh token

---

cmd/rosa/structure_test/command_args/rosa/verify/network/command_args.yml
cmd/verify/network/cmd.go

Adds profile flag to `very network` command to use different AWS profiles

OCM-10282 | fix: Add profile flag to very network command

---

tests/e2e/test_rosacli_account_roles.go
tests/e2e/test_rosacli_network_resources.go
tests/e2e/test_rosacli_oidc_config.go
tests/utils/helper/file.go
tests/utils/helper/oidc.go

- 64620: Fix some expected message
- 43070: Fix the parameter parse for unmanaged oidc config
- 57408: commented out the auto mode test as the aws account in the managed policies is the dev aws account which will lead failure.Move this back when the managed policies are supported officailly for classic account-roles
- 77140: The filesystem on PROWCI is read-only, that makes the file creattion failed. And also fix some design change
The job where found above failed cases is https://redhat-internal.slack.com/archives/C0519LZH1RA/p1737403094419139
logs: https://privatebin.corp.redhat.com/?319d99f0bec95506#B7Fmms8Gp1wNgdx2fTbaoxZvp6zAeFQKdMSix9drC4Rf

OCM-13513 | test: fix ids: 64620,43070,57408,77140

---

tests/e2e/test_rosacli_account_roles.go
tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_network_resources.go
tests/e2e/test_rosacli_upgrade.go
tests/e2e/test_rosacli_user_role.go

- 77159: The file system on prowci is read-only, adjust to use temp dir to create clouldformation file.And also fix some design change
- 77829: Fix expectred error message
- 52419: fix to use correct command to unlink user role
- 54469: To use temp dir for manual mode local files to avoid 'Permission deny'
- 75534: add the step to initiate the cluster_id and testClusterName in BeforeEach to avoid the failure across test cases in the same block
- 64187: '--control-plane' is removed since [OCM-7330](https://issues.redhat.com/browse/OCM-7330) was merged, remove the check for its help message
- 73814: remove the checkpoint of the requiredment of '--control-plane' for hostedcp upgrade
And remove all '--control-plane' flag in the cases of hostedcp cluster upgrade
local logs are …

OCM-13543 | test: fix 77159,77829,52419,54469,75534,64187,73814

---

cmd/describe/cluster/cmd.go

Causes failure to create cluster when feature toggle is disabled in Clusters Service

OCM-13681 | fix: Do not error/exit when fail to describe migrations

---

cmd/describe/cluster/cmd_test.go
pkg/info/info.go

Bumps version prior to creating RC (which will have RC version)

OCM-13516 | chore: Bump version prior to RC

---

cmd/edit/cluster/cmd.go

Due to concerns with backend, it's been asked to disable this feature for now. I think it's best and easiest to do this via 'removing' the flags (commenting out) for this release, so the migration cannot be initiated. And allow for a simple 1.2.51 release following this

OCM-13520 | feat: Disable SDN->OVN migration flags for 1.2.50

---

tests/e2e/test_rosacli_account_roles.go
tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_network_verifier.go
tests/e2e/test_rosacli_operator_roles.go
tests/e2e/test_rosacli_user_role.go

- 52419,52693: inital 'userRoleArnsToClean' in Before each to avoid the interference between multiple cases
- 54469,77962,77910: Add step to go to the temp dir for manual mode to fix the permission issue in the default dir
- 46310: Check if clusterConfig.Proxy is nil before acesssing its field to avoid invalid memory address failure
- 70370: Skip this destructive case on shared-vpc cluster as the VPC of the cluster owned by second AWS account
logs: https://privatebin.corp.redhat.com/?ce368a7076daf425#HVyWk1c2xtv5gon9czgs5uugwmiCWskCp6LiHoG3w412

OCM-13916 | test: fix ids: 52419,52693,54469,77962,77910,46310,70370

---

cmd/describe/cluster/cmd.go

Error output contained command to run with `-c CLUSTER_ID` - this is incorrect and caused an error on its own, the output should contain a cluster name instead when using `-c`

OCM-13951 | fix: Change error output for failed inflight check

---

pkg/ocm/clusters.go
pkg/ocm/migrations.go

Values with `_ipv4` were incorrectly used after SDK change, not populating the internal subnets when the request was made

OCM-13516 | fix: Rename key values used for migration API request

---

pkg/externalauthprovider/flags.go

Correction of `usernames` in external auth provider flag

OCM-13982 | fix: Spelling of flag in external auth provider

---

tests/e2e/hcp_external_auth_test.go
tests/e2e/rosa_autoscaler_test.go
tests/e2e/test_rosacli_network_verifier.go
tests/e2e/test_rosacli_node_pool.go

- 72536: It canot create external_auth_provider on the cluster which has already configured that, skip it if the cluster is configured with external_auth_provider
- 67348: design change, describe autoscaler is supported since [OCM-13946](https://issues.redhat.com/browse/OCM-13946)
- 75227:  it generated a dulicated machinepool name with two random charactors suffix. I will use a suffix of three charactor to decrease its happening
- 70370: The expected message of 'Failed Inflight Checks' is using cluster name actually, not the cluster id. Simplify the expected message.
Logs: https://privatebin.corp.redhat.com/?0f7901212a32a060#79asrSNRauy6KGPEijeVaks6zmBnDsPMMPNAASwaZ3wH

OCM-14095 | test: fix ids: 72536,67348,75227,70370

---

cmd/describe/autoscaler/cmd.go
pkg/clusterautoscaler/output.go

Only shows the values which can be changed / are used for Hosted Control Plane clusters
```
❯ ./rosa describe autoscaler -c hk-hcp
Maximum Node Provision Time:               20m
Maximum Pod Grace Period:                  700
Pod Priority Threshold:                    -11
Resource Limits:
- Maximum Nodes:                          400
```

OCM-13946 | feat: HCP autoscaler simpler describe output

---

cmd/edit/autoscaler/cmd.go
pkg/clusterautoscaler/flags.go
pkg/clusterautoscaler/validation.go

Disables interactive mode for edit/autoscaler for HCP clusters + adds some validation to provide the user with helpful messages

OCM-14168 | feat: Disable interactive mode when editing HCP autoscaler

---

tests/ci/data/profiles/rosa-classic.yaml
tests/ci/labels/category.go
tests/e2e/test_rosacli_cluster.go
tests/e2e/test_rosacli_cluster_post.go
tests/e2e/test_rosacli_idp.go
tests/e2e/test_rosacli_idp_user.go
tests/e2e/test_rosacli_machine_pool.go
tests/utils/handler/interface.go

I added labels to all test cases that are currently automated and in the FedRAMP regression test suite. I also added a new profile that creates a cluster that works in FedRAMP, and made a few small changes to support some differences between FedRAMP and commercial.

OCM-8373 | CI: Initial support for FedRAMP

---

cmd/create/machinepool/cmd.go
pkg/machinepool/machinepool.go
pkg/machinepool/machinepool_test.go

* `create/machinepool` and `edit/machinepool` for HCP now properly calculates the value of expected max/min nodes by grabbing `maxNodesTotal` from the global autoscaler before printing info messages

OCM-14167 | fix: Create+Edit/np info msg fixes with calculations

---

cmd/edit/machinepool/cmd_test.go
pkg/machinepool/machinepool.go
pkg/machinepool/machinepool_test.go

Issue was that the default node pool values were not being calculated for the info/warning msgs that print when doing risky scaling choices
This was because the cluster API response does not contain default NPs, had to use a separate API endpoint
So if the default NP had 50 nodes, and the new one had 50, the "total" this code would return would be `50` instead of `100`

OCM-14214 | fix: Calculate default NP values when create/edit np

---

tests/e2e/e2e_setup_test.go
tests/e2e/test_rosacli_cluster_post.go

https://privatebin.corp.redhat.com/?0f0656885e0a482e#2KS2VSfQUyVSSGogMaq3bsvw86rQSUQPN1JuWW2a78kC

OCM-13049 | ci: Add the workaround for public HCP with proxy to make all operators ready

---

cmd/create/accountroles/cmd.go

Removes gates for govcloud and `HCP` account roles. Does not remove gates for HCP sharedvpc

OCM-13382 | feat: Allow HCP create/accountroles in govcloud

---

tests/e2e/e2e_setup_test.go

Here is the run log
```
yingzhan@yingzhan-mac  ~/ying-work/code/rosa   ying-fix ±  ginkgo run --label-filter day1 tests/e2e --timeout 2h && ginkgo run --label-filter day1-readiness tests/e2e --timeout 1h
Running Suite: ROSA CLI e2e tests suite - /Users/yingzhan/ying-work/code/rosa/tests/e2e
Random Seed: 1740464598
Will run 1 of 259 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSStime="2025-02-25 14:52:58" level=info msg="Going to prepare a vpc with name ying0225-erhwmk, on region us-west-2, with cidr 10.0.0.0/16 "
time="2025-02-25 14:52:59" level=info msg="Going to create vpc and the follow resources on zones: "
time="2025-02-25 14:53:00" level=info msg="Create vpc success vpc-07320be917c3eb042" …
```

OCM-14251 | ci: get cluster value from json data

---

pkg/machinepool/machinepool.go
tests/ci/data/profiles/rosa-classic.yaml
tests/e2e/rosa_autoscaler_test.go
tests/e2e/test_rosacli_cluster.go

79846: fix some mistake of for block which leads failure
46310: Skip if the cluster is without proxy setting
67348: Fix the error message when edit autoscaler with unsupported flags on hosted-cp cluster
42832: Fix the failure by updating the cluster version in profile
local logs: https://privatebin.corp.redhat.com/?20ae6f10c37973c3#ZeQfeh5p5QKNaQ4oRsPwx4uhzoHCUhH8X6qeUkiUZfc

OCM-14274 | test: fix ids: 79846,46310,67348,42832

---

tests/e2e/test_rosacli_oidc_config.go
tests/e2e/test_rosacli_upgrade.go
tests/utils/exec/rosacli/version_service.go

- 64620: The extracted url is empty. It cannot be reproduced on local. Add '--output json' on the command and enrich the info message when the output is not expected
- 75445: failed as the expected policy version is the latest version of candidate channel group , need a small fix on automation code
logs:https://privatebin.corp.redhat.com/?d9f73496e4e876d6#Hrd61KbaUx3U74fUxzgwPfqt1EBv18qnv4BD6mjqEpax

OCM-14323 | test: fix ids: 75445,64620

---

cmd/create/operatorroles/by_prefix.go

Removes gates for creating HCP operator roles in govcloud

OCM-13381 | feat: Enable creating HCP operator roles in govcloud

---

pkg/aws/policies.go

An error occurs when deleting a support role, for example, then trying to upgrade a cluster. The error is a PANIC due to the AWS SDK not returning an error, and instead returning empty role lists + a nil role output. 
Checking for nil after the error check fixes the PANIC

OCM-14417 | fix: Bug with upgrading cluster and missing account roles

---

tests/ci/data/profiles/rosa-hcp.yaml
tests/e2e/hcp_machine_pool_test.go
tests/e2e/test_rosacli_cluster_post.go

- 75256: In the post step, the cluster has deleted. Update to use cluster config for skip step
- 72195: Add defer step to delete the security group creared in this case to avoid resource leak
- Disable proxy setting on rosa-hcp-shared-vpc-advanced profile to avoid destroy step failed. the destyor step of periodic-ci-openshift-rosa-master-e2e-rosa-hcp-shared-vpc-critical-high-f3 will be with one error as the sg of the proxy is created with aws account1 while the DeleteVPCChain uses the aws account2, no permission to delete the sg of the proxy. A new CI feature will be added later, try to support full cycle of the proxy and sg on shared-vpc cluster
logs:https://privatebin.corp.redhat.com/?608fb26e529b6b38#4ZjFbGR8H87VnZVRvtUz3dj9nScYPRg6TndNnFKeh9wA

OCM-14441 | test: fix ids: 75256,72195

---

tests/ci/data/profiles/rosa-hcp.yaml
tests/utils/handler/cluster_handler.go
tests/utils/handler/interface.go
tests/utils/handler/resources_handler.go
tests/utils/handler/resources_handler_clean.go
tests/utils/handler/resources_handler_prepare.go

- Add proxy cleanup step for all jobs to support the proxy on hosted-cp vpc cluster. It met error when clean up VPC as some proxy resources are not cleaned before this change
- Support security group settings on hosted-cp shared-vpc profile by adding the sg into the shared resources
- enable proxy and security group settings on 'rosa-hcp-shared-vpc-advanced' profile
Below testing on local are passed:
- day1 and destroy with 'rosa-hcp-shared-vpc-advanced' profile which proxy and sg setting are enabled
- day1 and destroy with 'rosa-advance' profile which proxy and sg setting are enabled

OCM-14545 | ci: Support security group and proxy settings for hosted-cp shared vpc profile

---

cmd/create/accountroles/cmd.go
cmd/create/cluster/cmd.go
cmd/create/cluster/validation.go
cmd/create/cluster/validation_test.go

Introduces proper validation of HCP Shared VPC on fedramp env, as well as tells the user which flags they should remove to stop getting the validation error
Introduces test as well for this validation

OCM-13390 | feat: Proper validation + test; HCPSVPC on fedramp

---

pkg/aws/helpers.go
pkg/aws/helpers_test.go
pkg/aws/policies.go

Sorts account-roles in a non-intrusive way (only visually for output) when running `rosa list account-roles`.
This sorts by 1st) Clumping roles of the same group together (I.E. same prefix) and 2nd) by whether or not the roles contain `-HCP-`.
Original output:
```
<prefix>-ControlPlane-Role
<prefix>-HCP-ROSA-Installer-Role
<prefix>-HCP-ROSA-Support-Role
<prefix>-HCP-ROSA-Worker-Role
<prefix>-Installer-Role
<prefix>-Support-Role
<prefix>-Worker-Role
```
New output:
```
<prefix>-HCP-ROSA-Installer-Role
<prefix>-HCP-ROSA-Support-Role
<prefix>-HCP-ROSA-Worker-Role
<prefix>-Installer-Role
<prefix>-Support-Role
<prefix>-Worker-Role
<prefix>-ControlPlane-Role
```

OCM-4649 | feat: /UX\ Output of `list account-roles` sorted by '-HCP-'

---

go.mod
go.sum
tests/ci/data/profiles/external.yaml
tests/ci/data/profiles/rosa-hcp.yaml
tests/utils/config/cluster.go
tests/utils/handler/cluster_handler.go
tests/utils/handler/interface.go
tests/utils/handler/profile.go
tests/utils/handler/resources_handler_prepare.go
vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/instance.go
vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/ram.go
vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/role.go
vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/route_table.go
vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/vpc.go
vendor/github.com/openshift-online/ocm-common/pkg/rosa/oidcconfigs/oidcconfigs.go
vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/bastion.go
vendor/modules.txt

1. Enable a new profile : ocpe2e-rosa-hcp-zero-egress. It is required to prepare some resources in the cluster VPC.Here is the [document](https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html/install_rosa_with_hcp_clusters/rosa-hcp-egress-lockdown-install#rosa-hcp-vpc-manual_rosa-hcp-egress-lockdown-install)
```
Procedure
Create the AWS security group by running the following command:
$ aws ec2 create-security-group \
--group-name allow-inbound-traffic \
--description "allow inbound traffic" \
--vpc-id <vpc_id> \ [1](https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html/install_rosa_with_hcp_clusters/rosa-hcp-egress-lockdown-install#CO11-1)
--region <aws_region> \ [2](https://docs.redhat.com/en/documentation/red_hat_openshift_service_on …
```

OCM-13150 | ci: Enabled rosa-hcp-zero-egress profile for OCPE2E

---

tests/ci/data/profiles/rosa-classic.yaml
tests/e2e/e2e_setup_test.go
tests/e2e/test_rosacli_network_verifier.go

- Change region for rosa-private-link profile to avoid cluster provision failure which were met these days for many times
- 70370: Simplified the expected inflight check message to avoid case failure which inflight check result is not expected sometime
- Improve the Day1Readiness step by returning error when timeout and use the cluster spec json to get the DNS. 
logs: https://privatebin.corp.redhat.com/?c04ca6d5dd046a34#EQhUHyhFjC3cmYMFCSpauRxJ5aD1EEXqzJuR2JSbhsyX

OCM-14736 | test: fix id:70370 and some update on rosa-private-link profile and improvement for Day1Readiness step

---

tests/ci/config/config.go
tests/utils/handler/cluster_handler.go

It met timeout error when waiting for cluster installing in Day1Readiness step,
```
[FAILED] Unexpected error:
<*errors.errorString | 0xc000ca4cf0>: 
timeout for cluster stuck waiting after 2 mins
{
s: "timeout for cluster stuck waiting after 2 mins",
}
occurred
```
To increase the wait time in this ticket

OCM-14796 | ci: increase the wait time for cluster installing in Day1Readiness step

---

cmd/create/network/cloudformation.go
cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
pkg/aws/cloudformation.go
pkg/network/network.go
pkg/options/network/create.go

This pull request extends the default cloudformation template so that is is possible to specify availability zones to be used during the stack creation:
```
rosa create network --param Region=us-west-2 --param Name=stack01 --param AvailabilityZones=us-west-2b,us-west-2d
```
Closes: [OCM-14846](https://issues.redhat.com/browse/OCM-14846)

OCM-14846 | feat: allow specifying availability zones for CF stack creation

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

JWT has a security flaw in 4.5.0
Bumped to 4.5.2 here, where it is fixed, and ran `go mod tidy` & `go mod vendor`

OCM-14781 | feat: Bump jwt version, to avoid security flaw

---

cmd/create/network/cmd.go
pkg/options/network/create.go

Before (random order of the template parameters):
```
$ rosa create network -h 
Available parameters in default template:
VpcCidr
Name
AZ4
AvailabilityZoneCount
AZ3
AZ1
Region
AZ2
Tags
...
```
After (sorted order of the template parameters):
```
$ rosa create network -h 
Available parameters in default template:
AZ1
AZ2
AZ3
AZ4
AvailabilityZoneCount
Name
Region
VpcCidr
Tags
...
```
Closes https://github.com/openshift/rosa/pull/2841

OCM-15005 | feat: sort CF template parameters in help output

---

cmd/create/cluster/cmd.go

Improved UX on error handling for privates clusters by adding some verifications to the subnets and better messaging to when a subnet is public and can't be used in this setting
On the terminal, execute the command `./rosa create cluster --hosted-cp --mode auto SUBNET1,SUBNET2`, here you should put a private and public subnet that are located in the same region, go through the process, and after selecting the option for the cluster to be private, you should see a message saying that the command could not be executed, and the program will stop running.
On the terminal, execute the command `./rosa create cluster --hosted-cp --mode auto`, go through the process, and after selecting the option for the cluster to be private, you should see a warning for public subnets that have been excluded …

OCM 6929 | fix: Improved UX for error handling in private clusters

---

cmd/create/cluster/cmd.go

Unhides the `channel-group` flag in `create/cluster` - related to EUS region support ([OCM-15097](https://issues.redhat.com//browse/OCM-15097))

OCM-15097 | feat: Un-hide `channel-group` flag in create/cluster

---

cmd/edit/cluster/cmd.go
cmd/rosa/structure_test/command_args/rosa/edit/cluster/command_args.yml
pkg/ocm/clusters.go

API body on changing channel-group:
```
time=2025-04-07T15:19:43-04:00 level=debug msg={
"kind": "Cluster",
"api": {
"listening": "external"
},
"disable_user_workload_monitoring": false,
"version": {
"kind": "Version",
"channel_group": "nightly"
}
}
```
-------------
Response when version is not supported in channel group from API:
```
E: Failed to update cluster: status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400', at '2025-04-07T19:19:44Z' and operation identifier is 'XXXX': The current version '4.18.6' is not available for the desired channel group 'nightly'
```
-------------
Version cannot be edited, only the channel group. If a user gets an error about unsupported version, they are to upgrade the version before editing the channel group.

OCM-15096 | feat: Introduce `channel-group` in edit/cluster

---

cmd/edit/cluster/cmd.go

Removes the default `"stable"` channel group value from `edit/cluster`

OCM-15190 | feat: Remove default channelgroup from edit/cluster

---

cmd/create/cluster/cmd.go
pkg/helper/roles/helpers.go

This PR improves the UX when handling account roles and introduces a new check to verify whether a role is **managed by Red Hat** or not and some warnings.
---
Before running the test cases, create an account role with version `4.13` using the following command:
```bash
./rosa create account-roles --mode auto --version 4.13
```
---
1. Run the command:
```bash
./rosa create cluster --hosted-cp --mode auto
```
2. During the interactive flow:
- Select an account role tied to version **4.13**
- Then choose a **different OpenShift version**, e.g., `4.14`
3. You should see the following **warnings**, and the command **will NOT stop running**:
```
W: Account roles not created by ROSA CLI cannot be listed, updated, or upgraded. Use ROSA CLI to create them before proceeding.
W: No suitable …
```

OCM-4667 | feat: added new warnings and validations to account-role

---

tests/ci/config/config.go
tests/ci/data/profiles/external.yaml
tests/e2e/e2e_day2_conf_test.go
tests/e2e/e2e_setup_test.go
tests/utils/handler/interface.go
tests/utils/handler/profile.go

[OCM-15397](https://issues.redhat.com//browse/OCM-15397): support  cluster autoscaler day2 action after cluster creation
```
ginkgo run --label-filter day2-readiness tests/e2e --timeout 2h
Running Suite: ROSA CLI e2e tests suite - /Users/yingzhan/ying-work/code/rosa/tests/e2e
Random Seed: 1745845618
Will run 1 of 266 specs
•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 266 Specs in 11.233 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 265 Skipped
PASS
ocm get  /api/clusters_mgmt/v1/clusters/2iedb0cnc0kvkmt9gec9qqqir1ndm9ia/autoscaler
{ …
```

OCM-15397 | ci: Support cluster autoscaler day2 action for HCP cluster

---

pkg/info/info.go

Bump ROSA CLI to the latest version to be released

OCM-15275 | chore: Bump ROSA version to 1.2.53

---

cmd/create/cluster/cmd.go
cmd/create/cluster/validation.go

Removes billing account ID when using HCP on fedramp, as well as forces the FIPS check in the same situation. Also added some UX in the form of warning the user they 1) don't need the billing account ID flag, and 2) informs them where it comes from

OCM-15600 | feat: Clean up UX + remove billing account checks for HCP govcloud

---

pkg/machinepool/machinepool_test.go
pkg/ocm/machines.go

In the API, we have a preflight which covers this validation case: https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/blob/master/cmd/clusters-service/service/aws_preflight/preflight_service.go#L442
It has been asked to remove from the CLI, so errors are consistent.
2 tests have also been removed, since they relate to the functionality which this validation provided

OCM-15158 | feat: Removed duplicated-from-API validation (machinepools)

---

.tekton/rosa-pull-request.yaml
.tekton/rosa-push.yaml
Dockerfile
Makefile
hack/build_cli.sh

Makes the PR pipeline run for every `master` branch push
Makes the on-push pipeline run for every `release_...` tag made

OCM-15757 | ci: Change triggers for konflux, get PR pipeline passing

---

.tekton/rosa-push.yaml

This way, any tag made with `v...` will be considered a release and will trigger a build. Can also be used for prereleases and testing the pipeline

OCM-15770 | ci: Change on-push pipeline to trigger with tags that start with `v`

---

pkg/machinepool/machinepool.go

Disables kubelet configs for interactive mode with `create/machinepool` when creating nodepools in fedramp envs for HCP
API does not support this feature, using it returns a CLI-exiting error. Disabling is the path forward for `create/machinepool` functionality for HCP in fedramp envs

OCM-13374 | feat: Disable kubelet configs for govcloud

---

pkg/machinepool/machinepool.go

Fixes issue with `edit/machinepool` interactive mode (specifically, HCP, so nodepools) trying to perform kubeletconfig API calls on govcloud. It is not supported so it is best to gate this feature to prevent the command from exiting early

OCM-13374 | feat: Disable edit/machinepool kubeletconfigs for HCP+gov

---

cmd/edit/cluster/cmd.go

Disables interactive checks for HCP billings accounts in govcloud envs. This is due to the fact billing accounts don't work yet for fedramp

OCM-15873 | fix: Disable edit/cluster billing account for HCP fedramp

---

.tekton/hcp-advanced-e2e-test.yaml
.tekton/rosa-push.yaml
.tekton/steps/clean-up-step.yaml
.tekton/steps/run-e2e-day1-step.yaml
.tekton/steps/run-e2e-day2-step.yaml
.tekton/tasks/e2e-clean-up-task.yaml
.tekton/tasks/e2e-task.yaml

- Add integration testing pipeline used to run e2e testing with the releasing image
- Add the first hcp-advanced  e2e testing job and will add more jobs after checking it works well
- Add an additional tag on the push image, this tag will be used by other pipeline to use the latest pushed image
To easy trigger the job to debug the first job, the trigger condition is a PR which title starts with e2e_trigger. It will be upgrade to trigger following the PUSH pipeline after the test of the pipeline is done and works well.

OCM-15880 | ci: Add integration pipeline on Konflux

---

.tekton/hcp-advanced-e2e-test.yaml
.tekton/steps/run-e2e-day2-step.yaml

[OCM-15880](https://issues.redhat.com//browse/OCM-15880) | ci: Update to use https url as TASKS_REPO value

OCM-15880 | ci: Update to use https url as TASKS_REPO value

---

tests/ci/config/config.go
tests/utils/handler/cluster_handler.go
tests/utils/handler/interface.go
tests/utils/handler/resources_handler_prepare.go

[OCM-15682](https://issues.redhat.com//browse/OCM-15682): Add new tag for unused subnets when creating clusters.It is due to OCP new feature:[OCPSTRAT-569](https://issues.redhat.com/browse/OCPSTRAT-569)
Run it in local with 4.18 and 4.19 version,cluster can be ready
```
ginkgo run --label-filter day1 tests/e2e --timeout 1h && ginkgo run --label-filter day1-readiness tests/e2e --timeout 2h 
Running Suite: ROSA CLI e2e tests suite - /Users/yingzhan/ying-work/code/rosa/tests/e2e
Random Seed: 1747643497
Will run 1 of 266 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS …
```

OCM-15682 | ci: Add new tag for unused subnets

---

cmd/login/cmd.go
pkg/fedramp/config.go
pkg/ocm/config.go

https://github.com/openshift/rosa/issues/2894
Logging into govcloud via ROSA CLI could be finicky if the user did not supply a correct environment.
--------
From #2894:
```
rosa login --env prod --govcloud --admin --region us-gov-west-1
To login to your Red Hat account, get an offline access token at
? Copy the token and paste it here:
```
This doesn't show a link to get token or throw an error that "prod" is not recognized.
```
rosa login --env production --govcloud --admin --region us-gov-west-1
To login to your Red Hat account, get an offline access token at https://api-admin.openshiftusgov.com/auth
? Copy the token and paste it here:
```
The proper value is production.
--------
This has been improved upon by introducing a warning when a user provides an incorrect env for a govcloud …

OCM-15907 | feat: Introduce warning + validation for govcloud env choice

---

cmd/list/cluster/cmd.go
pkg/rosa/runtime.go

* Fixes https://github.com/openshift/rosa/issues/2907 and https://github.com/openshift/rosa/issues/1386
* Fixes [OCM-16119](https://issues.redhat.com//browse/OCM-16119)
The issue stemmed from the AWS client needed to be used when listing clusters. The command is region-agnostic, but the client was created using `WithAWS` which always exits when no region is set with an error. 
To fix this, I introduced an "overloaded" function called `WithAWSWarnInsteadOfExit` to warn about no region being set and continue, rather than error+exit.

OCM-16119 | fix: No region set for command which needs no region, `list/clusters`

---

.golangci.yml
go.mod

OCM-10979 | fix: Bump Go version to 1.23.1

---

images/Dockerfile.konflux

Add GOFLAGS=-buildvcs=false env in Dockerfile.konflux to avoid bellow error when build-container:
```
[1/2] STEP 10/10: RUN make release
bash ./hack/build_cli.sh
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping. 
```

OCM-15880 | ci: Add GOFLAGS=-buildvcs=false env in Dockerfile.konflux

---

tests/e2e/hcp_machine_pool_test.go
tests/utils/constants/general.go
tests/utils/exec/rosacli/cmd_parser.go

-     77829,81295,77140,81295: new aws account 090777400063 parsing issue. Fix it by preprocessing the raw input string in escapeYamlStringValues
-     75921: Update the testing billing for new OCM account
-     56786: error message have changed, update the expected error message
Logs on local are here https://privatebin.corp.redhat.com/?47489464ef6a2cc1#8SGVuMjAXmSaT45bHmhy8X7oP2A3CUG9FUS9ma3FnXKL

OCM-16406 | test: fix ids: 77829,81295,77140,81295,75921,56786

---

cmd/create/accountroles/cmd.go
cmd/create/accountroles/creators.go

Introduces a warning letting the user know that re-running `rosa create account-roles` with `--force-policy-creation` can fix potential policy issues. The solution for [OCM-4117](https://issues.redhat.com//browse/OCM-4117) was running the command with that `-f` flag. So, I think this is a decent solution for now until it is decided a larger change must be made (Should we always force? Is there something different that will fix it?)

OCM-4117 | feat: Introduce warning around creating accountroles

---

tests/e2e/test_rosacli_account_roles.go
tests/e2e/test_rosacli_network_resources.go
tests/prow_ci.sh

- 43070,62083,57441: there will be error if no any account roles exists.
- 81295,77140: maximum number of addresses has been reached, do some improvement for this case to delete the SF immediately after each creation step
- Add `rosa init` command in rosa_login function which is used for CI
The logs on local is here:
https://privatebin.corp.redhat.com/?2985a780f9009598#J9EpUi7CFu7u24gva9NRk5eGH2aU2bGadiRto2ekMbSt

OCM-16579 | test: fix ids: 43070,62083,57441,81295,77140

---

cmd/create/cluster/cmd.go
pkg/interactive/validation.go
pkg/ocm/clusters.go
pkg/ocm/helpers.go
pkg/ocm/helpers_test.go

* Removes `if !reflect.DeepEqual(config.DefaultIngress, NewDefaultIngressSpec()) {` check when creating cluster spec
* * Replicates behavior in that it only adds the modified default ingress when something is changed, but now includes Private Ingress in that check
* * Fixes issue where private ingress would not be set unless default ingress had another change

OCM-15992 | fix: Remove check stopping private ingress changes

---

cmd/create/cluster/cmd.go

Fixes [OCM-16864](https://issues.redhat.com//browse/OCM-16864), a bug where Private API was not taken into account once introduced as the alternative for classic's PrivateLink in HCP in interactive mode.
Creation of a cluster will error after saying `Yes` to the Private API prompt when using HCP clusters. Example failure happens here in the cluster creation process:
```
? AWS region (default = 'us-west-2'): us-west-2
? Private API: Yes
? Private ingress: Yes
E: Private STS clusters are only supported through AWS PrivateLink
```
HCP with private API enabled via interactive (OK):
```
? Private API: Yes
? Private ingress: Yes
? Machine CIDR: 10.0.0.0/16
```
HCP with private API and ingress disabled (KO):
```
? Private API: No
? Private ingress: No
E: Private STS clusters are only supported …
```

OCM-16864 | fix: Introduce private API to private STS validation

---

tests/e2e/e2e_day2_conf_test.go
tests/e2e/hcp_machine_pool_test.go
tests/e2e/test_rosacli_machine_pool.go

60688 failed the unmanaged tag is needed for the subnets under the cluster vpc since cluster 4.19.
failed job : https://redhat-internal.slack.com/archives/C0519LZH1RA/p1751940209728169
fix solution:
Add 'kubernetes.io/cluster/unmanaged' tag on all day2 cases which creates testing subnets on the cluster vpc.
local log: https://privatebin.corp.redhat.com/?741a1eb8bc4d18fa#4yH6JjscnUwUT9dpB9VRdktLRSUBvgcJMGbqLx5GjT5L

OCM-17038 | test: fix id: 60688 add unmanaged tag on the testing subnets

---

tests/ci/data/profiles/rosa-hcp.yaml
tests/e2e/test_rosacli_cluster_post.go
tests/utils/handler/cluster_handler.go
tests/utils/handler/interface.go

Automated id:83155 as day1 and day1-post of api and ingress private.
The log on local is https://privatebin.corp.redhat.com/?27b8bf4f2c240dda#8XcsE8GgEePJ6X2Tv4CbNrt5hZGZKoVvjdbTAvrV5dM7

OCM-16933 | test: automate id:83155 as day1 and day1-post of api and ingress private

---

pkg/version/version.go

Changes download links for ROSA CLI in `pkg/version/version.go`

OCM-17058 | feat: Update mirror and base releases folder URI

---

tests/ci/data/profiles/external.yaml

According to this https://github.com/openshift/rosa/pull/2937, do the change.
Here is the log
```
yingzhan@yingzhan-mac  ~/ying-work/code/rosa   ying-fix ±  ginkgo run --label-filter day1 tests/e2e --timeout 1h && ginkgo run --label-filter day1-readiness tests/e2e --timeout 2h 
Running Suite: ROSA CLI e2e tests suite - /Users/yingzhan/ying-work/code/rosa/tests/e2e
Random Seed: 1752115636
Will run 1 of 268 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSStime="2025-07-10 10:51:08" level=info msg="Got aws shared credential file path: /Users/yingzhan/.aws/cre_shared "
time="2025-07-10 10:51:11" level=info …
```

OCM-16081 | ci: Add new attribute default_ingress_private for HCP profiles

---

cmd/create/cluster/cmd.go

Should fix an issue where when using interactive mode, you are unable to create a cluster with `private API` + `private Ingress` via interactive mode. This is because the args values for `privateIngress` (what is provided when the command runs, only) was used in place of the value which is updated by interactive mode

OCM-16902 | fix: Pass in non-args privteIngress value

---

cmd/create/cluster/cmd.go
cmd/create/cluster/validation.go
pkg/interactive/validation.go
pkg/interactive/validation_test.go

Fixes issue where HCP clusters failed to validate with `private` and `private-ingress` set to `true`. Also added validation for users who try to use `--private-link` with HCP clusters

OCM-16902 | fix: Fix private+privateIngress clusters + validation

---

tests/e2e/test_rosacli_cluster.go
tests/utils/handler/cluster_handler.go

- If the cluster is hosted-cp, don't use private-link flag anymore
- 68971: Skip if there is no version bellow 4.13
logs on my local is https://privatebin.corp.redhat.com/?ce9f9f42ae5d14d5#B2v8MJd3LsdTWKBcDFGCT9bGF1xaHifssSvnxnTKpQMU

OCM-17244 | test: fix id: 68971 and fix preparation to not use private-link flag anymore for hcp cluster

---

cmd/create/cluster/cmd.go

Adds `--private-ingress` to the generated cluster command which is spat out when creating a new cluster. Also introduces a fix for `--private` and `--private-link` to only allow each to show up in that generated command when the correct architecture is used. This fixes any issues where `--private-link` would still have a value, even though it is not used, and therefore `--private` would not be included in an HCP cluster's spat-out-command

OCM-16905 | feat: Introduce `--private-ingress` to cluster cmd

---

pkg/info/info.go

Bumps version on master as part of the release process

OCM-17311 | chore: Bump CLI version on master to 1.2.55

---

CLAUDE.md

Using the file from https://github.com/openshift/rosa/pull/2958 - I created a set of basic guidelines for Claude Code to work a bit better in this repo

OCM-17532 | docs: Add Claude Code development guidelines and repository instructions

---

.tekton/rosa-cli-e2e-test-push.yaml

The Konflux job fails because it uses string, rather than array, as  apply-tags value in rosa-cli-e2e-test-push.
And Since native Tekton doesn’t support if-else conditions, I split the apply-tags job into two separate jobs and used when clauses to control their execution based on conditions
Error is bellow:
`[User error] Validation failed for pipelinerun rosa-cli-e2e-test-on-push-2gxdp with error invalid input params for task apply-tags: param types don't match the user-specified type: [ADDITIONAL_TAGS]`

OCM-17617 | ci: Fix rosa-cli-e2e-test-push to use array as the apply-tags value

---

pkg/version/retriever.go
pkg/version/retriever_test.go
pkg/version/version.go

Fixes issue brought up by customers and internal users, where after moving from ART to CGW for the CLI's download mirror, redirects were not working as expected. We must migrate the links within the CLI, as well as get the version retrieval service working with the new website

OCM-17643 | fix: Fix retrieving versions for listing CLI versions

---

tests/prow_ci.sh

support to dowload latest rosa version when setting ROSACLI_BUILD=latest to meet a good experience

OCM-17483 | ci: Support latest value for ROSACLI_BUILD

---

.tekton/rosa-cli-e2e-test-push.yaml

It should use single quotes for image_tag to avoid treating as a literal string.
failure job: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-terraform-tenant/applications/rh-rosa-cli/pipelineruns/rosa-cli-e2e-test-on-push-dccz6/logs?task=apply-tags
`
step-apply-additional-tags-from-parameter :-
Applying tag {{ image_tag }}
time="2025-08-13T13:36:14Z" level=fatal msg="Invalid destination name docker://quay.io/redhat-user-workloads/rh-terraform-tenant/rosa-cli-e2e-test:{{ image_tag }}: invalid reference format"
`

OCM-17713 | ci: To use single quotes for image_tag to avoid treating as a literal string

---

cmd/upgrade/cluster/cmd.go
cmd/upgrade/cluster/cmd_test.go

Updates the warning message which spits out when `--dry-run` is not used

OCM-16535 | chore: Update warning around upgrade dry runs

---

pkg/machinepool/machinepool.go

Fixes a bug where an empty capacity reservation ID was passed into the API, causing a nil value error
Also fixes a future bug (not found yet) with a validator being leftover from a copied interactive prompt block (whoops)

OCM-17858 | fix: Allow nodepool creation without capacity reservation id

---

pkg/machinepool/machinepool.go

```
E: Failed to add machine pool to hosted cluster '2ktf5ln6lmllejp5p8orf40o84u5mop8': status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400', at '2025-08-26T08:33:20Z' and operation identifier is 'd001cc2f-78e2-423f-b750-96c56284db20': Replicas must be specified when using AWS Capacity Reservations
```
This error happens when replying `yes` to the `Enable autoscaling` prompt and supplying a value for the `Capacity Reservation ID` prompt. This is needless, letting the user get through the entire creation of a node pool only to tell them we allowed them to put in conflicting values in interactive mode. This MR makes the prompt for `Capacity Reservation ID` no longer show when the nodepool's `autoscaling` is set to `true`

OCM-17895 | fix: Do not prompt for capacity reservation ID if autoscaling=t

---

tests/utils/exec/rosacli/cluster_service.go

Fix the cluster desciption parsing of "[DEPRECATED] User Workload Monitoring"
After https://issues.redhat.com/browse/OCM-17719, as M1 stage,  "[DEPRECATED] User Workload Monitoring" is added in the cluster description of hosted-cp cluster, this change makes DescribeClusterAndReflect failure, this function is using in some automated cases and also the cluster setup step, will cause bellow error,
`[FAILED] Unexpected error: <*errors.errorString | 0xc000e47e90>: yaml: line 1: did not find expected key { s: "yaml: line 1: did not find expected key", } occurred`
The log of rerun with this fix on local has passed, without above error anymore.

OCM-18058 | ci: Fix the cluster desciption parsing of '[DEPRECATED] User Workload Monitoring'

---

cmd/create/cluster/cmd.go

This PR improves the UX when creating clusters by ensuring subnet selection is **required** for HCP (Hosted Control Plane) clusters while keeping it **optional** for Classic clusters, preventing deployment issues and providing clearer guidance to users.
The change has been applied to:
- `rosa create cluster` interactive mode for HCP clusters
**Key Change:** 
- Subnet selection prompt now uses `Required: isHostedCP` instead of `Required: false`
- This means subnets are mandatory for HCP clusters but remain optional for Classic clusters
- 
---
1. **Build the updated ROSA CLI:**
```bash
go build ./cmd/rosa
```
2. **Test HCP cluster creation (subnets required):**
```bash
./rosa create cluster --hosted-cp --interactive --dry-run
```
- Verify that the subnet prompt does NOT show "(optional)"
- …

OCM-7670 | fix: Removed optional from subnet selection for HCP

---

.tekton/steps/clean-up-step.yaml
.tekton/steps/export-resources-record-step.yaml
.tekton/tasks/e2e-clean-up-task.yaml
.tekton/tasks/e2e-task.yaml

Use env to avoid failure that param substitution in scripts is not allowed.
The Konflux hcp-advanced-e2e-test met bellow erorr: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-terraform-tenant/applications/rh-rosa-cli/pipelineruns/hcp-advanced-e2e-test-jl62v/logs?task=hcp-advance-e2e-test
```
// code placeholder
validation failed for referenced object export-resources-record: admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: non-existent variable in "#!/bin/bash\ncat /rosa/tests/output/$(params.cluster-profile)/konflux_resources.json > $(results.konflux-resources-json.path)\n": spec.script param substitution in scripts is not allowed.: spec.script 
```

OCM-18230 | ci: Use env to avoid failure that param substitution in scripts is not allowed

---

cmd/create/cluster/cmd.go
cmd/rosa/structure_test/command_args/rosa/create/cluster/command_args.yml
pkg/ocm/clusters.go

Adds hidden options to set both Master and Infra node types for Classic clusters to enable testing of regions where `[m|r]5` instances are not available and provisioning would normally fail.
Closes [SLSRE-371](https://issues.redhat.com//browse/SLSRE-371)

feat(SLSRE-371): add hidden options for setting master/infra machine types with rosa create cluster

---

go.mod
go.sum
tests/ci/config/config.go
tests/ci/data/profiles/external.yaml
tests/utils/handler/cluster_handler.go
tests/utils/handler/interface.go
tests/utils/handler/resources_handler_prepare.go
vendor/github.com/openshift-online/ocm-common/pkg/deprecation/transport_wrapper.go
vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/proxy.go
vendor/github.com/openshift-online/ocm-common/pkg/utils/pointers.go
vendor/modules.txt

[OCM-16969](https://issues.redhat.com//browse/OCM-16969) ：It support setup proxy with username/password way.Enable it in a new HCP profile
rosa describe cluster -c ying-proxy-0wby
```
Name:                       ying-proxy-0wby
Domain Prefix:              ying-proxy-0wby
Display Name:               ying-proxy-0wby
ID:                         2l40q27dvhbp0mhrr61799v2gl9ea4ik
External ID:                3e550e4f-999d-4af8-888b-0eafaf242046
Control Plane:              ROSA Service Hosted
OpenShift Version:          4.19.9
DNS:                        ying-proxy-0wby.961f.s3.devshift.org
AWS Account:                989064034108
AWS Billing Account:        301721915996
API URL:                    https://api.ying-proxy-0wby.961f.s3.devshift.org:443
Console …
```

OCM-16969 | ci: Add a new HCP profile with proxy that is set username/password

---

.tekton/steps/clean-up-step.yaml
.tekton/steps/run-e2e-day1-step.yaml
.tekton/steps/run-e2e-day2-step.yaml

The Konflux job of hcp-advanced-e2e fails as the aws credential file path is not correct in the step script.
The error is "ERROR: the shared vpc credential file /mnt/secrets/awscred_shared_account/.awscred_shared_account doesn't exist. Please check" https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-terraform-tenant/applications/rh-rosa-cli/taskruns/hcp-advanced-e2e-test-sgdvz-hcp-advance-e2e-test/logs
This fix will correct the aws credential path used in the job step

OCM-18536 | ci: Update the aws credential path in the steps scripts of e2e testing

---

.tekton/steps/clean-up-step.yaml
.tekton/steps/run-e2e-day1-step.yaml
.tekton/steps/run-e2e-day2-step.yaml

In konflux hcp-advance-e2e-test job, fix the ginkgo command in the step scripts, flags should precede the package name to avoid all cases selected to run

OCM-18557 | ci: Flags should precede the package name in the ginkgo commands in the steps scripts of e2e testing

---

cmd/create/cluster/cmd.go
cmd/create/cluster/validation.go
cmd/edit/cluster/cmd.go

Introduces day 1 and 2 billing account selection for classic clusters. Simple introduction since it is available for HCP already, the goal here was to replace the `if isHostedCp` gates with `if isHostedCp || (isClassic and isCapabilityEnabledForOrg)` so that billing account selection is available for customers with the correct capability for classic clusters
```swift
❯ ./rosa edit cluster -c hkepley --billing-account 123
I: Updated cluster 'hkepley'
❯ make
go build -ldflags="-X github.com/openshift/rosa/pkg/info.Build=a587d1642" ./cmd/rosa
❯ ./rosa edit cluster -c hkepley --billing-account 123
E: Provided billing account number 123 is not valid. Rerun the command with a valid billing account number
```
^ Example of editing, first command run was with a `false` org capability. Second run …

OCM-17611 | feat: Introduce billing account selection for classic

---

pkg/interactive/validation_test.go
pkg/ocm/helpers.go

This PR improves the validation error message for subnet configuration in ROSA Hosted Control Plane clusters, providing clearer guidance when clusters require public subnets.
The implementation includes:
- Updated error message in `ValidateHostedClusterSubnets` function to accurately describe subnet requirements
- Clarified that public subnets are required unless **both** API and ingress are private
- Updated test cases to match the new error message
---
1. Create a ROSA HCP cluster in interactive mode:
```bash
rosa create cluster --hosted-cp --interactive
```
2. Choose:
- Private API: **Yes**
- Private ingress: **No**
- Select only private subnets in "Subnet IDs"
3. **Old behavior:** Confusing error about "public hosted cluster"
4. **New behavior:** Clear error explaining subnets needed …

OCM-16903 | fix: changed messaging for validation error in HCP cluster

---

pkg/machinepool/machinepool.go

Disables prompt + usage entirely of the cap-res-id flag for govcloud ends

OCM-18786 | fix: Do not prompt capres in govcloud env
